- id: '1600374302972'
  alias: Kodi Wohnzimmer - Einschalten
  description: ''
  trigger:
  - platform: device
    device_id: 32e19680f91711eaa516c9e368eb4fd0
    domain: kodi
    entity_id: media_player.kodi_wohnzimmer
    type: turn_on
  condition: []
  action:
  - service: mqtt.publish
    data:
      topic: iotlink/workgroup/computer/commands/run
      payload: '{ "command": "C:\\Program Files\\Kodi\\kodi.exe", "path": "C:\\Program
        Files\\Kodi", "user": "", "visible": true, "fallback": true }'
  mode: single
- id: '1600374475624'
  alias: Kodi Wohnzimmer - Ausschalten
  description: ''
  trigger:
  - platform: device
    device_id: 32e19680f91711eaa516c9e368eb4fd0
    domain: kodi
    entity_id: media_player.kodi_wohnzimmer
    type: turn_off
  condition: []
  action:
  - service: kodi.call_method
    data:
      entity_id: media_player.kodi_wohnzimmer
      method: Application.Quit
  mode: single
