homeassistant:
  name: Home Assistant
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 100
  unit_system: metric
  time_zone: Europe/Berlin
  packages: !include_dir_named packages
  customize: !include_dir_merge_named customize
  customize_glob: !include_dir_merge_named customize_glob
  auth_providers:
    - type: trusted_networks
      allow_bypass_login: true
      trusted_networks:
        - 192.168.2.0/24
  whitelist_external_dirs:
     - /home/homeassistant/.homeassistant/

group: !include_dir_merge_named group

hacs:
  token: !secret github_access_token

zone:
  - name: Zu Hause
    latitude: !secret home_latitude
    longitude: !secret home_longitude
    radius: 60
    icon: mdi:home-account
  - name: Arbeit
    latitude: !secret work_latitude
    longitude: !secret work_longitude
    radius: 70
    icon: mdi:wan 