title: Home Assistant
views:
  - !include lovelace/wohnzimmer.yaml
  - !include lovelace/schlafzimmer.yaml
  - !include lovelace/kueche.yaml
  - !include lovelace/badezimmer.yaml
  - !include lovelace/flur.yaml
  - !include lovelace/kinderzimmer.yaml
  - !include lovelace/arbeitszimmer.yaml   