title: Home Assistant
views:
  - !include lovelace/information.yaml
  - !include lovelace/system.yaml
  - !include lovelace/wohnzimmer.yaml
  - !include lovelace/schlafzimmer.yaml
  - !include lovelace/kueche.yaml
  - !include lovelace/badezimmer.yaml
  - !include lovelace/flur.yaml
  - !include lovelace/arbeitszimmer.yaml
  - !include lovelace/sportzimmer.yaml
  - !include lovelace/wetter.yaml
  - !include lovelace/heimnetz.yaml
  - !include lovelace/geraete.yaml
  - !include lovelace/batterien.yaml

resources:
  - url: /local/lovelace/vertical-stack-in-card.js?v=v0.1.1
    type: js
  - url: /local/lovelace/card-tools.js?v=0.3
    type: js
  - url: /local/lovelace/popup-card.js
    type: js
  - url: /local/lovelace/layout-card.js
    type: js
  - url: /local/lovelace/fold-entity-row.js
    type: js
  - url: /local/lovelace/todoist-list.js
    type: js
  - url: /local/lovelace/mini-media-player-bundle.js?v=1.0.1
    type: module
  - url: /local/lovelace/mini-graph-card-bundle.js?v=0.3.0
    type: module