title: Home Assistant
views:
  - !include lovelace/information.yaml
  - !include lovelace/system.yaml
  - !include lovelace/wohnzimmer.yaml
  - !include lovelace/schlafzimmer.yaml
  - !include lovelace/kueche.yaml
  - !include lovelace/badezimmer.yaml
  - !include lovelace/flur.yaml
  - !include lovelace/arbeitszimmer.yaml
  - !include lovelace/sportzimmer.yaml
  - !include lovelace/wetter.yaml
  - !include lovelace/heimnetz.yaml
  - !include lovelace/geraete.yaml
  - !include lovelace/batterien.yaml

resources:
  - url: /community_plugin/lovelace-darksky-card/darksky-card.js
    type: module
  - url: /community_plugin/mini-media-player/mini-media-player.js
    type: module
  - url: /community_plugin/mini-graph-card/mini-graph-card.js
    type: module
  - url: /community_plugin/lovelace-card-tools/card-tools.js
    type: js
  - url: /community_plugin/lovelace-popup-card/popup-card.js
    type: js
  - url: /community_plugin/lovelace-layout-card/layout-card.js
    type: js
  - url: /community_plugin/lovelace-fold-entity-row/fold-entity-row.js
    type: js
  - url: /community_plugin/vertical-stack-in-card/vertical-stack-in-card.js
    type: js
  - url: /community_plugin/zha-network-card/zha-network-card.js
    type: js
  - url: /community_plugin/travel-time-card/travel-time-card.js
    type: js
  - url: /community_plugin/secondaryinfo-entity-row/secondaryinfo-entity-row.js
    type: js