title: Home Assistant
views:
  - !include lovelace/information.yaml
  - !include lovelace/system.yaml
  - !include lovelace/wohnzimmer.yaml
  - !include lovelace/schlafzimmer.yaml
  - !include lovelace/kueche.yaml
  - !include lovelace/badezimmer.yaml
  - !include lovelace/flur.yaml
  - !include lovelace/arbeitszimmer.yaml
  - !include lovelace/sportzimmer.yaml
  - !include lovelace/wetter.yaml
  - !include lovelace/heimnetz.yaml
  - !include lovelace/geraete.yaml
  - !include lovelace/batterien.yaml