title: Home Assistant
views:
  - !include lovelace/information.yaml
  - !include lovelace/system.yaml
  - !include lovelace/wetter.yaml
  - !include lovelace/heimnetz.yaml
  - !include lovelace/geraete.yaml
  - !include lovelace/batterien.yaml
