input_boolean:
  timer_schlafzimmer_aktiv:
    name: Sleeptimer aktiv
    initial: off
    icon: mdi:timer-off

  schlafen_einschalten_aktiv:
    name: "Schlafen einschalten aktiv"

  schlafen_aktiv:
    name: Schlafen
    initial: off

  schlafen_fernseher_einschalten:
    name: Fernseher einschalten
    initial: on
    icon: mdi:television

input_select:
  timer_schlafzimmer_dauer:
    name: Timer Schlafzimmer
    options:
      - 10
      - 30
      - 60
      - 70
      - 90
      - 120
    initial: 70
    icon: mdi:clock-end

timer:
  sleeptimer:
    name: Sleeptimer
    icon: mdi:filmstrip-off
    duration: 4200

  schlafen_einschalten:
    name: "Schlafen einschalten"
    duration: 7

binary_sensor:
  - platform: template
    sensors:
      schlafen_aktiv:
        friendly_name: Schlafen aktiv
        entity_id:
          - input_boolean.schlafen_aktiv
        value_template: >
          {{ is_state('input_boolean.schlafen_aktiv', 'on') }}

sensor:
  - platform: history_stats
    name: Schlafdauer
    entity_id: binary_sensor.schlafen_aktiv
    state: 'on'
    type: 'ratio'
    end: '{{ now() }}'
    duration:
      days: 7

  - platform: template
    sensors:
      timer_schlafzimmer_zeit:
        friendly_name: Fernseher ausschalten
        icon_template: mdi:filmstrip-off
        entity_id:
          - automation.sleeptimer_starten
          - input_boolean.timer_schlafzimmer_aktiv
          - input_select.timer_schlafzimmer_dauer
          - sensor.time
        unit_of_measurement: 'Minuten'
        value_template: >-
            {%- if is_state('input_boolean.timer_schlafzimmer_aktiv', 'on') %}
              {% set now = as_timestamp(now()) | int %}
              {% set last = as_timestamp(states.automation.sleeptimer_starten.attributes.last_triggered) | int %}
              {% set duration = states.input_select.timer_schlafzimmer_dauer.state | int %}
              {% set diff = (duration - ((now - last) / 60)) | int %}

              {% if diff < 0 %}
                {{ duration }}
              {% else %}
                {{ diff }}
              {% endif %}
            {% else %}
                -
            {%- endif %}

      schlafen_letzte_uhrzeit:
        friendly_name: Letzte Uhrzeit
        entity_id:
          - script.schlafen_gehen
        value_template: >
          {% if states.script.schlafen_gehen.attributes.last_triggered == None %}
            -
          {% else %}
            {{ as_timestamp(states.script.schlafen_gehen.attributes.last_triggered) | timestamp_custom('%H:%M') }}
          {% endif %}
        icon_template: >
          mdi:av-timer
        unit_of_measurement: 'Uhr'

      schlafen_dauer_durchschnitt:
        friendly_name: Durchschnittliche Dauer
        entity_id:
          - sensor.schlafdauer
        value_template: >
          {% if states.sensor.schlafdauer == None %}
            0
          {% else %}
            {% set stunden = states.sensor.schlafdauer.state | float * 24 / 100 | float %}
            {{'%0.2f' % stunden | float }}
          {% endif %}
        icon_template: >
          mdi:bell-sleep-outline
        unit_of_measurement: 'Stunden'

script:
  schlafen_gehen:
    alias: Schlafen gehen
    sequence:
      - service: !secret tts_service
        data_template:
          message: "Alle Ger채te werden ausgeschaltet. Gute Nacht."
      - service: input_boolean.turn_on
        entity_id: input_boolean.schlafen_aktiv
      - service: light.turn_on
        entity_id: light.bett
      - service: switch.turn_off
        entity_id: switch.multimedia, switch.wohnzimmer_radio, switch.balkon_radio, switch.flur_radio, switch.kuche_radio, switch.schlafzimmer_radio, switch.arbeitszimmer_radio
      - service: switch.turn_off
        entity_id: switch.watchtv_wohnzimmer, switch.monitor
      - service: input_boolean.turn_on
        entity_id: input_boolean.timer_schlafzimmer_aktiv
      - delay: '00:01:00'
      - service: light.turn_off
        entity_id: light.couch, light.strahler, light.vitrine
      - delay: '00:04:00'
      - service: switch.turn_off
        entity_id: switch.badezimmer_radio
      - service: light.turn_off
        entity_id: light.sideboard, light.schrank
      - condition: state
        entity_id: input_boolean.computer_ausschalten
        state: 'on'
      - service: switch.turn_off
        entity_id: switch.pc

  schlafen_gehen_fernseher:
    alias: Schlafen gehen - Fernseher einschalten
    sequence:
      - service: switch.turn_on
        entity_id: switch.watchtv_schlafzimmer

  sleeptimer_turn_off_tv:
    alias: Sleeptimer aktivieren
    sequence:
      - condition: state
        entity_id: input_boolean.timer_schlafzimmer_aktiv
        state: 'on'
      - service: script.watchtv_schlafzimmer_off

automation:
  - alias: "Schlafen gehen - Countdown starten"
    initial_state: true
    trigger:
      - platform: event
        event_type: xiaomi_aqara.click
        event_data:
          entity_id: binary_sensor.switch_158d0002c8c48b
          click_type: long_click_press
    condition:
      - condition: state
        entity_id: binary_sensor.schlafen_aktiv
        state: 'off'
      - condition: state
        entity_id: timer.schlafen_einschalten
        state: 'idle'
    action:
      - service: !secret tts_service
        data_template:
          echo: "wohnzimmer"
          message: "Alle Ger채te werden gleich ausgeschaltet."
      - delay: '00:00:02'
      - service: timer.start
        entity_id: timer.schlafen_einschalten
      - service: media_player.play_media
        data_template:
          entity_id:
            - media_player.tts
          media_content_id: >-
            http://192.168.2.70:8123/local/countdown/countdown_5.mp3
          media_content_type: music

  - alias: "Schlafen gehen - Countdown abbrechen"
    initial_state: true
    trigger:
      - platform: event
        event_type: xiaomi_aqara.click
        event_data:
          entity_id: binary_sensor.switch_158d0002c8c48b
          click_type: single
    condition:
      - condition: state
        entity_id: timer.schlafen_einschalten
        state: 'active'
    action:
      - service: media_player.media_pause
        entity_id: media_player.tts
      - service: !secret tts_service
        data_template:
          echo: "wohnzimmer"
          message: "Der Vorgang wurde abgebrochen."
      - service: timer.cancel
        entity_id: timer.schlafen_einschalten
      - service: media_player.clear_playlist
        entity_id: media_player.tts

  - alias: "Schlafen gehen - Starten"
    initial_state: true
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.schlafen_einschalten
    action:
      - service: !secret tts_service
        data_template:
          echo: "wohnzimmer"
          message: "Alle Ger채te werden jetzt ausgeschaltet. Gute Nacht."
      - service: script.schlafen_gehen

  - alias: "Schlafen gehen - Fernseher einschalten"
    initial_state: true
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.schlafen_einschalten
    condition:
      - condition: state
        entity_id: input_boolean.schlafen_fernseher_einschalten
        state: 'on'
    action:
      - service: script.schlafen_gehen_fernseher

  - alias: 'Sleeptimer starten'
    initial_state: true
    trigger:
      platform: state
      entity_id: input_boolean.timer_schlafzimmer_aktiv
      to: 'on'
    action:
      - service: timer.start
        entity_id: timer.sleeptimer
        data_template:
          duration: >
            {{ states.input_select.timer_schlafzimmer_dauer.state  | int * 60 | int }}

  - alias: 'Sleeptimer endet'
    initial_state: true
    trigger:
      - platform: numeric_state
        entity_id: sensor.timer_schlafzimmer_zeit
        below: 6
    condition:
      - condition: state
        entity_id: media_player.kodi_schlafzimmer
        state: 'playing'
    action:
      - service: notify.kodi_schlafzimmer
        data:
          title: 'Sleeptimer'
          message: >-
            {% set restzeit = states.sensor.timer_schlafzimmer_zeit.state | default(0) | int %}

            {% if restzeit > 1 %}
              Der Sleeptimer endet in {{ restzeit }} Minuten.
            {% else %}
              Der Sleeptimer endet in weniger als einer Minute.
            {% endif %}
          data:
            displaytime: 10000
            icon: "info"

  - alias: 'Sleeptimer ge채ndert'
    initial_state: true
    trigger:
      platform: state
      entity_id: input_select.timer_schlafzimmer_dauer
    action:
      - service: timer.start
        entity_id: timer.sleeptimer
        data_template:
          duration: >
            {{ states.input_select.timer_schlafzimmer_dauer.state  | int * 60 | int }}
      - service: input_boolean.turn_on
        entity_id: input_boolean.timer_schlafzimmer_aktiv

  - alias: 'Sleeptimer aktiviert'
    initial_state: true
    trigger:
      platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.sleeptimer
    action:
      - service: script.sleeptimer_turn_off_tv
      - service: light.turn_off
        entity_id: light.bett

  - alias: 'Sleeptimer abbrechen'
    initial_state: true
    trigger:
      platform: state
      entity_id: input_boolean.timer_schlafzimmer_aktiv
      to: 'off'
    action:
      - service: timer.cancel
        entity_id: timer.sleeptimer

  - alias: "Schlafzimmer - Kodi gestartet"
    initial_state: true
    trigger:
      platform: state
      entity_id: media_player.kodi_schlafzimmer
      to: 'playing'
    condition:
      - condition: state
        entity_id: timer.sleeptimer
        state: 'active'
    action:
      - service: light.turn_off
        entity_id: light.bett, light.sideboard, light.badezimmerschrank, light.schreibtisch, light.regal, light.arbeitszimmer_lampe

  - alias: "Schlafzimmer - Kodi pausiert"
    initial_state: true
    trigger:
      platform: state
      entity_id: binary_sensor.zigate_be83_presence
      to: 'on'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: media_player.kodi_schlafzimmer
          state: 'playing'
        - condition: state
          entity_id: timer.sleeptimer
          state: 'active'
    action:
      - service: media_player.media_pause
        entity_id: media_player.kodi_schlafzimmer

homeassistant:
  customize:
    script.schlafen_gehen:
      icon: mdi:hotel
      can_cancel: false

    timer.sleeptimer:
      hidden: true
    input_boolean.schlafen_aktiv:
      hidden: true
    binary_sensor.schlafen_aktiv:
      icon: mdi:sleep
    sensor.schlafdauer:
      hidden: true