switch:
  - platform: brematic
    host: 192.168.2.57
    switches:
      sportzimmer_fernseher:
        friendly_name: Sportzimmer Fernseher
        system_code: "00100"
        unit_code: "10000"
      sportzimmer_crosstrainer:
        friendly_name: Crosstrainer
        system_code: "00100"
        unit_code: "01000"

homeassistant:
  customize:
    switch.sportzimmer_fernseher:
      icon: mdi:television
      friendly_name: Fernseher
    switch.sportzimmer_crosstrainer:
      icon: mdi:run-fast