clear:
  description: >
    Deletes all saved data.

delete:
  description: >
    Deletes a saved state for an entity.
  fields:
    entity_id:
      description: ID of entity to delete from saver.
      example: light.patio

delete_variable:
  description: >
    Deletes a saved variable.
  fields:
    name:
      description: Name of the variable to delete from saver.
      example: counter

execute:
  description: >
    Executes a script using all saved entities and variables.
  fields:
    script:
      description: The script to excute using saved data.

set_variable:
  description: >
    Sets the value to the variable.
  fields:
    name:
      description: Name of the variable to save.
      example: counter
    value:
      description: The new value
      example: 3

save_state:
  description: >
    Saves the state and parameters of the entity.
  fields:
    entity_id:
      description: ID of the entity that should be saved.
      example: light.patio

restore_state:
  description: >
    Executes the script using saved state of the entity.
  fields:
    entity_id:
      description: ID of the entity to restore.
      example: light.patio
    restore_script:
      description: Script used to restore values.
    delete_after_run:
      description: "Deletes the saved state after an execution of the script. Default: true [Optional]"
      example: false
