light:
  - platform: flux_led
    devices:
      192.168.2.63:
        name: Schreibtisch
        mode: "rgb"

  - platform: switch
    name: Arbeitszimmer Lampe
    entity_id: switch.arbeitszimmer_lampe

input_boolean:
  bewegungsmelder_arbeitszimmer_deaktiviert:
    name: Bewegungsmelder deaktiviert
    initial: off
    icon: mdi:sync-off

switch:
  - platform: brematic
    host: !secret brematic_host
    system_code: '10000'
    switches:
      arbeitszimmer_lampe:
        unit_code: '00100'
        friendly_name: Lampe
        
homeassistant:
  customize:
    light.arbeitszimmer_lampe:
      friendly_name: Lampe
      icon: mdi:lamp