input_boolean:
  bewegungsmelder_arbeitszimmer_deaktiviert:
    name: Bewegungsmelder deaktiviert
    icon: mdi:sync-off

timer:
  licht_arbeitszimmer:
    name: Licht Arbeitszimmer
    icon: mdi:timer-off
    duration: 120
    
automation:  
  - alias: 'Licht Arbeitszimmer'
    id: "licht_arbeitszimmer"
    trigger: 
      - id: bewegungsmelder
        platform: state
        entity_id: binary_sensor.bewegungsmelder_arbeitszimmer
        to: 'on'
      - id: timer
        platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.licht_arbeitszimmer 
      - id: schalter
        platform: event
        event_type: zha_event
        event_data:
          device_ieee: 00:15:8d:00:02:13:45:68
          command: attribute_updated
          args:
            attribute_id: 0
            attribute_name: on_off     
            value: 1              
    condition:      
      - condition: or
        conditions:          
            - "{{ trigger.id == 'timer' }}"            
            - "{{ trigger.id == 'schalter' }}"
            - condition: and
              conditions:
                - "{{ is_state('binary_sensor.sonne_tagsueber', 'off') }}"
                - "{{ is_state('binary_sensor.home_office_aktiv', 'off') }}"
                - "{{ is_state('binary_sensor.bewegungsmelder_inaktiv_unterwegs', 'off') }}"
                - "{{ is_state('binary_sensor.bewegungsmelder_inaktiv_staubsauger', 'off') }}"
                - "{{ is_state('input_boolean.bewegungsmelder_arbeitszimmer_deaktiviert', 'off') }}"
    action:
      - choose:
          - conditions:
              - "{{ trigger.id == 'schalter' and is_state('light.arbeitszimmer_regal', 'off') }}"
            sequence:                
              - service: light.turn_on
                entity_id: light.arbeitszimmer_regal
          - conditions:
              - "{{ trigger.id == 'schalter' and is_state('light.arbeitszimmer_regal', 'on') }}"
            sequence:                
              - service: light.turn_off
                entity_id: light.arbeitszimmer_regal          
              - service: timer.cancel
                entity_id: timer.licht_arbeitszimmer                
          - conditions:
              - "{{ trigger.id == 'bewegungsmelder' and is_state('light.arbeitszimmer_regal', 'off') }}"
            sequence:                
              - service: light.turn_on
                entity_id: light.arbeitszimmer_regal
              - service: timer.start
                entity_id: timer.licht_arbeitszimmer                     
          - conditions:
              - "{{ trigger.id == 'timer' }}"
            sequence:                
              - service: light.turn_off
                entity_id: light.arbeitszimmer_regal          

homeassistant:
  customize:
    light.arbeitszimmer_regal:
      friendly_name: Regal
      icon: mdi:led-strip      