input_boolean:
  bewegungsmelder_arbeitszimmer_deaktiviert:
    name: Bewegungsmelder deaktiviert
    icon: mdi:sync-off
           
entity_controller:
  bewegung_arbeitszimmer:
    friendly_name: "Bewegung Arbeitszimmer"
    sensor: binary_sensor.bewegungsmelder_arbeitszimmer
    entities: light.arbeitszimmer_regal
    delay: 120
    behaviours:
      on_enter_overridden: 'off'
    overrides:
      - binary_sensor.sonne_tagsueber
      - binary_sensor.bewegungsmelder_inaktiv_unterwegs  
      - binary_sensor.bewegungsmelder_inaktiv_staubsauger
      - input_boolean.bewegungsmelder_arbeitszimmer_deaktiviert

homeassistant:
  customize:
    light.arbeitszimmer_regal:
      friendly_name: Regal
      icon: mdi:led-strip      