light:
  - platform: flux_led
    devices:
      192.168.2.63:
        name: Schreibtisch
        mode: "rgb"

  - platform: switch
    name: Arbeitszimmer Lampe
    entity_id: switch.arbeitszimmer_lampe

input_boolean:
  bewegungsmelder_arbeitszimmer_deaktiviert:
    name: Bewegungsmelder deaktiviert
    initial: off
    icon: mdi:sync-off

switch:
  - platform: brematic
    host: !secret brematic_host
    switches:
      arbeitszimmer_lampe:
        friendly_name: Lampe
        system_code: "10000"
        unit_code: "00100"

homeassistant:
  customize:
    switch.arbeitszimmer_lampe:
      hidden: true
    light.arbeitszimmer_lampe:
      friendly_name: Lampe
      icon: mdi:lamp