light:
  - platform: flux_led
    devices:
      192.168.2.63:
        name: Schreibtisch
        mode: "rgb"

  - platform: mqtt
    name: "Arbeitszimmer Lampe"
    state_topic: "stat/arbeitszimmerlampe/POWER"
    command_topic: "cmnd/arbeitszimmerlampe/POWER"
    availability_topic: "tele/arbeitszimmerlampe/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
        
input_boolean:
  bewegungsmelder_arbeitszimmer_deaktiviert:
    name: Bewegungsmelder deaktiviert
    initial: off
    icon: mdi:sync-off
        
homeassistant:
  customize:
    light.schreibtisch:
      icon: mdi:desk
    light.arbeitszimmer_lampe:
      friendly_name: Lampe
      icon: mdi:lamp