light:
  - platform: flux_led
    devices:
      192.168.2.63:
        name: Schreibtisch
        mode: "rgb"

  - platform: switch
    name: Arbeitszimmer Lampe
    entity_id: switch.arbeitszimmer_lampe

input_boolean:
  bewegungsmelder_arbeitszimmer_deaktiviert:
    name: Bewegungsmelder deaktiviert
    initial: off
    icon: mdi:sync-off

entity_controller:
  bewegung_arbeitszimmer:
    friendly_name: "Bewegung Arbeitszimmer"
    sensor: binary_sensor.zigate_eac1_presence
    entities:
      - light.schreibtisch
      - light.arbeitszimmer_lampe
    delay: 120
    overrides:
      - binary_sensor.sonne_tagsueber
      - input_boolean.bewegungsmelder_arbeitszimmer_deaktiviert

switch:
  - platform: brematic
    host: 192.168.2.57
    switches:
      arbeitszimmer_lampe:
        friendly_name: Lampe
        system_code: "10000"
        unit_code: "00100"

homeassistant:
  customize:
    switch.arbeitszimmer_lampe:
      hidden: true
    light.arbeitszimmer_lampe:
      friendly_name: Lampe
      icon: mdi:lamp