light:
  - platform: flux_led
    devices:
      192.168.2.63:
        name: Schreibtisch
        mode: "rgb"

  - platform: mqtt
    name: "Arbeitszimmer Lampe"
    state_topic: "stat/arbeitszimmerlampe/POWER"
    command_topic: "cmnd/arbeitszimmerlampe/POWER"
    availability_topic: "tele/arbeitszimmerlampe/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
        
input_boolean:
  bewegungsmelder_arbeitszimmer_deaktiviert:
    name: Bewegungsmelder deaktiviert
    initial: off
    icon: mdi:sync-off
   
entity_controller:
  bewegung_arbeitszimmer:
    friendly_name: "Bewegung Arbeitszimmer"
    sensor: binary_sensor.bewegungsmelder_arbeitszimmer
    entities:
      - light.schreibtisch
      - light.arbeitszimmer_lampe
    delay: 120
    grace_period: 60
    behaviours:
      on_enter_overridden: off
    overrides:
      - device_tracker.pc_arbeit
      - binary_sensor.home_office
      - binary_sensor.sonne_tagsueber      
      - binary_sensor.bewegungsmelder_inaktiv_unterwegs  
      - binary_sensor.bewegungsmelder_inaktiv_staubsauger
      - input_boolean.bewegungsmelder_arbeitszimmer_deaktiviert    
      
homeassistant:
  customize:
    light.schreibtisch:
      icon: mdi:desk
    light.arbeitszimmer_lampe:
      friendly_name: Lampe
      icon: mdi:lamp