input_boolean:
  bewegungsmelder_badezimmer_deaktiviert:
    name: Bewegungsmelder deaktiviert   
    icon: mdi:sync-off

entity_controller:      
  bewegung_badezimmer:
    friendly_name: "Bewegung Badezimmer"
    sensor: binary_sensor.bewegungsmelder_badezimmer
    entity: light.badezimmerschrank
    sensor_type_duration: True
    delay: 180
    overrides:
      - binary_sensor.sonne_tagsueber
      - binary_sensor.bewegungsmelder_inaktiv_unterwegs      
      - binary_sensor.bewegungsmelder_inaktiv_staubsauger
      - input_boolean.bewegungsmelder_badezimmer_deaktiviert
      - input_boolean.baden_aktiv
      
homeassistant:
  customize:
    light.badezimmerschrank:
      icon: mdi:led-strip