light:
  - platform: flux_led
    devices:
      192.168.2.48:
        name: Badezimmerschrank
        mode: "rgb"
#        mode: "grb"

input_boolean:
  bewegungsmelder_badezimmer_deaktiviert:
    name: Bewegungsmelder deaktiviert
    initial: off
    icon: mdi:sync-off

homeassistant:
  customize:
    light.badezimmerschrank:
      icon: mdi:led-strip