input_boolean:
  bewegungsmelder_balkon_deaktiviert:
    name: Bewegungsmelder deaktiviert    
    icon: mdi:sync-off

automation:
  - alias: 'Licht Balkon - Einschalten'
    id: "licht_balkon_einschalten"
    trigger:
      - id: bewegungsmelder_balkon
        platform: state
        entity_id: binary_sensor.bewegungsmelder_balkon
        to: 'on'      
      - id: schalter_balkon
        platform: event
        event_type: zha_event
        event_data:
          device_ieee: 00:15:8d:00:02:c7:62:ce
          command: click
          args:
            click_type: single 
    condition:
      - "{{ is_state('person.dennis', 'home') }}"
      - "{{ is_state('binary_sensor.besuch', 'off') }}"
      - "{{ is_state('binary_sensor.sonne_tagsueber', 'off') }}"
      - "{{ is_state('calendar.borussia_dortmund', 'off') }}"
      - "{{ is_state('input_boolean.bewegungsmelder_balkon_deaktiviert', 'off') }}"
    action:
      - service: light.turn_on
        entity_id: light.balkon_licht
      
  - alias: "Licht Balkon - Ausschalten"
    id: "licht_balkon_ausschalten"
    trigger:
      - platform: state
        entity_id: binary_sensor.bewegungsmelder_wohnzimmer
        to: 'on'
    condition:      
      - condition: state
        entity_id: binary_sensor.besuch
        state: 'off'      
      - condition: state
        entity_id: input_boolean.bewegungsmelder_balkon_deaktiviert
        state: 'off'            
      - condition: state
        entity_id: light.balkon_licht
        state: 'on'
        for:
          seconds: 10
    action:
      - service: light.turn_off
        entity_id: light.balkon_licht

homeassistant:
  customize:
    light.balkon_licht:
      icon: mdi:led-strip