input_boolean:
  bewegungsmelder_balkon_deaktiviert:
    name: Bewegungsmelder deaktiviert    
    icon: mdi:sync-off

  bewegungsmelder_balkon_aktiv:
    name: Bewegungsmelder aktiv
    
timer:
  licht_balkon:
    name: Licht Balkon    
    duration: 600
    
binary_sensor:
  - platform: template
    sensors:
      sonne_balkon:
        friendly_name: "Sonne Balkon"
        value_template: "{{ states('sensor.balkon_helligkeit_mittelwert') | float(0) > 100 }}"
          
automation:
  - alias: 'Licht Balkon - Einschalten'
    id: "licht_balkon_einschalten"
    trigger:
      - id: bewegungsmelder_balkon
        platform: state
        entity_id: binary_sensor.bewegungsmelder_balkon
        to: 'on'      
      - id: schalter_balkon
        platform: event
        event_type: zha_event
        event_data:
          device_ieee: 00:15:8d:00:02:c7:62:ce
          command: click
          args:
            click_type: single 
    condition:
      - "{{ is_state('light.balkon_licht', 'off') }}"
      - "{{ is_state('person.dennis', 'home') }}"
      - "{{ is_state('binary_sensor.sonne_balkon', 'off') }}"
      - "{{ is_state('binary_sensor.balkontuer', 'on') }}"      
      - "{{ is_state('input_boolean.bewegungsmelder_balkon_deaktiviert', 'off') }}"   
      - condition: or
        conditions:          
          - "{{ trigger.id == 'schalter_balkon' }}"
          - "{{ is_state('binary_sensor.besuch', 'off') }}"
          - "{{ is_state('binary_sensor.allein_zu_hause', 'on') }}"          
      - condition: or
        conditions:     
          - "{{ trigger.id == 'bewegungsmelder_balkon' }}"
          - "{{ is_state('calendar.borussia_dortmund', 'off') }}"                   
    action:
      - service: light.turn_on
        entity_id: light.balkon_licht
      - service: input_boolean.turn_on
        entity_id: input_boolean.bewegungsmelder_balkon_aktiv
      - if: "{{ trigger.id == 'schalter_balkon' and (is_state('binary_sensor.besuch', 'on') or is_state('binary_sensor.allein_zu_hause', 'off')) }}"
        then:
          - service: timer.start
            entity_id: timer.licht_balkon
                  
  - alias: "Licht Balkon - Ausschalten"
    id: "licht_balkon_ausschalten"
    trigger:
      - id: bewegungsmelder
        platform: state
        entity_id: binary_sensor.bewegungsmelder_wohnzimmer
        to: 'on'
      - id: timer
        platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.licht_balkon      
      - id: balkontuer
        platform: state
        entity_id: binary_sensor.balkontuer
        to: 'off'          
    condition:      
      - condition: state
        entity_id: input_boolean.bewegungsmelder_balkon_aktiv
        state: 'on'
        for:
          seconds: 10      
      - condition: or
        conditions:     
          - "{{ trigger.id == 'timer' }}"
          - "{{ trigger.id == 'balkontuer' and (is_state('binary_sensor.besuch', 'on') or is_state('binary_sensor.allein_zu_hause', 'off')) }}"
          - "{{ trigger.id == 'bewegungsmelder' and is_state('binary_sensor.besuch', 'off') and is_state('binary_sensor.allein_zu_hause', 'on') }}"
    action:
      - service: light.turn_off
        entity_id: light.balkon_licht
      - service: input_boolean.turn_off
        entity_id: input_boolean.bewegungsmelder_balkon_aktiv
      - if: "{{ not is_state('timer.licht_balkon', 'idle') }}"
        then:
          - service: timer.cancel
            entity_id: timer.licht_balkon        
        
homeassistant:
  customize:
    light.balkon_licht:
      icon: mdi:led-strip