light:
  - platform: flux_led
    devices:
      192.168.2.67:
        name: Balkon Licht
        mode: "rgb"

input_boolean:
  bewegungsmelder_balkon_deaktiviert:
    name: Bewegungsmelder deaktiviert
    initial: off
    icon: mdi:sync-off

automation:
  - alias: 'Licht Balkon - Einschalten'
    trigger:
      - platform: state
        entity_id: binary_sensor.schalter_balkon
        to: 'off'
    action:
      - service: light.toggle
        entity_id: light.balkon_licht
      
  - alias: "Licht Balkon - Ausschalten"
    trigger:
      - platform: state
        entity_id: binary_sensor.bewegungsmelder_wohnzimmer
        to: 'on'
    condition:
      - condition: state
        entity_id: entity_controller.bewegung_balkon
        state: 'active_timer'
      - condition: template
        value_template: >-
          {% set letzte_bewegung = as_timestamp(state_attr("entity_controller.bewegung_balkon", "last_triggered_at")) | timestamp_custom("%s", True) | int  %}
          {% set now = now().strftime("%s") | int %}
          {% set abstand_sekunden = ((now - letzte_bewegung | timestamp_custom("%s") | int)) | int %}

          {{ True if abstand_sekunden >= 10 else False }}
    action:
      - service: light.turn_off
        entity_id: light.balkon_licht

homeassistant:
  customize:
    light.balkon_licht:
      icon: mdi:led-strip