input_boolean:
  bewegungsmelder_flur_deaktiviert:
    name: Bewegungsmelder deaktiviert    
    icon: mdi:sync-off

entity_controller:
  bewegung_flur_vorne:
    friendly_name: "Bewegung Flur vorne"
    sensor: binary_sensor.bewegungsmelder_flur_vorne
    entity: light.flur_vorne
    delay: 180    
    behaviours:
      on_enter_overridden: 'off'
    overrides:
      - binary_sensor.sonne_tagsueber
      - binary_sensor.bewegungsmelder_inaktiv_unterwegs
      - binary_sensor.bewegungsmelder_inaktiv_staubsauger
      - input_boolean.bewegungsmelder_flur_deaktiviert
    night_mode:
      delay: 120
      service_data:
        brightness: 30
      start_time: '23:00:00'
      end_time: '07:00:00'              

  bewegung_flur_hinten:
    friendly_name: "Bewegung Flur hinten"
    sensor: binary_sensor.bewegungsmelder_flur_hinten
    entity: light.flur_hinten
    delay: 180
    grace_period: 60
    behaviours:
      on_enter_overridden: 'off'
    overrides:
      - binary_sensor.sonne_tagsueber
      - binary_sensor.bewegungsmelder_inaktiv_unterwegs
      - binary_sensor.bewegungsmelder_inaktiv_staubsauger
      - input_boolean.bewegungsmelder_flur_deaktiviert  
    night_mode:
      delay: 120
      service_data:
        brightness: 30
      start_time: '23:00:00'
      end_time: '07:00:00'

homeassistant:
  customize:
    light.flur_vorne:
      icon: mdi:led-strip
    light.flur_hinten:
      icon: mdi:led-strip