light:
  - platform: flux_led
    devices:
      192.168.2.54:
        name: Flur vorne
        mode: "rgb"

  - platform: flux_led
    devices:
      192.168.2.71:
        name: Flur hinten
        mode: "rgb"

input_boolean:
  bewegungsmelder_flur_deaktiviert:
    name: Bewegungsmelder deaktiviert
    initial: off
    icon: mdi:sync-off

homeassistant:
  customize:
    light.flur_vorne:
      icon: mdi:led-strip
    light.flur_hinten:
      icon: mdi:led-strip