input_boolean:
  bewegungsmelder_flur_deaktiviert:
    name: Bewegungsmelder deaktiviert    
    icon: mdi:sync-off

timer:
  licht_flur_vorne:
    name: Licht Flur vorne
    icon: mdi:timer-off
    duration: 120
  licht_flur_hinten:
    name: Licht Flur hinten
    icon: mdi:timer-off
    duration: 120
    
template:
  - binary_sensor:
      - name: "Bewegungsmelder Flur inaktiv"
        unique_id: bewegungsmelder_flur_inaktiv
        state: "{{ is_state('binary_sensor.allein_zu_hause', 'off') and is_state('binary_sensor.schlafen_aktiv', 'on') }}"

automation:
  - alias: 'Licht Flur vorne'
    id: "licht_flur_vorne"
    trigger: 
      - id: licht_on
        platform: state
        entity_id: binary_sensor.bewegungsmelder_flur_vorne
        to: 'on'
      - id: licht_off
        platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.licht_flur_vorne
    condition:      
      - condition: or
        conditions:          
            - "{{ trigger.id == 'licht_off' }}"        
            - condition: and
              conditions:
                - "{{ is_state('binary_sensor.sonne_tagsueber', 'off') }}"
                - "{{ is_state('binary_sensor.bewegungsmelder_inaktiv_unterwegs', 'off') }}"
                - "{{ is_state('binary_sensor.bewegungsmelder_inaktiv_staubsauger', 'off') }}"
                - "{{ is_state('input_boolean.bewegungsmelder_flur_deaktiviert', 'off') }}"
    action:
      - if: "{{ trigger.id == 'licht_on' }}"
        then:
          - service: light.turn_on
            entity_id: light.flur_vorne
          - service: timer.start
            entity_id: timer.licht_flur_vorne
      - if: "{{ trigger.id == 'licht_off' }}"
        then:
          - service: light.turn_off
            entity_id: light.flur_vorne    
            
  - alias: 'Licht Flur hinten'
    id: "licht_flur_hinten"
    trigger: 
      - id: licht_on
        platform: state
        entity_id: binary_sensor.bewegungsmelder_flur_hinten
        to: 'on'
      - id: licht_off
        platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.licht_flur_hinten
    condition:      
      - condition: or
        conditions:          
            - "{{ trigger.id == 'licht_off' }}"        
            - condition: and
              conditions:
                - "{{ is_state('binary_sensor.sonne_tagsueber', 'off') }}"
                - "{{ is_state('binary_sensor.bewegungsmelder_flur_inaktiv', 'off') }}"
                - "{{ is_state('binary_sensor.bewegungsmelder_inaktiv_unterwegs', 'off') }}"
                - "{{ is_state('binary_sensor.bewegungsmelder_inaktiv_staubsauger', 'off') }}"
                - "{{ is_state('input_boolean.bewegungsmelder_flur_deaktiviert', 'off') }}"
    action:
      - if: "{{ trigger.id == 'licht_on' }}"
        then:
          - service: light.turn_on
            entity_id: light.flur_hinten
          - service: timer.start
            entity_id: timer.licht_flur_hinten
      - if: "{{ trigger.id == 'licht_off' }}"
        then:
          - service: light.turn_off
            entity_id: light.flur_hinten    
            
homeassistant:
  customize:
    light.flur_vorne:
      icon: mdi:led-strip
    light.flur_hinten:
      icon: mdi:led-strip