light:
  - platform: switch
    name: Kinderzimmer Lampe
    entity_id: switch.kinderzimmer_lampe
          
input_boolean:
  bewegungsmelder_kinderzimmer_deaktiviert:
    name: Bewegungsmelder deaktiviert    
    icon: mdi:sync-off
              
entity_controller:
  bewegung_kinderzimmer:
    friendly_name: "Bewegung Kinerzimmer"
    sensor: binary_sensor.bewegungsmelder_kinderzimmer
    entities:
      - light.kinderzimmer_licht
      - light.kinderzimmer_lampe
    delay: 180
    grace_period: 60
    behaviours:
      on_enter_overridden: 'off'
    overrides:           
      - binary_sensor.sonne_tagsueber      
      - binary_sensor.bewegungsmelder_inaktiv_unterwegs  
      - binary_sensor.bewegungsmelder_inaktiv_staubsauger
      - input_boolean.bewegungsmelder_kinderzimmer_deaktiviert    
      
automation:           
  - alias: "Franzi - Licht Kindezimmer"
    id: "franzi_licht_kinderzimmer"
    trigger:
      - platform: state
        entity_id: person.franzi
      - platform: state
        entity_id: binary_sensor.nachts 
    condition:     
      - condition: or
        conditions:
          - "{{ is_state('person.franzi', 'home') and is_state('binary_sensor.nachts', 'on') and is_state('input_boolean.bewegungsmelder_kinderzimmer_deaktiviert', 'off') }}"
          - "{{ is_state('person.franzi', 'not_home') and is_state('binary_sensor.nachts', 'off') and is_state('input_boolean.bewegungsmelder_kinderzimmer_deaktiviert', 'on') }}"
    action:    
      - if: "{{ is_state('person.franzi', 'home') and is_state('binary_sensor.nachts', 'on') }}"
        then:          
          - service: input_boolean.turn_on
            entity_id: input_boolean.bewegungsmelder_kinderzimmer_deaktiviert  
          - service: light.turn_on
            entity_id: light.kinderzimmer_licht          
      - if: "{{ is_state('person.franzi', 'not_home') and is_state('binary_sensor.nachts', 'off')}}"
        then:          
          - service: input_boolean.turn_off
            entity_id: input_boolean.bewegungsmelder_kinderzimmer_deaktiviert  
          - service: light.turn_off
            entity_id: light.kinderzimmer_licht        
            
homeassistant:
  customize:
    light.kinderzimmer_licht:
      friendly_name: Licht
      icon: mdi:desk
    light.kinderzimmer_lampe:
      friendly_name: Lampe
      icon: mdi:lamp      