input_boolean:
  bewegungsmelder_kinderzimmer_deaktiviert:
    name: Bewegungsmelder deaktiviert    
    icon: mdi:sync-off     
    
input_number:
  helligkeit_kinderzimmer:
    name: Helligkeit Kinderzimmer
    min: 100
    max: 1000
    step: 50 
          
template:
  - binary_sensor:
      - name: "Licht Kinderzimmer"
        unique_id: licht_kinderzimmer
        state: >
          {% set istNachts = is_state('binary_sensor.nachts', 'on') %}
          {% set istDunkel = states('sensor.balkon_helligkeit_mittelwert') | float(0) < states('input_number.helligkeit_kinderzimmer') | float(500)%}
    
          {{ istNachts or istDunkel }}
                    
automation:           
  - alias: "Franzi - Licht Kinderzimmer"
    id: "franzi_licht_kinderzimmer"
    trigger:
      - id: licht_an
        platform: state
        entity_id: binary_sensor.licht_kinderzimmer 
        to: 'on'
      - id: licht_aus
        platform: state
        entity_id: binary_sensor.licht_kinderzimmer 
        to: 'off'
    condition:     
      - "{{ states('light.kinderzimmer_licht') != trigger.to_state.state }}"      
      - condition: or
        conditions:
          - "{{ is_state('person.franzi', 'home') }}"
          - "{{ trigger.id == 'licht_aus'  }}"
    action:                
      - if: "{{ trigger.id == 'licht_an' }}"
        then:          
          - service: light.turn_on
            entity_id: light.kinderzimmer_licht          
        else:        
          - service: light.turn_off
            entity_id: light.kinderzimmer_licht        
            
homeassistant:
  customize:
    light.kinderzimmer_licht:
      friendly_name: Licht
      icon: mdi:desk