light:
  - platform: flux_led
    devices:
      192.168.2.46:
        name: Küche Regal
        mode: "rgb"

  - platform: mqtt
    name: "Küche Schrank"
    state_topic: "stat/kuechenschrank/POWER"
    command_topic: "cmnd/kuechenschrank/POWER"
    availability_topic: "tele/kuechenschrank/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
        
input_boolean:
  bewegungsmelder_kueche_deaktiviert:
    name: Bewegungsmelder deaktiviert
    initial: off
    icon: mdi:sync-off
    
binary_sensor:
  - platform: template
    sensors:
      kuechelregal_abends:
        friendly_name: "Küchenregal abends"
        entity_id:
          - sensor.time        
        value_template: >-
          {% set hour = now().strftime("%H") | int %}
          
          {{ True if hour < 20 else False }}
          
      kuechenschrank_tagsueber:
        friendly_name: "Küchenschrank tagsüber"
        entity_id:
          - sensor.time        
        value_template: >-
          {% set hour = now().strftime("%H") | int %}
          
          {{ True if hour > 20 else False }}