light:
  - platform: switch
    name: Küche Schrank
    entity_id: switch.kuechenschrank
        
input_boolean:
  bewegungsmelder_kueche_deaktiviert:
    name: Bewegungsmelder deaktiviert    
    icon: mdi:sync-off
    
timer:
  licht_kueche:
    name: Licht Küche
    icon: mdi:timer-off
    duration: 120

automation:
  - alias: 'Licht Küche'
    id: "licht_kueche"
    trigger: 
      - id: licht_on
        platform: state
        entity_id: binary_sensor.bewegungsmelder_kueche
        to: 'on'
      - id: licht_off
        platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.licht_kueche 
    condition:      
      - condition: or
        conditions:          
            - "{{ trigger.id == 'licht_off' }}"        
            - condition: and
              conditions:
                - "{{ is_state('binary_sensor.sonne_tagsueber', 'off') }}"
                - "{{ is_state('binary_sensor.bewegungsmelder_inaktiv_unterwegs', 'off') }}"
                - "{{ is_state('binary_sensor.bewegungsmelder_inaktiv_staubsauger', 'off') }}"
                - "{{ is_state('input_boolean.bewegungsmelder_kueche_deaktiviert', 'off') }}"
    action:              
      - if: "{{ trigger.id == 'licht_on' and is_state('binary_sensor.nachts', 'on') }}"
        then:
          - service: light.turn_on
            entity_id: light.kueche_regal
          - service: timer.start
            entity_id: timer.licht_kueche
      - if: "{{ trigger.id == 'licht_on' and is_state('binary_sensor.nachts', 'off') }}"
        then:
          - service: light.turn_on
            entity_id: light.kueche_schrank
          - service: timer.start
            entity_id: timer.licht_kueche            
      - if: "{{ trigger.id == 'licht_off' }}"
        then:
          - service: light.turn_off
            entity_id: light.kueche_regal, light.kueche_schrank
             
homeassistant:
  customize:
    light.kueche_regal:      
      friendly_name: Küche Regal
      
    entity_controller.bewegung_kuechenregal:      
      friendly_name: Bewegung Küchenregal
    entity_controller.bewegung_kuechenschrank:      
      friendly_name: Bewegung Küchenschrank