light:
  - platform: flux_led
    devices:
      192.168.2.46:
        name: Küche Regal
        mode: "rgb"
      192.168.2.68:
        name: Küche Schrank
        mode: "rgbw"

  - platform: template
    lights:
      kuechenschrank:
        friendly_name: Küchenschrank
        value_template: >-
          {{ 'on' if is_state('light.kuche_schrank', 'on') else 'off' }}
        icon_template: >-
          {{ 'mdi:lightbulb-on' if is_state('light.kuche_schrank', 'on') else 'mdi:lightbulb-off' }}
        turn_on:
          - service: light.turn_on
            data:
              entity_id: light.kuche_schrank
              brightness: 255              
        turn_off:
          - service: light.turn_off
            entity_id: light.kuche_schrank       
        
input_boolean:
  bewegungsmelder_kueche_deaktiviert:
    name: Bewegungsmelder deaktiviert
    initial: off
    icon: mdi:sync-off
    
binary_sensor:
  - platform: template
    sensors:
      kuechenschrank_tagsueber:
        friendly_name: "Küchenschrank tagsüber"
        entity_id:
          - sensor.time        
        value_template: >-
          {% set hour = now().strftime("%H") | int %}
          
          {% if hour < 8 or hour > 19 %}
            True
          {% else %}
            False
          {% endif %}