light:
  - platform: flux_led
    devices:
      192.168.2.46:
        name: Küche Regal
        mode: "rgb"

  - platform: switch
    name: Küche Schrank
    entity_id: switch.kuchenschrank
        
input_boolean:
  bewegungsmelder_kueche_deaktiviert:
    name: Bewegungsmelder deaktiviert    
    icon: mdi:sync-off
    
binary_sensor:
  - platform: template
    sensors:
      kuechelregal_inaktiv:
        friendly_name: "Küchenregal inaktiv"   
        value_template: >-
          {% set time = states('sensor.time') %}
          {% set hour = now().strftime("%H") | int %}
          
          {{ True if (hour >= 7 and hour <= 20 ) else False }}
          
      kuechenschrank_inaktiv:
        friendly_name: "Küchenschrank inaktiv"    
        value_template: "{{ True if is_state('binary_sensor.kuechelregal_inaktiv', 'off') else False }}"
          
entity_controller:      
  bewegung_kuechenregal:
    friendly_name: "Bewegung Küchenregal"
    sensor: binary_sensor.bewegungsmelder_kueche
    entity: light.kuche_regal
    delay: 120     
    behaviours:
      on_enter_overridden: off
    overrides:
      - binary_sensor.sonne_tagsueber
      - binary_sensor.kuechelregal_inaktiv
      - binary_sensor.bewegungsmelder_inaktiv_unterwegs
      - binary_sensor.bewegungsmelder_inaktiv_staubsauger
      - input_boolean.bewegungsmelder_kueche_deaktiviert

  bewegung_kuechenschrank:
    friendly_name: "Bewegung Küchenschrank"
    sensor: binary_sensor.bewegungsmelder_kueche
    entity: light.kuche_schrank
    delay: 120
    behaviours:
      on_enter_overridden: off
    overrides:            
      - binary_sensor.sonne_tagsueber
      - binary_sensor.kuechenschrank_inaktiv
      - binary_sensor.bewegungsmelder_inaktiv_unterwegs
      - binary_sensor.bewegungsmelder_inaktiv_staubsauger
      - input_boolean.bewegungsmelder_kueche_deaktiviert          