light:
  - platform: flux_led
    devices:
      192.168.2.46:
        name: Regal
        mode: "rgb"
      192.168.2.68:
        name: Küchenschrank
        mode: "w"

input_boolean:
  bewegungsmelder_kueche_deaktiviert:
    name: Bewegungsmelder deaktiviert
    initial: off
    icon: mdi:sync-off

homeassistant:
  customize:
    light.kueche:
      icon: mdi:led-strip
    timer.licht_kueche:
      hidden: true