light:
  - platform: flux_led
    devices:
      192.168.2.46:
        name: K端che Regal
        mode: "rgb"

  - platform: mqtt
    name: "K端che Schrank"
    state_topic: "stat/kuechenschrank/POWER"
    command_topic: "cmnd/kuechenschrank/POWER"
    availability_topic: "tele/kuechenschrank/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
        
input_boolean:
  bewegungsmelder_kueche_deaktiviert:
    name: Bewegungsmelder deaktiviert
    initial: off
    icon: mdi:sync-off
    
binary_sensor:
  - platform: template
    sensors:
      kuechelregal_inaktiv:
        friendly_name: "K端chenregal inaktiv"   
        value_template: >-
          {% set time = states('sensor.time') %}
          {% set hour = now().strftime("%H") | int %}
          
          {{ True if (hour >= 7 and hour <= 20 ) else False }}
          
      kuechenschrank_inaktiv:
        friendly_name: "K端chenschrank inaktiv"    
        value_template: >-
          {% set time = states('sensor.time') %}
          {% set hour = now().strftime("%H") | int %}
          
          {{ True if ((hour > 20 and hour <= 23 ) or (hour >= 0 and hour < 7 )) else False }}