light:
  - platform: flux_led
    devices:
      192.168.2.46:
        name: Kueche Regal
        mode: "rgb"

  - platform: switch
    name: Küche Schrank
    entity_id: switch.kuechenschrank
        
input_boolean:
  bewegungsmelder_kueche_deaktiviert:
    name: Bewegungsmelder deaktiviert    
    icon: mdi:sync-off
    
binary_sensor:
  - platform: template
    sensors:
      kuechenschrank_inaktiv:
        friendly_name: "Küchenschrank inaktiv"   
        value_template: >-
          {% set hour = now().strftime("%H") | int %}
          
          {{ True if (hour < 7 or hour >= 20 ) else False }}
          
      kuechelregal_inaktiv:
        friendly_name: "Küchenregal inaktiv"    
        value_template: "{{ is_state('binary_sensor.kuechenschrank_inaktiv', 'off') }}"
          
entity_controller:      
  bewegung_kuechenregal:
    friendly_name: "Bewegung Kuechenregal"
    sensor: binary_sensor.bewegungsmelder_kueche
    entity: light.kueche_regal
    delay: 120     
    behaviours:
      on_enter_overridden: 'off'
    overrides:
      - binary_sensor.sonne_tagsueber
      - binary_sensor.kuechelregal_inaktiv
      - binary_sensor.bewegungsmelder_inaktiv_unterwegs
      - binary_sensor.bewegungsmelder_inaktiv_staubsauger
      - input_boolean.bewegungsmelder_kueche_deaktiviert

  bewegung_kuechenschrank:
    friendly_name: "Bewegung Kuechenschrank"
    sensor: binary_sensor.bewegungsmelder_kueche
    entity: light.kueche_schrank
    delay: 120
    behaviours:
      on_enter_overridden: 'off'
    overrides:            
      - binary_sensor.sonne_tagsueber
      - binary_sensor.kuechenschrank_inaktiv
      - binary_sensor.bewegungsmelder_inaktiv_unterwegs
      - binary_sensor.bewegungsmelder_inaktiv_staubsauger
      - input_boolean.bewegungsmelder_kueche_deaktiviert          
      
homeassistant:
  customize:
    light.kueche_regal:      
      friendly_name: Küche Regal
    entity_controller.bewegung_kuechenregal:      
      friendly_name: Bewegung Küchenregal
    entity_controller.bewegung_kuechenschrank:      
      friendly_name: Bewegunge Küchenschrank      
