light:
  - platform: flux_led
    devices:
      192.168.2.61:
        name: Bett
        mode: "rgb"       
    
  - platform: switch
    name: Kleiderschrank
    entity_id: switch.kleiderschrank
    
  - platform: switch
    name: Fernseher Schlafzimmer
    entity_id: switch.schlafzimmer_fernseher_licht

input_boolean:
  bewegungsmelder_schlafzimmer_deaktiviert:
    name: Bewegungsmelder deaktiviert
    initial: off
    icon: mdi:sync-off

automation:
  - alias: "Schlafzimmer Bett - Licht ausschalten"
    trigger:
      - platform: state        
        entity_id: binary_sensor.schalter_schlafzimmer
        to: 'on'
      - platform: state        
        entity_id: sensor.schalter_schlafzimmer
        to: '2'
      - platform: state        
        entity_id: binary_sensor.im_bett
        to: 'on'   
        for:
          seconds: 1
    condition:
      - condition: state
        entity_id: binary_sensor.schlafen_aktiv
        state: 'on'
      - condition: or
        conditions:
        - condition: state
          entity_id: media_player.kodi_schlafzimmer
          state: 'idle'
        - condition: state
          entity_id: media_player.kodi_schlafzimmer
          state: 'off'
      - condition: or
        conditions:
        - condition: state
          entity_id: media_player.tablet_schlafzimmer
          state: 'unavailable'
        - condition: state
          entity_id: media_player.tablet_schlafzimmer
          state: 'off'         
        - condition: state
          entity_id: media_player.tablet_schlafzimmer
          state: 'idle'               
    action:
      - service: light.turn_off
        entity_id: light.bett, light.kleiderschrank, light.flur_vorne, light.flur_hinten, light.badezimmerschrank, light.schreibtisch, light.kuche_regal, light.arbeitszimmer_lampe, light.sportzimmer_regal, light.couch, light.strahler

  - alias: 'Schlafzimmer Schrank - Licht ausschalten'
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.fenster_schlafzimmer
        to: 'on'
    condition:
      - condition: state
        entity_id: light.kleiderschrank
        state: 'on'      
    action:
      - service: light.turn_off
        entity_id:
          - light.kleiderschrank       

homeassistant:
  customize:
    light.bett:
      icon: mdi:bed-queen
    light.kleiderschrank:
      icon: mdi:wardrobe 
    light.fernseher_schlafzimmer:
      icon: mdi:television-classic
      friendly_name: Fernseher

    switch.licht_fernseher_schlafzimmer:
      assumed_state: false