light:
  - platform: flux_led
    devices:
      192.168.2.61:
        name: Bett
        mode: "rgb"
        
  - platform: mqtt
    name: "Kleiderschrank"
    state_topic: "stat/schlafzimmerkleiderschrank/POWER"
    command_topic: "cmnd/schlafzimmerkleiderschrank/POWER"
    availability_topic: "tele/schlafzimmerkleiderschrank/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    
  - platform: switch
    name: Fernseher Schlafzimmer
    entity_id: switch.licht_fernseher_schlafzimmer

input_boolean:
  bewegungsmelder_schlafzimmer_deaktiviert:
    name: Bewegungsmelder deaktiviert
    initial: off
    icon: mdi:sync-off

automation:
  - alias: "Licht Schlafzimmer - ausschalten"
    trigger:
      - platform: state        
        entity_id: binary_sensor.schalter_schlafzimmer
        to: 'on'
      - platform: state        
        entity_id: sensor.schalter_schlafzimmer
        to: '2'
    condition:
      - condition: or
        conditions:
        - condition: state
          entity_id: media_player.kodi_schlafzimmer
          state: 'idle'
        - condition: state
          entity_id: media_player.kodi_schlafzimmer
          state: 'off'
    action:
      - service: light.turn_off
        entity_id: light.bett, light.kleiderschrank, light.sideboard, light.schrank, light.badezimmerschrank, light.schreibtisch, light.kuche_regal, light.arbeitszimmer_lampe, light.sportzimmer_regal

homeassistant:
  customize:
    light.bett:
      icon: mdi:bed-queen
    light.kleiderschrank:
      icon: mdi:wardrobe 
    light.fernseher_schlafzimmer:
      icon: mdi:television-classic
      friendly_name: Fernseher

    switch.licht_fernseher_schlafzimmer:
      assumed_state: false