light:
  - platform: flux_led
    devices:
      192.168.2.61:
        name: Bett
        mode: "rgb"       
    
  - platform: switch
    name: Kleiderschrank
    entity_id: switch.kleiderschrank
    
  - platform: switch
    name: Fernseher Schlafzimmer
    entity_id: switch.schlafzimmer_fernseher_licht

input_boolean:
  bewegungsmelder_schlafzimmer_deaktiviert:
    name: Bewegungsmelder deaktiviert    
    icon: mdi:sync-off

entity_controller:           
  bewegung_schlafzimmer_bett:
    friendly_name: "Bewegung Schlafzimmer Bett"
    sensors: 
      - binary_sensor.bewegungsmelder_bett
      - binary_sensor.bewegungsmelder_schlafzimmer
    entity: light.bett
    delay: 120    
    service_data:
      brightness: 100
    behaviours:
      on_enter_overridden: 'off'
    overrides:
      - binary_sensor.schlafen_inaktiv
      - binary_sensor.sonne_tagsueber    
      - binary_sensor.bewegungsmelder_inaktiv_unterwegs
      - binary_sensor.bewegungsmelder_inaktiv_staubsauger
      - input_boolean.bewegungsmelder_schlafzimmer_deaktiviert
      
  bewegung_schlafzimmer_kleiderschrank:
    friendly_name: "Bewegung Schlafzimmer Kleiderschrank"
    sensor: binary_sensor.bewegungsmelder_schlafzimmer
    entity: light.kleiderschrank
    delay: 120 
    behaviours:
      on_enter_overridden: 'off'
    overrides:
      - binary_sensor.schlafen_aktiv
      - binary_sensor.sonne_tagsueber
      - binary_sensor.fenster_schlafzimmer
      - binary_sensor.bewegungsmelder_inaktiv_unterwegs
      - binary_sensor.bewegungsmelder_inaktiv_staubsauger
      - input_boolean.bewegungsmelder_schlafzimmer_deaktiviert     
           
automation:
  - alias: "Schlafzimmer - Licht ausschalten"
    id: "schlafzimmer_licht_ausschalten"  
    trigger:
      - id: schalter_schlafzimmer
        platform: event
        event_type: zha_event
        event_data:
          device_ieee: 00:15:8d:00:02:13:45:68
          command: attribute_updated
          args:
            attribute_id: 0
            attribute_name: on_off     
            value: 1
      - platform: state        
        entity_id: binary_sensor.im_bett
        to: 'on'   
        for:
          seconds: 1
    condition:
      - condition: state
        entity_id: binary_sensor.schlafen_aktiv
        state: 'on'
      - condition: state
        entity_id: binary_sensor.alarm_aktiv
        state: 'off'        
      - condition: state
        entity_id: binary_sensor.sonne_tagsueber
        state: 'off'             
      - condition: state        
        entity_id: binary_sensor.im_bett
        state: 'on'   
        for:
          seconds: 1               
    action:
      - service: homeassistant.turn_off
        entity_id: group.licht_wohnung

  - alias: "Kleiderschrank - Licht ausschalten"
    id: "kleiderschrank_licht_ausschalten"
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.fenster_schlafzimmer
        to: 'on'
    condition:
      - condition: state
        entity_id: light.kleiderschrank
        state: 'on'      
    action:
      - service: light.turn_off
        entity_id:
          - light.kleiderschrank       

homeassistant:
  customize:
    light.bett:
      icon: mdi:bed-queen
    light.kleiderschrank:
      icon: mdi:wardrobe 
    light.fernseher_schlafzimmer:
      icon: mdi:television-classic
      friendly_name: Fernseher

    switch.licht_fernseher_schlafzimmer:
      assumed_state: false