input_boolean:
  bewegungsmelder_schlafzimmer_deaktiviert:
    name: Bewegungsmelder deaktiviert    
    icon: mdi:sync-off
    
  schlafzimmer_fernseher_licht:
    name: Schlafzimmer Fernseher Licht  
    
timer:
  licht_schlafzimmer:
    name: Licht Schlafzimmer
    icon: mdi:timer-off
    duration: 120
    
light:
  - platform: template
    lights:
      schlafzimmer_fernseher:
        friendly_name: Schlafzimmer Fernseher
        unique_id: schlafzimmer_fernseher_licht
        value_template: "{{ is_state('input_boolean.schlafzimmer_fernseher_licht', 'on') }}"
        icon_template: mdi:television-classic
        turn_on:
          - service: remote.send_command
            target:
              entity_id: remote.broadlink_schlafzimmer_remote
            data:             
              device: schlafzimmer_licht
              command:
                - turn_on    
          - service: input_boolean.turn_on
            entity_id: input_boolean.schlafzimmer_fernseher_licht           
        turn_off:
          - service: remote.send_command
            target:
              entity_id: remote.broadlink_schlafzimmer_remote
            data:                       
              device: schlafzimmer_licht
              command:
                - turn_off
          - service: input_boolean.turn_off
            entity_id: input_boolean.schlafzimmer_fernseher_licht
            
  - platform: switch
    name: Kleiderschrank
    entity_id: switch.kleiderschrank

automation:
  - alias: 'Licht Schlafzimmer'
    id: "licht_schlafzimmer"
    trigger: 
      - id: licht_on
        platform: state
        entity_id: binary_sensor.bewegungsmelder_schlafzimmer
        to: 'on'
      - id: licht_on
        platform: state
        entity_id: binary_sensor.bewegungsmelder_bett
        to: 'on'        
      - id: licht_off
        platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.licht_schlafzimmer 
    condition:      
      - condition: or
        conditions:          
            - "{{ trigger.id == 'licht_off' }}"        
            - condition: and
              conditions:
                - "{{ is_state('binary_sensor.sonne_tagsueber', 'off') }}"
                - "{{ is_state('binary_sensor.schlafen_aktiv', 'off') }}"
                - "{{ is_state('binary_sensor.fenster_schlafzimmer', 'off') }}"
                - "{{ is_state('binary_sensor.bewegungsmelder_inaktiv_unterwegs', 'off') }}"
                - "{{ is_state('binary_sensor.bewegungsmelder_inaktiv_staubsauger', 'off') }}"
                - "{{ is_state('input_boolean.bewegungsmelder_schlafzimmer_deaktiviert', 'off') }}"
                - "{{ is_state('input_boolean.schlafen_einschalten_aktiv', 'off') }}"
    action:
      - if: "{{ trigger.id == 'licht_on' }}"
        then:
          - service: light.turn_on
            entity_id: light.kleiderschrank
          - service: timer.start
            entity_id: timer.licht_schlafzimmer
      - if: "{{ trigger.id == 'licht_off' }}"
        then:
          - service: light.turn_off
            entity_id: light.kleiderschrank   
            
  - alias: "Schlafzimmer - Licht einschalten"
    id: "schlafzimmer_licht_einschalten"  
    trigger:
      - id: schalter_bett
        platform: event
        event_type: zha_event
        event_data:
          device_ieee: 00:15:8d:00:02:13:45:68
          command: attribute_updated
          args:
            attribute_id: 0
            attribute_name: on_off     
            value: 1
      - id: schalter_schlafzimmer
        platform: event
        event_type: zha_event
        event_data:
          device_ieee: 00:12:4b:00:29:2b:72:4b
          command: toggle          
    condition:
      - "{{ is_state('sensor.lichter_eingeschaltet', '0') }}"
      - "{{ is_state('binary_sensor.wecker_aktiv', 'off') }}" 
      - "{{ not states('media_player.kodi_schlafzimmer') in ['playing', 'paused'] }}"
      - "{{ not states('media_player.fire_tv_schlafzimmer') in ['playing', 'paused'] }}"
      - "{{ not states('media_player.tablet_schlafzimmer') in ['playing', 'paused'] }}"
    action:
      - service: light.turn_on
        entity_id: light.bett
        
  - alias: "Schlafzimmer - Licht ausschalten"
    id: "schlafzimmer_licht_ausschalten"  
    trigger:
      - id: schalter_bett
        platform: event
        event_type: zha_event
        event_data:
          device_ieee: 00:15:8d:00:02:13:45:68
          command: attribute_updated
          args:
            attribute_id: 0
            attribute_name: on_off     
            value: 1
      - id: schalter_schlafzimmer
        platform: event
        event_type: zha_event
        event_data:
          device_ieee: 00:12:4b:00:29:2b:72:4b
          command: toggle              
      - id: sensor_bett
        platform: state        
        entity_id: binary_sensor.im_bett
        to: 'on'
        for:
          seconds: 2
    condition:
      - "{{ not is_state('sensor.lichter_eingeschaltet', '0') }}"
      - "{{ is_state('binary_sensor.wecker_aktiv', 'off') }}"
      - condition: or
        conditions:          
          - "{{ trigger.id == 'schalter_bett' or trigger.id == 'schalter_schlafzimmer' }}"
          - condition: and
            conditions:
              - "{{ is_state('binary_sensor.allein_zu_hause', 'on') and is_state('binary_sensor.nachts', 'on') }}"                
              - condition: state        
                entity_id: binary_sensor.im_bett
                state: 'on'   
                for:
                  seconds: 2          
    action:
      - service: script.licht_wohnung_ausschalten     
      
  - alias: "Kleiderschrank - Licht ausschalten"
    id: "kleiderschrank_licht_ausschalten"
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.fenster_schlafzimmer
        to: 'on'
    condition:
      - condition: state
        entity_id: light.kleiderschrank
        state: 'on'      
    action:
      - service: light.turn_off
        entity_id:
          - light.kleiderschrank       

homeassistant:
  customize:
    light.bett:
      icon: mdi:bed-queen
    light.kleiderschrank:
      icon: mdi:wardrobe 
    light.schlafzimmer_fernseher:
      friendly_name: Fernseher
