input_boolean:
  bewegungsmelder_schlafzimmer_deaktiviert:
    name: Bewegungsmelder deaktiviert    
    icon: mdi:sync-off
    
  schlafzimmer_fernseher_licht:
    name: Schlafzimmer Fernseher Licht  
    
timer:
  licht_schlafzimmer:
    name: Licht Schlafzimmer
    icon: mdi:timer-off
    duration: 120
    
template:
  - light:
    - unique_id: schlafzimmer_fernseher_licht
      default_entity_id: light.schlafzimmer_fernseher
      name: Schlafzimmer Fernseher
      icon: mdi:television-classic      
      state: "{{ is_state('input_boolean.schlafzimmer_fernseher_licht', 'on') }}"
      turn_on:
        - target:
            entity_id: remote.broadlink_schlafzimmer_remote
          data:
            device: schlafzimmer_licht
            command:
              - turn_on
          action: remote.send_command
        - entity_id: input_boolean.schlafzimmer_fernseher_licht
          action: input_boolean.turn_on
      turn_off:
        - target:
            entity_id: remote.broadlink_schlafzimmer_remote
          data:
            device: schlafzimmer_licht
            command:
              - turn_off
          action: remote.send_command
        - entity_id: input_boolean.schlafzimmer_fernseher_licht
          action: input_boolean.turn_off
      
light:            
  - platform: switch
    name: Kleiderschrank
    entity_id: switch.kleiderschrank

automation:
  - alias: 'Licht Schlafzimmer - Kleiderschrank'
    id: "licht_schlafzimmer_kleiderschrank"
    trigger: 
      - id: licht_on
        platform: state
        entity_id: binary_sensor.bewegungsmelder_schlafzimmer
        to: 'on'    
      - id: licht_off
        platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.licht_schlafzimmer 
      - id: licht_off
        platform: state
        entity_id:
          - binary_sensor.fenster_schlafzimmer
        to: 'on'          
    condition:      
      - condition: or
        conditions:          
            - "{{ trigger.id == 'licht_off' and is_state('light.kleiderschrank', 'on') }}"        
            - condition: and
              conditions:
                - "{{ is_state('binary_sensor.sonne_tagsueber', 'off') }}"
                - "{{ is_state('binary_sensor.schlafen_aktiv', 'off') }}"
                - "{{ is_state('binary_sensor.fenster_schlafzimmer', 'off') }}"
                - "{{ is_state('binary_sensor.bewegungsmelder_inaktiv_unterwegs', 'off') }}"
                - "{{ is_state('binary_sensor.bewegungsmelder_inaktiv_staubsauger', 'off') }}"
                - "{{ is_state('input_boolean.bewegungsmelder_schlafzimmer_deaktiviert', 'off') }}"
                - "{{ is_state('input_boolean.schlafen_einschalten_aktiv', 'off') }}"
    action:
      - if: "{{ trigger.id == 'licht_off' }}"
        then:
          - service: light.turn_off
            entity_id: light.kleiderschrank         
      - if: "{{ trigger.id == 'licht_on' }}"
        then:
          - service: light.turn_on
            entity_id: light.kleiderschrank
          - service: timer.start
            entity_id: timer.licht_schlafzimmer
            
  - alias: "Licht Schlafzimmer - Schalter"
    id: "schlafzimmer_licht_einschalten"  
    trigger:
      - id: schalter_bett
        platform: event    
        event_type: zha_event
        event_data:
          device_ieee: 00:15:8d:00:01:83:77:4a
          command: click
          args:
            click_type: single             
      - id: schalter_bett
        platform: event    
        event_type: zha_event
        event_data:
          device_ieee: 00:15:8d:00:02:c8:c4:8b
          command: click
          args:
            click_type: single            
    condition:
      - "{{ is_state('binary_sensor.sonne_tagsueber', 'off') }}"
    action:
      - if: "{{ is_state('light.bett', 'off') }}"
        then:        
          - service: light.turn_on
            entity_id: light.bett
        else:
          - service: script.licht_wohnung_ausschalten       

homeassistant:
  customize:
    light.bett:
      icon: mdi:bed-queen
    light.kleiderschrank:
      icon: mdi:wardrobe 
    light.schlafzimmer_fernseher:
      friendly_name: Fernseher
