light:
  - platform: flux_led
    devices:
      192.168.2.61:
        name: Bett
        mode: "rgb"

  - platform: switch
    name: Fernseher Schlafzimmer
    entity_id: switch.licht_fernseher_schlafzimmer

input_boolean:
  bewegungsmelder_schlafzimmer_deaktiviert:
    name: Bewegungsmelder deaktiviert
    initial: off
    icon: mdi:sync-off

automation:
  - alias: "Licht Schlafzimmer - ausschalten"
    initial_state: true
    trigger:
      - platform: event
        event_type: xiaomi_aqara.click
        event_data:
          entity_id: binary_sensor.schalter_schlafzimmer
          click_type: single
    condition:
      - condition: or
        conditions:
        - condition: state
          entity_id: media_player.kodi_schlafzimmer
          state: 'idle'
        - condition: state
          entity_id: media_player.kodi_schlafzimmer
          state: 'off'
    action:
      - service: light.turn_off
        entity_id: light.bett, light.sideboard, light.schrank, light.badezimmerschrank, light.schreibtisch, light.regal, light.arbeitszimmer_lampe

homeassistant:
  customize:
    light.bett:
      icon: mdi:led-strip
    light.fernseher_schlafzimmer:
      icon: mdi:television-classic
      friendly_name: Fernseher

    switch.licht_fernseher_schlafzimmer:
      hidden: true
      assumed_state: false