light:
  - platform: flux_led
    devices:
      192.168.2.61:
        name: Bett
        mode: "rgb"       
    
  - platform: switch
    name: Kleiderschrank
    entity_id: switch.kleiderschrank
    
  - platform: switch
    name: Fernseher Schlafzimmer
    entity_id: switch.schlafzimmer_fernseher_licht

input_boolean:
  bewegungsmelder_schlafzimmer_deaktiviert:
    name: Bewegungsmelder deaktiviert    
    icon: mdi:sync-off

entity_controller:           
  bewegung_schlafzimmer_bett:
    friendly_name: "Bewegung Schlafzimmer Bett"
    sensor: binary_sensor.bewegungsmelder_schlafzimmer
    entity: light.bett
    delay: 120    
    service_data:
      brightness: 100
    night_mode:
      delay: 120
      service_data:
        brightness: 60
      start_time: '23:00:00'
      end_time: '05:00:00'     
    behaviours:
      on_enter_overridden: off
    overrides:
      - binary_sensor.schlafen_inaktiv
      - binary_sensor.sonne_tagsueber    
      - binary_sensor.bewegungsmelder_inaktiv_unterwegs
      - binary_sensor.bewegungsmelder_inaktiv_staubsauger
      - input_boolean.bewegungsmelder_schlafzimmer_deaktiviert

  bewegung_schlafzimmer_kleiderschrank:
    friendly_name: "Bewegung Schlafzimmer Kleiderschrank"
    sensor: binary_sensor.bewegungsmelder_schlafzimmer
    entity: light.kleiderschrank
    delay: 120 
    behaviours:
      on_enter_overridden: off
    overrides:
      - binary_sensor.schlafen_aktiv
      - binary_sensor.sonne_tagsueber
      - binary_sensor.fenster_schlafzimmer
      - binary_sensor.bewegungsmelder_inaktiv_unterwegs
      - binary_sensor.bewegungsmelder_inaktiv_staubsauger
      - input_boolean.bewegungsmelder_schlafzimmer_deaktiviert     
      
automation:
  - alias: "Schlafzimmer Bett - Licht ausschalten"
    trigger:
      - platform: state        
        entity_id: binary_sensor.schalter_schlafzimmer
        to: 'on'
      - platform: state        
        entity_id: sensor.schalter_schlafzimmer
        to: '2'
      - platform: state        
        entity_id: binary_sensor.im_bett
        to: 'on'   
        for:
          seconds: 1
    condition:
      - condition: state
        entity_id: binary_sensor.schlafen_aktiv
        state: 'on'
      - condition: state
        entity_id: binary_sensor.alarm_aktiv
        state: 'off'        
      - condition: state        
        entity_id: binary_sensor.im_bett
        state: 'on'   
        for:
          seconds: 1   
      - condition: or
        conditions:
          - condition: state
            entity_id: media_player.kodi_schlafzimmer
            state: 'unavailable'
          - condition: state
            entity_id: media_player.kodi_schlafzimmer
            state: 'idle'
          - condition: state
            entity_id: media_player.kodi_schlafzimmer
            state: 'off'
      - condition: or
        conditions:
          - condition: state
            entity_id: media_player.tablet_schlafzimmer
            state: 'unavailable'
          - condition: state
            entity_id: media_player.tablet_schlafzimmer
            state: 'off'         
          - condition: state
            entity_id: media_player.tablet_schlafzimmer
            state: 'idle'               
    action:
      - service: homeassistant.turn_off
        entity_id: group.licht_wohnung

  - alias: 'Schlafzimmer Schrank - Licht ausschalten'
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.fenster_schlafzimmer
        to: 'on'
    condition:
      - condition: state
        entity_id: light.kleiderschrank
        state: 'on'      
    action:
      - service: light.turn_off
        entity_id:
          - light.kleiderschrank       

homeassistant:
  customize:
    light.bett:
      icon: mdi:bed-queen
    light.kleiderschrank:
      icon: mdi:wardrobe 
    light.fernseher_schlafzimmer:
      icon: mdi:television-classic
      friendly_name: Fernseher

    switch.licht_fernseher_schlafzimmer:
      assumed_state: false