switch:
  - platform: brematic
    host: !secret brematic_host
    system_code: '00100'
    switches:      
      sportzimmer_regal:
        unit_code: '00100'
        friendly_name: Sportzimmer Regal    
      
light:
  - platform: switch
    name: Sportzimmer Regal
    entity_id: switch.sportzimmer_regal
  
input_boolean:
  bewegungsmelder_sportzimmer_deaktiviert:
    name: Bewegungsmelder deaktiviert
    initial: off
    icon: mdi:sync-off
                
homeassistant:
  customize:
    light.sportzimmer_regal:
      friendly_name: Regal
      icon: mdi:led-strip