input_boolean:
  bewegungsmelder_wohnzimmer_deaktiviert:
    name: Bewegungsmelder deaktiviert
    initial: off
    icon: mdi:sync-off

light:
  - platform: switch
    name: Couch
    entity_id: switch.couch

  - platform: switch
    name: Strahler
    entity_id: switch.strahler

  - platform: switch
    name: Vitrine
    entity_id: switch.vitrine

switch:
  - platform: brematic
    host: !secret brematic_host
    switches:
      vitrine:
        friendly_name: Vitrine
        system_code: "00000"
        unit_code: "00100"

automation:
  - alias: Licht Abends
    trigger:
      platform: state
      entity_id: binary_sensor.sonne_tagsueber
      to: 'off'
    condition:
      - condition: time
        after: '15:00'
      - condition: state
        entity_id: binary_sensor.zu_hause
        state: 'on'
      - condition: state
        entity_id: light.couch
        state: 'off'
      - condition: state
        entity_id: light.strahler
        state: 'off'
    action:
      - service: light.turn_on
        entity_id: light.couch, light.strahler

  - alias: Licht Couch
    trigger:
      - platform: event
        event_type: xiaomi_aqara.cube_action
        event_data:
          entity_id: binary_sensor.cube_wohnzimmer
          action_type: tap_twice
    condition:
      - condition: state
        entity_id: calendar.borussia_dortmund
        state: 'off'
    action:
      - service: light.toggle
        entity_id: light.couch

homeassistant:
  customize:
    light.couch:
      icon: mdi:sofa
    light.strahler:
      icon: mdi:spotlight
    light.vitrine:
      icon: mdi:lightbulb-on-outline