input_boolean:
  bewegungsmelder_wohnzimmer_deaktiviert:
    name: Bewegungsmelder deaktiviert    
    icon: mdi:sync-off

light:
  - platform: switch
    name: Couch
    entity_id: switch.wohnzimmer_couch

  - platform: switch
    name: Strahler
    entity_id: switch.wohnzimmer_strahler

binary_sensor:
  - platform: template
    sensors:
      bewegungsmelder_inaktiv_tagsueber:
        friendly_name: Bewegungsmelder inaktiv tagsüber
        value_template: >
          {% set homeOfficeAktiv = is_state('binary_sensor.home_office', 'on') %}
          {% set schlafenAktiv = is_state('binary_sensor.schlafen_aktiv', 'on') %}
        
          {{ False if homeOfficeAktiv or schlafenAktiv else True }}
          
entity_controller:
  bewegung_wohnzimmer:
    friendly_name: "Bewegung Wohnzimmer"
    sensor: binary_sensor.bewegungsmelder_wohnzimmer
    entities: light.couch
    delay: 60
    behaviours:
      on_enter_overridden: 'off'
    overrides:
      - binary_sensor.sonne_tagsueber  
      - binary_sensor.bewegungsmelder_inaktiv_tagsueber         
      - binary_sensor.bewegungsmelder_inaktiv_unterwegs
      - binary_sensor.bewegungsmelder_inaktiv_staubsauger
      - input_boolean.bewegungsmelder_wohnzimmer_deaktiviert      
      
automation:
  - alias: "Wohnzimmer - Licht Abends"
    id: "wohnzimmer_licht_abends"
    trigger:
      platform: state
      entity_id: binary_sensor.sonne_tagsueber
      to: 'off'
    condition:
      - condition: time
        after: '15:00'
      - condition: state
        entity_id: binary_sensor.zu_hause
        state: 'on'
      - condition: state
        entity_id: binary_sensor.home_office
        state: 'off'
      - condition: state
        entity_id: light.couch
        state: 'off'
      - condition: state
        entity_id: light.strahler
        state: 'off'
      - condition: state
        entity_id: input_boolean.baden_aktiv
        state: 'off'        
    action:
      - service: light.turn_on
        entity_id: light.couch, light.strahler

  - alias: "Wohnzimmer - Licht Couch"
    id: "wohnzimmer_licht_couch"
    trigger:
      - platform: state
        entity_id: sensor.cube_bewegung
    condition:
      - condition: template
        value_template: '{{ True if "double_tap" in trigger.to_state.state else False }}'
      - condition: or
        conditions:          
          - condition: state
            entity_id: calendar.borussia_dortmund
            state: 'off'
          - condition: template
            value_template: '{{ True if "(T.B.A.)" in state_attr("calendar.borussia_dortmund", "message") else False }}'
      - condition: template
        value_template: '{{ is_state("media_player.benachrichtigungen", "playing") == False }}'           
    action:
      - service: light.toggle
        entity_id: light.couch, light.strahler

homeassistant:
  customize:
    light.couch:
      icon: mdi:sofa
    light.strahler:
      icon: mdi:spotlight