input_boolean:
  bewegungsmelder_wohnzimmer_deaktiviert:
    name: Bewegungsmelder deaktiviert
    initial: off
    icon: mdi:sync-off

light:
  - platform: switch
    name: Couch
    entity_id: switch.couch

  - platform: switch
    name: Strahler
    entity_id: switch.strahler

  - platform: switch
    name: Vitrine
    entity_id: switch.vitrine

switch:
  - platform: brematic
    host: !secret brematic_host
    system_code: '10000'
    switches:
      vitrine:
        unit_code: '00010'
        friendly_name: Vitrine

automation:
  - alias: Licht Abends
    trigger:
      platform: state
      entity_id: binary_sensor.sonne_tagsueber
      to: 'off'
    condition:
      - condition: time
        after: '15:00'
      - condition: state
        entity_id: binary_sensor.zu_hause
        state: 'on'
      - condition: state
        entity_id: light.couch
        state: 'off'
      - condition: state
        entity_id: light.strahler
        state: 'off'
    action:
      - service: light.turn_on
        entity_id: light.couch, light.strahler

  - alias: Licht Couch
    trigger:
      - platform: state
        entity_id: sensor.cube_bewegung
    condition:
      - condition: template
        value_template: '{{ True if "double_tap" in trigger.to_state.state else False }}'
      - condition: or
        conditions:          
          - condition: state
            entity_id: calendar.borussia_dortmund
            state: 'off'
          - condition: template
            value_template: '{{ True if "(T.B.A.)" in state_attr("calendar.borussia_dortmund", "message") else False }}'
      - condition: template
        value_template: '{{ is_state("media_player.home_assistant", "playing") == False }}'           
    action:
      - service: light.toggle
        entity_id: light.couch

homeassistant:
  customize:
    light.couch:
      icon: mdi:sofa
    light.strahler:
      icon: mdi:spotlight
    light.vitrine:
      icon: mdi:lightbulb-on-outline