input_boolean:
  bewegungsmelder_wohnzimmer_deaktiviert:
    name: Bewegungsmelder deaktiviert    
    icon: mdi:sync-off

light:
  - platform: switch
    name: Wohnzimmer Couch
    entity_id: switch.wohnzimmer_couch

  - platform: switch
    name: Wohnzimmer Strahler
    entity_id: switch.wohnzimmer_strahler

  - platform: switch
    name: Wohnzimmer Schrank
    entity_id: switch.wohnzimmer_schrank
      
automation:
  - alias: "Wohnzimmer - Licht Abends"
    id: "wohnzimmer_licht_abends"
    trigger:
      - platform: state
        entity_id: binary_sensor.sonne_tagsueber
        to: 'off'
        for: '00:01:00'
    condition:      
      - "{{ (now().hour | int) >= 15 }}"
      - "{{ not is_state('sensor.personen_zu_hause', '0') }}"
      - "{{ is_state('binary_sensor.home_office_aktiv', 'off') }}"
      - "{{ is_state('binary_sensor.baden_aktiv', 'off') }}"      
      - "{{ is_state('light.wohnzimmer_couch', 'off') }}"
      - "{{ is_state('light.wohnzimmer_strahler', 'off') }}"
      - "{{ is_state('light.wohnzimmer_schrank', 'off') }}"     
    action:
      - if: "{{ is_state('switch.watchtv_wohnzimmer', 'on') }}"
        then:
          - service: light.turn_on
            entity_id: light.wohnzimmer_strahler
        else:
          - service: light.turn_on
            entity_id: light.wohnzimmer_schrank

  - alias: "Wohnzimmer - Licht Nachts"
    id: "wohnzimmer_licht_nachts"
    trigger:
      - platform: state
        entity_id: binary_sensor.nachts
        to: 'on'
    condition:      
      - "{{ not is_state('sensor.personen_zu_hause', '0') }}"
      - "{{ is_state('binary_sensor.home_office_aktiv', 'off') }}"
      - "{{ is_state('binary_sensor.baden_aktiv', 'off') }}"      
      - "{{ is_state('light.wohnzimmer_strahler', 'off') }}"      
    action:
      - service: light.turn_on
        entity_id: light.wohnzimmer_strahler      
      - service: light.turn_off
        entity_id: light.wohnzimmer_schrank
            
  - alias: "Wohnzimmer - Licht Couch"
    id: "wohnzimmer_licht_couch"
    trigger:
      - id: cube_wohnzimmer
        platform: event
        event_type: zha_event
        event_data:
          device_ieee: 00:15:8d:00:01:10:0d:7a
          command: knock   
    condition:
      - condition: or
        conditions:          
          - "{{ is_state('calendar.borussia_dortmund', 'off') }}"
          - "{{ True if '(T.B.A.)' in state_attr('calendar.borussia_dortmund', 'message') else False }}"
      - "{{ is_state('media_player.home_assistant', 'playing') == False }}"
    action:
      - service: light.toggle
        entity_id: light.wohnzimmer_schrank
            
homeassistant:
  customize:
    light.wohnzimmer_couch:
      icon: mdi:sofa
    light.wohnzimmer_strahler:
      icon: mdi:spotlight
    light.wohnzimmer_schrank:
      icon: mdi:cupboard