input_boolean:
  bewegungsmelder_wohnzimmer_deaktiviert:
    name: Bewegungsmelder deaktiviert    
    icon: mdi:sync-off

light:
  - platform: switch
    name: Wohnzimmer Couch
    entity_id: switch.wohnzimmer_couch

  - platform: switch
    name: Wohnzimmer Schrank
    entity_id: switch.wohnzimmer_schrank
      
  - platform: switch
    name: Discokugel
    entity_id: switch.discokugel
    
  - platform: switch
    name: Lichterkette
    entity_id: switch.lichterkette
    
automation:
  - alias: "Wohnzimmer - Licht Abends"
    id: "wohnzimmer_licht_abends"
    trigger:
      - platform: state
        entity_id: binary_sensor.sonne_tagsueber
        to: 'off'
        for: '00:01:00'
    condition:      
      - "{{ (now().hour | int) >= 15 }}"
      - "{{ is_state('binary_sensor.erwachsene_zu_hause', 'on') }}"
      - "{{ is_state('binary_sensor.home_office_aktiv', 'off') }}"
      - "{{ is_state('binary_sensor.baden_aktiv', 'off') }}"     
      - "{{ is_state('light.wohnzimmer_couch', 'off') }}"
      - "{{ is_state('light.wohnzimmer_schrank', 'off') }}"     
    action:
      - if: "{{ is_state('switch.watchtv_wohnzimmer', 'on') }}"
        then:
          - service: light.turn_on
            entity_id: light.wohnzimmer_couch
        else:
          - service: light.turn_on
            entity_id: light.wohnzimmer_schrank

  - alias: "Wohnzimmer - Licht Nachts"
    id: "wohnzimmer_licht_nachts"
    trigger:
      - platform: state
        entity_id: binary_sensor.nachts
        to: 'on'
    condition:      
      - "{{ is_state('binary_sensor.erwachsene_zu_hause', 'on') }}"
      - "{{ is_state('binary_sensor.home_office_aktiv', 'off') }}"
      - "{{ is_state('binary_sensor.baden_aktiv', 'off') }}"      
      - "{{ is_state('light.wohnzimmer_couch', 'off') }}"      
    action:
      - service: light.turn_on
        entity_id: light.wohnzimmer_couch      
      - service: light.turn_off
        entity_id: light.wohnzimmer_schrank
           
  - alias: "Wohnzimmer - Licht Tagsüber"
    id: "wohnzimmer_licht_tagsueber"
    trigger:
      - platform: state
        entity_id: binary_sensor.sonne_tagsueber
        to: 'on'
        for: '00:01:00'
    condition:   
      - condition: or
        conditions:               
          - "{{ is_state('light.wohnzimmer_schrank', 'on') }}"
          - "{{ is_state('light.wohnzimmer_couch', 'on') }}"
    action:
      - service: light.turn_off
        entity_id: light.wohnzimmer_couch, light.wohnzimmer_schrank     
      - service: light.turn_off
        entity_id: light.wohnzimmer_schrank
        
#  - alias: "Weihnachtsbeleuchtung"
#    id: "Weihnachtsbeleuchtung"
#    trigger:
#      - platform: state
#        entity_id: binary_sensor.weihnachtsbeleuchtung
#        to: 'on'
#    condition:               
#      - "{{ is_state('binary_sensor.adventszeit', 'on') }}"        
#    action:
#      - service: light.turn_on
#        entity_id: light.weihnachtsstern, light.lichterkette
            
homeassistant:
  customize:
    light.wohnzimmer_couch:
      icon: mdi:sofa
    light.wohnzimmer_schrank:
      icon: mdi:cupboard
    light.discokugel:
      icon: mdi:party-popper      
#    light.weihnachtsstern:
#      icon: mdi:star-four-points  
    light.lichterkette:
      icon: mdi:string-lights            