input_boolean:
  bewegungsmelder_wohnzimmer_deaktiviert:
    name: Bewegungsmelder deaktiviert    
    icon: mdi:sync-off

light:
  - platform: switch
    name: Wohnzimmer Couch
    entity_id: switch.wohnzimmer_couch

  - platform: switch
    name: Wohnzimmer Strahler
    entity_id: switch.wohnzimmer_strahler

  - platform: switch
    name: Wohnzimmer Schrank
    entity_id: switch.wohnzimmer_schrank
      
automation:
  - alias: "Wohnzimmer - Licht Abends"
    id: "wohnzimmer_licht_abends"
    trigger:
      - platform: state
        entity_id: binary_sensor.sonne_tagsueber
        to: 'off'
        for: '00:01:00'
    condition:      
      - "{{ (now().hour | int) >= 15 }}"
      - "{{ is_state('person.dennis', 'home') }}"
      - "{{ is_state('binary_sensor.home_office_aktiv', 'off') }}"
      - "{{ is_state('binary_sensor.baden_aktiv', 'off') }}"      
      - "{{ is_state('light.wohnzimmer_couch', 'off') }}"
      - "{{ is_state('light.wohnzimmer_strahler', 'off') }}"
      - "{{ is_state('light.wohnzimmer_schrank', 'off') }}"     
    action:
      - service: light.turn_on
        entity_id: light.wohnzimmer_schrank

  - alias: "Wohnzimmer - Licht Couch"
    id: "wohnzimmer_licht_couch"
    trigger:
      - id: cube_wohnzimmer
        platform: event
        event_type: zha_event
        event_data:
          device_ieee: 00:15:8d:00:01:10:0d:7a
          command: knock   
    condition:
      - condition: or
        conditions:          
          - "{{ is_state('calendar.borussia_dortmund', 'off') }}"
          - "{{ True if '(T.B.A.)' in state_attr('calendar.borussia_dortmund', 'message') else False }}"
      - "{{ is_state('media_player.home_assistant', 'playing') == False }}"
    action:
      - service: light.toggle
        entity_id: light.wohnzimmer_schrank

  - alias: "Weihnachtsbeleuchtung"
    id: "weihnachtsbeleuchtung"
    trigger:
      - platform: state
        entity_id: binary_sensor.weihnachtsbeleuchtung        
    condition:     
      - condition: or
        conditions:       
          - "{{ states('sensor.personen_zu_hause')|int(0) > 0 }}"
          - "{{ trigger.to_state.state == 'off' }}"
    action:
      - if: "{{ trigger.to_state.state == 'on' }}"
        then:
          - service: light.turn_on
            entity_id: light.leuchtstern, light.balkon_lichterkette
      - if: "{{ trigger.to_state.state == 'off' }}"
        then:
          - service: light.turn_off
            entity_id: light.leuchtstern, light.balkon_lichterkette
            
homeassistant:
  customize:
    light.wohnzimmer_couch:
      icon: mdi:sofa
    light.wohnzimmer_strahler:
      icon: mdi:spotlight
    light.wohnzimmer_schrank:
      icon: mdi:cupboard