input_boolean:
  bewegungsmelder_zimmer_aaron_deaktiviert:
    name: Bewegungsmelder deaktiviert
    icon: mdi:sync-off

timer:
  licht_zimmer_aaron:
    name: Licht Zimmer Aaron
    icon: mdi:timer-off
    duration: 120
  
input_number:
  helligkeit_zimmer_aaron:
    name: Helligkeit Zimmer Aaron
    min: 100
    max: 1000
    step: 50 
    
template:
  - binary_sensor:
      - name: "Licht Zimmer Aaron"
        unique_id: licht_zimmer_aaron
        state: >
          {% set istNachts = is_state('binary_sensor.nachts', 'on') %}
          {% set istDunkel = states('sensor.balkon_helligkeit_mittelwert') | float(0) < states('input_number.helligkeit_zimmer_aaron') | float(500)%}
    
          {{ istNachts or istDunkel }}
            
automation:  
  - alias: 'Licht Zimmer Aaron'
    id: "licht_zimmer_aaron"
    trigger: 
      - id: licht_schalter
        platform: event
        event_type: zha_event
        event_data:
          device_ieee: 54:ef:44:10:00:e8:72:44
          command: 2_single
          args:
            click_type: single       
      - id: licht_an
        platform: state
        entity_id: binary_sensor.bewegungsmelder_zimmer_aaron
        to: 'on'
      - id: licht_an_dunkel
        platform: state
        entity_id: binary_sensor.licht_zimmer_aaron
        to: 'on'        
      - id: licht_aus
        platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.licht_zimmer_aaron
      - id: licht_aus
        platform: state
        entity_id: binary_sensor.sonne_tagsueber 
        to: 'on'        
      - id: licht_aus
        platform: state
        entity_id: binary_sensor.licht_zimmer_aaron
        to: 'off'            
    condition:          
      - condition: or
        conditions:   
            - "{{ trigger.id == 'licht_schalter' and is_state('binary_sensor.home_office_aktiv', 'off') }}"     
            - "{{ trigger.id == 'licht_aus' }}"                    
            - condition: and
              conditions:
                - "{{ trigger.id == 'licht_an_dunkel' }}"
                - "{{ is_state('binary_sensor.erwachsene_zu_hause', 'on') }}"
            - condition: and
              conditions:
                - "{{ is_state('binary_sensor.sonne_tagsueber', 'off') }}"
                - "{{ is_state('binary_sensor.bewegungsmelder_inaktiv_unterwegs', 'off') }}"
                - "{{ is_state('binary_sensor.bewegungsmelder_inaktiv_staubsauger', 'off') }}"
                - "{{ is_state('input_boolean.bewegungsmelder_zimmer_aaron_deaktiviert', 'off') }}"
                - "{{ is_state('binary_sensor.home_office_aktiv', 'off') }}"
                - "{{ is_state('light.zimmer_aaron_licht', 'off') or not is_state('timer.licht_zimmer_aaron', 'idle') }}"
    action:
      - if: "{{ trigger.id == 'licht_schalter' }}"
        then:
          - service: light.toggle
            entity_id: light.zimmer_aaron_licht      
      - if: "{{ trigger.id == 'licht_an_dunkel' }}"
        then:
          - service: light.turn_on
            entity_id: light.zimmer_aaron_licht
      - if: "{{ trigger.id == 'licht_an' }}"
        then:
          - service: light.turn_on
            entity_id: light.zimmer_aaron_licht
          - service: timer.start
            entity_id: timer.licht_zimmer_aaron
      - if: "{{ trigger.id == 'licht_aus' }}"
        then:
          - service: light.turn_off
            entity_id: light.zimmer_aaron_licht        