input_number:
  batteriestand_warnlevel:
    name: Warnlevel
    min: 10
    max: 80
    step: 5

sensor:
  - platform: attributes
    friendly_name: "Batteriestand"
    attribute: battery_level
    unit_of_measurement: "%"
    entities:
      - zwave.fibaro_badezimmer
      - zigate.bewegungsmelder_flur_vorne
      - zigate.bewegungsmelder_flur_hinten
      - zigate.bewegungsmelder_arbeitszimmer
      - zigate.bewegungsmelder_schlafzimmer
      - zigate.bewegungsmelder_kueche
      - zigate.bewegungsmelder_balkon
      - zigate.fenster_wohnzimmer
      - zigate.fenster_schlafzimmer
      - zigate.fenster_kueche
      - zigate.fenster_arbeitszimmer
      - zigate.fenster_sportzimmer
      - zigate.thermometer_flur
      - zigate.thermometer_balkon
      - zigate.thermometer_schlafzimmer
      - zigate.thermometer_arbeitszimmer
      - zigate.thermometer_kueche
      - zigate.thermometer_sportzimmer
      - zigate.thermometer_parkplatz
      - zigate.thermometer_kuehlschrank
      - zigate.thermometer_gefrierschrank
      - zigate.thermometer_hardware
      - zigate.tuersensor
      - zigate.tuerklingel
      - zigate.briefkasten
      - binary_sensor.schalter_wohnzimmer
      - binary_sensor.schalter_schlafzimmer
      - binary_sensor.schalter_flur
      - binary_sensor.schalter_balkon
      - binary_sensor.vibration_wohnzimmer
      - binary_sensor.vibration_schlafzimmer
      - binary_sensor.cube_wohnzimmer

  - platform: template
    sensors:
      batteriestand_niedrig:
        friendly_name: Batteriestand niedrig
        entity_id:
          - sensor.time
          - input_number.batteriestand_warnlevel
          - sensor.laufzeit_minuten
        icon_template: >
          {% set min_battery_level = states.input_number.batteriestand_warnlevel.state | int -%}
          {% set ns = namespace(found=false) -%}
          {% for entity_id in states.group.batteriestand.attributes.entity_id -%}
            {% set parts = entity_id.split('.') -%}
            {% if (states(entity_id) | replace("%","") | int) <= min_battery_level -%}
              {% set ns.found = true -%}
            {% endif -%}
          {% endfor -%}

          {% if ns.found == True %}
            mdi:battery-charging-10
          {% else %}
            mdi:battery
          {% endif %}
        value_template: >
          {% set min_battery_level = states.input_number.batteriestand_warnlevel.state | int -%}
          {% set ns = namespace(found=0) -%}
          {% for entity_id in states.group.batteriestand.attributes.entity_id -%}
            {% set parts = entity_id.split('.') -%}
            {% if (states(entity_id) | replace("%","") | int) <= min_battery_level -%}
              {% set ns.found = ns.found + 1 -%}
            {% endif -%}
          {% endfor -%}
          {{ ns.found }}

automation:
  - alias: 'Batteriestand niedrig'
    trigger:
      - platform: time
        at: '19:15:00'
    condition:
      - condition: state
        entity_id: binary_sensor.zu_hause
        state: 'on'
      - condition: template
        value_template: >
          {% set count_entities = states.sensor.batteriestand_niedrig.state | int -%}

          {{ count_entities > 0 }}
    action:
      - service: !secret tts_service
        data_template:
          message: >-
            {% set min_battery_level = states.input_number.batteriestand_warnlevel.state | int -%}
            {% set count_entities = states.sensor.batteriestand_niedrig.state | int -%}

            {% if count_entities > 1 %}
              {{ "Der Batteriestand der folgenden Geräte ist niedrig. " }}
            {% else %}
              {{ "Der Batteriestand des folgenden Gerätes ist niedrig. " }}
            {% endif %}

            {%- for entity_id in states.group.batteriestand.attributes.entity_id -%}
              {%- set parts = entity_id.split('.') -%}
              {%- if (states(entity_id) | replace("%","") | int) <= min_battery_level -%}
                {{ states[parts[0]][parts[1]].name }},
              {%- endif -%}
            {%- endfor -%}