input_number:
  batteriestand_warnlevel:
    name: Warnlevel
    min: 10
    max: 80
    step: 5

sensor:
  - platform: attributes
    friendly_name: "Batteriestand"
    attribute: battery_level
    unit_of_measurement: "%"
    entities:
      - zigate.bewegungsmelder_flur_vorne
      - zigate.bewegungsmelder_flur_hinten
      - zigate.bewegungsmelder_arbeitszimmer
      - zigate.bewegungsmelder_sportzimmer
      - zigate.bewegungsmelder_schlafzimmer
      - zigate.bewegungsmelder_kueche
      - zigate.bewegungsmelder_balkon
      - zigate.fenster_wohnzimmer
      - zigate.fenster_schlafzimmer
      - zigate.fenster_kueche
      - zigate.fenster_arbeitszimmer
      - zigate.fenster_sportzimmer
      - zigate.thermometer_flur
      - zigate.thermometer_balkon
      - zigate.thermometer_schlafzimmer
      - zigate.thermometer_arbeitszimmer
      - zigate.thermometer_kueche
      - zigate.thermometer_sportzimmer
      - zigate.thermometer_parkplatz
      - zigate.thermometer_kuehlschrank
      - zigate.thermometer_hardware
      - zigate.tuersensor
      - zigate.tuer_kuehlschrank
      - zigate.tuer_gefrierschrank
      - binary_sensor.schalter_wohnzimmer
      - binary_sensor.schalter_schlafzimmer
      - binary_sensor.schalter_flur
      - binary_sensor.schalter_balkon
      - binary_sensor.vibration_wohnzimmer
      - binary_sensor.vibration_schlafzimmer
      - binary_sensor.cube_wohnzimmer

  - platform: template
    sensors:
      batteriestand_niedrig:
        friendly_name: Batteriestand niedrig
        entity_id:
          - sensor.time
          - input_number.batteriestand_warnlevel
          - sensor.laufzeit_minuten
        icon_template: >
          {% set min_battery_level = states('input_number.batteriestand_warnlevel') | int -%}
          {% set ns = namespace(found=false) -%}
          {% for entity_id in state_attr('group.batteriestand', 'entity_id') -%}
            {% set parts = entity_id.split('.') -%}
            {% if (states(entity_id) | replace("%","") | int) <= min_battery_level -%}
              {% set ns.found = true -%}
            {% endif -%}
          {% endfor -%}

          {% if ns.found == True %}
            mdi:battery-charging-10
          {% else %}
            mdi:battery
          {% endif %}
        value_template: >
          {% set min_battery_level = states('input_number.batteriestand_warnlevel') | int -%}
          {% set ns = namespace(found=0) -%}
          
          {% for entity_id in state_attr('group.batteriestand', 'entity_id') -%}
            {% set parts = entity_id.split('.') -%}
            {% if (states(entity_id) | replace("%","") | int) <= min_battery_level -%}
              {% set ns.found = ns.found + 1 -%}
            {% endif -%}
          {% endfor -%}
          
          {{ ns.found | int }}