person:

device_tracker:
  - platform: fritz
    host: !secret fritzbox_host
    username: !secret fritzbox_username
    password: !secret fritzbox_password
    interval_seconds: 5
    consider_home: 60
    new_device_defaults:
      track_new_devices: false

  - platform: phonetracker
    url: !secret phonetracker_url
    token: !secret phonetracker_token
    devices:
      - HandyGPS

fritzbox:
  devices:
    - host: !secret fritzbox_host
      username: !secret fritzbox_username
      password: !secret fritzbox_password

sensor:
  - platform: fritzbox_callmonitor
    name: Telefon
    phonebook: 0
    username: !secret fritzbox_username
    password: !secret fritzbox_password

  - platform: fritzbox_calllist
    name: Anrufliste
    host: !secret fritzbox_host
    username: !secret fritzbox_username
    password: !secret fritzbox_password

#  - platform: fritzbox_netmonitor
#    name: Netmonitor
#    host: !secret fritzbox_host
#    username: !secret fritzbox_username
#    password: !secret fritzbox_password

  - platform: places
    name: Aufenthaltsort Handy
    devicetracker_id: device_tracker.handygps
    options: street_street_number,city
    api_key: !secret openstreetmap_email
    display_zone: hide
    scan_interval: 60

  - platform: template
    sensors:
      gaeste_wlan_ssid:
        friendly_name: "Gäste-Wlan SSID"
        value_template: >-
          {{ state_attr('switch.gaste_wlan', 'SSID')}}
        icon_template: >-
            {% if is_state('switch.gaste_wlan', 'on') == True %}
              mdi:wifi
            {% else %}
              mdi:wifi-off
            {% endif %}
      gaeste_wlan_password:
        friendly_name: "Gäste-Wlan Passwort"
        value_template: >-
          {{ state_attr('switch.gaste_wlan', 'Password')}}
        icon_template: >-
            {% if is_state('switch.gaste_wlan', 'on') == True %}
              mdi:wifi-strength-4-lock
            {% else %}
              mdi:wifi-strength-lock-outline
            {% endif %}

binary_sensor:
  - platform: template
    sensors:
      zu_hause:
        friendly_name: "zu Hause"
        device_class: occupancy
        value_template: >-
          {% if is_state('device_tracker.handy', 'home')
            or is_state('device_tracker.handygps', 'home')
          %}
            true
          {% else %}
            false
          {% endif %}

proximity:
  home:
    devices:
      - device_tracker.handy
      - device_tracker.handygps
    tolerance: 50

shell_command:
  send_position: "curl -X POST '{{ url }}?lat={{ states.device_tracker.netzwerkdj.attributes.latitude }}&lon={{ states.device_tracker.netzwerkdj.attributes.longitude }}&timestamp={{ as_timestamp(now()) | int }}'"

switch:
  - platform: fritzbox_guestwifi
    name: "Gäste Wlan"
    wlan_password: !secret fritzbox_guest_password
    host: !secret fritzbox_host
    username: !secret fritzbox_username
    password: !secret fritzbox_password
    interface: 2

automation:
  - alias: "Gäste-Wlan eingeschaltet - TTS"
    initial_state: true
    trigger:
      - platform: state
        entity_id: switch.gaste_wlan
        to: 'on'
    action:
      service: !secret tts_service
      data_template:
        echo: "wohnzimmer"
        message: >-
          Der Gastzugang wurde eingeschaltet. Der Name lautet "{{ state_attr('switch.gaste_wlan', 'SSID') }}". Das Passwort ist "{{ state_attr('switch.gaste_wlan', 'Password') }}".

  - alias: "Gäste-Wlan ausgeschaltet - TTS"
    initial_state: true
    trigger:
      - platform: state
        entity_id: switch.gaste_wlan
        to: 'off'
    action:
      service: !secret tts_service
      data_template:
        echo: "wohnzimmer"
        message: >-
          Der Gastzugang wurde ausgeschaltet.


  - alias: "Zu Hause - Standort aktualisieren"
    initial_state: true
    trigger:
      - platform: state
        entity_id: device_tracker.handy
        to: 'home'
    action:
      - service: shell_command.send_position
        data:
          url: !secret phonetracker_send_position_url
      - service: device_tracker.see
        data_template:
          dev_id: handygps
          location_name: 'home'
          gps: ["{{ states.device_tracker.netzwerkdj.attributes.latitude }}", "{{ states.device_tracker.netzwerkdj.attributes.longitude }}"]

homeassistant:
  customize:
    sensor.netmonitor:
      friendly_name: Fritzbox
      icon: mdi:router-wireless
    switch.gaste_wlan:
      icon: mdi:wifi
    binary_sensor.zu_hause:
      hidden: true

    sensor.aufenthaltsort_handy:
      friendly_name: Aufenthaltsort
      icon: mdi:google-maps
    proximity.home:
      friendly_name: Entfernung

    device_tracker.edimaxwohnzimmerradio:
      icon: mdi:power-socket-eu
      friendly_name: Wohnzimmer Radio
    device_tracker.edimaxschlafzimmerradio:
      icon: mdi:power-socket-eu
      friendly_name: Schlafzimmer Radio

    device_tracker.tplinkarbeitszimmerradio:
      icon: mdi:power-socket-eu
      friendly_name: Arbeitszimmer Radio
    device_tracker.tplinkkuecheradio:
      icon: mdi:power-socket-eu
      friendly_name: Küche Radio
    device_tracker.tplinkbadezimmerradio:
      icon: mdi:power-socket-eu
      friendly_name: Badezimmer Radio
    device_tracker.tplinkwohnzimmermonitor:
      icon: mdi:power-socket-eu
      friendly_name: Wohnzimmer Monitor
    device_tracker.tplinkflurradio:
      icon: mdi:power-socket-eu
      friendly_name: Flur Radio
    device_tracker.tplinkwaschmaschine:
      icon: mdi:power-socket-eu
      friendly_name: Waschmaschine
    device_tracker.tplinktrockner:
      icon: mdi:power-socket-eu
      friendly_name: Trockner
    device_tracker.tplinkschlafzimmerfernseher:
      icon: mdi:power-socket-eu
      friendly_name: Schlafzimmer Fernseher
    device_tracker.fritzrepeater:
      icon: mdi:wifi
      friendly_name: Repeater

    device_tracker.computer:
      icon: mdi:desktop-classic
    device_tracker.pihomeassistant:
      icon: mdi:home-assistant
    device_tracker.broadlinkwohnzimmer:
      icon: mdi:remote
    device_tracker.broadlinkschlafzimmer:
      icon: mdi:remote
    device_tracker.diskstation:
      icon: mdi:server-network
    device_tracker.netzwerkdj:
      icon: mdi:router-wireless
    device_tracker.epsondrucker:
      icon: mdi:printer
    device_tracker.brematicgateway:
      icon: mdi:signal-variant
    device_tracker.maxheizung:
      icon: mdi:radiator
    device_tracker.xiaomivacuum:
      icon: mdi:robot-vacuum-variant

    device_tracker.echokueche:
      icon: mdi:amazon-alexa
    device_tracker.echowohnzimmer:
      icon: mdi:amazon-alexa
    device_tracker.echoschlafzimmer:
      icon: mdi:amazon-alexa
    device_tracker.echoflur:
      icon: mdi:amazon-alexa

    device_tracker.tabletwohnzimmer:
      icon: mdi:tablet-android
    device_tracker.tabletbadezimmer:
      icon: mdi:tablet-android
    device_tracker.tabletschlafzimmer:
      icon: mdi:tablet-android
    device_tracker.tabletkueche:
      icon: mdi:tablet-android

    device_tracker.firetvschlafzimmer:
      icon: mdi:fire
    device_tracker.firetvbadezimmer:
      icon: mdi:fire
    device_tracker.firetvsportzimmer:
      icon: mdi:fire

    device_tracker.handy:
      icon: mdi:cellphone
    device_tracker.handygps:
      icon: mdi:cellphone
      hidden: true
    device_tracker.handyurlaub:
      hidden: true

    device_tracker.magichomeflurvorne:
      icon: mdi:lightbulb-on-outline
    device_tracker.magichomeflurhinten:
      icon: mdi:lightbulb-on-outline
    device_tracker.magichomebadezimmer:
      icon: mdi:lightbulb-on-outline
    device_tracker.magichomeschlafzimmer:
      icon: mdi:lightbulb-on-outline
    device_tracker.magichomekueche:
      icon: mdi:lightbulb-on-outline
    device_tracker.magichomekuechenschraenke:
      icon: mdi:lightbulb-on-outline
      hidden: true
    device_tracker.magichomearbeitszimmer:
      icon: mdi:lightbulb-on-outline
    device_tracker.magichomebalkon:
      icon: mdi:lightbulb-on-outline

    device_tracker.soundbar:
      icon: mdi:music-note
    device_tracker.dreamscreen:
      icon: mdi:track-light

    device_tracker.piliving:
      icon: mdi:raspberrypi
      friendly_name: Wohnzimmer
    device_tracker.pibath:
      icon: mdi:raspberrypi
      friendly_name: Badezimmer
    device_tracker.pikitchen:
      icon: mdi:raspberrypi
      friendly_name: Küche
    device_tracker.pisleeping:
      icon: mdi:raspberrypi
      friendly_name: Schlafzimmer
    device_tracker.picorridor:
      icon: mdi:raspberrypi
      friendly_name: Flur
    device_tracker.piworking:
      icon: mdi:raspberrypi
      friendly_name: Arbeitszimmer
    device_tracker.pibalcony:
      icon: mdi:raspberrypi
      friendly_name: Balkon
    device_tracker.pimultimedia:
      icon: mdi:speaker-wireless
      friendly_name: Multimedia

    device_tracker.tabletprestigio:
      hidden: true
    device_tracker.laptopdj:
      hidden: true