input_text:
  guest_wifi_ssid:
    name: 'Gäste Wlan - SSID'
    
  guest_wifi_password:
    name: 'Gäste Wlan - Password'

sensor:    
  - platform: template
    sensors:
      gaeste_wlan_ssid:
        friendly_name: "Gäste-Wlan SSID"
        value_template: "{{ states('input_text.guest_wifi_ssid') }}"
        icon_template: "{{ 'mdi:wifi' if is_state('switch.fritz_box_7272_wi_fi_pretty_fly_for_a_wifi', 'on') else 'mdi:wifi-off' }}"
            
      gaeste_wlan_password:
        friendly_name: "Gäste-Wlan Passwort"
        value_template: "{{ states('input_text.guest_wifi_password') }}"
        icon_template: "{{ 'mdi:wifi-strength-4-lock' if is_state('switch.fritz_box_7272_wi_fi_pretty_fly_for_a_wifi', 'on') else 'mdi:wifi-strength-lock-outline' }}"
            
      heimnetz_offline:
        friendly_name: Geräte offline
        icon_template: >
          {% set wifiOffline = expand('group.heimnetz')
            | selectattr('state','eq','not_home') 
            | map(attribute='name')
            | list %}

          {{ 'mdi:access-point-network' if wifiOffline | length == 0 else 'mdi:access-point-network-off' }}
        value_template: >
          {% set wifiOffline = expand('group.heimnetz')
            | selectattr('state','eq','not_home') 
            | map(attribute='name')
            | list %}

          {{ wifiOffline | length }}            

automation:
  - alias: "Gäste-Wlan eingeschaltet"
    id: "gaeste_wlan_eingeschaltet"
    trigger:
      - platform: state
        entity_id: switch.fritz_box_7272_wi_fi_pretty_fly_for_a_wifi
        from: 'off'
        to: 'on'        
    action:
      - service: !secret tts_service
        data:
          echo: "wohnzimmer"
          message: >-
            Der Gastzugang wurde eingeschaltet. Der Name lautet "{{ states('sensor.gaeste_wlan_ssid') }}".
            Das Passwort ist "{{ states('sensor.gaeste_wlan_password') }}".

  - alias: "Gäste-Wlan ausgeschaltet"
    id: "gaeste_wlan_ausgeschaltet"
    trigger:
      - platform: state
        entity_id: switch.fritz_box_7272_wi_fi_pretty_fly_for_a_wifi
        from: 'on'
        to: 'off'
    action:        
      - service: !secret tts_service
        data:
          echo: "wohnzimmer"
          message: >-
            Der Gastzugang wurde ausgeschaltet.

  - alias: "Wlan offline"
    id: "wlan_offline"
    trigger:
      - platform: state
        entity_id: switch.fritz_box_7272_wi_fi_netzwerkdj
        from: 'on'
        for: '00:30:00'
    action:
      - choose:
          - conditions:
            - condition: state
              entity_id: person.dennis
              state: 'not_home'
            sequence:
              - service: notify.telegram
                data:                  
                  message: "Das Wlan ist seit 30 Minuten offline"
        default:
          - service: !secret tts_service
            data:
              message: "Das Wlan ist seit 30 Minuten offline"    

homeassistant:
  customize:
    sensor.netmonitor:
      friendly_name: Fritzbox
      icon: mdi:router-wireless
      
    sensor.speedtest_download:
      icon: mdi:download-network
    sensor.speedtest_upload:
      icon: mdi:upload-network
      
    device_tracker.squeezebox:
      icon: mdi:music-box-outline       
    device_tracker.fritzrepeater:
      icon: mdi:wifi
    device_tracker.computer:
      icon: mdi:desktop-classic
    device_tracker.computerarbeit:
      icon: mdi:desktop-classic
      friendly_name: Computer Arbeit
    device_tracker.pihomeassistant:
      icon: mdi:home-assistant
    device_tracker.broadlinkschlafzimmer:
      icon: mdi:remote
    device_tracker.diskstation:
      icon: mdi:server-network
    device_tracker.netzwerkdj:
      icon: mdi:router-wireless
      friendly_name: Netzwerk
    device_tracker.epsondrucker:
      icon: mdi:printer
    device_tracker.xiaomivacuum:
      icon: mdi:robot-vacuum-variant
    device_tracker.xiaomifan:
      icon: mdi:fan      
    device_tracker.soundbar:
      icon: mdi:music-note
    device_tracker.fernseherwohnzimmer:
      icon: mdi:television
    device_tracker.kamerawohnzimmer:
      icon: mdi:cctv

  customize_glob:
    device_tracker.tasmota*:
      icon: mdi:developer-board     
    device_tracker.radio*:
      icon: mdi:raspberry-pi
    device_tracker.magichome*:
      icon: mdi:lightbulb-on-outline
    device_tracker.firetv*:
      icon: mdi:fire
    device_tracker.tablet*:
      icon: mdi:tablet-android
    device_tracker.echo*:
      icon: mdi:amazon-alexa
    device_tracker.shelly*:
      icon: mdi:connection
    device_tracker.handy*:
      icon: mdi:cellphone
    device_tracker.tplink*:
      icon: mdi:power-socket-eu
    device_tracker.edimax*:
      icon: mdi:power-socket-eu      