input_text:
  guest_wifi_ssid:
    name: 'Gäste Wlan - SSID'
    
  guest_wifi_password:
    name: 'Gäste Wlan - Password'

sensor:
  - platform: fritzbox_netmonitor
    name: Netmonitor
    host: !secret fritzbox_host
    
  - platform: template
    sensors:
      netmonitor_uptime:
        friendly_name: "Fritzbox - Laufzeit"    
        value_template: >-
          {% set onlineSeconds = state_attr('sensor.netmonitor','uptime') | int %}
          
          {%if onlineSeconds == 0 or onlineSeconds == None %}
            -
          {% else %}
            {% set now = as_timestamp(now()) | int %}
            {% set lastReboot = now - onlineSeconds | int %}
            {% set weekday = lastReboot | timestamp_custom("%w", True) | int %}

            {{ ['Montag','Dienstag','Mittwoch','Donnerstag','Freitag','Samstag','Sonntag'][weekday-1] }}, {{ lastReboot | timestamp_custom("%d.%m.%Y", True) | string }}               
          {% endif %}
        icon_template: >-
          mdi:calendar-range        
           
      netmonitor_data_sent:
        friendly_name: "Fritzbox - Daten gesendet" 
        unit_of_measurement: GB
        value_template: >-
          {% set bytesSent = (state_attr('sensor.netmonitor','bytes_sent')) %}
          {{ (bytesSent / 1024 / 1024 / 1024) | round(2) if bytesSent else '-' }}         
        icon_template: >-
          mdi:upload-network
          
      netmonitor_data_received:
        friendly_name: "Fritzbox - Daten empfangen"   
        unit_of_measurement: GB
        value_template: >-               
          {% set bytesReceived = (state_attr('sensor.netmonitor','bytes_received')) %}
          {{ (bytesReceived / 1024 / 1024 / 1024) | round(2) if bytesReceived else '-' }}
        icon_template: >-
          mdi:download-network          
          
      gaeste_wlan_ssid:
        friendly_name: "Gäste-Wlan SSID"
        value_template: >-
          {{ states('input_text.guest_wifi_ssid')}}
        icon_template: >-
            {% if is_state('switch.fritzbox_7272_guest_wifi', 'on') == True %}
              mdi:wifi
            {% else %}
              mdi:wifi-off
            {% endif %}
            
      gaeste_wlan_password:
        friendly_name: "Gäste-Wlan Passwort"
        value_template: >-
          {{ states('input_text.guest_wifi_password')}}
        icon_template: >-
            {% if is_state('switch.fritzbox_7272_guest_wifi', 'on') == True %}
              mdi:wifi-strength-4-lock
            {% else %}
              mdi:wifi-strength-lock-outline
            {% endif %}
            
      heimnetz_offline:
        friendly_name: Geräte offline
        icon_template: >
          {% set time = states('sensor.time') %}
          {% set ns = namespace(found=false) -%}

          {%- for entity_id in state_attr('group.heimnetz', 'entity_id') -%}
            {% set parts = entity_id.split('.') -%}
            
            {% if states(entity_id) == 'not_home' %}
              {% set ns.found = true -%}
            {% endif %}
          {%- endfor %}

          {% if ns.found == True %}
            mdi:access-point-network-off
          {% else %}
            mdi:access-point-network
          {% endif %}
        value_template: >
          {% set ns = namespace(found=0) -%}

          {%- for entity_id in state_attr('group.heimnetz', 'entity_id') -%}
            {% set parts = entity_id.split('.') -%}
            
            {% if states(entity_id) == 'not_home' %}
              {% set ns.found = ns.found + 1 -%}
            {% endif %}
          {%- endfor %}

          {{ ns.found | int }}            
    
automation:
  - alias: "Gäste-Wlan eingeschaltet - TTS"
    trigger:
      - platform: state
        entity_id: switch.fritzbox_7272_guest_wifi
        from: 'off'
        to: 'on'
    action:
      service: !secret tts_service
      data_template:
        echo: "wohnzimmer"
        message: >-
          Der Gastzugang wurde eingeschaltet. Der Name lautet "{{ states('sensor.gaeste_wlan_ssid') }}".
          Das Passwort ist "{{ states('sensor.gaeste_wlan_password') }}".

  - alias: "Gäste-Wlan ausgeschaltet - TTS"
    trigger:
      - platform: state
        entity_id: switch.fritzbox_7272_guest_wifi
        from: 'on'
        to: 'off'
    action:
      service: !secret tts_service
      data_template:
        echo: "wohnzimmer"
        message: >-
          Der Gastzugang wurde ausgeschaltet.

homeassistant:
  customize:
    sensor.netmonitor:
      friendly_name: Fritzbox
      icon: mdi:router-wireless
    switch.fritzbox_wifi:
      friendly_name: Wlan
    switch.fritzbox_7272_guest_wifi:
      friendly_name: Gäste Wlan

    device_tracker.tplinkwohnzimmerradio:
      icon: mdi:power-socket-eu
      friendly_name: Wohnzimmer Radio
    device_tracker.tplinkschlafzimmerradio:
      icon: mdi:power-socket-eu
      friendly_name: Schlafzimmer Radio
    device_tracker.tplinkkuecheradio:
      icon: mdi:power-socket-eu
      friendly_name: Küche Radio
    device_tracker.tplinkbadezimmerradio:
      icon: mdi:power-socket-eu
      friendly_name: Badezimmer Radio
    device_tracker.tplinkwohnzimmermonitor:
      icon: mdi:power-socket-eu
      friendly_name: Wohnzimmer Monitor
    device_tracker.tplinkflurradio:
      icon: mdi:power-socket-eu
      friendly_name: Flur Radio
    device_tracker.tplinkwaschmaschine:
      icon: mdi:power-socket-eu
      friendly_name: Waschmaschine
    device_tracker.tplinktrockner:
      icon: mdi:power-socket-eu
      friendly_name: Trockner
    device_tracker.tplinkkellerradio:
      icon: mdi:power-socket-eu
      friendly_name: Keller Radio
    device_tracker.tplinkschlafzimmerfernseher:
      icon: mdi:power-socket-eu
      friendly_name: Schlafzimmer Fernseher
    device_tracker.tplinksportzimmerfernseher:
      icon: mdi:power-socket-eu
      friendly_name: Sportzimmer Fernseher
    device_tracker.edimaxsportzimmerlicht:
      icon: mdi:power-socket-eu
      friendly_name: Sportzimmer Licht
    device_tracker.edimaxcrosstrainer:
      icon: mdi:power-socket-eu
      friendly_name: Crosstrainer
    device_tracker.fritzrepeater:
      icon: mdi:wifi
      friendly_name: Repeater
    device_tracker.pihole:
      icon: mdi:pi-hole

    device_tracker.computer:
      icon: mdi:desktop-classic
    device_tracker.pc:
      icon: mdi:desktop-classic
      friendly_name: Computer
    device_tracker.computerarbeit:
      icon: mdi:desktop-classic
      friendly_name: Computer Arbeit
    device_tracker.pihomeassistant:
      icon: mdi:home-assistant
    device_tracker.broadlinkschlafzimmer:
      icon: mdi:remote
    device_tracker.diskstation:
      icon: mdi:server-network
    device_tracker.netzwerkdj:
      icon: mdi:router-wireless
      friendly_name: Netzwerk
    device_tracker.epsondrucker:
      icon: mdi:printer
    device_tracker.maxheizung:
      icon: mdi:radiator
    device_tracker.xiaomivacuum:
      icon: mdi:robot-vacuum-variant
    device_tracker.xiaomifan:
      icon: mdi:fan

    device_tracker.echokueche:
      icon: mdi:amazon-alexa
    device_tracker.echowohnzimmer:
      icon: mdi:amazon-alexa
    device_tracker.echobadezimmer:
      icon: mdi:amazon-alexa
    device_tracker.echoschlafzimmer:
      icon: mdi:amazon-alexa
    device_tracker.echoflur:
      icon: mdi:amazon-alexa

    device_tracker.tabletwohnzimmer:
      icon: mdi:tablet-android
    device_tracker.tabletbadezimmer:
      icon: mdi:tablet-android
    device_tracker.tabletschlafzimmer:
      icon: mdi:tablet-android
    device_tracker.tabletkueche:
      icon: mdi:tablet-android
    device_tracker.tabletbalkon:
      icon: mdi:tablet-android

    device_tracker.firetvschlafzimmer:
      icon: mdi:fire
    device_tracker.firetvbadezimmer:
      icon: mdi:fire
    device_tracker.firetvsportzimmer:
      icon: mdi:fire

    device_tracker.handy:
      icon: mdi:cellphone
    device_tracker.handygps:
      icon: mdi:cellphone
    device_tracker.handymqtt:
      icon: mdi:cellphone 
    device_tracker.handyfritzbox:
      icon: mdi:cellphone      
    device_tracker.handyping:
      icon: mdi:cellphone           

    device_tracker.magichomeflurvorne:
      icon: mdi:lightbulb-on-outline
    device_tracker.magichomeflurhinten:
      icon: mdi:lightbulb-on-outline
    device_tracker.magichomebadezimmer:
      icon: mdi:lightbulb-on-outline
    device_tracker.magichomeschlafzimmer:
      icon: mdi:lightbulb-on-outline
    device_tracker.magichomekueche:
      icon: mdi:lightbulb-on-outline
    device_tracker.magichomearbeitszimmer:
      icon: mdi:lightbulb-on-outline
    device_tracker.magichomebalkon:
      icon: mdi:lightbulb-on-outline

    device_tracker.soundbar:
      icon: mdi:music-note
    device_tracker.fernseherwohnzimmer:
      icon: mdi:television
    device_tracker.kamerawohnzimmer:
      icon: mdi:cctv
      friendly_name: Kamera
      
    device_tracker.radiowohnzimmer:
      icon: mdi:raspberry-pi
      friendly_name: Wohnzimmer
    device_tracker.radiobadezimmer:
      icon: mdi:raspberry-pi
      friendly_name: Badezimmer
    device_tracker.radiokueche:
      icon: mdi:raspberry-pi
      friendly_name: Küche
    device_tracker.radioschlafzimmer:
      icon: mdi:raspberry-pi
      friendly_name: Schlafzimmer
    device_tracker.radioflur:
      icon: mdi:raspberry-pi
      friendly_name: Flur
    device_tracker.radioarbeitszimmer:
      icon: mdi:raspberry-pi
      friendly_name: Arbeitszimmer
    device_tracker.radiobalkon:
      icon: mdi:raspberry-pi
      friendly_name: Balkon
    device_tracker.radiokeller:
      icon: mdi:raspberry-pi
      friendly_name: Keller
      
    device_tracker.tasmotaarbeitszimmerlampe:
      icon: mdi:developer-board
    device_tracker.tasmotaarbeitszimmerradio:
      icon: mdi:developer-board
    device_tracker.tasmotabalkonradio:
      icon: mdi:developer-board
    device_tracker.tasmotakuechenschrank:
      icon: mdi:developer-board
    device_tracker.tasmotaladegeraet:
      icon: mdi:developer-board
    device_tracker.tasmotamonitorlinks:
      icon: mdi:developer-board
    device_tracker.tasmotamonitorrechts:
      icon: mdi:developer-board
    device_tracker.tasmotaspuelmaschine:
      icon: mdi:developer-board
      
    device_tracker.esptuerklingel:
      icon: mdi:wifi-star
      friendly_name: Türklingel

    sensor.speedtest_download:
      icon: mdi:download-network
    sensor.speedtest_upload:
      icon: mdi:upload-network      