input_text:
  guest_wifi_ssid:
    name: 'Gäste Wlan - SSID'
    
  guest_wifi_password:
    name: 'Gäste Wlan - Password'

sensor:
#  - platform: fritzbox_netmonitor
#    name: Netmonitor
#    host: !secret fritzbox_host
    
  - platform: template
    sensors:
      netmonitor_status:
        friendly_name: "Fritzbox - Status"    
        value_template: >-
          {% set fritzboxStatus = states('sensor.netmonitor') %}
          
          {{ '-' if fritzboxStatus == 'unknown' else fritzboxStatus }}          
        icon_template: mdi:table-network    
          
      netmonitor_uptime:
        friendly_name: "Fritzbox - Laufzeit"    
        value_template: >-
          {% set onlineSeconds = state_attr('sensor.netmonitor','uptime') | int %}
          
          {% if onlineSeconds == 0 or onlineSeconds == None %}
            -
          {% else %}
            {% set now = as_timestamp(now()) | int %}
            {% set lastReboot = now - onlineSeconds | int %}
            {% set weekday = lastReboot | timestamp_custom("%w", True) | int %}

            {{ ['Montag','Dienstag','Mittwoch','Donnerstag','Freitag','Samstag','Sonntag'][weekday-1] }}, {{ lastReboot | timestamp_custom("%d.%m.%Y", True) | string }}               
          {% endif %}
        icon_template: >-
          mdi:calendar-range        
           
      netmonitor_data_sent:
        friendly_name: "Fritzbox - Daten gesendet" 
        unit_of_measurement: GB
        value_template: >-
          {% set bytesSent = (state_attr('sensor.netmonitor','bytes_sent')) %}
          {{ (bytesSent / 1024 / 1024 / 1024) | round(2) if bytesSent else '-' }}         
        icon_template: >-
          mdi:upload-network
          
      netmonitor_data_received:
        friendly_name: "Fritzbox - Daten empfangen"   
        unit_of_measurement: GB
        value_template: >-               
          {% set bytesReceived = (state_attr('sensor.netmonitor','bytes_received')) %}
          {{ (bytesReceived / 1024 / 1024 / 1024) | round(2) if bytesReceived else '-' }}
        icon_template: >-
          mdi:download-network          
          
      gaeste_wlan_ssid:
        friendly_name: "Gäste-Wlan SSID"
        value_template: >-
          {{ states('input_text.guest_wifi_ssid')}}
        icon_template: >-
            {% if is_state('switch.fritzbox_7272_guest_wifi', 'on') == True %}
              mdi:wifi
            {% else %}
              mdi:wifi-off
            {% endif %}
            
      gaeste_wlan_password:
        friendly_name: "Gäste-Wlan Passwort"
        value_template: >-
          {{ states('input_text.guest_wifi_password')}}
        icon_template: >-
            {% if is_state('switch.fritzbox_7272_guest_wifi', 'on') == True %}
              mdi:wifi-strength-4-lock
            {% else %}
              mdi:wifi-strength-lock-outline
            {% endif %}
            
      heimnetz_offline:
        friendly_name: Geräte offline
        icon_template: >
          {% set wifiOffline = expand('group.heimnetz')
            | selectattr('state','eq','not_home') 
            | map(attribute='name')
            | list %}

          {{ 'mdi:access-point-network' if wifiOffline | length == 0 else 'mdi:access-point-network-off' }}
        value_template: >
          {% set wifiOffline = expand('group.heimnetz')
            | selectattr('state','eq','not_home') 
            | map(attribute='name')
            | list %}

          {{ wifiOffline | length }}            
    
automation:
  - alias: "Gäste-Wlan eingeschaltet"
    id: "gaeste_wlan_eingeschaltet"
    trigger:
      - platform: state
        entity_id: switch.fritzbox_7272_guest_wifi
        from: 'off'
        to: 'on'
    action:
      service: !secret tts_service
      data_template:
        echo: "wohnzimmer"
        message: >-
          Der Gastzugang wurde eingeschaltet. Der Name lautet "{{ states('sensor.gaeste_wlan_ssid') }}".
          Das Passwort ist "{{ states('sensor.gaeste_wlan_password') }}".

  - alias: "Gäste-Wlan ausgeschaltet"
    id: "gaeste_wlan_ausgeschaltet"
    trigger:
      - platform: state
        entity_id: switch.fritzbox_7272_guest_wifi
        from: 'on'
        to: 'off'
    action:
      service: !secret tts_service
      data_template:
        echo: "wohnzimmer"
        message: >-
          Der Gastzugang wurde ausgeschaltet.

homeassistant:
  customize:
    sensor.netmonitor:
      friendly_name: Fritzbox
      icon: mdi:router-wireless
      
    switch.fritzbox_wifi:
      friendly_name: Wlan
    switch.fritzbox_7272_guest_wifi:
      friendly_name: Gäste Wlan
      
    sensor.speedtest_download:
      icon: mdi:download-network
    sensor.speedtest_upload:
      icon: mdi:upload-network
      
    device_tracker.fritzrepeater:
      icon: mdi:wifi
    device_tracker.computer:
      icon: mdi:desktop-classic
    device_tracker.computerarbeit:
      icon: mdi:desktop-classic
      friendly_name: Computer Arbeit
    device_tracker.pihomeassistant:
      icon: mdi:home-assistant
    device_tracker.broadlinkschlafzimmer:
      icon: mdi:remote
    device_tracker.diskstation:
      icon: mdi:server-network
    device_tracker.netzwerkdj:
      icon: mdi:router-wireless
      friendly_name: Netzwerk
    device_tracker.epsondrucker:
      icon: mdi:printer
    device_tracker.xiaomivacuum:
      icon: mdi:robot-vacuum-variant
    device_tracker.xiaomifan:
      icon: mdi:fan      
    device_tracker.soundbar:
      icon: mdi:music-note
    device_tracker.fernseherwohnzimmer:
      icon: mdi:television
    device_tracker.kamerawohnzimmer:
      icon: mdi:cctv

  customize_glob:
    device_tracker.tasmota*:
      icon: mdi:developer-board     
    device_tracker.radio*:
      icon: mdi:raspberry-pi
    device_tracker.magichome*:
      icon: mdi:lightbulb-on-outline
    device_tracker.firetv*:
      icon: mdi:fire
    device_tracker.tablet*:
      icon: mdi:tablet-android
    device_tracker.echo*:
      icon: mdi:amazon-alexa
    device_tracker.shelly*:
      icon: mdi:connection
    device_tracker.handy*:
      icon: mdi:cellphone
    device_tracker.tplink*:
      icon: mdi:power-socket-eu
    device_tracker.edimax*:
      icon: mdi:power-socket-eu      