mqtt:
  broker: !secret mqtt_host
  client_id: !secret mqtt_clientid
  username: !secret mqtt_username
  password: !secret mqtt_password

binary_sensor:
  - platform: mqtt
    name: "Bluetooth Gateway"
    state_topic: "lwt_topic"
    payload_on: "online"
    payload_off: "offline"
    device_class: connectivity

switch:
  - platform: mqtt
    name: "Ladegerät"
    state_topic: "stat/ladegeraet/POWER"
    command_topic: "cmnd/ladegeraet/POWER"
    availability_topic: "tele/ladegeraet/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    icon: "mdi:battery-charging"

homeassistant:
  customize:
    binary_sensor.bluetooth_gateway:
      icon: mdi:bluetooth-connect