mqtt:
  broker: !secret mqtt_host
  client_id: !secret mqtt_clientid
  username: !secret mqtt_username
  password: !secret mqtt_password

binary_sensor:
  - platform: mqtt
    name: "Bluetooth Gateway"
    state_topic: "lwt_topic"
    payload_on: "online"
    payload_off: "offline"
    device_class: connectivity

  - platform: mqtt
    name: "Winthing"
    state_topic: "winthing/system/online"
    payload_on: "true"
    payload_off: "false"
    device_class: connectivity

homeassistant:
  customize:
    binary_sensor.bluetooth_gateway:
      icon: mdi:access-point-network