homeassistant:
  customize:
    switch.monitor:
      icon: mdi:monitor

    switch.waschmaschine:
      icon: mdi:washing-machine
    switch.trockner:
      icon: mdi:tumble-dryer

  customize_glob:
    switch.*_radio:
      icon: mdi:radio