xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - mac: !secret xiaomi_mac
      key: !secret xiaomi_password

homeassistant:
  customize:
    device_tracker.xiaomigateway:
      icon: mdi:cube