xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - mac: !secret xiaomi_mac
      key: !secret xiaomi_password

sensor:
  - platform: template
    sensors:
      cube_wohnzimmer_status:
        friendly_name: Xiaomi Cube
        entity_id:
          - binary_sensor.cube_wohnzimmer
        value_template: >
          {% set lastState = state_attr("binary_sensor.cube_wohnzimmer", "last_action") %}

          {% if lastState == None %}
            Unbekannt
          {% elif lastState == 'flip90' %}
            Drehen 90°
          {% elif lastState == 'flip180' %}
            Drehen 180°
          {% elif lastState == 'move' %}
            Bewegung
          {% elif lastState == 'shake_air' %}
            Schütteln
          {% elif lastState == 'swing' %}
            Schwingen
          {% elif lastState == 'alert' %}
            Alarm
          {% elif lastState == 'wakeup' %}
            Aufgewacht
          {% elif lastState == 'free_fall' %}
            Freier Fall
          {% elif lastState == 'rotate' %}
            Rotieren
          {% elif lastState == 'tap_twice' %}
            Klopfen
          {% else %}
            Unbekannt
          {% endif %}
        icon_template: >
            mdi:cube-outline

      vibration_wohnzimmer_status:
        friendly_name: Vibration Status
        value_template: >
          {% if is_state('binary_sensor.vibration_wohnzimmer', 'unknown') or state_attr('binary_sensor.vibration_wohnzimmer', 'last_action') == None %}
            Unbekannt
          {% else %}
            {% set lastState = state_attr('binary_sensor.vibration_wohnzimmer', 'last_action') %}

            {% if lastState == 'vibrate' %}
              Vibration
            {% elif lastState == 'tilt' %}
              Neigung
            {% elif lastState == 'free_fall' %}
              Freier Fall
            {% else %}
              Unbekannt
            {% endif %}
          {% endif %}
        icon_template: >
            mdi:vibrate

      vibration_schlafzimmer_status:
        friendly_name: Vibration Status
        value_template: >
          {% if is_state('binary_sensor.vibration_schlafzimmer', 'unknown') or state_attr('binary_sensor.vibration_schlafzimmer', 'last_action') == None %}
            Unbekannt
          {% else %}
            {% set lastState = state_attr('binary_sensor.vibration_schlafzimmer', 'last_action') %}

            {% if lastState == 'vibrate' %}
              Vibration
            {% elif lastState == 'tilt' %}
              Neigung
            {% elif lastState == 'free_fall' %}
              Freier Fall
            {% else %}
              Unbekannt
            {% endif %}
          {% endif %}
        icon_template: >
            mdi:vibrate

homeassistant:
  customize:
    device_tracker.xiaomigateway:
      icon: mdi:cube