xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - mac: !secret xiaomi_mac
      key: !secret xiaomi_password

sensor:
  - platform: template
    sensors:
      xiaomi_tuersensor_batterie:
        friendly_name: Türsensor
        entity_id:
          - binary_sensor.zigate_229b_onoff
        value_template: >-
          {% if is_state('binary_sensor.zigate_229b_onoff', 'unknown') %}
            0
          {% else %}
            {{ states.binary_sensor.zigate_229b_onoff.attributes["battery_level"] | float}}
          {% endif %}
        unit_of_measurement: '%'
        device_class: battery

      xiaomi_tuerklingel_batterie:
        friendly_name: Türklingel
        entity_id:
          - binary_sensor.zigate_9bc8_onoff
        value_template: >-
          {% if is_state('binary_sensor.zigate_9bc8_onoff', 'unknown') %}
            0
          {% else %}
            {{ states.binary_sensor.zigate_9bc8_onoff.attributes["battery_level"] | float}}
          {% endif %}
        unit_of_measurement: '%'
        device_class: battery

      xiaomi_schalter_wohnzimmer_batterie:
        friendly_name: Schalter Wohnzimmer
        entity_id:
          - binary_sensor.switch_158d0002c8c48b
        value_template: >-
          {% if is_state('binary_sensor.switch_158d0002c8c48b', 'unknown') %}
            0
          {% else %}
            {{ states.binary_sensor.switch_158d0002c8c48b.attributes["battery_level"] | float}}
          {% endif %}
        unit_of_measurement: '%'
        device_class: battery

      xiaomi_schalter_schlafzimmer_batterie:
        friendly_name: Schalter Schlafzimmer
        entity_id:
          - binary_sensor.switch_158d0002134568
        value_template: >-
          {% if is_state('binary_sensor.switch_158d0002134568', 'unknown') %}
            0
          {% else %}
            {{ states.binary_sensor.switch_158d0002134568.attributes["battery_level"] | float}}
          {% endif %}
        unit_of_measurement: '%'
        device_class: battery

      xiaomi_schalter_flur_batterie:
        friendly_name: Schalter Flur
        entity_id:
          - binary_sensor.switch_158d0001c30867
        value_template: >-
          {% if is_state('binary_sensor.switch_158d0001c30867', 'unknown') %}
            0
          {% else %}
            {{ states.binary_sensor.switch_158d0001c30867.attributes["battery_level"] | float}}
          {% endif %}
        unit_of_measurement: '%'
        device_class: battery

      xiaomi_schalter_kueche_batterie:
        friendly_name: Schalter Küche
        entity_id:
          - binary_sensor.switch_158d0002c762ce
        value_template: >-
          {% if is_state('binary_sensor.switch_158d0002c762ce', 'unknown') %}
            0
          {% else %}
            {{ states.binary_sensor.switch_158d0002c762ce.attributes["battery_level"] | float}}
          {% endif %}
        unit_of_measurement: '%'
        device_class: battery

      xiaomi_vibration_wohnzimmer_batterie:
        friendly_name: Vibration Wohnzimmer
        entity_id:
          - binary_sensor.vibration_158d0002a48dc8
        value_template: >-
          {% if is_state('binary_sensor.vibration_158d0002a48dc8', 'unknown') %}
            0
          {% else %}
            {{ states.binary_sensor.vibration_158d0002a48dc8.attributes["battery_level"] | float}}
          {% endif %}
        unit_of_measurement: '%'
        device_class: battery

      xiaomi_vibration_schlafzimmer_batterie:
        friendly_name: Vibration Schlafzimmer
        entity_id:
          - binary_sensor.vibration_158d0002a222a1
        value_template: >-
          {% if is_state('sbinary_sensor.vibration_158d0002a222a1', 'unknown') %}
            0
          {% else %}
            {{ states.binary_sensor.vibration_158d0002a222a1.attributes["battery_level"] | float}}
          {% endif %}
        unit_of_measurement: '%'
        device_class: battery

      xiaomi_cube_batterie:
        friendly_name: Cube Wohnzimmer
        entity_id:
          - binary_sensor.cube_158d0001100d7a
        value_template: >-
          {% if is_state('binary_sensor.cube_158d0001100d7a', 'unknown') %}
            0
          {% else %}
            {{ states.binary_sensor.cube_158d0001100d7a.attributes["battery_level"] | float}}
          {% endif %}
        unit_of_measurement: '%'
        device_class: battery

      xiaomi_cube_status:
        friendly_name: Xiaomi Cube
        entity_id:
          - binary_sensor.cube_158d0001100d7a
        value_template: >
          {% set lastState = states.binary_sensor.cube_158d0001100d7a.attributes.last_action %}

          {% if lastState == None %}
            Unbekannt
          {% elif lastState == 'flip90' %}
            Drehen 90°
          {% elif lastState == 'flip180' %}
            Drehen 180°
          {% elif lastState == 'move' %}
            Bewegung
          {% elif lastState == 'shake_air' %}
            Schütteln
          {% elif lastState == 'swing' %}
            Schwingen
          {% elif lastState == 'alert' %}
            Alarm
          {% elif lastState == 'wakeup' %}
            Aufgewacht
          {% elif lastState == 'free_fall' %}
            Freier Fall
          {% elif lastState == 'rotate' %}
            Rotieren
          {% elif lastState == 'tap_twice' %}
            Klopfen
          {% else %}
            Unbekannt
          {% endif %}
        icon_template: >
            mdi:cube-outline

      xiaomi_vibration_wohnzimmer_status:
        friendly_name: Vibration Status
        value_template: >
          {% if is_state('binary_sensor.vibration_158d0002a48dc8', 'unknown') or states.binary_sensor.vibration_158d0002a48dc8.attributes["last_action"] == None %}
            Unbekannt
          {% else %}
            {% set lastState = states.binary_sensor.vibration_158d0002a48dc8.attributes["last_action"] %}

            {% if lastState == 'vibrate' %}
              Vibration
            {% elif lastState == 'tilt' %}
              Neigung
            {% elif lastState == 'free_fall' %}
              Freier Fall
            {% else %}
              Unbekannt
            {% endif %}
          {% endif %}
        icon_template: >
            mdi:vibrate

      xiaomi_vibration_schlafzimmer_status:
        friendly_name: Vibration Status
        value_template: >
          {% if is_state('binary_sensor.vibration_158d0002a222a1', 'unknown') or states.binary_sensor.vibration_158d0002a222a1.attributes["last_action"] == None %}
            Unbekannt
          {% else %}
            {% set lastState = states.binary_sensor.vibration_158d0002a222a1.attributes["last_action"] %}

            {% if lastState == 'vibrate' %}
              Vibration
            {% elif lastState == 'tilt' %}
              Neigung
            {% elif lastState == 'free_fall' %}
              Freier Fall
            {% else %}
              Unbekannt
            {% endif %}
          {% endif %}
        icon_template: >
            mdi:vibrate

homeassistant:
  customize:
    device_tracker.xiaomigateway:
      icon: mdi:cube

    vacuum.xiaomi_vacuum_cleaner:
      friendly_name: Xiaomi Robot

    sensor.illumination_7811dcaf15a8:
      friendly_name: Xioami Helligkeit
      hidden: true
    light.gateway_light_7811dcaf15a8:
      friendly_name: Xiaomi Licht
      hidden: true

    binary_sensor.switch_158d0001c30867:
      friendly_name: Schalter Flur
      hidden: true
    binary_sensor.switch_158d0002134568:
      friendly_name: Schalter Schlafzimmer
      hidden: true
    binary_sensor.switch_158d0002c8c48b:
      friendly_name: Schalter Wohnzimmer
      hidden: true
    binary_sensor.switch_158d0002c762ce:
      friendly_name: Schalter Küche
      hidden: true

    binary_sensor.cube_158d0001100d7a:
      friendly_name: Cube Schlafzimmer
      hidden: true

    binary_sensor.vibration_158d0002a48dc8:
      friendly_name: Vibration Wohnzimmer
      hidden: true
    sensor.bed_activity_158d0002a48dc8:
      friendly_name: Aktivität Wohnzimmer
      hidden: true
    sensor.coordination_158d0002a48dc8:
      friendly_name: Koordinaten Wohnzimmer
      hidden: true
    sensor.tilt_angle_158d0002a48dc8:
      friendly_name: Winkel Wohnzimmer
      hidden: true

    binary_sensor.vibration_158d0002a222a1:
      friendly_name: Vibration Schlafzimmer
      hidden: true
    sensor.bed_activity_158d0002a222a1:
      friendly_name: Aktivität Schlafzimmer
      hidden: true
    sensor.coordination_158d0002a222a1:
      friendly_name: Koordinaten Schlafzimmer
      hidden: true
    sensor.tilt_angle_158d0002a222a1:
      friendly_name: Winkel Schlafzimmer
      hidden: true