xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - mac: !secret xiaomi_mac
      key: !secret xiaomi_password

sensor:
  - platform: template
    sensors:
      tuersensor_batterie:
        friendly_name: Türsensor
        entity_id:
          - zigate.tuersensor
        value_template: >-
          {% if is_state('zigate.tuersensor', 'unavailable') %}
            0
          {% else %}
            {{ state_attr("zigate.tuersensor", "battery_level") | float }}
          {% endif %}
        unit_of_measurement: '%'
        device_class: battery

      tuerklingel_batterie:
        friendly_name: Türklingel
        entity_id:
          - zigate.tuerklingel
        value_template: >-
          {% if is_state('zigate.tuerklingel', 'unavailable') %}
            0
          {% else %}
            {{ state_attr("zigate.tuerklingel", "battery_level") | float }}
          {% endif %}
        unit_of_measurement: '%'
        device_class: battery

      briefkasten_batterie:
        friendly_name: Briefkasten
        entity_id:
          - zigate.briefkasten
        value_template: >-
          {% if is_state('zigate.briefkasten', 'unavailable') %}
            0
          {% else %}
            {{ state_attr("zigate.briefkasten", "battery_level") | float }}
          {% endif %}
        unit_of_measurement: '%'
        device_class: battery

      schalter_wohnzimmer_batterie:
        friendly_name: Schalter Wohnzimmer
        entity_id:
          - binary_sensor.schalter_wohnzimmer
        value_template: >-
          {% if is_state('binary_sensor.schalter_wohnzimmer', 'unknown') %}
            0
          {% else %}
            {{ state_attr("binary_sensor.schalter_wohnzimmer", "battery_level") | float }}
          {% endif %}
        unit_of_measurement: '%'
        device_class: battery

      schalter_schlafzimmer_batterie:
        friendly_name: Schalter Schlafzimmer
        entity_id:
          - binary_sensor.schalter_schlafzimmer
        value_template: >-
          {% if is_state('binary_sensor.schalter_schlafzimmer', 'unknown') %}
            0
          {% else %}
            {{ state_attr("binary_sensor.schalter_schlafzimmer", "battery_level") | float }}
          {% endif %}
        unit_of_measurement: '%'
        device_class: battery

      schalter_flur_batterie:
        friendly_name: Schalter Flur
        entity_id:
          - binary_sensor.schalter_flur
        value_template: >-
          {% if is_state('binary_sensor.schalter_flur', 'unknown') %}
            0
          {% else %}
            {{ state_attr("binary_sensor.schalter_flur", "battery_level") | float }}
          {% endif %}
        unit_of_measurement: '%'
        device_class: battery

      schalter_balkon_batterie:
        friendly_name: Schalter Balkon
        entity_id:
          - binary_sensor.schalter_balkon
        value_template: >-
          {% if is_state('binary_sensor.schalter_balkon', 'unknown') %}
            0
          {% else %}
            {{ state_attr("binary_sensor.schalter_balkon", "battery_level") | float }}
          {% endif %}
        unit_of_measurement: '%'
        device_class: battery

      vibration_wohnzimmer_batterie:
        friendly_name: Vibration Wohnzimmer
        entity_id:
          - binary_sensor.vibration_wohnzimmer
        value_template: >-
          {% if is_state('binary_sensor.vibration_wohnzimmer', 'unknown') %}
            0
          {% else %}
            {{ state_attr("binary_sensor.vibration_wohnzimmer", "battery_level") | float }}
          {% endif %}
        unit_of_measurement: '%'
        device_class: battery

      vibration_schlafzimmer_batterie:
        friendly_name: Vibration Schlafzimmer
        entity_id:
          - binary_sensor.vibration_schlafzimmer
        value_template: >-
          {% if is_state('binary_sensor.vibration_schlafzimmer', 'unknown') %}
            0
          {% else %}
            {{ state_attr("binary_sensor.vibration_schlafzimmer", "battery_level") | float }}
          {% endif %}
        unit_of_measurement: '%'
        device_class: battery

      cube_wohnzimmer_batterie:
        friendly_name: Cube Wohnzimmer
        entity_id:
          - binary_sensor.cube_wohnzimmer
        value_template: >-
          {% if is_state('binary_sensor.cube_wohnzimmer', 'unknown') %}
            0
          {% else %}
            {{ state_attr("binary_sensor.cube_wohnzimmer", "battery_level") | float }}
          {% endif %}
        unit_of_measurement: '%'
        device_class: battery

      cube_wohnzimmer_status:
        friendly_name: Xiaomi Cube
        entity_id:
          - binary_sensor.cube_wohnzimmer
        value_template: >
          {% set lastState = state_attr("binary_sensor.cube_wohnzimmer", "last_action") %}

          {% if lastState == None %}
            Unbekannt
          {% elif lastState == 'flip90' %}
            Drehen 90°
          {% elif lastState == 'flip180' %}
            Drehen 180°
          {% elif lastState == 'move' %}
            Bewegung
          {% elif lastState == 'shake_air' %}
            Schütteln
          {% elif lastState == 'swing' %}
            Schwingen
          {% elif lastState == 'alert' %}
            Alarm
          {% elif lastState == 'wakeup' %}
            Aufgewacht
          {% elif lastState == 'free_fall' %}
            Freier Fall
          {% elif lastState == 'rotate' %}
            Rotieren
          {% elif lastState == 'tap_twice' %}
            Klopfen
          {% else %}
            Unbekannt
          {% endif %}
        icon_template: >
            mdi:cube-outline

      vibration_wohnzimmer_status:
        friendly_name: Vibration Status
        value_template: >
          {% if is_state('binary_sensor.vibration_wohnzimmer', 'unknown') or states.binary_sensor.vibration_wohnzimmer.attributes["last_action"] == None %}
            Unbekannt
          {% else %}
            {% set lastState = states.binary_sensor.vibration_wohnzimmer.attributes["last_action"] %}

            {% if lastState == 'vibrate' %}
              Vibration
            {% elif lastState == 'tilt' %}
              Neigung
            {% elif lastState == 'free_fall' %}
              Freier Fall
            {% else %}
              Unbekannt
            {% endif %}
          {% endif %}
        icon_template: >
            mdi:vibrate

      vibration_schlafzimmer_status:
        friendly_name: Vibration Status
        value_template: >
          {% if is_state('binary_sensor.vibration_schlafzimmer', 'unknown') or states.binary_sensor.vibration_schlafzimmer.attributes["last_action"] == None %}
            Unbekannt
          {% else %}
            {% set lastState = states.binary_sensor.vibration_schlafzimmer.attributes["last_action"] %}

            {% if lastState == 'vibrate' %}
              Vibration
            {% elif lastState == 'tilt' %}
              Neigung
            {% elif lastState == 'free_fall' %}
              Freier Fall
            {% else %}
              Unbekannt
            {% endif %}
          {% endif %}
        icon_template: >
            mdi:vibrate

homeassistant:
  customize:
    device_tracker.xiaomigateway:
      icon: mdi:cube

    vacuum.xiaomi_vacuum_cleaner:
      friendly_name: Xiaomi Robot