zigate:
  port: /dev/ttyUSB1
  channel: 24
  enable_led : false

homeassistant:
  customize:
    zigate.6e71:
      friendly_name: 'Fenster Wohnzimmer'
    zigate.bd4c:
      friendly_name: 'Fenster Schlafzimmer'
    zigate.9619:
      friendly_name: 'Fenster Küche'
    zigate.3415:
      friendly_name: 'Fenster Arbeitszimmer'
    zigate.2d17:
      friendly_name: 'Fenster Sportzimmer'

    binary_sensor.fenster_wohnzimmer:
      device_class: window
    binary_sensor.fenster_schlafzimmer:
      device_class: window
    binary_sensor.fenster_kueche:
      device_class: window
    binary_sensor.fenster_arbeitszimmer:
      device_class: window
    binary_sensor.fenster_sportzimmer:
      device_class: window