zigate:
  port: /dev/ttyUSB0
  channel: 24
  enable_led : false

input_number:
  zigate_offline_puffer:
    name: Puffer
    min: 1
    max: 24
    step: 1
    initial: 24

sensor:
  - platform: template
    sensors:
      zigate_offline:
        friendly_name: Geräte offline
        entity_id:
          - sensor.time
          - sensor.laufzeit_minuten
          - input_number.zigate_offline_puffer
        icon_template: >
          {% set now = as_timestamp(now()) | int %}
          {% set puffer = states('input_number.zigate_offline_puffer') | int * 60 | int -%}
          {% set ns = namespace(found=false) -%}

          {% for entity_id in state_attr('group.zigate', 'entity_id') -%}
            {% set lastChange = as_timestamp(states(entity_id)) | int %}
            {% set difference = (now - lastChange ) / 60 | round() %}

            {% if difference > puffer %}
              {% set ns.found = true -%}
            {% endif %}
          {% endfor -%}

          {% if ns.found == True %}
            mdi:access-point-network-off
          {% else %}
            mdi:access-point-network
          {% endif %}
        value_template: >
          {% set now = as_timestamp(now()) | int %}
          {% set puffer = states('input_number.zigate_offline_puffer') | int * 60 | int -%}
          {% set ns = namespace(found=0) -%}

          {% for entity_id in state_attr('group.zigate', 'entity_id') -%}
            {% set lastChange = as_timestamp(states(entity_id)) | int %}
            {% set difference = (now - lastChange ) / 60 | round() %}

            {% if difference > puffer %}
              {% set ns.found = ns.found + 1 -%}
            {% endif %}
          {% endfor -%}

          {{ ns.found | int }}