zigate:
  port: /dev/ttyUSB0
  channel: 24
  enable_led : false

homeassistant:
  customize:
    binary_sensor.fenster_wohnzimmer:
      device_class: window
    binary_sensor.fenster_schlafzimmer:
      device_class: window
    binary_sensor.fenster_kueche:
      device_class: window
    binary_sensor.fenster_arbeitszimmer:
      device_class: window
    binary_sensor.fenster_sportzimmer:
      device_class: window