zigate:
  port: /dev/ttyUSB0
  channel: 24
  enable_led : false
  admin_panel: true

input_number:
  zigate_offline_puffer:
    name: Puffer
    min: 1
    max: 24
    step: 1

input_select:
  cube_letzte_aktion:
    name: Letzte Aktion
    options:
      - 'Unbekannt'
      - 'Drehen 90°'
      - 'Drehen 180°'
      - 'Bewegung'
      - 'Schütteln'
      - 'Alarm'
      - 'Aufgewacht'
      - 'Freier Fall'
      - 'Rotieren'
      - 'Klopfen'

sensor:
  - platform: template
    sensors:
      cube_status:
        friendly_name: Xiaomi Cube
        value_template: >-
          {{ states("input_select.cube_letzte_aktion") }}
        icon_template: >
            mdi:cube-outline
            
      zigate_offline:
        friendly_name: Geräte offline        
        icon_template: >
          {% set zigateEntities = expand('group.zigate') %}
          {% set now = as_timestamp(now(), None) | int %}
          {% set puffer = states('input_number.zigate_offline_puffer') | int * 60 | int -%}
          {% set ns = namespace(found=false) -%}         
          
          {% for x in zigateEntities if ((now - (as_timestamp(x.state, None) | int) ) / 60 | round(default=0)) > puffer %}
            {% set ns.found = true -%}
          {% endfor %}

          {{ "mdi:access-point-network-off" if ns.found == True else "mdi:access-point-network" }}

        value_template: >
          {% set zigateEntities = expand('group.zigate') %}
          {% set now = as_timestamp(now(), None) | int %}
          {% set puffer = states('input_number.zigate_offline_puffer') | int * 60 | int -%}
          {% set ns = namespace(found=false) -%}
          
          {% for x in zigateEntities if ((now - (as_timestamp(x.state, None) | int) ) / 60 | round(default=0)) > puffer %}
            {% set ns.found = ns.found + 1 -%}
          {% endfor %}        
        
          {{ ns.found | int }}

script:
  zigate_geraet_paaren:
    alias: "Gerät paaren"
    sequence:
      - service: zigate.permit_join
      
automation:
  - alias: "Cube - Letzte Aktion"
    id: "cube_letzte_aktion"
    trigger:
      - platform: state
        entity_id:
          - sensor.cube_bewegung
          - sensor.cube_drehung
    condition:
      condition: or
      conditions:
        - condition: template
          value_template: >-
            {{ True if trigger.entity_id == "sensor.cube_drehung" else False }}
        - condition: template
          value_template: >-
            {{ True if trigger.to_state.state else False }}
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.cube_letzte_aktion    
          option: >-
            {% if trigger.entity_id == "sensor.cube_drehung" %}
              Rotieren
            {% else %}
              {% set lastAction = states("sensor.cube_bewegung") %}

              {% if lastAction == None %}
                Unbekannt
              {% elif 'flip90' in lastAction %}
                Drehen 90°
              {% elif 'flip180' in lastAction %}
                Drehen 180°
              {% elif 'push' in lastAction %}
                Bewegung
              {% elif 'shake' in lastAction %}
                Schütteln
              {% elif 'alert' in lastAction %}
                Alarm
              {% elif 'wakeup' in lastAction %}
                Aufgewacht
              {% elif 'drop' in lastAction %}
                Freier Fall
              {% elif 'double_tap' in lastAction %}
                Klopfen
              {% else %}
                Unbekannt
              {% endif %}               
            {% endif %}
            

homeassistant:
  customize:
    binary_sensor.tuersensor:
      device_class: door      

    script.zigate_geraet_paaren:
      icon: mdi:connection
      
  customize_glob:
    binary_sensor.bewegungsmelder_*:
      device_class: motion
      
    sensor.helligkeit_*:
      device_class: illuminance    