homeassistant:
  customize:
    binary_sensor.wohnungstuer:
      device_class: door           
    binary_sensor.balkontuer:
      device_class: door
      
  customize_glob:
    binary_sensor.fenster_*:
      device_class: window           