zwave:
  usb_path: /dev/ttyACM0

homeassistant:
  customize:
    zwave.aeotec_zw090_zstick_gen5_eu:
      friendly_name: Z-Wave Stick

    sensor.badezimmer_helligkeit:
      device_class: illuminance
    sensor.wohnzimmer_helligkeit:
      device_class: illuminance
    sensor.wohnzimmer_luftfeuchtigkeit:
      device_class: humidity

    sensor.aeotec_wohnzimmer_burglar:
      friendly_name: Bewegungsmelder
    sensor.aeotec_wohnzimmer_ultraviolet:
      friendly_name: UV-Licht
      icon: mdi:flash-circle
    sensor.aeotec_wohnzimmer_alarm_level:
      friendly_name: Alarmlevel
    sensor.aeotec_wohnzimmer_alarm_type:
      friendly_name: Alarmtyp
    binary_sensor.aeotec_wohnzimmer_sensor:
      friendly_name: Alarm
    sensor.aeotec_wohnzimmer_sourcenodeid:
      friendly_name: Aeotec Wohnzimmer ID

    sensor.fibaro_badezimmer_alarm_level:
      friendly_name: Alarmlevel
    sensor.fibaro_badezimmer_alarm_type:
      friendly_name: Alarmtyp
    binary_sensor.fibaro_badezimmer_sensor:
      friendly_name: Alarm
    sensor.fibaro_badezimmer_sourcenodeid:
      friendly_name: Fibaro Badezimmer ID
    sensor.fibaro_badezimmer_general:
      friendly_name: Fibaro General
    sensor.fibaro_badezimmer_burglar:
      friendly_name: Bewegungsmelder
    sensor.fibaro_badezimmer_seismic_intensity:
      friendly_name: Erdbeben
      icon: mdi:earth