alexa_media:
  accounts:
    - email: !secret amazon_email
      password: !secret amazon_password
      url: amazon.de
      exclude_devices:
        - "Überall"
        - "Echo Simon"
        - "FireTablet Badezimmer"
        - "FireTablet Balkon" 
        - "FireTablet Balkon's Alexa Apps"        
        - "FireTV Schlafzimmer"
        - "FireTV Badezimmer"
        - "FireTV Sportzimmer"
        
sensor:
  - platform: template
    sensors:
      echo_wohnzimmer_timer:
        friendly_name: Timer
        icon_template: mdi:timer-off
        entity_id:
          - sensor.echo_wohnzimmer_next_timer
          - sensor.time
        unit_of_measurement: 'Minuten'
        value_template: >-
          {%if is_state('sensor.echo_wohnzimmer_next_timer', 'None') or is_state('sensor.echo_wohnzimmer_next_timer', 'unavailable') %}
            -
          {% else %}
            {% set timer = as_timestamp(states('sensor.echo_wohnzimmer_next_timer')) | int %}
            {% set now = as_timestamp(now()) | int %}
            {% set diff = ((timer - now) / 60) | int %}

            {{ diff }}
          {% endif %}