input_boolean:
  alexa_witz_gestartet:
    name: Alexa Witz - Gestartet
    initial: off
  
counter:
  alexa_witz_status:
    name: Alexa Witz - Statusänderungen    
    initial: 0
    step: 1      
        
automation:
  - alias: "Alexa Witz - Aktiv"
    id: "alexa_witz_aktiv"
    trigger:
      - platform: state
        entity_id: media_player.echo_wohnzimmer
    condition:
      - condition: state
        entity_id: input_boolean.alexa_witz_gestartet
        state: 'on'
      - condition: template
        value_template: '{{ trigger.from_state.attributes.media_position_updated_at != trigger.to_state.attributes.media_position_updated_at }}'
    action:
      - service: counter.increment
        entity_id: counter.alexa_witz_status
       
  - alias: "Alexa Witz - Beendet"
    id: "alexa_witz_beendet"
    trigger:
      - platform: numeric_state
        entity_id: counter.alexa_witz_status
        above: 3
    condition:
      - condition: state
        entity_id: input_boolean.alexa_witz_gestartet
        state: 'on'
    action:
      - service: script.alexa_witz_beendet
        
  - alias: "Alexa Witz"
    id: "alexa_witz"  
    trigger:
      - platform: state
        entity_id: binary_sensor.schalter_badezimmer
        to: 'off'       
    condition:
      - condition: state
        entity_id: binary_sensor.besuch
        state: 'on'
    action:
      - service: script.alexa_witz
        data:
          echo: badezimmer
        
script:
  alexa_witz_gestartet:
    alias: "Alexa Witz - Gestartet"
    sequence:
      - service: input_boolean.turn_on
        entity_id: input_boolean.alexa_witz_gestartet
      - service: media_player.play_media
        data:
          entity_id: media_player.echo_wohnzimmer
          media_content_id: Alexa.Joke.Play
          media_content_type: sequence
      - service: switch.turn_on
        entity_id: switch.radios_lautlos     
       
  alexa_witz_beendet:
    alias: "Alexa Witz - Beendet"
    sequence:
      - service: counter.reset
        entity_id: counter.alexa_witz_status
      - service: input_boolean.turn_off
        entity_id: input_boolean.alexa_witz_gestartet        
      - service: switch.turn_off
        entity_id: switch.radios_lautlos
          
  alexa_witz:
    alias: "Alexa Witz"
    sequence:
      - service: media_player.play_media
        data:          
          entity_id: media_player.echo_{{ echo }}
          media_content_id: Alexa.Joke.Play
          media_content_type: sequence          
          
homeassistant:
  customize:
    script.alexa_witz_gestartet:
      can_cancel: false
      icon: mdi:emoticon-excited-outline          
      friendly_name: Witz erzählen