automation:
  - alias: "BVB - Torhymne"
    id: "bvb_torhymne"
    trigger:
      - id: cube_wohnzimmer
        platform: event
        event_type: zha_event
        event_data:
          device_ieee: 00:15:8d:00:01:10:0d:7a
          command: drop    
      - id: schalter_balkon
        platform: event
        event_type: zha_event
        event_data:
          device_ieee: 00:15:8d:00:02:c7:62:ce
          command: click
          args:
            click_type: single
    condition:
      - condition: state
        entity_id: calendar.borussia_dortmund
        state: 'on'
      - condition: template
        value_template: '{{ True if not "(T.B.A.)" in state_attr("calendar.borussia_dortmund", "message") else False }}'
    action:
      - service: media_player.play_media
        data:
          entity_id: media_player.squeezebox
          media_content_id: http://192.168.2.75:8123/local/sounds/torhymne.mp3
          media_content_type: music

  - alias: "BVB - Musik starten"
    id: "bvb_musik_starten"
    trigger:
      - id: cube_wohnzimmer
        platform: event
        event_type: zha_event
        event_data:
          device_ieee: 00:15:8d:00:01:10:0d:7a
          command: knock   
    condition:    
      - condition: state
        entity_id: calendar.borussia_dortmund
        state: 'on'
      - condition: template
        value_template: '{{ True if not "(T.B.A.)" in state_attr("calendar.borussia_dortmund", "message") else False }}'        
      - condition: not
        conditions:
          - condition: state
            entity_id: media_player.squeezebox
            state: 'playing'
    action:
      - service: media_player.play_media
        data:
          entity_id: media_player.squeezebox
          media_content_id: http://192.168.2.75:8123/local/sounds/heja_bvb.mp3
          media_content_type: music

  - alias: "BVB - Musik stoppen"
    id: "bvb_musik_stoppen"
    trigger:
      - id: cube_wohnzimmer
        platform: event
        event_type: zha_event
        event_data:
          device_ieee: 00:15:8d:00:01:10:0d:7a
          command: knock   
    condition:           
      - condition: state
        entity_id: calendar.borussia_dortmund
        state: 'on'
      - condition: template
        value_template: '{{ True if "(T.B.A.)" in state_attr("calendar.borussia_dortmund", "message") else False }}'
      - condition: state
        entity_id: media_player.squeezebox
        state: 'playing'
    action:
      - service: media_player.media_pause
        entity_id: media_player.squeezebox                  
                    
  - alias: "Radio Badezimmer - BVB"
    id: "radio_badezimmer_bvb"
    trigger:
      - platform: state
        entity_id: media_player.radio_badezimmer
        to: 'playing'
    condition:  
      - "{{ is_state('calendar.borussia_dortmund', 'on') }}"          
      - "{{ True if not '(T.B.A.)' in state_attr('calendar.borussia_dortmund', 'message') else False }}"    
      - "{{ not is_state_attr('media_player.radio_badezimmer', 'media_artist', 'Borussia Dortmund') }}"    
    action:
      - service: squeezebox.call_method
        data:
          entity_id: media_player.radio_badezimmer
          command: 'playlist'
          parameters:
            - play
            - 'BVB'        