input_boolean:
  bvb_tor_aktiv:
    name: BVB Tor aktiv     

automation:
  - alias: "BVB - Torhymne"
    id: "bvb_torhymne"
    trigger:
      - id: cube_wohnzimmer
        platform: event
        event_type: zha_event
        event_data:
          device_ieee: 00:15:8d:00:01:10:0d:7a
          command: drop    
      - id: schalter_wohnzimmer
        platform: event
        event_type: zha_event
        event_data:
          device_ieee: 00:15:8d:00:02:c8:c4:8b
          command: click
          args:
            click_type: single            
      - id: schalter_balkon
        platform: event
        event_type: zha_event
        event_data:
          device_ieee: 00:15:8d:00:02:c7:62:ce
          command: click
          args:
            click_type: single
    condition:
      - "{{ is_state('calendar.borussia_dortmund', 'on') }}"
      - "{{ True if not '(T.B.A.)' in state_attr('calendar.borussia_dortmund', 'message') else False }}"
    action:
      - service: media_player.play_media
        data:
          entity_id: media_player.squeezebox
          media_content_id: http://192.168.2.75:8123/local/sounds/torhymne.mp3
          media_content_type: music
      - service: scene.create
        data:          
          scene_id: bvb_tor
          snapshot_entities:
            - light.wohnzimmer_schrank
      - service: input_boolean.turn_on
        entity_id: input_boolean.bvb_tor_aktiv              
      - alias: 'BVB Tor - Licht'
        repeat:
          while:                  
            - condition: state
              entity_id: media_player.squeezebox
              state: 'playing'   
            - condition: state
              entity_id: input_boolean.bvb_tor_aktiv
              state: 'on'                      
          sequence:
            - service: light.toggle
              entity_id: light.wohnzimmer_schrank
            - delay:
                seconds: 0.8

  - alias: "BVB - Torhymne Ende"
    id: "bvb_torhymne_ende"
    trigger:
      - platform: state
        entity_id: media_player.squeezebox
        to: 'idle'          
      - platform: state
        entity_id: input_boolean.bvb_tor_aktiv
        to: 'on'    
        for:
          seconds: 33
    condition:
      - condition: state
        entity_id: input_boolean.bvb_tor_aktiv
        state: 'on'              
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.bvb_tor_aktiv
      - service: scene.turn_on
        entity_id: scene.bvb_tor

  - alias: "BVB - Musik starten"
    id: "bvb_musik_starten"
    trigger:
      - id: cube_wohnzimmer
        platform: event
        event_type: zha_event
        event_data:
          device_ieee: 00:15:8d:00:01:10:0d:7a
          command: knock   
    condition:    
      - condition: state
        entity_id: calendar.borussia_dortmund
        state: 'on'
      - condition: template
        value_template: '{{ True if not "(T.B.A.)" in state_attr("calendar.borussia_dortmund", "message") else False }}'        
      - condition: not
        conditions:
          - condition: state
            entity_id: media_player.squeezebox
            state: 'playing'
    action:
      - service: media_player.play_media
        data:
          entity_id: media_player.squeezebox
          media_content_id: http://192.168.2.75:8123/local/sounds/heja_bvb.mp3
          media_content_type: music

  - alias: "BVB - Musik stoppen"
    id: "bvb_musik_stoppen"
    trigger:
      - id: cube_wohnzimmer
        platform: event
        event_type: zha_event
        event_data:
          device_ieee: 00:15:8d:00:01:10:0d:7a
          command: knock   
    condition:           
      - condition: state
        entity_id: calendar.borussia_dortmund
        state: 'on'
      - condition: template
        value_template: '{{ True if "(T.B.A.)" in state_attr("calendar.borussia_dortmund", "message") else False }}'
      - condition: state
        entity_id: media_player.squeezebox
        state: 'playing'
    action:
      - service: media_player.media_pause
        entity_id: media_player.squeezebox      
      - service: media_player.clear_playlist
        data:
          entity_id: media_player.squeezebox        
          
  - alias: "BVB - Benachrichtigung Tor"
    id: "bvb_benachrichtigung_tor"
    trigger:
      - platform: template
        value_template: "{{ state_attr('sensor.borussia_dortmund', 'team_score') }}"
      - platform: template
        value_template: "{{ state_attr('sensor.borussia_dortmund', 'opponent_score') }}"        
    condition:
      - "{{ is_state('sensor.borussia_dortmund', 'IN') }}"      
      - "{{ is_state('person.dennis', 'not_home') }}"      
    action:
      - service: notify.telegram
        data:
          title: "Tor"
          message: >-
            {% set scoreTeam = state_attr('sensor.borussia_dortmund', 'team_score') %}
            {% set scoreOpponent = state_attr('sensor.borussia_dortmund', 'opponent_score') %}
            
            {% set nameTeam = state_attr('sensor.borussia_dortmund', 'team_name') %}
            {% set nameOpponent = state_attr('sensor.borussia_dortmund', 'opponent_name') %}
            
            {{ nameTeam ~ ' ' ~ scoreTeam ~ ' - ' ~ scoreOpponent ~ ' ' ~ nameOpponent }}
 