automation:
  - alias: "DFB - Torhymne"
    id: "dfb_torhymne"
    trigger:
      - id: cube_wohnzimmer
        platform: event
        event_type: zha_event
        event_data:
          device_ieee: 00:15:8d:00:01:10:0d:7a
          command: drop    
    condition:
      - "{{ is_state('calendar.nationalmannschaft', 'on') }}"
    action:
      - service: media_player.play_media
        data:
          entity_id: media_player.home_assistant
          media_content_id: http://192.168.2.75:8123/local/sounds/torhymne_dfb.mp3
          media_content_type: music     