notify:
  - platform: kodi
    name: Kodi Wohnzimmer
    host: !secret computer_host
    username: !secret kodi_username
    password: !secret kodi_password
    
input_boolean:
  musik_ausschalten:
    name: Musik ausschalten
    icon: mdi:music-off
    
  kodi_wohnzimmer_pausiert:
    name: Kodi Wohnzimmer pausiert    

  firefox_wohnzimmer_aktiv:
    name: Firefox Wohnzimmer aktiv
    icon: mdi:youtube-tv
    
  firefox_wohnzimmer_pausiert:
    name: Firefox Wohnzimmer pausiert    
    
binary_sensor:
  - platform: template
    sensors:
      firefox_wohnzimmer_aktiv:
        friendly_name: Firefox aktiv
        icon_template: "mdi:youtube-tv"
        value_template: "{{ is_state('input_boolean.firefox_wohnzimmer_aktiv', 'on') }}"
        
cover:
  - platform: template
    covers:
      kodi_untertitel:
        friendly_name: "Untertitel"
        position_template: 50
        open_cover:
          service: kodi.call_method
          data:
            entity_id: media_player.kodi_wohnzimmer
            method: Input.ExecuteAction
            action: subtitledelayplus
        close_cover:
          service: kodi.call_method
          data:
            entity_id: media_player.kodi_wohnzimmer
            method: Input.ExecuteAction
            action: subtitledelayminus
        stop_cover:
          service: kodi.call_method
          data:
            entity_id: media_player.kodi_wohnzimmer
            method: Input.ExecuteAction
            action: showsubtitles
        icon_template: mdi:message-bulleted      

      fernseher_sender:
        friendly_name: "Fernseher Sender"
        position_template: 50
        open_cover:
          - service: media_player.play_media
            data:
              entity_id: media_player.fernseher_wohnzimmer
              media_content_id: "KEY_CHUP"
              media_content_type: "send_key"
        close_cover:
          - service: media_player.play_media
            data:
              entity_id: media_player.fernseher_wohnzimmer
              media_content_id: "KEY_CHDOWN"
              media_content_type: "send_key"
        stop_cover:
          - service: media_player.play_media
            data:
              entity_id: media_player.fernseher_wohnzimmer
              media_content_id: "KEY_PRECH"
              media_content_type: "send_key"
        icon_template: >-
          mdi:remote-tv

switch:
  - platform: template
    switches:
      watchtv_wohnzimmer:
        friendly_name: "Fernsehen"
        value_template: "{{ is_state('media_player.fernseher_wohnzimmer', 'on') }}"
        turn_on:
          - service: media_player.turn_on
            entity_id: media_player.fernseher_wohnzimmer  
          - choose:
              - conditions:
                  - condition: state
                    entity_id: media_player.soundbar
                    state: 'off'
                sequence:  
                  - service: media_player.turn_on
                    entity_id: media_player.soundbar        
                  - wait_template: "{{is_state('media_player.soundbar', 'on')}}"
                  - service: media_player.select_source
                    entity_id: media_player.soundbar
                    data:
                      source: TV
        turn_off:
          - service: media_player.media_stop
            entity_id: media_player.kodi_wohnzimmer
          - wait_template: "{{is_state('media_player.kodi_wohnzimmer', 'idle')}}"
            timeout: '00:00:02'
            continue_on_timeout: 'true'
          - service: media_player.turn_off
            entity_id: media_player.kodi_wohnzimmer
          - wait_template: "{{is_state('media_player.kodi_wohnzimmer', 'off')}}"
            timeout: '00:00:02'
            continue_on_timeout: 'true'          
          - service: media_player.turn_off
            entity_id: media_player.fernseher_wohnzimmer
          - choose:
              - conditions:
                  - condition: state
                    entity_id: media_player.soundbar
                    state: 'on'
                sequence:
                  - service: media_player.turn_off
                    entity_id: media_player.soundbar
     
script:
  kodi_wohnzimmer_starten:
    alias: "Kodi Wohnzimmer - Starten"
    sequence:
      - service: media_player.media_play
        entity_id: media_player.kodi_wohnzimmer
      - service: input_boolean.turn_off
        entity_id: input_boolean.kodi_wohnzimmer_pausiert
      - service: homeassistant.turn_off
        entity_id: group.licht_fernsehen         
      - choose:
          - conditions:
              - condition: state
                entity_id: media_player.radio_badezimmer
                state: 'playing'          
            sequence:
              - service: media_player.media_pause
                entity_id: media_player.radio_badezimmer
        
  kodi_wohnzimmer_pausieren:
    alias: "Kodi Wohnzimmer - Pausieren"
    sequence:
      - service: media_player.media_pause
        entity_id: media_player.kodi_wohnzimmer        
      - service: input_boolean.turn_on
        entity_id: input_boolean.kodi_wohnzimmer_pausiert
      - choose:
          - conditions:
              - condition: template
                value_template: >-
                  {% if triggerId and (triggerId == 'bewegungsmelder_balkon' or triggerId == 'schalter_balkon') %}
                    {{ is_state('binary_sensor.sonne_tagsueber', 'off') }}
                  {% else %}
                    False
                  {% endif %}                  
            sequence:
              - service: switch.turn_on
                entity_id: light.balkon_licht  
                
automation:      
  - alias: "Kodi Wohnzimmer - Musik ausschalten"
    id: "kodi_wohnzimmer_musik_ausschalten"
    trigger:
      - platform: state
        entity_id: media_player.kodi_wohnzimmer
        from: 'off'
        to: 'idle'
    condition:
      - "{{ (states('sensor.laufzeit_minuten') | float(0)) > 1 }}"         
      - condition: state
        state: 'on'
        entity_id: input_boolean.musik_ausschalten      
    action:  
      - service: script.radios_ausschalten
        data:
          badezimmerEingeschaltetLassen: True
          
  - alias: "Kodi Wohnzimmer - Wiedergabe"
    id: "kodi_wohnzimmer_wiedergabe"    
    trigger:
      - id: schalter_wohnzimmer
        platform: event
        event_type: zha_event
        event_data:
          device_ieee: 00:15:8d:00:02:c8:c4:8b
          command: click
          args:
            click_type: single   
      - id: cube_wohnzimmer
        platform: event
        event_type: zha_event
        event_data:
          device_ieee: 00:15:8d:00:01:10:0d:7a
          command: flip      
    condition:
      - condition: state
        entity_id: binary_sensor.besuch
        state: 'off'               
      - condition: or
        conditions:
        - condition: state
          entity_id: media_player.kodi_wohnzimmer
          state: 'playing'
        - condition: state
          entity_id: media_player.kodi_wohnzimmer
          state: 'paused'
    action:
      - service: media_player.media_play_pause
        entity_id: media_player.kodi_wohnzimmer
          
  - alias: "Kodi Wohnzimmer - Starten"
    id: "kodi_wohnzimmer_starten"
    trigger:
      - platform: state
        entity_id: binary_sensor.bewegungsmelder_wohnzimmer
        to: 'on'
    condition:
      - condition: state
        entity_id: media_player.kodi_wohnzimmer
        state: 'paused'
      - condition: state
        entity_id: input_boolean.kodi_wohnzimmer_pausiert
        state: 'on'
      - condition: state
        entity_id: sensor.telefon
        state: 'idle'
      - condition: state
        entity_id: 'sensor.handy'
        state: 'idle'
    action:
      - service: script.kodi_wohnzimmer_starten
        
  - alias: "Kodi Wohnzimmer - Pausieren"
    id: "kodi_wohnzimmer_pausieren"
    trigger:
      - id: bewegungsmelder_flur_vorne
        platform: state
        entity_id: binary_sensor.bewegungsmelder_flur_vorne
        to: 'on'
      - id: bewegungsmelder_flur_hinten
        platform: state
        entity_id: binary_sensor.bewegungsmelder_flur_hinten
        to: 'on'
      - id: bewegungsmelder_balkon
        platform: state
        entity_id: binary_sensor.bewegungsmelder_balkon
        to: 'on'            
      - id: schalter_balkon
        platform: event
        event_type: zha_event
        event_data:
          device_ieee: 00:15:8d:00:02:c7:62:ce
          command: click
          args:
            click_type: double            
    condition:
      - condition: state
        entity_id: media_player.kodi_wohnzimmer
        state: 'playing'
      - condition: state
        entity_id: binary_sensor.besuch
        state: 'off'        
      - condition: state
        entity_id: sensor.telefon
        state: 'idle'
      - condition: state
        entity_id: 'sensor.handy'
        state: 'idle'   
      - condition: template       
        value_template: >-  
          {% if trigger.id == 'bewegungsmelder_balkon' or trigger.id == 'schalter_balkon' %}
            {{ is_state('binary_sensor.balkontuer', 'on') }}
          {% else %}
            True
          {% endif %}
    action:
      - service: script.kodi_wohnzimmer_pausieren
        data:
          triggerId: trigger.id          
        
  - alias: "Kodi Wohnzimmer - Nächster Titel"
    id: "kodi_wohnzimmer_naechster_titel"
    trigger:
      - id: cube_wohnzimmer
        platform: event
        event_type: zha_event
        event_data:
          device_ieee: 00:15:8d:00:01:10:0d:7a
          command: drop    
    condition:   
      - "{{ is_state('media_player.kodi_wohnzimmer', 'playing') }}"
    action:
      - service: media_player.media_next_track
        entity_id: media_player.kodi_wohnzimmer

  - alias: "Kodi Wohnzimmer - Untertitel"
    id: "kodi_wohnzimmer_untertitel"    
    trigger:
      - id: cube_wohnzimmer
        platform: event
        event_type: zha_event
        event_data:
          device_ieee: 00:15:8d:00:01:10:0d:7a
          command: shake    
    condition:     
      - condition: state
        entity_id: media_player.kodi_wohnzimmer
        state: 'playing'        
    action:
      - service: cover.stop_cover
        entity_id: cover.kodi_untertitel          
          
  - alias: "Firefox Wohnzimmer - Pausieren"
    id: "firefox_wohnzimmer_pausieren"
    trigger:
      - platform: state
        entity_id: binary_sensor.bewegungsmelder_flur_vorne
        to: 'on'
      - platform: state
        entity_id: binary_sensor.bewegungsmelder_flur_hinten
        to: 'on'
      - platform: state
        entity_id: binary_sensor.bewegungsmelder_balkon
        to: 'on'     
        id: bewegungsmelder_balkon
      - platform: event
        event_type: zha_event
        event_data:
          device_ieee: 00:15:8d:00:02:c7:62:ce
          command: click
          args:
            click_type: double 
        id: schalter_balkon
    condition:
      - condition: state
        entity_id: binary_sensor.firefox_wohnzimmer_aktiv
        state: 'on'
      - condition: state
        entity_id: input_boolean.firefox_wohnzimmer_pausiert
        state: 'off'        
      - condition: state
        entity_id: binary_sensor.besuch
        state: 'off'        
      - condition: state
        entity_id: sensor.telefon
        state: 'idle'
      - condition: state
        entity_id: 'sensor.handy'
        state: 'idle'           
      - condition: template       
        value_template: >-         
          {% if trigger.id == 'bewegungsmelder_balkon' or trigger.id == 'schalter_balkon' %}
            {{ is_state('binary_sensor.balkontuer', 'on') }}
          {% else %}
            True
          {% endif %}        
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.firefox_wohnzimmer_pausiert
      - service: switch.turn_on
        entity_id: switch.computer_wiedergabe                

  - alias: "Firefox Wohnzimmer - Status ändern"
    id: "firefox_wohnzimmer_status_geaendert"
    trigger:
      - platform: state
        entity_id: binary_sensor.computer_mozilla_firefox_fullscreen
#        entity_id: binary_sensor.computer_firefox
    condition:
      - "{{ is_state('binary_sensor.computer_mozilla_firefox_fullscreen', 'unavailable') == False }}"
      - "{{ trigger.to_state.state != states('input_boolean.firefox_wohnzimmer_aktiv') }}"
    action:
      - service: input_boolean.toggle
        entity_id: input_boolean.firefox_wohnzimmer_aktiv           
        
  - alias: "Firefox Wohnzimmer - Starten"
    id: "firefox_wohnzimmer_starten"
    trigger:
      - platform: state
        entity_id: binary_sensor.bewegungsmelder_wohnzimmer
        to: 'on'
    condition:
      - condition: state
        entity_id: input_boolean.firefox_wohnzimmer_pausiert
        state: 'on'
      - condition: state
        entity_id: sensor.telefon
        state: 'idle'
      - condition: state
        entity_id: 'sensor.handy'
        state: 'idle'   
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.firefox_wohnzimmer_pausiert      
      - service: switch.turn_on
        entity_id: switch.computer_wiedergabe
      - service: homeassistant.turn_off
        entity_id: group.licht_fernsehen              
      - condition: state
        entity_id: media_player.radio_badezimmer
        state: 'playing'
      - service: media_player.media_pause
        entity_id: media_player.radio_badezimmer                                 

homeassistant:
  customize:
    media_player.soundbar:
      icon: mdi:music
          
    switch.watchtv_wohnzimmer:
      icon: mdi:television-classic