switch:
  - platform: tplink
    host: 192.168.2.60
    name: Schlafzimmer Fernseher
    
  - platform: broadlink
    host: 192.168.2.28
    mac: 'B4:43:0D:F9:2F:E5'
    type: rm_mini
    friendly_name: Broadlink Schlafzimmer
    switches:
      fernseher_schlafzimmer_remote:
        friendly_name: Fernseher Schlafzimmer Remote
        command_on: 'JgAYAZaSFDYUNRU1FBEUERQRFBAVEBQ2FDYUNRQRFBEUERQQFRAUERQ2FBEUEBUQFBEUERQRFDUUERQ2FDUVNRQ2FDUUNhQABgGWkhQ2FDUUNhQRFBEUEBUQFBEUNhQ1FDYUERQRFBAUERQRFBEUNRUQFBEUERQRFBAVEBQ2FBEUNRU1FDYUNRQ2FDUVAAYBlpIUNRU1FDYUERQQFRAUERQRFDUVNRQ2FBEUEBQRFBEUERQRFDUUERQRFBEUEBUQFRAUNhQRFDUUNhQ1FTUUNhQ1FQAGAJeSFDUUNhQ1FRAVEBQRFBEUERQ1FTUUNhQQFRAUERQRFBEUERQ1FBEUERQRFBAVEBQRFDYUEBU1FDYUNRQ2FDUVNRQADQU=='
        command_off: 'JgAYAZaSFDYUNRU1FBEUERQRFBAVEBQ2FDYUNRQRFBEUERQQFRAUERQ2FBEUEBUQFBEUERQRFDUUERQ2FDUVNRQ2FDUUNhQABgGWkhQ2FDUUNhQRFBEUEBUQFBEUNhQ1FDYUERQRFBAUERQRFBEUNRUQFBEUERQRFBAVEBQ2FBEUNRU1FDYUNRQ2FDUVAAYBlpIUNRU1FDYUERQQFRAUERQRFDUVNRQ2FBEUEBQRFBEUERQRFDUUERQRFBEUEBUQFRAUNhQRFDUUNhQ1FTUUNhQ1FQAGAJeSFDUUNhQ1FRAVEBQRFBEUERQ1FTUUNhQQFRAUERQRFBEUERQ1FBEUERQRFBAVEBQRFDYUEBU1FDYUNRQ2FDUVNRQADQU=='           
      licht_fernseher_schlafzimmer:
        friendly_name: Fernseher
        command_on: 'JgBYAAABL5EWDxYQFRAVERUQFREVEBYPFTUVNRY0FjQVNBY0FTUVNRY0FjMWEBUQFhAVEBURFTQWEBURFDUVNRU1FTQUNhQSEwAFIgABLEkUAAxbAAEsSRQADQU=='
        command_off: 'JgBYAAABK5QTEhMTExMSEhMTExITEhMTEzcUNRM3EzcTNxM2EzcTNxMSEzcTEhMTExITEhMTEzcTNhMTEzYTNxM3EzcTNxMSEwAFIgABLUgUAAxbAAEsSBUADQU=='                                     
               
  - platform: template
    switches:
      watchtv_schlafzimmer:
        friendly_name: Fernsehen
        entity_id:
          - switch.schlafzimmer_fernseher       
        value_template: "{{ is_state('switch.schlafzimmer_fernseher', 'on') }}"        
        turn_on:
          service: script.watchtv_schlafzimmer_on
        turn_off:
          service: script.watchtv_schlafzimmer_off             
    
cover:
  - platform: template
    covers:      
      fernseher_schlafzimmer_lautstaerke:
        friendly_name: Fernseher Lautstärke
        position_template: 50
        open_cover:
          service: switch.broadlink_send_packet_192_168_2_28
          data:
            packet:            
              - "JgBeAZOVEzcRORE4EhMRFBEUERMSExI4ETgSOBITERQRFBETEhMSOBE4EjgRFBEUERQRExITEhMRFBEUETgSOBE5ETgROREABgOUlBI4ETkROBEUERQRFBETEhMSOBE4EjgRFBEUERQRExITEjgROBI4ERQRFBETEhMSExEUERQRFBE4EjgROBI4ETkRAAYDlJQSOBE5ETgSExEUERQRExITEjgRORE4EhMRFBEUERMSExI4ETkROBITERQRFBETEhMSExITERQROBI4ETkROBI4EQAGA5SUEjgRORE4EhMRFBEUERQRExI4ETkROBITERQRFBEUERMSOBE5ETgSExEUERQRFBETEhMSExEUETgSOBE5ETgSOBEABgOUlBI4ETkROBITERQRFBETEhMSOBE4EjgRFBEUERQRExITEjgROBI4ERQRFBETEhMSExEUERQRFBE4EjgROBI4ETgSAA0FAAAAAAAAAAAAAA=="
        close_cover:
          service: switch.broadlink_send_packet_192_168_2_28
          data:
            packet:             
              - "JgAYAZSUEjgRORE4EhMRFBEUERQRExI4ETkROBITERQRFBETEhMSOBE4EhMSOBEUERQRExITEhMRFBE4EhMSOBE4EjgROREABgOTlRI4ETgSOBITERQRFBETEhMSOBE4EzcRFBEUERQRExITEjgROBITEjgRFBEUERMSExITERQROBITEjgSNxM3EjgRAAYDlJUROBI4ETgSExITERQRFBEUETgSOBE4ExISExEUERQRExI4ETkRExI4ERQRFBETEhMSExEUETgSExI4EjcTNxE5EQAGA5SUEjgRORE4ExIRFBEUERQRExI4ETkSNxITERQRFBEUERMSOBI4EhISOBEUERQRFBETEhMSExE5ERQROBI4ETgSOBEADQU=="
        stop_cover:
          service: switch.broadlink_send_packet_192_168_2_28
          data:
            packet: 
              - "JgBGAJWUETgSOBI4ERMSExITERQRFBE4EjgRORISEhMSExEUERQROBI4ETgSOBEUERQRExITEhMRFBEUERQROBI4ETgSOBEADQUAAA=="            
        icon_template: >-
          {% if is_state('switch.schlafzimmer_fernseher', 'on') %}
            mdi:volume-high
          {% else %}
            mdi:volume-low
          {% endif %}                
                            
script:
  watchtv_schlafzimmer_on:
    alias: "Fernsehen Schlafzimmer einschalten"
    sequence:
      - service: switch.turn_on
        entity_id: switch.schlafzimmer_fernseher
      - delay: '00:00:05'
      - service: light.turn_on
        entity_id: light.licht_fernseher_schlafzimmer      
      - service: switch.turn_on
        entity_id: switch.fernseher_schlafzimmer_remote
      - service: media_player.turn_on
        entity_id: media_player.fire_tv_schlafzimmer   
      - service: switch.turn_on
        entity_id: switch.kodi_schlafzimmer        
        
  watchtv_schlafzimmer_off:
    alias: "Fernsehen Schlafzimmer ausschalten"
    sequence:
      - service: switch.turn_off
        entity_id: switch.kodi_schlafzimmer           
      - service: media_player.turn_off
        entity_id: media_player.fire_tv_schlafzimmer         
      - service: switch.turn_off
        entity_id: switch.schlafzimmer_fernseher, switch.fernseher_schlafzimmer_remote
      - service: light.turn_off
        entity_id: light.licht_fernseher_schlafzimmer
      - service: input_boolean.turn_off
        entity_id: input_boolean.timer_schlafzimmer_aktiv
        
automation:             
  - alias: "Wiedergabe Schlafzimmer - Schalter"
    initial_state: true
    trigger:
      - platform: event
        event_type: xiaomi_aqara.click
        event_data:
          entity_id: binary_sensor.switch_158d0002134568
          click_type: single
    condition: 
      - condition: or
        conditions:          
        - condition: state
          entity_id: media_player.kodi_schlafzimmer
          state: 'playing'
        - condition: state
          entity_id: media_player.kodi_schlafzimmer
          state: 'paused'          
    action:
      - service: media_player.media_play_pause
        entity_id: media_player.kodi_schlafzimmer
        
homeassistant:
  customize:
    switch.watchtv_schlafzimmer:
      icon: mdi:television-classic 
    switch.schlafzimmer_fernseher:
      icon: mdi:television
      friendly_name: Fernseher    
      
    switch.fernseher_schlafzimmer_remote:
      hidden: true