switch:
  - platform: brematic
    host: !secret brematic_host
    system_code: '00100'
    switches:      
      sportzimmer_fernseher:
        unit_code: '10000'
        friendly_name: Sportzimmer Fernseher

homeassistant:
  customize:
    switch.sportzimmer_fernseher:
      icon: mdi:television
      assumed_state: false