media_player:
  - platform: androidtv
    host: 192.168.2.27
    name: Fire TV Sportzimmer   
    adbkey: '/home/homeassistant/.homeassistant/adbkey'
   
switch:
  - platform: template
    switches:
      kodi_sportzimmer:
        friendly_name: Kodi
        entity_id:
          - media_player.fire_tv_sportzimmer
        icon_template: >-
          mdi:kodi
        value_template: >-
          {{ state_attr('media_player.fire_tv_sportzimmer', 'source') == "Kodi" }}
        turn_on:
          - service: media_player.select_source
            data:
              entity_id: media_player.fire_tv_sportzimmer
              source: "org.xbmc.kodi"
        turn_off:
          - service: kodi.call_method
            data:
              entity_id: media_player.kodi_sportzimmer
              method: Input.Home
          - service: media_player.select_source
            data:
              entity_id: media_player.fire_tv_sportzimmer
              source: "com.amazon.tv.launcher"        

homeassistant:
  customize:
    switch.sportzimmer_fernseher:
      icon: mdi:television