media_player:
  - platform: androidtv
    host: 192.168.2.84
    name: Fire TV Schlafzimmer
    adbkey: '/home/homeassistant/.homeassistant/adbkey'

switch: 
  - platform: broadlink
    mac: 'B4:43:0D:F9:2F:E5'
    switches:
      - name: Schlafzimmer Fernseher Remote
        command_on: 'JgAYAZaSFDYUNRU1FBEUERQRFBAVEBQ2FDYUNRQRFBEUERQQFRAUERQ2FBEUEBUQFBEUERQRFDUUERQ2FDUVNRQ2FDUUNhQABgGWkhQ2FDUUNhQRFBEUEBUQFBEUNhQ1FDYUERQRFBAUERQRFBEUNRUQFBEUERQRFBAVEBQ2FBEUNRU1FDYUNRQ2FDUVAAYBlpIUNRU1FDYUERQQFRAUERQRFDUVNRQ2FBEUEBQRFBEUERQRFDUUERQRFBEUEBUQFRAUNhQRFDUUNhQ1FTUUNhQ1FQAGAJeSFDUUNhQ1FRAVEBQRFBEUERQ1FTUUNhQQFRAUERQRFBEUERQ1FBEUERQRFBAVEBQRFDYUEBU1FDYUNRQ2FDUVNRQADQU=='
        command_off: 'JgAYAZaSFDYUNRU1FBEUERQRFBAVEBQ2FDYUNRQRFBEUERQQFRAUERQ2FBEUEBUQFBEUERQRFDUUERQ2FDUVNRQ2FDUUNhQABgGWkhQ2FDUUNhQRFBEUEBUQFBEUNhQ1FDYUERQRFBAUERQRFBEUNRUQFBEUERQRFBAVEBQ2FBEUNRU1FDYUNRQ2FDUVAAYBlpIUNRU1FDYUERQQFRAUERQRFDUVNRQ2FBEUEBQRFBEUERQRFDUUERQRFBEUEBUQFRAUNhQRFDUUNhQ1FTUUNhQ1FQAGAJeSFDUUNhQ1FRAVEBQRFBEUERQ1FTUUNhQQFRAUERQRFBEUERQ1FBEUERQRFBAVEBQRFDYUEBU1FDYUNRQ2FDUVNRQADQU=='
      - name: Schlafzimmer Fernseher Licht
        command_on: 'JgBYAAABL5EWDxYQFRAVERUQFREVEBYPFTUVNRY0FjQVNBY0FTUVNRY0FjMWEBUQFhAVEBURFTQWEBURFDUVNRU1FTQUNhQSEwAFIgABLEkUAAxbAAEsSRQADQU=='
        command_off: 'JgBYAAABK5QTEhMTExMSEhMTExITEhMTEzcUNRM3EzcTNxM2EzcTNxMSEzcTEhMTExITEhMTEzcTNhMTEzYTNxM3EzcTNxMSEwAFIgABLUgUAAxbAAEsSBUADQU=='
  
  - platform: template
    switches:
      watchtv_schlafzimmer:
        friendly_name: Fernsehen
        value_template: "{{ is_state('switch.schlafzimmer_fernseher', 'on') }}"
        turn_on:
          service: script.watchtv_schlafzimmer_on
        turn_off:
          service: script.watchtv_schlafzimmer_off
          
      kodi_schlafzimmer:
        friendly_name: Kodi
        icon_template: >-
          mdi:kodi
        value_template: >-
          {{ state_attr('media_player.firetv_schlafzimmer', 'source') == "Kodi" }}
        turn_on:
          - service: media_player.select_source
            data:
              entity_id: media_player.firetv_schlafzimmer
              source: "org.xbmc.kodi"
        turn_off:
          - service: kodi.call_method
            data:
              entity_id: media_player.kodi_schlafzimmer
              method: Input.Home
          - service: media_player.select_source
            data:
              entity_id: media_player.firetv_schlafzimmer
              source: "com.amazon.tv.launcher"

cover:
  - platform: template
    covers:
      fernseher_schlafzimmer_lautstaerke:
        friendly_name: Fernseher Lautstärke
        position_template: 50
        open_cover:
          - service: remote.send_command
            data:
              entity_id: remote.broadlink_schlafzimmer_remote
              command: "b64:JgBeAZOVEzcRORE4EhMRFBEUERMSExI4ETgSOBITERQRFBETEhMSOBE4EjgRFBEUERQRExITEhMRFBEUETgSOBE5ETgROREABgOUlBI4ETkROBEUERQRFBETEhMSOBE4EjgRFBEUERQRExITEjgROBI4ERQRFBETEhMSExEUERQRFBE4EjgROBI4ETkRAAYDlJQSOBE5ETgSExEUERQRExITEjgRORE4EhMRFBEUERMSExI4ETkROBITERQRFBETEhMSExITERQROBI4ETkROBI4EQAGA5SUEjgRORE4EhMRFBEUERQRExI4ETkROBITERQRFBEUERMSOBE5ETgSExEUERQRFBETEhMSExEUETgSOBE5ETgSOBEABgOUlBI4ETkROBITERQRFBETEhMSOBE4EjgRFBEUERQRExITEjgROBI4ERQRFBETEhMSExEUERQRFBE4EjgROBI4ETgSAA0FAAAAAAAAAAAAAA=="          
        close_cover:
          - service: remote.send_command
            data:
              entity_id: remote.broadlink_schlafzimmer_remote
              command: "b64:JgAYAZSUEjgRORE4EhMRFBEUERQRExI4ETkROBITERQRFBETEhMSOBE4EhMSOBEUERQRExITEhMRFBE4EhMSOBE4EjgROREABgOTlRI4ETgSOBITERQRFBETEhMSOBE4EzcRFBEUERQRExITEjgROBITEjgRFBEUERMSExITERQROBITEjgSNxM3EjgRAAYDlJUROBI4ETgSExITERQRFBEUETgSOBE4ExISExEUERQRExI4ETkRExI4ERQRFBETEhMSExEUETgSExI4EjcTNxE5EQAGA5SUEjgRORE4ExIRFBEUERQRExI4ETkSNxITERQRFBEUERMSOBI4EhISOBEUERQRFBETEhMSExE5ERQROBI4ETgSOBEADQU=="
        stop_cover:
          - service: remote.send_command
            data:
              entity_id: remote.broadlink_schlafzimmer_remote
              command: "b64:JgBGAJWUETgSOBI4ERMSExITERQRFBE4EjgRORISEhMSExEUERQROBI4ETgSOBEUERQRExITEhMRFBEUERQROBI4ETgSOBEADQUAAA=="
        icon_template: >-
          {% if is_state('switch.schlafzimmer_fernseher', 'on') %}
            mdi:volume-high
          {% else %}
            mdi:volume-low
          {% endif %}

script:
  watchtv_schlafzimmer_on:
    alias: "Fernsehen Schlafzimmer einschalten"
    sequence:
      - service: switch.turn_on
        entity_id: switch.schlafzimmer_fernseher
      - delay: '00:00:05'
      - service: light.turn_on
        entity_id: light.fernseher_schlafzimmer
      - service: switch.turn_on
        entity_id: switch.schlafzimmer_fernseher_remote
      - service: media_player.turn_on
        entity_id: media_player.firetv_schlafzimmer
      - service: switch.turn_on
        entity_id: switch.kodi_schlafzimmer

  watchtv_schlafzimmer_off:
    alias: "Fernsehen Schlafzimmer ausschalten"
    sequence:
      - service: switch.turn_off
        entity_id: switch.kodi_schlafzimmer
      - service: media_player.turn_off
        entity_id: media_player.firetv_schlafzimmer
      - service: switch.turn_off
        entity_id: switch.schlafzimmer_fernseher, switch.schlafzimmer_fernseher_remote
      - service: light.turn_off
        entity_id: light.fernseher_schlafzimmer
      - service: input_boolean.turn_off
        entity_id: input_boolean.timer_schlafzimmer_aktiv

automation:       
  - alias: "Schlafzimmer Kodi - Wiedergabe"
    trigger:
      - platform: state        
        entity_id: binary_sensor.schalter_schlafzimmer
        to: 'on'
      - platform: state        
        entity_id: sensor.schalter_schlafzimmer
        to: '2'
      - platform: state        
        entity_id: binary_sensor.im_bett
        to: 'on'
        for:
          seconds: 1   
    condition:
      - condition: state        
        entity_id: binary_sensor.im_bett
        state: 'on'   
        for:
          seconds: 1
      - condition: or
        conditions:
        - condition: state
          entity_id: media_player.kodi_schlafzimmer
          state: 'playing'
        - condition: state
          entity_id: media_player.kodi_schlafzimmer
          state: 'paused'
    action:
      - service: media_player.media_play_pause
        entity_id: media_player.kodi_schlafzimmer  
        
  - alias: "Schlafzimmer - Kodi gestartet"
    trigger:
      platform: state
      entity_id: media_player.kodi_schlafzimmer
      to: 'playing'
    condition:
      - condition: state
        entity_id: binary_sensor.schlafen_aktiv
        state: 'on'
    action:
      - service: light.turn_off
        entity_id: light.bett, light.kleiderschrank, light.flur_vorne, light.flur_hinten, light.badezimmerschrank, light.schreibtisch, light.kuche_regal, light.arbeitszimmer_lampe, light.sportzimmer_regal

  - alias: "Schlafzimmer - Kodi pausiert"
    trigger:
      platform: state
      entity_id: binary_sensor.bewegungsmelder_schlafzimmer
      to: 'on'
    condition:
      - condition: state
        entity_id: media_player.kodi_schlafzimmer
        state: 'playing'
      - condition: state
        entity_id: binary_sensor.schlafen_aktiv
        state: 'on'
    action:
      - service: media_player.media_pause
        entity_id: media_player.kodi_schlafzimmer  

homeassistant:
  customize:
    switch.watchtv_schlafzimmer:
      icon: mdi:television-classic
    switch.schlafzimmer_fernseher:
      icon: mdi:television