switch: 
  - platform: broadlink
    mac: 'B4:43:0D:F9:2F:E5'
    switches:
      - name: Schlafzimmer Fernseher Remote
        command_on: 'JgAYAZaSFDYUNRU1FBEUERQRFBAVEBQ2FDYUNRQRFBEUERQQFRAUERQ2FBEUEBUQFBEUERQRFDUUERQ2FDUVNRQ2FDUUNhQABgGWkhQ2FDUUNhQRFBEUEBUQFBEUNhQ1FDYUERQRFBAUERQRFBEUNRUQFBEUERQRFBAVEBQ2FBEUNRU1FDYUNRQ2FDUVAAYBlpIUNRU1FDYUERQQFRAUERQRFDUVNRQ2FBEUEBQRFBEUERQRFDUUERQRFBEUEBUQFRAUNhQRFDUUNhQ1FTUUNhQ1FQAGAJeSFDUUNhQ1FRAVEBQRFBEUERQ1FTUUNhQQFRAUERQRFBEUERQ1FBEUERQRFBAVEBQRFDYUEBU1FDYUNRQ2FDUVNRQADQU=='
        command_off: 'JgAYAZaSFDYUNRU1FBEUERQRFBAVEBQ2FDYUNRQRFBEUERQQFRAUERQ2FBEUEBUQFBEUERQRFDUUERQ2FDUVNRQ2FDUUNhQABgGWkhQ2FDUUNhQRFBEUEBUQFBEUNhQ1FDYUERQRFBAUERQRFBEUNRUQFBEUERQRFBAVEBQ2FBEUNRU1FDYUNRQ2FDUVAAYBlpIUNRU1FDYUERQQFRAUERQRFDUVNRQ2FBEUEBQRFBEUERQRFDUUERQRFBEUEBUQFRAUNhQRFDUUNhQ1FTUUNhQ1FQAGAJeSFDUUNhQ1FRAVEBQRFBEUERQ1FTUUNhQQFRAUERQRFBEUERQ1FBEUERQRFBAVEBQRFDYUEBU1FDYUNRQ2FDUVNRQADQU=='
      - name: Schlafzimmer Fernseher Licht
        command_on: 'JgBYAAABL5EWDxYQFRAVERUQFREVEBYPFTUVNRY0FjQVNBY0FTUVNRY0FjMWEBUQFhAVEBURFTQWEBURFDUVNRU1FTQUNhQSEwAFIgABLEkUAAxbAAEsSRQADQU=='
        command_off: 'JgBYAAABK5QTEhMTExMSEhMTExITEhMTEzcUNRM3EzcTNxM2EzcTNxMSEzcTEhMTExITEhMTEzcTNhMTEzYTNxM3EzcTNxMSEwAFIgABLUgUAAxbAAEsSBUADQU=='
  
  - platform: template
    switches:
      watchtv_schlafzimmer:
        friendly_name: Fernsehen
        value_template: "{{ is_state('switch.schlafzimmer_fernseher', 'on') }}"
        turn_on:
          - service: switch.turn_on
            entity_id: switch.schlafzimmer_fernseher
          - delay: '00:00:05'
          - service: light.turn_on
            entity_id: light.fernseher_schlafzimmer
          - service: switch.turn_on
            entity_id: switch.schlafzimmer_fernseher_remote
          - service: media_player.turn_on
            entity_id: media_player.fire_tv_schlafzimmer
          - service: switch.turn_on
            entity_id: switch.kodi_schlafzimmer
        turn_off:
          - service: switch.turn_off
            entity_id: switch.kodi_schlafzimmer
          - service: media_player.turn_off
            entity_id: media_player.fire_tv_schlafzimmer
          - service: switch.turn_off
            entity_id: switch.schlafzimmer_fernseher, switch.schlafzimmer_fernseher_remote
          - service: light.turn_off
            entity_id: light.fernseher_schlafzimmer
          - service: input_boolean.turn_off
            entity_id: input_boolean.timer_schlafzimmer_aktiv
          
      kodi_schlafzimmer:
        friendly_name: Kodi
        icon_template: >-
          mdi:kodi
        value_template: >-
          {{ state_attr('media_player.fire_tv_schlafzimmer', 'source') == "Kodi" }}
        turn_on:
          - service: media_player.select_source
            data:
              entity_id: media_player.fire_tv_schlafzimmer
              source: "org.xbmc.kodi"
        turn_off:
          - service: kodi.call_method
            data:
              entity_id: media_player.kodi_schlafzimmer
              method: Input.Home
          - service: media_player.select_source
            data:
              entity_id: media_player.fire_tv_schlafzimmer
              source: "com.amazon.tv.launcher"
              
cover:
  - platform: template
    covers:
      fernseher_schlafzimmer_lautstaerke:
        friendly_name: Fernseher Lautstärke
        position_template: 50
        open_cover:
          - service: remote.send_command
            data:
              entity_id: remote.broadlink_schlafzimmer_remote
              command: "b64:JgBeAZOVEzcRORE4EhMRFBEUERMSExI4ETgSOBITERQRFBETEhMSOBE4EjgRFBEUERQRExITEhMRFBEUETgSOBE5ETgROREABgOUlBI4ETkROBEUERQRFBETEhMSOBE4EjgRFBEUERQRExITEjgROBI4ERQRFBETEhMSExEUERQRFBE4EjgROBI4ETkRAAYDlJQSOBE5ETgSExEUERQRExITEjgRORE4EhMRFBEUERMSExI4ETkROBITERQRFBETEhMSExITERQROBI4ETkROBI4EQAGA5SUEjgRORE4EhMRFBEUERQRExI4ETkROBITERQRFBEUERMSOBE5ETgSExEUERQRFBETEhMSExEUETgSOBE5ETgSOBEABgOUlBI4ETkROBITERQRFBETEhMSOBE4EjgRFBEUERQRExITEjgROBI4ERQRFBETEhMSExEUERQRFBE4EjgROBI4ETgSAA0FAAAAAAAAAAAAAA=="          
        close_cover:
          - service: remote.send_command
            data:
              entity_id: remote.broadlink_schlafzimmer_remote
              command: "b64:JgAYAZSUEjgRORE4EhMRFBEUERQRExI4ETkROBITERQRFBETEhMSOBE4EhMSOBEUERQRExITEhMRFBE4EhMSOBE4EjgROREABgOTlRI4ETgSOBITERQRFBETEhMSOBE4EzcRFBEUERQRExITEjgROBITEjgRFBEUERMSExITERQROBITEjgSNxM3EjgRAAYDlJUROBI4ETgSExITERQRFBEUETgSOBE4ExISExEUERQRExI4ETkRExI4ERQRFBETEhMSExEUETgSExI4EjcTNxE5EQAGA5SUEjgRORE4ExIRFBEUERQRExI4ETkSNxITERQRFBEUERMSOBI4EhISOBEUERQRFBETEhMSExE5ERQROBI4ETgSOBEADQU=="
        stop_cover:
          - service: remote.send_command
            data:
              entity_id: remote.broadlink_schlafzimmer_remote
              command: "b64:JgBGAJWUETgSOBI4ERMSExITERQRFBE4EjgRORISEhMSExEUERQROBI4ETgSOBEUERQRExITEhMRFBEUERQROBI4ETgSOBEADQUAAA=="
        icon_template: >-
          {% if is_state('switch.schlafzimmer_fernseher', 'on') %}
            mdi:volume-high
          {% else %}
            mdi:volume-low
          {% endif %}

automation:       
  - alias: "Schlafzimmer - Wiedergabe"
    id: "schlafzimmer_wiedergabe" 
    trigger:
      - id: pause
        platform: state
        entity_id: binary_sensor.bewegungsmelder_bett
        to: 'on'
      - id: play
        platform: state        
        entity_id: binary_sensor.im_bett
        to: 'on'
        for:
          seconds: 1       
      - id: play_pause
        platform: event
        event_type: zha_event
        event_data:
          device_ieee: 00:15:8d:00:02:13:45:68
          command: attribute_updated
          args:
            attribute_id: 0
            attribute_name: on_off     
            value: 1
    condition:
      - "{{ is_state('binary_sensor.schlafen_aktiv', 'on') }}"
      - condition: or
        conditions:
          - "{{ states('media_player.kodi_schlafzimmer') in ['playing', 'paused']}}"
          - "{{ states('media_player.fire_tv_schlafzimmer') in ['playing', 'paused']}}"
      - condition: template
        value_template: >-
          {% set now = as_timestamp(now()) | int(0) %}
          {% set last = as_timestamp(state_attr("automation.schlafzimmer_wiedergabe", "last_triggered"), None) | int(0) %}

          {{now - last > 5 }}          
    action:
      - choose:
          - conditions:
              - "{{ states('media_player.kodi_schlafzimmer') in ['playing', 'paused']}}"
            sequence: 
              - service: media_player.media_{{ trigger.id }}
                entity_id: media_player.kodi_schlafzimmer              
          - conditions:
              - "{{ states('media_player.fire_tv_schlafzimmer') in ['playing', 'paused']}}"
              - "{{ state_attr('media_player.fire_tv_schlafzimmer', 'source') in ['Netflix', 'Disney+']}}"
            sequence: 
              - service: media_player.media_{{ trigger.id }}
                entity_id: media_player.fire_tv_schlafzimmer

  - alias: "Schlafzimmer - Fernseher ausschalten"
    id: "schlafzimmer_fernseher_ausschalten"
    trigger:
      - id: schalter_schlafzimmer
        platform: event
        event_type: zha_event
        event_data:
          device_ieee: 00:15:8d:00:02:13:45:68
          command: attribute_updated
          args:
            attribute_id: 32768
            attribute_name: Unknown     
            value: 3
    condition:
      - condition: state
        entity_id: input_boolean.timer_schlafzimmer_aktiv
        state: 'on'        
    action:
      - service: switch.turn_off
        entity_id: switch.watchtv_schlafzimmer

homeassistant:
  customize:
    switch.watchtv_schlafzimmer:
      icon: mdi:television-classic
    switch.schlafzimmer_fernseher:
      icon: mdi:television