#media_player:
#  - platform: androidtv
#    host: !secret firetv_sportzimmer_host
#    name: Fire TV Sportzimmer   
#    adbkey: '/home/homeassistant/.homeassistant/adbkey'
   
notify:
  - platform: kodi
    name: Kodi Sportzimmer
    host: !secret firetv_sportzimmer_host  
    
input_boolean:
  kodi_sportzimmer_pausiert:
    name: Kodi Sportzimmer pausiert
    initial: off
    
switch:
  - platform: template
    switches:
      kodi_sportzimmer:
        friendly_name: Kodi
        icon_template: >-
          mdi:kodi
        value_template: >-
          {{ state_attr('media_player.fire_tv_sportzimmer', 'source') == "Kodi" }}
        turn_on:
          - service: media_player.select_source
            data:
              entity_id: media_player.fire_tv_sportzimmer
              source: "org.xbmc.kodi"
        turn_off:
          - service: kodi.call_method
            data:
              entity_id: media_player.kodi_sportzimmer
              method: Input.Home
          - service: media_player.select_source
            data:
              entity_id: media_player.fire_tv_sportzimmer
              source: "com.amazon.tv.launcher"        
             
automation:
  - alias: 'Telefon aktiv - Kodi Sportzimmer pausieren'
    trigger:
      - platform: state
        entity_id: sensor.telefon
        to: 'ringing'
      - platform: state
        entity_id: sensor.telefon
        to: 'dialing'
    condition:
      - condition: state
        entity_id: media_player.kodi_sportzimmer
        state: 'playing'   
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.kodi_sportzimmer_pausiert
      - service: media_player.media_pause
        entity_id: media_player.kodi_sportzimmer      
      - service: notify.kodi_sportzimmer
        data:
          title: 'Telefon'
          message: >-
            {% if is_state("sensor.telefon", 'dialing') %}
              {{ state_attr('sensor.telefon', 'to_name') }} ({{ state_attr('sensor.telefon', 'to') }}) wird angerufen.
            {% elif is_state("sensor.telefon", 'ringing') %}
              {% if state_attr('sensor.telefon', 'from') == '' %}
                Ein Anruf ohne Rufnummer.
              {% elif state_attr('sensor.telefon', 'from_name')  == 'unknown' %}
                Ein Anruf von einer unbekannten Rufnummer ({{ state_attr('sensor.telefon', 'from') }}).
              {% else %}
                Anruf von {{ state_attr('sensor.telefon', 'from_name') }} ({{ state_attr('sensor.telefon', 'from') }}).
              {% endif %}
            {% endif %}
          data:
            displaytime: 5000
            icon: "info"

  - alias: 'Telefon inaktiv - Kodi Sportzimmer wiedergeben'
    trigger:
      - platform: state
        entity_id: sensor.telefon
        to: 'idle'
    condition:
      - condition: state
        entity_id: media_player.kodi_sportzimmer
        state: 'paused'
      - condition: state
        entity_id: input_boolean.kodi_sportzimmer_pausiert
        state: 'on'
      - condition: template
        value_template: '{{ is_state("sensor.handy", "incoming") == False and is_state("sensor.handy", "outgoing") == False }}'        
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.kodi_sportzimmer_pausiert
      - service: media_player.media_play
        entity_id: media_player.kodi_spotzimmer
      - service: notify.kodi_sportzimmer
        data:
          title: 'Telefon'
          message: 'Anruf beendet'
          data:
            displaytime: 2000
            icon: "info"         

  - alias: 'Handy aktiv - Kodi Sportzimmer pausieren'
    trigger:
      - platform: state
        entity_id: sensor.handy
        to: 'incoming'
      - platform: state
        entity_id: sensor.handy
        to: 'outgoing'
    condition:
      - condition: state
        entity_id: media_player.kodi_sportzimmer
        state: 'playing'           
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.kodi_sportzimmer_pausiert
      - service: media_player.media_pause
        entity_id: media_player.kodi_sportzimmer
      - service: notify.kodi_sportzimmer
        data:
          title: 'Handy'
          message: >-
            {% set name = state_attr('sensor.handy', 'name') %}
            {% set number = state_attr('sensor.handy', 'number') %}
            
            {% if is_state("sensor.handy", "outgoing") %}
              {% if name == number %}
                {{ state_attr('sensor.handy', 'name') }} wird angerufen.
              {% else %}
                {{ state_attr('sensor.handy', 'name') }} ({{ state_attr('sensor.handy', 'number') }}) wird angerufen.
              {% endif %}
              
            {% elif is_state("sensor.handy", "incoming") %}
              {% if name == number %}
                Eingehender Anruf von {{ state_attr('sensor.handy', 'name') }}.
              {% else %}
                Eingehender Anruf von {{ state_attr('sensor.handy', 'name') }} ({{ state_attr('sensor.handy', 'number') }}).
              {% endif %}                          
            {% endif %}                                 
          data:
            displaytime: 5000
            icon: "info"

  - alias: 'Handy inaktiv - Kodi Sportzimmer wiedergeben'
    trigger:
      - platform: state
        entity_id: sensor.handy
        to: 'idle'
    condition:
      - condition: state
        entity_id: media_player.kodi_sportzimmer
        state: 'paused'
      - condition: state
        entity_id: input_boolean.kodi_sportzimmer_pausiert
        state: 'on'
      - condition: state
        entity_id: sensor.telefon
        state: 'idle'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.kodi_sportzimmer_pausiert
      - service: media_player.media_play
        entity_id: media_player.kodi_sportzimmer
      - service: notify.kodi_sportzimmer
        data:
          title: 'Handy'
          message: 'Anruf beendet'
          data:
            displaytime: 2000
            icon: "info"

homeassistant:
  customize:
    switch.sportzimmer_fernseher:
      icon: mdi:television