notify:
  - platform: kodi
    name: Kodi Wohnzimmer
    host: !secret computer_host
    username: !secret kodi_username
    password: !secret kodi_password
    
input_boolean:
  musik_ausschalten:
    name: Musik ausschalten
    icon: mdi:music-off
    
  kodi_wohnzimmer_pausiert:
    name: Kodi Wohnzimmer pausiert    
  kodi_wohnzimmer_pausieren:
    name: Kodi Wohnzimmer pausieren    
    icon: mdi:sync-off

  youtube_wohnzimmer_aktiv:
    name: Youtube Wohnzimmer aktiv
    icon: mdi:youtube-tv
  youtube_wohnzimmer_pausiert:
    name: Youtube Wohnzimmer pausiert    
  youtube_wohnzimmer_pausieren:
    name: Youtube Wohnzimmer pausieren    
    icon: mdi:sync-off
    
binary_sensor:
  - platform: mqtt
    name: "Kodi Wohnzimmer - MQTT"    
    state_topic: "kodi_wohnzimmer/connected"
    payload_on: "2"
    payload_off: "0"
    device_class: connectivity
    json_attributes_topic: "kodi_wohnzimmer/status/progress"
    json_attributes_template: "{{ value_json | tojson }}"   

  - platform: template
    sensors:
      youtube_wohnzimmer_aktiv:
        friendly_name: Youtube aktiv
        icon_template: "mdi:youtube-tv"
        value_template: "{{ is_state('input_boolean.youtube_wohnzimmer_aktiv', 'on') }}"
    
cover:
  - platform: template
    covers:
      kodi_untertitel:
        friendly_name: "Untertitel"
        position_template: 50
        open_cover:
          service: kodi.call_method
          data:
            entity_id: media_player.kodi_wohnzimmer
            method: Input.ExecuteAction
            action: subtitledelayplus
        close_cover:
          service: kodi.call_method
          data:
            entity_id: media_player.kodi_wohnzimmer
            method: Input.ExecuteAction
            action: subtitledelayminus
        stop_cover:
          service: kodi.call_method
          data:
            entity_id: media_player.kodi_wohnzimmer
            method: Input.ExecuteAction
            action: showsubtitles
        icon_template: >-
          mdi:message-bulleted      

      fernseher_sender:
        friendly_name: "Fernseher Sender"
        position_template: 50
        open_cover:
          - service: media_player.play_media
            data:
              entity_id: media_player.fernseher_wohnzimmer
              media_content_id: "KEY_CHUP"
              media_content_type: "send_key"
        close_cover:
          - service: media_player.play_media
            data:
              entity_id: media_player.fernseher_wohnzimmer
              media_content_id: "KEY_CHDOWN"
              media_content_type: "send_key"
        stop_cover:
          - service: media_player.play_media
            data:
              entity_id: media_player.fernseher_wohnzimmer
              media_content_id: "KEY_PRECH"
              media_content_type: "send_key"
        icon_template: >-
          mdi:remote-tv

switch:
  - platform: template
    switches:
      watchtv_wohnzimmer:
        friendly_name: "Fernsehen"
        value_template: "{{ is_state('media_player.fernseher_wohnzimmer', 'on') }}"
        turn_on:
          - service: media_player.turn_on
            entity_id: media_player.fernseher_wohnzimmer  
          - choose:
              - conditions:
                  - condition: state
                    entity_id: media_player.soundbar
                    state: 'off'
                sequence:  
                  - service: media_player.turn_on
                    entity_id: media_player.soundbar        
                  - wait_template: "{{is_state('media_player.soundbar', 'on')}}"
                  - service: media_player.select_source
                    entity_id: media_player.soundbar
                    data:
                      source: TV
        turn_off:
          - service: media_player.media_stop
            entity_id: media_player.kodi_wohnzimmer
          - wait_template: "{{is_state('media_player.kodi_wohnzimmer', 'idle')}}"
            timeout: '00:00:02'
            continue_on_timeout: 'true'
          - service: media_player.turn_off
            entity_id: media_player.kodi_wohnzimmer
          - wait_template: "{{is_state('media_player.kodi_wohnzimmer', 'off')}}"
            timeout: '00:00:02'
            continue_on_timeout: 'true'          
          - service: media_player.turn_off
            entity_id: media_player.fernseher_wohnzimmer
          - choose:
              - conditions:
                  - condition: state
                    entity_id: media_player.soundbar
                    state: 'on'
                sequence:
                  - service: media_player.turn_off
                    entity_id: media_player.soundbar
          
automation:      
  - alias: "Kodi Wohnzimmer - Musik ausschalten"
    id: "kodi_wohnzimmer_musik_ausschalten"
    trigger:
      - platform: state
        entity_id: media_player.kodi_wohnzimmer
        from: 'off'
        to: 'idle'
    condition:
      - condition: state
        state: 'on'
        entity_id: switch.alle_radios
      - condition: state
        state: 'on'
        entity_id: input_boolean.musik_ausschalten
      - condition: numeric_state
        entity_id: sensor.laufzeit_minuten
        above: 2
    action:
      - service: script.radios_pausieren
      - service: switch.turn_off
        entity_id: switch.wohnzimmer_radio, switch.balkon_radio, switch.flur_radio, switch.kuche_radio, switch.schlafzimmer_radio, switch.arbeitszimmer_radio     

  - id: "kodi_wohnzimmer_wiedergabe"
    alias: "Kodi Wohnzimmer - Wiedergabe"
    trigger:
      - platform: state
        entity_id: binary_sensor.schalter_wohnzimmer
        to: 'off'
      - platform: state
        entity_id: sensor.cube_bewegung        
    condition:
      - condition: template
        value_template: >-
          {% if trigger.entity_id == 'sensor.cube_bewegung' %}
            {{ True if "flip90" in trigger.to_state.state else False }}
          {% else %}
            True
          {% endif %}   
      - condition: or
        conditions:
        - condition: state
          entity_id: media_player.kodi_wohnzimmer
          state: 'playing'
        - condition: state
          entity_id: media_player.kodi_wohnzimmer
          state: 'paused'
    action:
      - service: media_player.media_play_pause
        entity_id: media_player.kodi_wohnzimmer     
           
  - alias: "Kodi Wohnzimmer - Nächster Titel"
    id: "kodi_wohnzimmer_naechster_titel"
    trigger:
      - platform: state
        entity_id: sensor.cube_bewegung
    condition:
      - condition: template
        value_template: '{{ True if "drop" in trigger.to_state.state else False }}'         
      - condition: template
        value_template: '{{ is_state("media_player.kodi_wohnzimmer", "off") == False }}'
    action:
      - service: media_player.media_next_track
        entity_id: media_player.kodi_wohnzimmer

  - id: "kodi_wohnzimmer_untertitel"
    alias: "Kodi Wohnzimmer - Untertitel"
    trigger:
      - platform: state
        entity_id: sensor.cube_bewegung
    condition:
      - condition: template
        value_template: '{{ True if "shake" in trigger.to_state.state else False }}'         
      - condition: state
        entity_id: media_player.kodi_wohnzimmer
        state: 'playing'        
    action:
      - service: cover.stop_cover
        entity_id: cover.kodi_untertitel

  - alias: "Kodi Wohnzimmer - Pausieren"
    id: "kodi_wohnzimmer_pausieren"
    trigger:
      - platform: state
        entity_id: binary_sensor.bewegungsmelder_flur_vorne
        to: 'on'
      - platform: state
        entity_id: binary_sensor.bewegungsmelder_flur_hinten
        to: 'on'
      - platform: state
        entity_id: binary_sensor.bewegungsmelder_balkon
        to: 'on'    
      - platform: state
        entity_id: sensor.schalter_balkon
        to: '2'        
    condition:
      - condition: state
        entity_id: media_player.kodi_wohnzimmer
        state: 'playing'
      - condition: state
        entity_id: input_boolean.kodi_wohnzimmer_pausieren
        state: 'on'
      - condition: state
        entity_id: binary_sensor.besuch
        state: 'off'        
      - condition: state
        entity_id: sensor.telefon
        state: 'idle'
      - condition: template
        value_template: '{{ is_state("sensor.handy", "incoming") == False and is_state("sensor.handy", "outgoing") == False }}'
      - condition: template       
        value_template: >-
          {% set triggerEntity = trigger.entity_id %}
          
          {% if triggerEntity == 'binary_sensor.bewegungsmelder_balkon' or triggerEntity == 'sensor.schalter_balkon' %}
            {{ is_state('binary_sensor.balkontuer', 'on') }}
          {% else %}
            True
          {% endif %}
    action:
      - service: media_player.media_pause
        entity_id: media_player.kodi_wohnzimmer        
      - service: input_boolean.turn_on
        entity_id: input_boolean.kodi_wohnzimmer_pausiert
      - choose:
          - conditions:
              - condition: template
                value_template: >-
                  {% set triggerEntity = trigger.entity_id %}

                  {% if triggerEntity == 'binary_sensor.bewegungsmelder_balkon' or triggerEntity == 'sensor.schalter_balkon' %}
                    {{ is_state('binary_sensor.sonne_tagsueber', 'off') }}
                  {% else %}
                    False
                  {% endif %}                  
            sequence:
              - service: switch.turn_on
                entity_id: light.balkon_licht  

  - alias: "Kodi Wohnzimmer - Starten"
    id: "kodi_wohnzimmer_starten"
    trigger:
      - platform: state
        entity_id: binary_sensor.bewegungsmelder_wohnzimmer
        to: 'on'
    condition:
      - condition: state
        entity_id: media_player.kodi_wohnzimmer
        state: 'paused'
      - condition: state
        entity_id: input_boolean.kodi_wohnzimmer_pausiert
        state: 'on'
      - condition: state
        entity_id: sensor.telefon
        state: 'idle'
      - condition: template
        value_template: '{{ is_state("sensor.handy", "incoming") == False and is_state("sensor.handy", "outgoing") == False }}'
    action:
      - service: media_player.media_play
        entity_id: media_player.kodi_wohnzimmer
      - service: input_boolean.turn_off
        entity_id: input_boolean.kodi_wohnzimmer_pausiert
      - service: light.turn_off
        entity_id: light.flur_vorne, light.flur_hinten, light.badezimmerschrank, light.schreibtisch, light.kuche_regal, light.arbeitszimmer_lampe, light.balkon_licht, light.sportzimmer_regal
      - condition: state
        entity_id: media_player.badezimmer
        state: 'playing'
      - service: media_player.media_pause
        entity_id: media_player.badezimmer

  - alias: "Youtube Wohnzimmer - Pausieren"
    id: youtube_wohnzimmer_pausieren
    trigger:
      - platform: state
        entity_id: binary_sensor.bewegungsmelder_flur_vorne
        to: 'on'
      - platform: state
        entity_id: binary_sensor.bewegungsmelder_flur_hinten
        to: 'on'
      - platform: state
        entity_id: binary_sensor.bewegungsmelder_balkon
        to: 'on'     
      - platform: state
        entity_id: sensor.schalter_balkon
        to: '2'
    condition:
      - condition: state
        entity_id: binary_sensor.youtube_wohnzimmer_aktiv
        state: 'on'
      - condition: state
        entity_id: input_boolean.youtube_wohnzimmer_pausieren
        state: 'on'
      - condition: state
        entity_id: input_boolean.youtube_wohnzimmer_pausiert
        state: 'off'        
      - condition: state
        entity_id: binary_sensor.besuch
        state: 'off'        
      - condition: state
        entity_id: sensor.telefon
        state: 'idle'
      - condition: template
        value_template: '{{ is_state("sensor.handy", "incoming") == False and is_state("sensor.handy", "outgoing") == False }}'
      - condition: template       
        value_template: >-
          {% set triggerEntity = trigger.entity_id %}
          
          {% if triggerEntity == 'binary_sensor.bewegungsmelder_balkon' or triggerEntity == 'sensor.schalter_balkon' %}
            {{ is_state('binary_sensor.balkontuer', 'on') }}
          {% else %}
            True
          {% endif %}        
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.youtube_wohnzimmer_pausiert
      - service: switch.turn_on
        entity_id: switch.computer_wiedergabe                

  - alias: "Youtube Wohnzimmer - Starten"
    id: youtube_wohnzimmer_starten
    trigger:
      - platform: state
        entity_id: binary_sensor.bewegungsmelder_wohnzimmer
        to: 'on'
    condition:
      - condition: state
        entity_id: input_boolean.youtube_wohnzimmer_pausiert
        state: 'on'
      - condition: state
        entity_id: sensor.telefon
        state: 'idle'
      - condition: template
        value_template: '{{ is_state("sensor.handy", "incoming") == False and is_state("sensor.handy", "outgoing") == False }}'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.youtube_wohnzimmer_pausiert      
      - service: switch.turn_on
        entity_id: switch.computer_wiedergabe
      - service: light.turn_off
        entity_id: light.flur_vorne, light.flur_hinten, light.badezimmerschrank, light.schreibtisch, light.kuche_regal, light.arbeitszimmer_lampe, light.balkon_licht, light.sportzimmer_regal
      - condition: state
        entity_id: media_player.badezimmer
        state: 'playing'
      - service: media_player.media_pause
        entity_id: media_player.badezimmer                      
           
  - alias: "Soundbar Lautstärke - Cube"
    id: "soundbar_laustaerke_cube"
    trigger:
      - platform: state
        entity_id: sensor.cube_drehung
    condition:
      - condition: state
        entity_id: media_player.soundbar
        state: 'on'
      - condition: numeric_state
        entity_id: sensor.laufzeit_minuten
        above: 5       
      - condition: template
        value_template: >-
          {% set now = as_timestamp(now()) | int %}
          {% set last = as_timestamp(state_attr("automation.soundbar_lautstarke_cube", "last_triggered")) | int %}
          {% set diff = ((now - last)) | int %}

          {{ diff >= 5 }}        
    action:
      - service: media_player.volume_set
        data_template:
          entity_id: media_player.soundbar
          volume_level: >
            {% if is_state('media_player.soundbar', 'off') %}
              {% set oldState = 0 %}
            {% elif state_attr('media_player.soundbar', 'volume_level') == None %}            
              {% set oldState = 0 %}
            {% else %}
              {% set oldState = state_attr('media_player.soundbar', 'volume_level') | float -%}
            {% endif %}

            {% if trigger.to_state.state | float > 0 %}
               {% set newState = oldState + 0.05 -%}
            {% else %}
               {% set newState = oldState - 0.05 -%}
            {% endif %}

            {{ newState }}

homeassistant:
  customize:
    media_player.soundbar:
      icon: mdi:music
          
    switch.watchtv_wohnzimmer:
      icon: mdi:television-classic