input_boolean:
  musik_ausschalten:
    name: Musik ausschalten
    icon: mdi:music-off
    
  wiedergabe_pausieren:
    name: Wiedergabe pausieren
    icon: mdi:play-pause  

template:
  - switch:
      - default_entity_id: switch.watchtv_wohnzimmer
        name: Fernsehen Wohnzimmer
        state: "{{ is_state('media_player.fernseher_wohnzimmer', 'on') }}"
        turn_on:
          - action: media_player.turn_on
            entity_id: media_player.fernseher_wohnzimmer            
          - choose:
            - conditions:
              - condition: state
                entity_id: media_player.soundbar
                state: 'off'
                match: all
              sequence:
                - action: media_player.turn_on
                  entity_id:
                    - media_player.soundbar                
                - wait_template: '{{is_state(''media_player.soundbar'', ''on'')}}'
                - action: media_player.select_source
                  entity_id: media_player.soundbar
                  data:
                    source: TV                
        turn_off:
          - action: media_player.turn_off
            entity_id: media_player.fernseher_wohnzimmer            
          - choose:
            - conditions:
                - condition: state
                  entity_id: media_player.soundbar
                  state: 'on'
                  match: all
              sequence:
                - action: media_player.turn_off
                  entity_id: media_player.soundbar                   
     
  - cover:
      - default_entity_id: cover.fernseher_sender
        name: Fernseher Sender
        icon: mdi:remote-tv        
        position: '50'     
        open_cover:
          - action: media_player.play_media
            data:
              entity_id: media_player.fernseher_wohnzimmer
              media_content_id: "KEY_CHUP"
              media_content_type: "send_key"
        close_cover:
          - action: media_player.play_media
            data:
              entity_id: media_player.fernseher_wohnzimmer
              media_content_id: "KEY_CHDOWN"
              media_content_type: "send_key"
        stop_cover:
          - action: media_player.play_media
            data:
              entity_id: media_player.fernseher_wohnzimmer
              media_content_id: "KEY_PRECH"
              media_content_type: "send_key"

      
automation:
  - alias: "Fernseher eingeschaltet - Radios ausschalten"
    id: "fernseher_eingeschaltet_radios_ausschalten"
    trigger:
      - platform: state
        entity_id: switch.watchtv_wohnzimmer
        to: 'on' 
    condition:    
      - "{{ is_state('switch.wiedergabe_aktiv', 'on') and states('sensor.radios_eingeschaltet') | int() > 1 }}"      
    action:    
      - service: switch.turn_off
        entity_id: switch.wohnzimmer_radio, switch.balkon_radio, switch.flur_radio, switch.kueche_radio, switch.badezimmer_radio, switch.schlafzimmer_radio          
      - if: "{{ is_state('binary_sensor.home_office_aktiv', 'off') }}"
        then:
          - service: switch.turn_off
            entity_id: switch.zimmer_aaron_radio 
           
  - alias: "Soundbar aussschalten"
    id: "soundbar_aussschalten"
    trigger:
      - platform: state
        entity_id: switch.watchtv_wohnzimmer
        to: 'off'
        for:
          minutes: 10
    condition:    
      - "{{ is_state('media_player.soundbar', 'on') }}"
    action:    
      - service: media_player.turn_off
        entity_id: media_player.soundbar      
        
homeassistant:
  customize:
    media_player.soundbar:
      icon: mdi:music
          
    switch.watchtv_wohnzimmer:
      icon: mdi:television-classic