media_player:
  - platform: androidtv
    host: !secret firetv_sportzimmer_host
    name: Fire TV Sportzimmer
   
notify:
  - platform: kodi
    name: Kodi Sportzimmer
    host: !secret firetv_sportzimmer_host  
    
input_boolean:
  kodi_sportzimmer_pausiert:
    name: Kodi Sportzimmer pausiert
    
switch:
  - platform: template
    switches:
      kodi_sportzimmer:
        friendly_name: Kodi
        icon_template: >-
          mdi:kodi
        value_template: >-
          {{ state_attr('media_player.fire_tv_sportzimmer', 'source') == "Kodi" }}
        turn_on:
          - service: media_player.select_source
            data:
              entity_id: media_player.fire_tv_sportzimmer
              source: "org.xbmc.kodi"
        turn_off:
          - service: kodi.call_method
            data:
              entity_id: media_player.kodi_sportzimmer
              method: Input.Home
          - service: media_player.select_source
            data:
              entity_id: media_player.fire_tv_sportzimmer
              source: "com.amazon.tv.launcher"  

homeassistant:
  customize:
    switch.sportzimmer_fernseher:
      icon: mdi:television