input_boolean:
  musik_ausschalten:
    name: Musik ausschalten
    icon: mdi:music-off
    
  wiedergabe_pausieren:
    name: Wiedergabe pausieren
    icon: mdi:play-pause  

cover:
  - platform: template
    covers:
      fernseher_sender:
        friendly_name: "Fernseher Sender"
        position_template: 50
        open_cover:
          - service: media_player.play_media
            data:
              entity_id: media_player.fernseher_wohnzimmer
              media_content_id: "KEY_CHUP"
              media_content_type: "send_key"
        close_cover:
          - service: media_player.play_media
            data:
              entity_id: media_player.fernseher_wohnzimmer
              media_content_id: "KEY_CHDOWN"
              media_content_type: "send_key"
        stop_cover:
          - service: media_player.play_media
            data:
              entity_id: media_player.fernseher_wohnzimmer
              media_content_id: "KEY_PRECH"
              media_content_type: "send_key"
        icon_template: >-
          mdi:remote-tv

switch:
  - platform: template
    switches:
      watchtv_wohnzimmer:
        friendly_name: "Fernsehen"
        value_template: "{{ is_state('media_player.fernseher_wohnzimmer', 'on') }}"
        turn_on:
          - service: media_player.turn_on
            entity_id: media_player.fernseher_wohnzimmer  
          - choose:
              - conditions:
                  - condition: state
                    entity_id: media_player.soundbar
                    state: 'off'
                sequence:  
                  - service: media_player.turn_on
                    entity_id: media_player.soundbar        
                  - wait_template: "{{is_state('media_player.soundbar', 'on')}}"
                  - service: media_player.select_source
                    entity_id: media_player.soundbar
                    data:
                      source: TV
        turn_off:      
          - service: media_player.turn_off
            entity_id: media_player.fernseher_wohnzimmer           
          - choose:
              - conditions:
                  - condition: state
                    entity_id: media_player.soundbar
                    state: 'on'
                sequence:
                  - service: media_player.turn_off
                    entity_id: media_player.soundbar    
     
automation:
  - alias: "Fernseher eingeschaltet - Radio ausschalten"
    id: "fernseher_eingeschaltet_radio_ausschalten"
    trigger:
      - platform: state
        entity_id: switch.watchtv_wohnzimmer
        to: 'on' 
    condition:    
      - "{{ is_state('switch.wohnzimmer_radio', 'on') }}"      
    action:    
      - service: switch.turn_off
        entity_id: switch.wohnzimmer_radio
            
homeassistant:
  customize:
    media_player.soundbar:
      icon: mdi:music
          
    switch.watchtv_wohnzimmer:
      icon: mdi:television-classic