input_boolean:
  uhr_einschalten:
    name: Uhr einschalten
    icon: mdi:alarm-multiple

automation:
  - alias: "Uhr - Glocke starten"
    id: "uhr_glocke_starten"
    trigger:
      - platform: template
        value_template: "{{ now().strftime('%M')|int in [0,30] }}"
    condition:  
      - "{{ is_state('input_boolean.uhr_einschalten', 'on') }}"
      - "{{ is_state('binary_sensor.baden_aktiv', 'off') }}"   
      - "{{ is_state('person.dennis', 'home') }}"
      - "{{ is_state('binary_sensor.home_office_aktiv', 'off') }}"
      - "{{ is_state('binary_sensor.schlafen_aktiv', 'off') }}"
      - "{{ is_state('calendar.borussia_dortmund', 'off') }}"
      - "{{ is_state('calendar.formel1_rennen', 'off') }}"
      - "{{ is_state('calendar.formel1_qualifikation', 'off') }}"           
    action:
      - service: media_player.play_media
        data:
          entity_id: media_player.home_assistant
          media_content_id: >-
            {% if now().strftime("%M")|int == 30 %}
              http://192.168.2.75:8123/local/uhr/GrandFatherChime_half.mp3
            {% else %}
              http://192.168.2.75:8123/local/uhr/GrandFatherChime_{{now().strftime("%I")}}.mp3
            {% endif %}
          media_content_type: music

  - alias: 'Uhr - Glocke abbrechen'
    id: "uhr_glocke_abbrechen"
    trigger:
      - id: uhr_ausschalten
        platform: state
        entity_id: input_boolean.uhr_einschalten
        to: 'off'
      - id: cube_wohnzimmer
        platform: event
        event_type: zha_event
        event_data:
          device_ieee: 00:15:8d:00:01:10:0d:7a
          command: knock   
    condition:         
      - condition: state
        entity_id: media_player.home_assistant
        state: 'playing'
    action:
      - service: media_player.media_pause
        entity_id:
          - media_player.home_assistant
      - service: input_boolean.turn_on
        entity_id: input_boolean.uhr_einschalten               