switch:   
  - platform: template
    switches:
      wiedergabe_badezimmer:
        friendly_name: Wiedergabe Badezimmer
        value_template: >-
          {{ is_state('media_player.badezimmer', 'playing') }}
        icon_template: >-
          {{ 'mdi:play-circle-outline' if is_state('media_player.badezimmer', 'playing') else 'mdi:pause-circle-outline' }}
        turn_on:
          - service: media_player.media_play
            data:
              entity_id: media_player.badezimmer
        turn_off:
          - service: media_player.media_pause
            data:
              entity_id: media_player.badezimmer

      wiedergabe_aktiv:
        friendly_name: Wiedergabe aktiv
        value_template: >-
          {% if is_state('media_player.kuche', 'playing')
            or is_state('media_player.badezimmer', 'playing')
            or is_state('media_player.wohnzimmer', 'playing')
            or is_state('media_player.schlafzimmer', 'playing')
            or is_state('media_player.arbeitszimmer', 'playing')
            or is_state('media_player.flur', 'playing')
            or is_state('media_player.balkon', 'playing')
          %}
            True
          {% else %}
            False
          {% endif %}
        icon_template: >-
          {% if is_state('media_player.kuche', 'playing')
            or is_state('media_player.badezimmer', 'playing')
            or is_state('media_player.wohnzimmer', 'playing')
            or is_state('media_player.schlafzimmer', 'playing')
            or is_state('media_player.arbeitszimmer', 'playing')
            or is_state('media_player.flur', 'playing')
            or is_state('media_player.balkon', 'playing')
          %}
            mdi:play-circle-outline
          {% else %}
            mdi:pause-circle-outline
          {% endif %}
        turn_on:
          service: script.radios_starten
        turn_off:
          service: script.radios_pausieren

      alle_radios:
        friendly_name: Alle Radios
        value_template: >-
          {% if is_state('switch.wohnzimmer_radio', 'on')
            or is_state('switch.balkon_radio', 'on')
            or is_state('switch.schlafzimmer_radio', 'on')
            or is_state('switch.flur_radio', 'on')
            or is_state('switch.badezimmer_radio', 'on')
            or is_state('switch.arbeitszimmer_radio', 'on')
            or is_state('switch.kuche_radio', 'on')
          %}
            True
          {% else %}
            False
          {% endif %}
        turn_on:
          service: script.radios_einschalten
        turn_off:
          service: script.radios_ausschalten

input_boolean:
  radio_balkon_aktiv:
    name: Radio Balkon aktiv
  radio_balkon_bewegungsmelder_deaktiviert:
    name: Radio Balkon Bewegungsmelder deaktiviert  
    icon: mdi:voice-off
  musik_pausiert:
    name: Musik pausiert

binary_sensor:
  - platform: template
    sensors:         
      radio_badezimmer_inaktiv:
        friendly_name: Radio Badezimmer inaktiv
        device_class: motion
        value_template: >-
          {% if is_state('entity_controller.radio_badezimmer_bewegung', 'active_timer') %}
            false
          {% elif is_state('media_player.badezimmer', 'playing') %}
            true
          {% elif is_state('switch.wohnzimmer_radio', 'on')
            or is_state('switch.balkon_radio', 'on')
            or is_state('switch.schlafzimmer_radio', 'on')
            or is_state('switch.flur_radio', 'on')
            or is_state('switch.arbeitszimmer_radio', 'on')
            or is_state('switch.kuche_radio', 'on')
          %}
            true
          {% else %}
            false
          {% endif %}

entity_controller:
  radio_badezimmer:
    friendly_name: "Radio Badezimmer - Bewegung"
    sensor: binary_sensor.bewegungsmelder_badezimmer
    sensor_type_duration: True
    entity: switch.wiedergabe_badezimmer
    delay: 120
    overrides:
      - binary_sensor.radio_badezimmer_inaktiv
      
automation:
  - alias: 'Radio Balkon - Einschalten'
    trigger:
      - platform: state
        entity_id: binary_sensor.zu_hause
        to: 'on'
      - platform: state
        entity_id: binary_sensor.home_office
        to: 'off'
    condition:
      - condition: state
        entity_id: binary_sensor.zu_hause
        state: 'on'
      - condition: state
        entity_id: binary_sensor.home_office
        state: 'off'
      - condition: template
        value_template: '{{ now().isoweekday() != 7 }}'        
      - condition: time
        after: '08:00'
        before: '20:00'
      - condition: numeric_state
        entity_id: sensor.balkon_temperatur
        above: 15
      - condition: numeric_state
        entity_id: sensor.laufzeit_minuten
        above: 5
    action:
      - service: switch.turn_on
        entity_id: switch.balkon_radio
        
  - alias: 'Radio Balkon - Bewegung erkannt'
    trigger:
      - platform: state
        entity_id: binary_sensor.bewegungsmelder_balkon
        to: 'on'
    condition:
      - condition: time
        after: '08:00'
        before: '22:00'
      - condition: or
        conditions:
          - condition: time
            after: '08:00'            
            before: '12:00'           
          - condition: time
            after: '15:00'
            before: '22:00'  
      - condition: template
        value_template: '{{ now().isoweekday() != 7 }}'   
      - condition: state
        entity_id: 'switch.wiedergabe_aktiv'
        state: 'on'
      - condition: state
        entity_id: 'media_player.balkon'
        state: 'off'
      - condition: state
        entity_id: 'input_boolean.radio_balkon_bewegungsmelder_deaktiviert'
        state: 'off'        
      - condition: template
        value_template: '{{ is_state("sensor.handy", "incoming") == False and is_state("sensor.handy", "outgoing") == False }}'
      - condition: state
        entity_id: 'sensor.telefon'
        state: 'idle'
      - condition: state
        entity_id: binary_sensor.besuch
        state: 'off'
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.radio_balkon_aktiv
      - service: media_player.turn_on
        data:
          entity_id: media_player.balkon

  - alias: 'Radio Balkon - Keine Bewegung'
    trigger:
      - platform: state
        entity_id: binary_sensor.bewegungsmelder_wohnzimmer
        to: 'on'
    condition:
      - condition: state
        entity_id: input_boolean.radio_balkon_aktiv
        state: 'on'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.radio_balkon_aktiv
      - service: media_player.turn_off
        data:
          entity_id: media_player.balkon

  - alias: 'Radio Balkon - Starten'
    trigger:
      - platform: state
        entity_id: sensor.schalter_balkon
        to: '2'
    condition:
      - condition: state
        entity_id: switch.balkon_radio
        state: 'on'
      - condition: state
        entity_id: 'switch.wiedergabe_aktiv'
        state: 'on'        
      - condition: not
        conditions:
          - condition: state
            entity_id: media_player.balkon
            state: 'playing'                        
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.radio_balkon_aktiv
      - service: media_player.turn_on
        data:
          entity_id: media_player.balkon
      
  - alias: 'Radio Balkon - Synchronisieren'
    trigger:
      - platform: state
        entity_id: sensor.schalter_balkon
        to: '2'
    condition:
      - condition: state
        entity_id: media_player.balkon
        state: 'playing'
    action:
      - service: script.sync_radios

  - alias: 'Radios pausieren'
    trigger:
      - platform: state
        entity_id: binary_sensor.tuersensor
        to: 'on'
      - platform: state
        entity_id: binary_sensor.schalter_arbeitszimmer
        to: 'off'    
    condition:
      - condition: state
        entity_id: switch.wiedergabe_aktiv
        state: 'on'
      - condition: template
        value_template: '{{ is_state("sensor.handy", "incoming") == False and is_state("sensor.handy", "outgoing") == False }}'
      - condition: state
        entity_id: 'sensor.telefon'
        state: 'idle'          
      - condition: state
        entity_id: input_boolean.musik_pausiert
        state: 'off'
      - condition: template
        value_template: >-
          {% set now = as_timestamp(now()) | int %}
          {% set last = as_timestamp(state_attr("automation.alles_ausschalten", "last_triggered")) | int %}
          {% set diff = ((now - last) / 60) | int %}

          {{ diff >= 10 }}
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.musik_pausiert
      - service: media_player.volume_mute
        data:
          entity_id: media_player.kuche, media_player.badezimmer, media_player.wohnzimmer, media_player.schlafzimmer, media_player.arbeitszimmer, media_player.flur, media_player.balkon
          is_volume_muted: true        

  - alias: 'Radios starten'
    trigger:
      - platform: state
        entity_id: binary_sensor.tuersensor
        to: 'off'
      - platform: state
        entity_id: binary_sensor.schalter_arbeitszimmer
        to: 'off'        
    condition:
      - condition: state
        entity_id: input_boolean.musik_pausiert
        state: 'on'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.musik_pausiert
      - service: media_player.volume_mute
        data:
          entity_id: media_player.kuche, media_player.badezimmer, media_player.wohnzimmer, media_player.schlafzimmer, media_player.arbeitszimmer, media_player.flur, media_player.balkon
          is_volume_muted: false    
          
script:
  sync_radios:
    alias: Radios synchronisieren
    sequence:
      - condition: state
        entity_id: media_player.wohnzimmer
        state: 'playing'
      - service: media_player.turn_off
        entity_id: media_player.wohnzimmer
      - delay: '00:00:02'
      - service: media_player.turn_on
        entity_id: media_player.wohnzimmer

  radios_einschalten:
    alias: Radios einschalten
    sequence:
      - service: switch.turn_on
        entity_id: switch.wohnzimmer_radio, switch.balkon_radio, switch.flur_radio, switch.badezimmer_radio, switch.kuche_radio, switch.schlafzimmer_radio, switch.arbeitszimmer_radio

  radios_ausschalten:
    alias: Radios ausschalten
    sequence:
      - service: script.radios_pausieren
      - service: switch.turn_off
        entity_id: switch.wohnzimmer_radio, switch.balkon_radio, switch.flur_radio, switch.badezimmer_radio, switch.kuche_radio, switch.schlafzimmer_radio, switch.arbeitszimmer_radio

  radios_starten:
    alias: Radios abspielen
    sequence:
      - service: media_player.media_play
        entity_id: media_player.kuche, media_player.badezimmer, media_player.wohnzimmer, media_player.schlafzimmer, media_player.arbeitszimmer, media_player.flur

  radios_pausieren:
      alias: Radios pausieren
      sequence:
        - service: media_player.media_pause
          entity_id: media_player.kuche, media_player.badezimmer, media_player.wohnzimmer, media_player.schlafzimmer, media_player.arbeitszimmer, media_player.flur

  wohnung_radios_einschalten:
    alias: "Wohnung - Radios einschalten"
    sequence:
      - service: switch.turn_on
        entity_id: switch.badezimmer_radio, switch.wohnzimmer_radio, switch.flur_radio, switch.kuche_radio
      - wait_template: >-
          {% if is_state('media_player.kuche', 'playing')
            and is_state('media_player.badezimmer', 'playing')
            and is_state('media_player.wohnzimmer', 'playing')
            and is_state('media_player.flur', 'playing')
          %}
            True
          {% else %}
            False
          {% endif %}      
        timeout: '00:02:00'
      - service: script.sync_radios
      
homeassistant:
  customize:
    script.sync_radios:
      can_cancel: false
      icon: mdi:sync
    switch.alle_radios:
      icon: mdi:cast-off

    switch.wohnzimmer_radio:
      icon: mdi:radio
    switch.schlafzimmer_radio:
      icon: mdi:radio   
    switch.balkon_radio:
      icon: mdi:radio