tts:
  - platform: google_cloud
    key_file: !secret google_cloud_key
    language: 'de-DE'
    
  - platform: google_translate
    language: 'de'

notify:
  - platform: alexa_media
    name: Alexa
   
input_boolean:
  sprachausgabe:
    name: Sprachausgabe
    icon: mdi:message-bulleted    

script:
  alexa_tts:
    alias: "Alexa TTS"
    sequence:      
      - condition: and
        conditions:
          - condition: state
            entity_id: person.dennis
            state: 'home'        
          - condition: or
            conditions:      
              - condition: and
                conditions:
                  - condition: state
                    entity_id: binary_sensor.schlafen_aktiv
                    state: 'off'      
                  - condition: state
                    entity_id: input_boolean.nicht_stoeren
                    state: 'off'                          
              - condition: template
                value_template: "{{ override is defined and override == true }}"
      - service: notify.alexa_media
        data:
          data:
            type: tts
          target: >-
            {% set letzteBewegung = states('sensor.letzte_bewegung') %}

            {% if echo is defined and echo|length %}
              media_player.echo_{{ echo }}
            {% elif letzteBewegung == None %}
              media_player.echo_wohnzimmer
            {% elif letzteBewegung == 'Flur vorne' or letzteBewegung == 'Flur hinten' or letzteBewegung == 'Arbeitszimmer' %}
              media_player.echo_flur
            {% elif letzteBewegung == 'Badezimmer' %}
              media_player.echo_badezimmer
            {% elif letzteBewegung == 'Küche' %}
              media_player.echo_kueche
            {% else %}
              media_player.echo_wohnzimmer
            {% endif %}
          message: "{{ message }}"

  google_tts:
    alias: "Google TTS"
    sequence:
      - condition: and
        conditions:
          - condition: state
            entity_id: person.dennis
            state: 'home'
          - condition: state
            entity_id: binary_sensor.schlafen_aktiv
            state: 'off'
          - condition: state
            entity_id: input_boolean.nicht_stoeren
            state: 'off'            
      - service: tts.google_translate_say
        data:
          entity_id: media_player.squeezebox
          message: "{{ message }}"

automation:
  - alias: "Echo Wohnzimmer - Timer ausschalten"
    id: "echo_wohnzimmer_timers_ausschalten"
    trigger:
      - platform: state
        entity_id: binary_sensor.bewegungsmelder_flur_vorne
        to: 'on'
      - platform: state
        entity_id: binary_sensor.bewegungsmelder_flur_hinten
        to: 'on'        
    condition:
      - condition: not
        conditions:
          - condition: state
            entity_id: sensor.echo_wohnzimmer_next_timer
            state: 'unavailable'
      - condition: template
        value_template: "{{ (as_timestamp(states('sensor.echo_wohnzimmer_next_timer'), None) | int(0)) < (as_timestamp(now()) | int(0)) }}"        
    action:
      - service: media_player.play_media
        data:
          entity_id: media_player.echo_wohnzimmer
          media_content_id: 'Alarm ausschalten'
          media_content_type: custom        