input_boolean:
  licht_simulaton:
    name: "Lichtsimulation"
    icon: mdi:lightbulb-group-outline

alarm_control_panel:
  - platform: manual
    name: Alarm
    arming_time: 60
    delay_time: 60
    trigger_time: 10
    disarmed:
      trigger_time: 0
    armed_home:
      arming_time: 0
      delay_time: 0
    armed_away:
      arming_time: 0

automation:      
  - alias: "Alarm - Aktiviert"
    id: "alarm_aktiviert"
    trigger:
      - platform: state
        entity_id: binary_sensor.zu_hause
        to: 'off'
        for:
          minutes: 1
    action:
      - service: alarm_control_panel.alarm_arm_away
        entity_id: alarm_control_panel.alarm
      - service: switch.turn_on
        entity_id: switch.kamera_wohnzimmer

  - alias: "Alarm - Ausgelöst"
    id: "alarm_ausgeloest"
    trigger:
      - platform: state
        entity_id: binary_sensor.tuersensor
        to: 'on'
    condition:
      - condition: state
        entity_id: alarm_control_panel.alarm
        state: armed_away
      - condition: state
        entity_id: binary_sensor.zu_hause
        state: 'off'
    action:
      service: alarm_control_panel.alarm_trigger
      entity_id: alarm_control_panel.alarm

  - alias: "Alarm - Nachricht Telegram"
    id: "alarm_nachricht_telegram"
    trigger:
      - platform: state
        entity_id: alarm_control_panel.alarm
        to: 'triggered'
    action:
      - service: notify.telegram
        data_template:
          title: "Alarm"
          message: "Der Alarm in der Wohnung wurde ausgelöst."
      - condition: state
        entity_id: switch.kamera_wohnzimmer
        state: 'on'
      - service: telegram_bot.send_photo
        data_template:
          caption: 'Kamera'
          url: 'http://192.168.2.75:8123/api/camera_proxy/camera.kamera_wohnzimmer?token={{ state_attr("camera.kamera_wohnzimmer", "access_token") }}'
                    
  - alias: "Alarm - Nachricht Bewegungsmelder"
    id: "alarm_nachricht_bewegungsmelder"
    trigger:
      - platform: state
        entity_id: binary_sensor.bewegungsmelder_badezimmer
        to: 'on'
      - platform: state
        entity_id: binary_sensor.bewegungsmelder_wohnzimmer
        to: 'on'
      - platform: state
        entity_id: binary_sensor.bewegungsmelder_flur_vorne
        to: 'on'
      - platform: state
        entity_id: binary_sensor.bewegungsmelder_arbeitszimmer
        to: 'on'
      - platform: state
        entity_id: binary_sensor.bewegungsmelder_sportszimmer
        to: 'on'        
      - platform: state
        entity_id: binary_sensor.bewegungsmelder_schlafzimmer
        to: 'on'
      - platform: state
        entity_id: binary_sensor.bewegungsmelder_kueche
        to: 'on'
    condition:
      - condition: state
        entity_id: binary_sensor.zu_hause
        state: 'off'
      - condition: state
        entity_id: alarm_control_panel.alarm
        state: 'armed_away'
      - condition: state
        entity_id: 'vacuum.roborock_vacuum'
        state: 'docked'
    action:
      service: notify.telegram
      data_template:
        title: "Bewegung erkannt"
        message: >-
          {% if trigger.entity_id == "binary_sensor.bewegungsmelder_badezimmer" %}
             Im Badezimmer wurde eine Bewegung erkannt.
          {% elif trigger.entity_id == "binary_sensor.bewegungsmelder_wohnzimmer" %}
            Im Wohnzimmer wurde eine Bewegung erkannt.
          {% elif trigger.entity_id == "binary_sensor.bewegungsmelder_flur_vorne" %}
            Im Flur wurde eine Bewegung erkannt.
          {% elif trigger.entity_id == "binary_sensor.bewegungsmelder_arbeitszimmer" %}
            Im Arbeitszimmer wurde eine Bewegung erkannt.
          {% elif trigger.entity_id == "binary_sensor.bewegungsmelder_sportszimmer" %}
            Im Sportzimmer wurde eine Bewegung erkannt.            
          {% elif trigger.entity_id == "binary_sensor.bewegungsmelder_schlafzimmer" %}
            Im Schlafzimmer wurde eine Bewegung erkannt.
          {% elif trigger.entity_id == "binary_sensor.bewegungsmelder_kueche" %}
            In der Küche wurde eine Bewegung erkannt.
          {% else %}
            Eine sonstige Bewegung wurde erkannt.
          {% endif %}

  - alias: "Alarm - Nachricht Fenster"
    id: "alarm_nachricht_fenster"
    trigger:
      - platform: state
        entity_id: binary_sensor.balkontuer
        to: 'on'      
      - platform: state
        entity_id: binary_sensor.fenster_wohnzimmer
        to: 'on'
      - platform: state
        entity_id: binary_sensor.fenster_schlafzimmer
        to: 'on'
      - platform: state
        entity_id: binary_sensor.fenster_kueche
        to: 'on'
      - platform: state
        entity_id: binary_sensor.fenster_arbeitszimmer
        to: 'on'
      - platform: state
        entity_id: binary_sensor.fenster_sportzimmer
        to: 'on'
    condition:
      - condition: state
        entity_id: binary_sensor.zu_hause
        state: 'off'
      - condition: state
        entity_id: alarm_control_panel.alarm
        state: 'armed_away'
    action:
      service: notify.telegram
      data_template:
        title: "Fenster geöffnet"
        message: >-
          {% if trigger.entity_id == "binary_sensor.balkontuer" %}
            Die Balontür wurde geöffnet.
          {% elif trigger.entity_id == "binary_sensor.fenster_wohnzimmer" %}
            Das Fenster im Wohnzimmer wurde geöffnet.            
          {% elif trigger.entity_id == "binary_sensor.fenster_schlafzimmer" %}
            Das Fenster im Schlafzimmer wurde geöffnet.
          {% elif trigger.entity_id == "binary_sensor.fenster_kueche" %}
            Das Fenster in der Küche wurde geöffnet.
          {% elif trigger.entity_id == "binary_sensor.fenster_arbeitszimmer" %}
            Das Fenster im Arbeitszimmer wurde geöffnet.
          {% elif trigger.entity_id == "binary_sensor.fenster_sportzimmer" %}
            Das Fenster im Sportzimmer wurde geöffnet.
          {% endif %}              
