input_boolean:
  baden_aktiv:
    name: "Baden aktiv"
    
automation:
  - alias: "Baden - Starten"
    id: "baden_starten"  
    trigger:
      - id: schalter_badezimmer
        platform: event
        event_type: zha_event
        event_data:
          device_ieee: 00:15:8d:00:02:e9:58:3a
          command: click
          args:
            click_type: single           
    condition:
      - condition: state
        entity_id: binary_sensor.besuch
        state: 'off'
      - condition: state
        entity_id: input_boolean.baden_aktiv
        state: 'off'       
      - condition: state
        entity_id: binary_sensor.schlafen_aktiv
        state: 'off'             
    action:
      - service: !secret tts_service
        data:
          echo: "badezimmer"
          message: "Alle Geräte werden ausgeschaltet. Viel Spaß beim Baden."
      - service: entity_controller.enable_stay_mode
        entity_id: entity_controller.bewegung_badezimmer
      - service: light.turn_on
        entity_id: light.badezimmerschrank        
      - service: input_boolean.turn_on
        entity_id: input_boolean.baden_aktiv
      - service: switch.turn_off
        entity_id: switch.watchtv_wohnzimmer, switch.computer
      - service: script.radios_ausschalten
      - service: light.turn_off
        entity_id: light.wohnzimmer_couch, light.wohnzimmer_strahler, light.wohnzimmer_schrank, light.kueche_regal, light.kueche_schrank
        
  - alias: "Baden - Beenden"
    id: "baden_beenden"
    trigger:
      - id: schalter_badezimmer
        platform: event
        event_type: zha_event
        event_data:
          device_ieee: 00:15:8d:00:02:e9:58:3a
          command: click
          args:
            click_type: single    
    condition:
      - condition: state
        entity_id: input_boolean.baden_aktiv
        state: 'on'       
    action:        
      - service: !secret tts_service
        data:
          echo: "badezimmer"
          message: "Alle Geräte werden wieder eingeschaltet."          
      - service: input_boolean.turn_off
        entity_id: input_boolean.baden_aktiv
      - service: entity_controller.disable_stay_mode
        entity_id: entity_controller.bewegung_badezimmer        
      - service: light.turn_off
        entity_id: light.badezimmerschrank
      - service: switch.turn_on
        entity_id: switch.computer     
      - choose:
          conditions:
            - condition: state
              entity_id: binary_sensor.sonne_tagsueber
              state: 'off'
          sequence:
            - service: light.turn_on
              entity_id: light.wohnzimmer_schrank        
      - choose:
          conditions:
            - condition: time
              before: "20:00:00"
          sequence:
            - service: script.wohnung_radios_einschalten
        default:
          - service: switch.turn_on
            entity_id: switch.watchtv_wohnzimmer, switch.badezimmer_radio       
          - wait_template: "{{ is_state('media_player.radio_badezimmer', 'playing') }}"
          - service: media_player.media_pause
            entity_id: media_player.radio_badezimmer
