input_boolean:
  baden_aktiv:
    name: "Baden aktiv"
    
automation:
  - alias: "Baden - Starten"
    id: "baden_starten"  
    trigger:
      - platform: state
        entity_id: binary_sensor.schalter_badezimmer
        to: 'off'       
    condition:
      - condition: state
        entity_id: binary_sensor.besuch
        state: 'off'
      - condition: state
        entity_id: input_boolean.baden_aktiv
        state: 'off'       
      - condition: state
        entity_id: binary_sensor.schlafen_aktiv
        state: 'off'             
    action:
      - service: !secret tts_service
        data:
          echo: "badezimmer"
          message: "Alle Geräte werden ausgeschaltet. Viel Spaß beim Baden."
      - service: input_boolean.turn_on
        entity_id: input_boolean.baden_aktiv, input_boolean.bewegungsmelder_badezimmer_deaktiviert
      - service: light.turn_on
        entity_id: light.badezimmerschrank
      - service: switch.turn_off
        entity_id: switch.watchtv_wohnzimmer, switch.monitor, switch.pc
      - service: script.radios_ausschalten
      - service: light.turn_off
        entity_id: light.wohnzimmer_couch, light.wohnzimmer_strahler, light.wohnzimmer_schrank
        
  - alias: "Baden - Beenden"
    id: "baden_beenden"
    trigger:
      - platform: state
        entity_id: binary_sensor.schalter_badezimmer
        to: 'off'       
    condition:
      - condition: state
        entity_id: input_boolean.baden_aktiv
        state: 'on'       
    action:        
      - service: !secret tts_service
        data:
          echo: "badezimmer"
          message: "Alle Geräte werden wieder eingeschaltet."          
      - service: input_boolean.turn_off
        entity_id: input_boolean.baden_aktiv, input_boolean.bewegungsmelder_badezimmer_deaktiviert
      - service: light.turn_off
        entity_id: light.badezimmerschrank
      - service: switch.turn_on
        entity_id: switch.computer      
      - choose:
          conditions:
            - condition: time
              before: "20:00:00"
          sequence:
            - service: script.wohnung_radios_einschalten
        default:
          - service: switch.turn_on
            entity_id: switch.watchtv_wohnzimmer, switch.badezimmer_radio
      - choose:
          conditions:
            - condition: state
              entity_id: binary_sensor.sonne_tagsueber
              state: 'off'
          sequence:
            - service: light.turn_on
              entity_id: light.wohnzimmer_couch, light.wohnzimmer_strahler