input_boolean:   
  besuch:
    name: "Besuch"
    icon: mdi:account-multiple   

binary_sensor:
  - platform: template
    sensors:         
      besuch:
        friendly_name: "Besuch"
        device_class: presence        
        value_template: >-
          {{ True if is_state('input_boolean.besuch', 'on') else False }}     
              
automation:
  - alias: "Zu Hause - Besuch Schalter"
    id: "zu_hause_besuch_schalter"
    trigger:
      - id: schalter_flur
        platform: event
        event_type: zha_event
        event_data:
          device_ieee: 00:15:8d:00:01:c3:08:67
          command: click
          args:
            click_type: single           
    condition:
      - condition: state
        entity_id: person.dennis
        state: 'home'
    action:
      - service: input_boolean.toggle
        entity_id: input_boolean.besuch  