input_boolean:   
  besuch:
    name: "Besuch"
    icon: mdi:account-multiple   

template:
  - binary_sensor:       
      - name: "Besuch"
        unique_id: besuch
        device_class: presence 
        state: "{{ is_state('input_boolean.besuch', 'on') }}"     
        
automation:
  - alias: "Zu Hause - Besuch Schalter"
    id: "zu_hause_besuch_schalter"
    trigger:
      - id: schalter_flur
        platform: event
        event_type: zha_event
        event_data:
          device_ieee: 00:15:8d:00:01:c3:08:67
          command: click
          args:
            click_type: single           
    condition:
      - condition: state
        entity_id: person.dennis
        state: 'home'
    action:
      - service: input_boolean.toggle
        entity_id: input_boolean.besuch  
        
  - alias: "Natalie - Kalender"
    id: "natalie_kalender"
    trigger:
      - id: home
        platform: calendar
        event: start
        entity_id: calendar.besuch_natalie
      - id: not_home
        platform: calendar
        event: end
        entity_id: calendar.besuch_natalie    
    action:      
      - service: mqtt.publish
        data:
           topic: 'handy_natalie/location'
           payload: '{{ trigger.id }}'
           retain: true             