input_boolean:   
  besuch:
    name: "Besuch"
    icon: mdi:account-multiple   
    
  besuch_franzi:
    name: "Besuch Franzi"
    icon: mdi:human-child   

  besuch_natalie:
    name: "Besuch Natalie"
    icon: mdi:human-female   
    
template:
  - binary_sensor:       
      - name: "Besuch"
        unique_id: besuch
        device_class: presence 
        state: "{{ is_state('input_boolean.besuch', 'on') }}"     
        
automation:
  - alias: "Besuch Schalter"
    id: "besuch_schalter"
    trigger:
      - id: schalter_flur
        platform: event
        event_type: zha_event
        event_data:
          device_ieee: 00:15:8d:00:01:c3:08:67
          command: click
          args:
            click_type: single           
    condition:
      - condition: state
        entity_id: person.dennis
        state: 'home'
    action:
      - service: input_boolean.toggle
        entity_id: input_boolean.besuch  
        
  - alias: "Natalie - Besuch"
    id: "natalie_besuch"
    trigger:
      - id: home
        platform: calendar
        event: start
        entity_id: calendar.besuch_natalie
      - id: home
        platform: state
        entity_id: input_boolean.besuch_natalie   
        to: 'on'
      - id: not_home
        platform: calendar
        event: end
        entity_id: calendar.besuch_natalie    
      - id: not_home
        platform: state
        entity_id: input_boolean.besuch_natalie
        to: 'off'
    action:      
      - service: mqtt.publish
        data:
           topic: 'presence/natalie'
           payload: '{{ trigger.id }}'
           retain: true             
           
  - alias: "Franzi - Besuch"
    id: "franzi_besuch"
    trigger:
      - platform: state
        entity_id: input_boolean.besuch_franzi
    action:      
      - service: mqtt.publish
        data:
           topic: "presence/franzi"
           payload: "{{ 'home' if trigger.to_state.state == 'on' else 'not_home' }}"
           retain: true
           
  - alias: "Franzi - Licht Arbeitszimmer"
    id: "franzi_licht_arbeitszimmer"
    trigger:
      - platform: state
        entity_id: person.franzi
      - platform: state
        entity_id: binary_sensor.nachts 
    condition:     
      - condition: or
        conditions:
          - "{{ is_state('person.franzi', 'home') and is_state('binary_sensor.nachts', 'on') and is_state('input_boolean.bewegungsmelder_arbeitszimmer_deaktiviert', 'off') }}"
          - "{{ is_state('person.franzi', 'not_home') and is_state('binary_sensor.nachts', 'off') and is_state('input_boolean.bewegungsmelder_arbeitszimmer_deaktiviert', 'on') }}"
    action:    
      - if: "{{ is_state('person.franzi', 'home') and is_state('binary_sensor.nachts', 'on') }}"
        then:          
          - service: input_boolean.turn_on
            entity_id: input_boolean.bewegungsmelder_arbeitszimmer_deaktiviert  
          - service: light.turn_on
            entity_id: light.schreibtisch          
      - if: "{{ is_state('person.franzi', 'not_home') and is_state('binary_sensor.nachts', 'off')}}"
        then:          
          - service: input_boolean.turn_off
            entity_id: input_boolean.bewegungsmelder_arbeitszimmer_deaktiviert  
          - service: light.turn_off
            entity_id: light.schreibtisch                    