input_boolean:   
  besuch:
    name: "Besuch"
    icon: mdi:account-multiple   
    
  besuch_franzi:
    name: "Besuch Franzi"
    icon: mdi:human-child   

  besuch_natalie:
    name: "Besuch Natalie"
    icon: mdi:human-female   
    
  besuch_flori:
    name: "Besuch Flori"
    icon: mdi:dog-side   
    
template:
  - binary_sensor:       
      - name: "Besuch"
        unique_id: besuch
        device_class: presence 
        state: "{{ is_state('input_boolean.besuch', 'on') }}"     
       
mqtt:
  device_tracker:
    - name: "Handy Natalie MQTT"
      state_topic: "presence/natalie"
    
    - name: "Franzi MQTT"
      state_topic: "presence/franzi"
      
    - name: "Flori MQTT"
      state_topic: "presence/flori"
      
automation:
  - alias: "Besuch Schalter"
    id: "besuch_schalter"
    trigger:
      - id: schalter_flur
        platform: event
        event_type: zha_event
        event_data:
          device_ieee: 00:15:8d:00:01:c3:08:67
          command: click
          args:
            click_type: single           
    condition:
      - condition: state
        entity_id: person.dennis
        state: 'home'
    action:
      - service: input_boolean.toggle
        entity_id: input_boolean.besuch  
        
  - alias: "Natalie - Besuch"
    id: "natalie_besuch"
    trigger:
      - platform: state
        entity_id: input_boolean.besuch_natalie           
    action:      
      - service: mqtt.publish
        data:
           topic: 'presence/natalie'
           payload: "{{ 'home' if trigger.to_state.state == 'on' else 'not_home' }}"
           retain: true             
           
  - alias: "Franzi - Besuch"
    id: "franzi_besuch"
    trigger:
      - platform: state
        entity_id: input_boolean.besuch_franzi
    action:      
      - service: mqtt.publish
        data:
           topic: "presence/franzi"
           payload: "{{ 'home' if trigger.to_state.state == 'on' else 'not_home' }}"
           retain: true            
           
  - alias: "Flori - Besuch"
    id: "flori_besuch"
    trigger:
      - platform: state
        entity_id: input_boolean.besuch_flori
    action:      
      - service: mqtt.publish
        data:
           topic: "presence/flori"
           payload: "{{ 'home' if trigger.to_state.state == 'on' else 'not_home' }}"
           retain: true                    
           
homeassistant:
  customize:
    person.natalie:
      icon: mdi:human-female
    person.franzi:
      icon: mdi:human-child
    person.flori:
      icon: mdi:dog-side      