timer:
  home_office_ende:
    name: "Home Office beenden"
    duration: 7
             
input_boolean:
  home_office:
    name: Home Office    
  
  home_office_aktiv:
    name: Home Office aktiv
    
  home_office_musik_pausiert:
    name: Musik pausiert    

  home_office_pause:
    name: Home Office Pause
    icon: mdi:bell-sleep
    
input_select:
  computer_arbeit_ausschalten:
    name: Computer ausschalten
    icon: mdi:power-settings
    options:      
      - Ruhezustand
      - Herunterfahren
      - Nichts unternehmen
    
input_number:
  home_office_heute_gearbeitet:
    name: Home Office Heute gearbeitet
    min: 0
    max: 540

input_text:
  teams_status:
    name: Microsoft Teams Status
    icon: mdi:microsoft-teams
  teams_activity:
    name: Microsoft Teams Aktivität
    icon: mdi:phone-off
     
sensor:
  - platform: template
    sensors:
      teams_status:
        friendly_name: "Microsoft Teams Status"
        value_template: "{{states('input_text.teams_status')}}"
        icon_template: "{{state_attr('input_text.teams_status','icon')}}"
        unique_id: sensor.teams_status
      teams_activity:
        friendly_name: "Microsoft Teams Aktivität"
        value_template: "{{states('input_text.teams_activity')}}"
        unique_id: sensor.teams_activity
            
binary_sensor:
  - platform: ping
    host: !secret computer_arbeit_host    
    name: "Computer Arbeit Ping"    
    scan_interval: 30
    
  - platform: template
    sensors:
      home_office_heute:
        friendly_name: 'Home Office heute'
        icon_template: mdi:home-city
        value_template: >-
          {% set istHomeOffice = is_state('input_boolean.home_office', 'on') %}
          {% set istArbeitstag = is_state('binary_sensor.arbeitstag', 'on') %}
          {% set keinUrlaub = is_state('calendar.urlaub', 'off') %}
          {% set nichtKrank = is_state('calendar.arbeit_krank', 'off') %}

          {{ True if (istHomeOffice and istArbeitstag and keinUrlaub and nichtKrank) else False }}
          
      home_office_aktiv:
        friendly_name: 'Home Office aktiv'
        icon_template: mdi:home-city
        value_template: "{{ is_state('input_boolean.home_office_aktiv', 'on') }}"

      home_office_pause:
        friendly_name: 'Home Office Pause'
        icon_template: mdi:bell-sleep
        value_template: "{{ is_state('input_boolean.home_office_pause', 'on') }}"
        
switch:
  - platform: template
    switches:
      pc_arbeit:
        friendly_name: PC Arbeit        
        value_template: "{{ is_state('binary_sensor.computer_arbeit_ping', 'on') }}"
        icon_template: mdi:desktop-tower
        turn_on:
          service: wake_on_lan.send_magic_packet
          data:
            mac: !secret computer_arbeit_mac
            broadcast_address: !secret fritzbox_broadcast
            broadcast_port: 9
        turn_off:
          - choose:
              - conditions:
                  - condition: state
                    entity_id: input_select.computer_arbeit_ausschalten
                    state: 'Ruhezustand'
                sequence:
                  - service: button.press
                    entity_id: button.computer_arbeit_ruhezustand
              - conditions:
                  - condition: state
                    entity_id: input_select.computer_arbeit_ausschalten
                    state: 'Herunterfahren'
                sequence:
                  - service: button.press
                    entity_id: button.computer_arbeit_herunterfahren

      computer_arbeit:
        friendly_name: Computer Arbeit
        value_template: "{{ is_state('switch.pc_arbeit', 'on') and is_state('switch.arbeitszimmer_monitore', 'on') }}"
        icon_template: mdi:desktop-classic
        turn_on:
          service: switch.turn_on
          entity_id: switch.arbeitszimmer_monitore, switch.pc_arbeit
        turn_off:
          service: switch.turn_off
          entity_id: switch.arbeitszimmer_monitore, switch.pc_arbeit   
          
script:
  home_office_start:
    alias: 'Home Office - Start'
    sequence:
      - service: input_boolean.turn_on
        entity_id: input_boolean.home_office_aktiv
      - service: switch.turn_off
        entity_id: switch.computer, switch.watchtv_wohnzimmer
      - service: switch.turn_on
        entity_id: switch.arbeitszimmer_radio, switch.computer_arbeit
      - choose:
          - conditions:
              - condition: state
                entity_id: climate.heizung_arbeitszimmer
                state: 'on'
            sequence:
              - service: climate.set_preset_mode
                data:
                  entity_id: climate.heizung_arbeitszimmer
                  preset_mode: 'comfort'
      - choose:
          - conditions:
              - condition: or
                conditions:
                  - condition: state
                    entity_id: binary_sensor.arbeitstag_morgen
                    state: 'off'
                  - condition: state
                    entity_id: binary_sensor.urlaub_morgen
                    state: 'on'                       
            sequence:
              - service: input_select.select_option
                data:
                  entity_id: input_select.computer_arbeit_ausschalten  
                  option: 'Herunterfahren'     
        default:
          - service: input_select.select_option
            data:
              entity_id: input_select.computer_arbeit_ausschalten  
              option: 'Ruhezustand'             
          
  home_office_ende:
    alias: 'Home Office - Ende'
    sequence:
      - service: input_boolean.turn_off
        entity_id: input_boolean.home_office_aktiv
      - service: switch.turn_off
        entity_id: switch.arbeitszimmer_radio, switch.computer_arbeit
      - service: input_number.set_value        
        data:
          entity_id: input_number.home_office_heute_gearbeitet
          value: 0             
      - service: switch.turn_on
        entity_id: switch.computer, switch.watchtv_wohnzimmer
      - service: input_select.select_option
        data:
          entity_id: input_select.computer_ausschalten  
          option: 'Ruhezustand'          
      - service: input_boolean.turn_off
        entity_id: input_boolean.home_office_pause      
      - choose:
          - conditions:
              - condition: state
                entity_id: binary_sensor.sonne_tagsueber
                state: 'off'
            sequence:
              - service: light.turn_on
                entity_id: light.wohnzimmer_schrank           
      - choose:
          - conditions:
              - condition: numeric_state
                entity_id: sensor.bewegungsmelder_balkon_temperatur
                above: -5
            sequence:
              - service: switch.turn_on
                entity_id: switch.balkon_radio        
      - choose:
          - conditions:
              - condition: state
                entity_id: climate.heizung_arbeitszimmer
                attribute: preset_mode
                state: 'heat'
            sequence:              
              - service: climate.set_preset_mode
                data:
                  entity_id: climate.heizung_arbeitszimmer
                  preset_mode: 'eco'                   
        
automation:
  - alias: "Home Office - Start"
    id: "home_office_start"
    trigger:
      - platform: event
        event_type: zha_event
        event_data:
          device_ieee: 00:15:8d:00:01:83:77:4a
          command: click
          args:
            click_type: double   
    condition:
      - condition: or
        conditions:
          - "{{ is_state('binary_sensor.home_office_heute', 'on') }}"
          - "{{ is_state('binary_sensor.buero_heute', 'on') }}"
      - "{{ is_state('binary_sensor.home_office_aktiv', 'off') }}" 
    action:
      - service: script.home_office_start

  - alias: "Home Office - Countdown starten"
    id: "home_office_countdown_starten"
    trigger:
      - platform: event
        event_type: zha_event
        event_data:
          device_ieee: 00:15:8d:00:01:83:77:4a
          command: click
          args:
            click_type: double       
    condition:
      - condition: state
        entity_id: binary_sensor.home_office_aktiv
        state: 'on'
      - condition: state
        entity_id: timer.home_office_ende
        state: 'idle'
    action:
      - service: !secret tts_service
        data:
          echo: "flur"
          message: "Der Computer wird Arbeitszimmer wird gleich ausgeschaltet."
      - delay: '00:00:04'
      - service: timer.start
        entity_id: timer.home_office_ende
      - service: media_player.play_media
        data:
          entity_id: media_player.home_assistant
          media_content_id: http://192.168.2.75:8123/local/sounds/countdown_5.mp3
          media_content_type: music

  - alias: "Home Office - Countdown abbrechen"
    id: "home_office_countdown_abbrechen"
    trigger:
      - platform: event
        event_type: zha_event
        event_data:
          device_ieee: 00:15:8d:00:01:83:77:4a
          command: click
          args:
            click_type: single   
    condition:
      - condition: state
        entity_id: timer.home_office_ende
        state: 'active'
    action:
      - service: media_player.media_pause
        entity_id: media_player.home_assistant
      - service: !secret tts_service
        data:
          echo: "flur"
          message: "Der Vorgang wurde abgebrochen."
      - service: timer.cancel
        entity_id: timer.home_office_ende

  - alias: "Home Office - Ende"
    id: "home_office_ende"
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.home_office_ende
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: input_select.computer_arbeit_ausschalten
                state: 'Herunterfahren'
            sequence:
              - service: !secret tts_service
                data:
                  echo: "flur"
                  message: "Der Computer im Arbeitszimmer wird jetzt heruntergefahren."
        default:      
          - service: !secret tts_service
            data:
              echo: "flur"
              message: "Der Computer im Arbeitszimmer wird jetzt ausgeschaltet."
      - delay: '00:00:02'
      - service: script.home_office_ende

  - alias: "Home Office - Computer eingeschaltet"
    id: "home_office_computer_eingeschaltet"
    trigger:
      - platform: state
        entity_id: switch.computer_arbeit
        to: 'on'
        for: '00:05:00'
    condition:       
      - condition: state
        entity_id: binary_sensor.home_office_aktiv
        state: 'off'        
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: binary_sensor.schlafen_aktiv
                state: 'on'                
            sequence:
              - service: switch.turn_off
                entity_id: switch.computer_arbeit
          - conditions:
              - condition: state
                entity_id: person.dennis
                state: 'off'                
            sequence:
                  - service: notify.telegram
                    data:                      
                      message: 'Der Computer im Arbeitszimmer wurde eingeschaltet und wird jetzt heruntergefahren.'
                  - service: switch.turn_off
                    entity_id: switch.computer_arbeit                  
        default:      
          - service: !secret tts_service
            data:          
              message: "Der Computer im Arbeitszimmer wurde eingeschaltet."
     
  - alias: "Home Office - Status geändert"
    id: "home_office_status_geaendert"
    trigger:
      - platform: state
        entity_id: calendar.arbeit_buero
        to: 'on'
      - platform: state
        entity_id: calendar.arbeit_buero
        to: 'off'        
    action:
      - choose:
          - conditions:
              - "{{ True if trigger.to_state.state == 'on' else False }}"
            sequence:
              - service: input_boolean.turn_off
                entity_id: input_boolean.home_office
        default:
          - service: input_boolean.turn_on
            entity_id: input_boolean.home_office
      
  - alias: "Home Office - Telefon aktiv"
    id: "home_office_telefon_aktiv"
    trigger:
      - platform: state
        entity_id: binary_sensor.computer_arbeit_mikrofon        
        to: 'on'
    condition:       
      - condition: state
        entity_id: input_boolean.home_office_musik_pausiert
        state: 'off'
      - condition: state
        entity_id: binary_sensor.home_office_aktiv
        state: 'on'        
    action:
    
      - service: input_boolean.turn_on
        entity_id: input_boolean.home_office_musik_pausiert
      - service: switch.turn_on
        entity_id: switch.radios_lautlos
      - choose:
          - conditions:
              - condition: or
                conditions:
                  - "{{ is_state('binary_sensor.balkontuer', 'on') }}"
                  - "{{ is_state('binary_sensor.home_office_pause', 'on') }}"   
            sequence:
              - service: !secret tts_service
                data:
                  echo: "wohnzimmer"
                  message: "Ein eingehender Anruf im Arbeitszimmer"
                  
  - alias: "Home Office - Telefon inaktiv"
    id: "home_office_telefon_inaktiv"
    trigger:
      - platform: state
        entity_id: binary_sensor.computer_arbeit_mikrofon
        from: 'on'
        to: 'off'
    condition:
      - condition: state
        entity_id: input_boolean.home_office_musik_pausiert
        state: 'on'
    action:                 
      - service: input_boolean.turn_off
        entity_id: input_boolean.home_office_musik_pausiert
      - service: switch.turn_off
        entity_id: switch.radios_lautlos                      
     
  - alias: "Home Office - Radios Schalter"
    id: "home_office_radios_schalter"
    trigger:
      - platform: event
        event_type: zha_event
        event_data:
          device_ieee: 00:15:8d:00:01:83:77:4a
          command: click
          args:
            click_type: single   
    condition:       
      - condition: state
        entity_id: binary_sensor.home_office_aktiv
        state: 'on'        
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: input_boolean.home_office_musik_pausiert
                state: 'on'            
            sequence:
              - service: input_boolean.turn_off
                entity_id: input_boolean.home_office_musik_pausiert
              - service: switch.turn_off
                entity_id: switch.radios_lautlos       
        default:
          - service: input_boolean.turn_on
            entity_id: input_boolean.home_office_musik_pausiert
          - service: switch.turn_on
            entity_id: switch.radios_lautlos                
        
  - alias: "Home Office - Pause"
    id: "home_office_pause"    
    trigger:
      - platform: event
        event_type: zha_event
        event_data:
          device_ieee: 00:15:8d:00:01:10:0d:7a
          command: flip      
    condition:           
      - condition: state
        entity_id: binary_sensor.home_office_aktiv
        state: 'on'
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: binary_sensor.home_office_pause
                state: 'off'     
            sequence:
              - service: input_boolean.turn_on
                entity_id: input_boolean.home_office_pause                
        default:          
          - service: input_boolean.turn_off
            entity_id: input_boolean.home_office_pause