timer:
  home_office_ende:
    name: "Home Office beenden"
    duration: 7
             
input_boolean:
  home_office:
    name: Home Office
    icon: mdi:home-city-outline
  
  home_office_aktiv:
    name: Home Office aktiv
    
  home_office_musik_pausiert:
    name: Musik pausiert    
   
input_select:
  computer_arbeit_ausschalten:
    name: Computer ausschalten
    icon: mdi:power-settings
    options:      
      - Ruhezustand
      - Herunterfahren
      - Nichts unternehmen
    
binary_sensor:
  - platform: mqtt
    name: "Computer Arbeit"
    state_topic: "homeassistant/sensor/PC-DJAESCHKE/availability"
    payload_on: "online"
    payload_off: "offline"
    device_class: connectivity
    
  - platform: template
    sensors:
      home_office_heute:
        friendly_name: 'Home Office heute'
        icon_template: mdi:home-city
        value_template: >-
          {% set istHomeOffice = is_state('input_boolean.home_office', 'on') %}
          {% set istArbeitstag = is_state('binary_sensor.arbeitstag', 'on') %}
          {% set keinUrlaub = is_state('calendar.urlaub', 'off') %}
          {% set nichtKrank = is_state('calendar.arbeit_krank', 'off') %}

          {{ True if (istHomeOffice and istArbeitstag and keinUrlaub and nichtKrank) else False }}
          
      home_office_aktiv:
        friendly_name: 'Home Office aktiv'
        icon_template: mdi:home-city
        value_template: "{{ is_state('input_boolean.home_office_aktiv', 'on') }}"

switch:
  - platform: template
    switches:
      pc_arbeit:
        friendly_name: PC Arbeit        
        value_template: "{{ is_state('binary_sensor.computer_arbeit', 'on') }}"
        icon_template: mdi:desktop-tower
        turn_on:
          service: wake_on_lan.send_magic_packet
          data:
            mac: !secret computer_arbeit_mac
            broadcast_address: !secret fritzbox_broadcast
            broadcast_port: 9
        turn_off:
          - choose:
              - conditions:
                  - condition: state
                    entity_id: input_select.computer_arbeit_ausschalten
                    state: 'Ruhezustand'
                sequence:
                  - service: switch.turn_on
                    entity_id: switch.computer_arbeit_ruhezustand
              - conditions:
                  - condition: state
                    entity_id: input_select.computer_arbeit_ausschalten
                    state: 'Herunterfahren'
                sequence:
                  - service: switch.turn_on
                    entity_id: switch.computer_arbeit_herunterfahren

script:
  home_office_start:
    alias: 'Home Office - Start'
    sequence:
      - service: input_boolean.turn_on
        entity_id: input_boolean.home_office_aktiv
      - service: switch.turn_off
        entity_id: switch.schlafzimmer_radio, switch.monitor, switch.pc
      - service: switch.turn_on
        entity_id: switch.arbeitszimmer_radio, switch.pc_arbeit, switch.arbeitszimmer_monitore  
      - service: light.turn_off
        entity_id: light.schreibtisch, light.arbeitszimmer_lampe
      - choose:
          - conditions:
              - condition: state
                entity_id: climate.arbeitszimmer
                state: 'on'
            sequence:
              - service: climate.set_preset_mode
                data:
                  entity_id: climate.arbeitszimmer
                  preset_mode: 'comfort'
      - choose:
          - conditions:
              - condition: or
                conditions:
                  - condition: state
                    entity_id: binary_sensor.arbeitstag_morgen
                    state: 'off'
                  - condition: state
                    entity_id: binary_sensor.urlaub_morgen
                    state: 'on'                       
            sequence:
              - service: input_select.select_option
                data:
                  entity_id: input_select.computer_arbeit_ausschalten  
                  option: 'Herunterfahren'     
        default:
          - service: input_select.select_option
            data:
              entity_id: input_select.computer_arbeit_ausschalten  
              option: 'Ruhezustand'             
          
  home_office_ende:
    alias: 'Home Office - Ende'
    sequence:
      - service: input_boolean.turn_off
        entity_id: input_boolean.home_office_aktiv
      - service: switch.turn_off
        entity_id: switch.arbeitszimmer_radio, switch.arbeitszimmer_monitore, switch.pc_arbeit
      - service: switch.turn_on
        entity_id: switch.computer, switch.watchtv_wohnzimmer
      - choose:
          - conditions:
              - condition: numeric_state
                entity_id: sensor.bewegungsmelder_balkon_temperatur
                above: 10
            sequence:
              - service: switch.turn_on
                entity_id: switch.balkon_radio        
      - choose:
          - conditions:
              - condition: state
                entity_id: climate.arbeitszimmer
                attribute: preset_mode
                state: 'heat'
            sequence:              
              - service: climate.set_preset_mode
                data:
                  entity_id: climate.arbeitszimmer
                  preset_mode: 'eco'
      - delay: '00:00:10'
      - choose:
          - conditions:
              - condition: state
                entity_id: sensor.sonne_tagsueber
                state: 'off'
            sequence:
              - service: light.turn_on
                entity_id: light.wohnzimmer_schrank                      
        
automation:
  - alias: "Home Office - Start"
    id: "home_office_start"
    trigger:
      - platform: event
        event_type: zha_event
        event_data:
          device_ieee: 00:15:8d:00:01:83:77:4a
          command: click
          args:
            click_type: double   
    condition:
      - condition: state
        entity_id: binary_sensor.home_office_heute
        state: 'on'       
      - condition: state
        entity_id: binary_sensor.home_office_aktiv
        state: 'off'     
    action:
      - service: script.home_office_start

  - alias: "Home Office - Countdown starten"
    id: "home_office_countdown_starten"
    trigger:
      - platform: event
        event_type: zha_event
        event_data:
          device_ieee: 00:15:8d:00:01:83:77:4a
          command: click
          args:
            click_type: double       
    condition:
      - condition: state
        entity_id: binary_sensor.home_office_aktiv
        state: 'on'
      - condition: state
        entity_id: timer.home_office_ende
        state: 'idle'
    action:
      - service: !secret tts_service
        data:
          echo: "flur"
          message: "Der Computer wird Arbeitszimmer wird gleich ausgeschaltet."
      - delay: '00:00:04'
      - service: timer.start
        entity_id: timer.home_office_ende
      - service: media_player.play_media
        data:
          entity_id: media_player.benachrichtigungen
          media_content_id: sounds/countdown_5.mp3
          media_content_type: music

  - alias: "Home Office - Countdown abbrechen"
    id: "home_office_countdown_abbrechen"
    trigger:
      - platform: event
        event_type: zha_event
        event_data:
          device_ieee: 00:15:8d:00:01:83:77:4a
          command: click
          args:
            click_type: single   
    condition:
      - condition: state
        entity_id: timer.home_office_ende
        state: 'active'
    action:
      - service: media_player.media_pause
        entity_id: media_player.benachrichtigungen
      - service: !secret tts_service
        data:
          echo: "flur"
          message: "Der Vorgang wurde abgebrochen."
      - service: timer.cancel
        entity_id: timer.home_office_ende

  - alias: "Home Office - Ende"
    id: "home_office_ende"
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.home_office_ende
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: input_select.computer_arbeit_ausschalten
                state: 'Herunterfahren'
            sequence:
              - service: !secret tts_service
                data:
                  echo: "flur"
                  message: "Der Computer im Arbeitszimmer wird jetzt heruntergefahren."
        default:      
          - service: !secret tts_service
            data:
              echo: "flur"
              message: "Der Computer im Arbeitszimmer wird jetzt ausgeschaltet."
      - delay: '00:00:02'
      - service: script.home_office_ende

  - alias: "Home Office - Computer eingeschaltet"
    id: "home_office_computer_eingeschaltet"
    trigger:
      - platform: state
        entity_id: switch.pc_arbeit
        to: 'on'
        for: '00:05:00'
    condition:       
      - condition: state
        entity_id: binary_sensor.home_office_aktiv
        state: 'off'        
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: binary_sensor.schlafen_aktiv
                state: 'on'                
            sequence:
              - service: switch.turn_off
                entity_id: switch.pc_arbeit
          - conditions:
              - condition: state
                entity_id: binary_sensor.zu_hause
                state: 'off'                
            sequence:
                  - service: notify.telegram
                    data:                      
                      message: 'Der Computer im Arbeitszimmer wurde eingeschaltet und wird jetzt heruntergefahren.'
                  - service: switch.turn_off
                    entity_id: switch.pc_arbeit                  
        default:      
          - service: !secret tts_service
            data:          
              message: "Der Computer im Arbeitszimmer wurde eingeschaltet."
     
  - alias: "Home Office - Status geändert"
    id: "home_office_status_geaendert"
    trigger:
      - platform: state
        entity_id: calendar.arbeit_buero
        to: 'on'
      - platform: state
        entity_id: calendar.arbeit_buero
        to: 'off'        
    action:
      - choose:
          - conditions:
              - "{{ True if trigger.to_state.state == 'on' else False }}"
            sequence:
              - service: input_boolean.turn_off
                entity_id: input_boolean.home_office
        default:
          - service: input_boolean.turn_on
            entity_id: input_boolean.home_office
      
  - alias: "Home Office - Radios pausieren"
    id: "home_office_radios_pausieren"
    trigger:
      - platform: event
        event_type: zha_event
        event_data:
          device_ieee: 00:15:8d:00:01:83:77:4a
          command: click
          args:
            click_type: single   
      - platform: state
        entity_id: binary_sensor.computer_arbeit_mikrofon
        from: 'off'
        to: 'on'
    condition:       
      - condition: state
        entity_id: input_boolean.home_office_musik_pausiert
        state: 'off'
      - condition: state
        entity_id: binary_sensor.home_office_aktiv
        state: 'on'        
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.home_office_musik_pausiert
      - service: switch.turn_on
        entity_id: switch.radios_lautlos

  - alias: "Home Office - Radios starten"
    id: "home_office_radios_starten"
    trigger:
      - platform: event
        event_type: zha_event
        event_data:
          device_ieee: 00:15:8d:00:01:83:77:4a
          command: click
          args:
            click_type: single   
      - platform: state
        entity_id: binary_sensor.computer_arbeit_mikrofon
        from: 'on'
        to: 'off'
    condition:
      - condition: state
        entity_id: input_boolean.home_office_musik_pausiert
        state: 'on'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.home_office_musik_pausiert
      - service: switch.turn_off
        entity_id: switch.radios_lautlos      
        
homeassistant:
  customize:
    switch.arbeitszimmer_monitore:
      icon: mdi:monitor-dashboard      