timer:
  home_office_ende:
    name: "Home Office beenden"
    duration: 7
             
input_boolean:
  home_office:
    name: Home Office
    icon: mdi:home-city-outline
  
  home_office_aktiv:
    name: Home Office aktiv
    
  computer_arbeit_ausschalten:
    name: Computer Arbeit ausschalten    
    icon: mdi:desktop-classic
    
  home_office_musik_pausiert:
    name: Musik pausiert    
    
binary_sensor:
  - platform: template
    sensors:
      home_office_heute:
        friendly_name: 'Home Office heute'
        icon_template: mdi:home-city
        value_template: >-
          {% set istHomeOffice = is_state('input_boolean.home_office', 'on') %}
          {% set istArbeitstag = is_state('binary_sensor.arbeitstag', 'on') %}
          {% set keinUrlaub = is_state('calendar.urlaub', 'off') %}
          {% set nichtKrank = is_state('calendar.arbeit_krank', 'off') %}

          {{ True if (istHomeOffice and istArbeitstag and keinUrlaub and nichtKrank) else False }}
          
      home_office:
        friendly_name: 'Home Office'
        icon_template: mdi:home-city
        value_template: >-
          {% set homeOfficeHeute = is_state('binary_sensor.home_office_heute', 'on') %}
          {% set homeOfficeAktiv = is_state('input_boolean.home_office_aktiv', 'on') %}

          {{ True if (homeOfficeHeute and homeOfficeAktiv) else False }}
      
sensor:
  - platform: template
    sensors:
      teams_status:
        friendly_name: "Microsoft Teams - Status"
        value_template: >-
          {% if states('sensor.teams_status') == '' -%}
            Offline
          {%- endif %}
        icon_template: >-
          {% if states('sensor.teams_status') == '' -%}
            mdi:microsoft-teams
          {%- endif %}
        unique_id: sensor.teams_status
        
      teams_activity:
        friendly_name: "Microsoft Teams - Aktivität"
        value_template: >-
          {% if states('sensor.teams_activity') == '' -%}
            Offline
          {%- endif %}
        icon_template: >-
          {% if states('sensor.teams_activity') == '' -%}
            mdi:microsoft-teams
          {%- endif %}
        unique_id: sensor.teams_activity          
          
      teams_status_de:
        friendly_name: "Microsoft Teams - Status"
        value_template: >-
          {% set teamsStatus = states('sensor.teams_status') %}

          {% if teamsStatus == 'Available' %}
            Verfügbar
          {% elif teamsStatus == 'Busy' %}
            Beschäftigt
          {% elif teamsStatus == 'Away' %}
            Abwesend
          {% elif teamsStatus == 'Do not disturb' %}
            Nicht stören
          {% elif teamsStatus == 'In a meeting' %}
            In einer Besprechung
          {% else %} 
            Offline
          {% endif %}
        icon_template: "mdi:microsoft-teams"
        
      teams_activity_de:
        friendly_name: "Microsoft Teams - Aktivität"
        value_template: >-
          {% if states('sensor.teams_activity') == 'In a call' %}
            Am Telefon
          {% else %} 
            Nicht am Telefon
          {% endif %}
        icon_template: >-
          {% if states('sensor.teams_activity') == 'In a call' %}
            mdi:phone-in-talk
          {% else %} 
            mdi:phone-off
          {% endif %}
          
switch:
  - platform: template
    switches:
      pc_arbeit:
        friendly_name: PC Arbeit        
        value_template: "{{ is_state('device_tracker.computerarbeit', 'home') }}"
        icon_template: mdi:desktop-tower
        turn_on:
          service: wake_on_lan.send_magic_packet
          data:
            mac: !secret computerarbeit_mac
            broadcast_address: !secret fritzbox_broadcast
            broadcast_port: 9
        turn_off:
          service: switch.turn_on
          entity_id: switch.computer_arbeit_ruhezustand

script:
  home_office_start:
    alias: 'Home Office - Start'
    sequence:
      - service: input_boolean.turn_on
        entity_id: input_boolean.home_office_aktiv
      - service: switch.turn_off
        entity_id: switch.schlafzimmer_radio, switch.monitor        
      - service: switch.turn_on
        entity_id: switch.arbeitszimmer_radio, switch.pc_arbeit, switch.arbeitszimmer_monitore  
      - service: light.turn_off
        entity_id: light.schreibtisch, light.arbeitszimmer_lampe
      - service: climate.set_preset_mode
        data:
          entity_id: climate.arbeitszimmer
          preset_mode: 'comfort'
      - condition: state
        entity_id: input_boolean.computer_ausschalten
        state: 'on'
      - service: switch.turn_off
        entity_id: switch.pc
          
  home_office_ende:
    alias: 'Home Office - Ende'
    sequence:
      - service: input_boolean.turn_off
        entity_id: input_boolean.home_office_aktiv
      - service: switch.turn_off
        entity_id: switch.arbeitszimmer_radio, switch.arbeitszimmer_monitore
      - service: switch.turn_on
        entity_id: switch.computer
      - service: climate.set_preset_mode
        data:
          entity_id: climate.arbeitszimmer
          preset_mode: 'eco'        
      - condition: state
        entity_id: input_boolean.computer_arbeit_ausschalten
        state: 'on'
      - service: switch.turn_off
        entity_id: switch.pc_arbeit      
        
automation:
  - alias: 'Home Office - Start'
    trigger:
      - platform: state
        entity_id: sensor.schalter_arbeitszimmer
        to: '2'     
    condition:
      - condition: state
        entity_id: binary_sensor.home_office_heute
        state: 'on'       
      - condition: state
        entity_id: input_boolean.home_office_aktiv
        state: 'off'     
    action:
      - service: script.home_office_start

  - alias: "Home Office - Countdown starten"
    trigger:
      - platform: state
        entity_id: sensor.schalter_arbeitszimmer
        to: '2'      
    condition:
      - condition: state
        entity_id: input_boolean.home_office_aktiv
        state: 'on'
      - condition: state
        entity_id: timer.home_office_ende
        state: 'idle'
    action:
      - service: !secret tts_service
        data_template:
          echo: "flur"
          message: "Der Computer wird Arbeitszimmer wird gleich ausgeschaltet."
      - delay: '00:00:02'
      - service: timer.start
        entity_id: timer.home_office_ende
      - service: media_player.play_media
        data_template:
          entity_id: media_player.benachrichtigungen
          media_content_id: http://192.168.2.75:8123/local/sounds/countdown_5.mp3
          media_content_type: music

  - alias: "Home Office - Countdown abbrechen"
    trigger:
      - platform: state
        entity_id: binary_sensor.schalter_arbeitszimmer
        to: 'off'
    condition:
      - condition: state
        entity_id: timer.home_office_ende
        state: 'active'
    action:
      - service: media_player.media_pause
        entity_id: media_player.benachrichtigungen
      - service: !secret tts_service
        data_template:
          echo: "flur"
          message: "Der Vorgang wurde abgebrochen."
      - service: timer.cancel
        entity_id: timer.home_office_ende

  - alias: "Home Office - Ende"
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.home_office_ende
    action:
      - service: !secret tts_service
        data_template:
          echo: "flur"
          message: "Der Computer im Arbeitszimmer wird jetzt ausgeschaltet."
      - service: script.home_office_ende

  - alias: "Home Office - Status geändert"
    trigger:
      - platform: state
        entity_id: calendar.arbeit_buero
    action:
      - choose:
          - conditions:
              - condition: template
                value_template: "{{ True if trigger.to_state.state == 'on' else False }}"
            sequence:
              - service: input_boolean.turn_off
                entity_id: input_boolean.home_office
        default:
          - service: input_boolean.turn_on
            entity_id: input_boolean.home_office
      
  - alias: 'Home Office - Radios pausieren'
    trigger:
      - platform: state
        entity_id: binary_sensor.schalter_arbeitszimmer
        to: 'off'
      - platform: state
        entity_id: binary_sensor.computer_arbeit_mikrofon
        from: 'off'
        to: 'on'
    condition:       
      - condition: state
        entity_id: input_boolean.home_office_musik_pausiert
        state: 'off'
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.home_office_musik_pausiert
      - service: switch.turn_on
        entity_id: switch.radios_lautlos

  - alias: 'Home Office - Radios starten'
    trigger:
      - platform: state
        entity_id: binary_sensor.schalter_arbeitszimmer
        to: 'off'
      - platform: state
        entity_id: binary_sensor.computer_arbeit_mikrofon
        from: 'on'
        to: 'off'
    condition:
      - condition: state
        entity_id: input_boolean.home_office_musik_pausiert
        state: 'on'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.home_office_musik_pausiert
      - service: switch.turn_off
        entity_id: switch.radios_lautlos      
        
homeassistant:
  customize:
    switch.arbeitszimmer_monitore:
      icon: mdi:monitor-dashboard      