input_number:
  alarmdelay:
    name: Verzögerung
    min: 0   
    max: 30
    step: 5
    icon: mdi:timer-sand

  alarmadvance:
    name: Vorlauf
    min: 0    
    max: 30
    step: 5
    icon: mdi:timer-sand

input_boolean:
  alarm_aktiv:
    name: Wecker aktiv    
    icon: mdi:alarm-multiple

  wecker_erinnerung_morgen:
    name: Erinnerung morgen    
    
  wecker_zeit_geaendert:
    name: Zeit geändert     

input_text:
  alarm_standard_office:
    name: Wecker Büro
    initial: '05:15'
  alarm_standard_homeoffice:
    name: Wecker Home Office 
    initial: '06:00'    
    
binary_sensor:
  - platform: template
    sensors:
      alarm_aktiv:
        friendly_name: Alarm aktiv
        icon_template: mdi:alarm-multiple
        device_class: sound
        value_template: "{{ True if is_state('input_boolean.alarm_aktiv', 'on') else False }}"

sensor:
  - platform: template
    sensors:
      wecker_startzeit:
        friendly_name: Wecker Startzeit
        icon_template: mdi:alarm-bell
        unit_of_measurement: 'Uhr'
        value_template: >-
          {% set alarmSensor = states('sensor.tablet_schlafzimmer_nachster_wecker')%}

          {% if alarmSensor == 'unavailable' %}
            -
          {% else %}
            {{ as_timestamp(alarmSensor) | timestamp_custom("%H:%M", True) }}
          {% endif %}              
        
      wecker_startdatum:
        friendly_name: Wecker Startdatum
        icon_template: mdi:calendar-clock
        value_template: >-
          {% set alarmSensor = states('sensor.tablet_schlafzimmer_nachster_wecker')%}

          {% if alarmSensor == 'unavailable' %}
            -
          {% else %}
            {% set weekday = as_timestamp(alarmSensor) | timestamp_custom("%w", True) | int %}
            {{ ['Montag','Dienstag','Mittwoch','Donnerstag','Freitag','Samstag','Sonntag'][weekday-1] }}, {{ as_timestamp(alarmSensor) | timestamp_custom("%d.%m.%Y", True) | string }}          
          {% endif %}

automation:
  - alias: "Wecker starten"
    trigger:
      - platform: template
        value_template: >-
          {% set jetzt = as_timestamp(states('sensor.date_time').replace(',','')) | int %}         
          {% set vorlauf = (states('input_number.alarmadvance' ) | int) * 60  %}
          {% set wecker = as_timestamp(states('sensor.tablet_schlafzimmer_nachster_wecker')) | int %}
          
          {{ wecker == jetzt + vorlauf }}
    condition:
      condition: and
      conditions:
        - condition: numeric_state
          entity_id: sensor.laufzeit_minuten
          above: 5
        - condition: state
          entity_id: input_boolean.alarm_aktiv
          state: 'off'        
        - condition: state
          entity_id: binary_sensor.schlafen_aktiv
          state: 'on'
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.alarm_aktiv  
      - service: light.turn_on
        data:
          entity_id: light.bett
          effect: colorloop
      - service: switch.turn_on
        entity_id: switch.schlafzimmer_radio               
      - delay: "00:{{ states('input_number.alarmdelay') | int }}:00" 
      - service: script.wohnung_radios_einschalten

  - alias: "Weckzeit geändert - Erinnerung"
    trigger:
      - platform: state
        entity_id: input_boolean.wecker_zeit_geaendert
        to: 'on'
        for:
          minutes: 5
    condition:
      - condition: state
        entity_id: binary_sensor.alarm_aktiv
        state: 'on'
    action:
      - service: !secret tts_service
        data_template:
          echo: "schlafzimmer"
          message: >-
            {% set currentTime = states('sensor.time') %}
            
            {% if '00:00' <= currentTime < '05:00' %}
              {% set message = 'Gute Nacht!' %}
            {% elif '05:00' <= currentTime < '12:00' %}
              {% set message = 'Guten Morgen!.' %}
            {% elif '12:00' <= currentTime < '19:00' %}
              {% set message = 'Guten Tag!' %}
            {% else %}
              {% set message = 'Guten Abend!' %}
            {% endif %}
            
            {{ message }} Der Wecker ist ausgeschaltet. Du solltest jetzt aufstehen!
      - delay: "00:00:10"
      - service: media_player.play_media
        data:
          entity_id: media_player.echo_schlafzimmer
          media_content_type: sound
          media_content_id: amzn_sfx_scifi_alarm_04