input_select:
  zu_hause_begruessung:
    name: Begrüßung
    options:
      - Deaktiviert
      - Tür
      - Handy      

input_boolean:
  geraete_einschalten:
    name: "Geräte einschalten"
  
  anwesenheit_franzi:
    name: "Anwesenheit Franzi"
    icon: mdi:human-child   

  anwesenheit_aaron:
    name: "Anwesenheit Aaron"
    icon: mdi:baby
    
  anwesenheit_natalie:
    name: "Anwesenheit Natalie"
    icon: mdi:human-female   
    
  anwesenheit_flori:
    name: "Anwesenheit Flori"
    icon: mdi:dog-side       
    
shell_command:
  send_position: "curl -X POST '{{ url }}?lat={{ state_attr('zone.home', 'latitude') }}&lon={{ state_attr('zone.home', 'longitude') }}&timestamp={{ as_timestamp(now()) | int(0) }}'"

mqtt:
  device_tracker:
    - name: "Handy Natalie MQTT"
      state_topic: "presence/natalie"
    
    - name: "Franzi MQTT"
      state_topic: "presence/franzi"
      
    - name: "Aaron MQTT"
      state_topic: "presence/aaron"
      
    - name: "Flori MQTT"
      state_topic: "presence/flori"
      
template:
  - sensor:
      - name: "Personen zu Hause"
        unique_id: personen_zu_hause
        state: >
          {% set personenZuHause = expand('group.personen')
            | selectattr('state','eq','home') 
            | list
            | length %}
            
          {{ personenZuHause }}
          
  - binary_sensor:
      - name: "Allein zu Hause"
        unique_id: allein_zu_hause
        state: "{{ is_state('sensor.personen_zu_hause', '1') and is_state('person.dennis', 'home') }}"
          
script:
  zu_hause:
    alias: "Zu Hause"
    sequence:
      - service: switch.turn_on
        entity_id: switch.computer, switch.arbeitszimmer_monitore           
      - choose:
          - conditions:
              - condition: state
                entity_id: binary_sensor.sonne_tagsueber
                state: 'off'
            sequence:
              - service: light.turn_on
                entity_id: light.wohnzimmer_schrank           
      - service: script.radios_einschalten     
      - if: "{{ is_state('person.franzi', 'home') and is_state('binary_sensor.licht_kinderzimmer', 'on') }}"
        then:          
          - service: light.turn_on
            entity_id: light.kinderzimmer_licht          

  zu_hause_home_office:
    alias: "Zu Hause - Home Office"
    sequence:      
      - service: switch.turn_on
        entity_id: switch.arbeitszimmer_radio, switch.computer_arbeit, switch.arbeitszimmer_monitore
      - service: script.radios_einschalten   
        data:
          radioBalkon: false         
      - service: input_boolean.turn_on
        entity_id: input_boolean.home_office_aktiv          
      - choose:
          - conditions:
              - condition: or
                conditions:
                  - condition: state
                    entity_id: binary_sensor.arbeitstag_morgen
                    state: 'off'
                  - condition: state
                    entity_id: binary_sensor.urlaub_morgen
                    state: 'on'                       
            sequence:
              - service: input_select.select_option
                data:
                  entity_id: input_select.computer_arbeit_ausschalten  
                  option: 'Herunterfahren'     
        default:
          - service: input_select.select_option
            data:
              entity_id: input_select.computer_arbeit_ausschalten  
              option: 'Ruhezustand'
            
  zu_hause_abends:
    alias: "Zu Hause - abends"
    sequence:
      - service: light.turn_on
        entity_id: light.wohnzimmer_schrank
      - service: switch.turn_on
        entity_id: switch.computer, switch.arbeitszimmer_monitore   
      - service: switch.turn_on
        entity_id: switch.badezimmer_radio    
      - wait_template: "{{ is_state('media_player.radio_badezimmer', 'playing') }}"
      - service: media_player.media_pause
        entity_id: media_player.radio_badezimmer    
      - if: "{{ is_state('person.franzi', 'home') }}"
        then:          
          - service: light.turn_on
            entity_id: light.kinderzimmer_licht            

  zu_hause_standort:
    alias: "Zu Hause - Standort"
    sequence:
      - service: shell_command.send_position
        data:
          url: !secret phonetrack_send_position_url
      - service: device_tracker.see
        data:
          dev_id: 'handy_gps'
          location_name: home
          source_type: gps
          gps_accuracy: 20
          battery: "{{ states('sensor.handy_battery_level') | int(0) }}"
          gps: 
            - !secret home_latitude
            - !secret home_longitude                  
      - service: mqtt.publish
        data:
           topic: 'handy/location'
           payload: home
           retain: true          
        
  zu_hause_begruessung:
    alias: "Zu Hause - Begrüßung"
    sequence:
      - delay: '00:00:15'
      - choose:
          - conditions:          
              condition: or
              conditions:               
                - "{{ is_state('binary_sensor.nachts', 'on') }}"
                - "{{ is_state('binary_sensor.allein_zu_hause', 'off') }}"
            sequence:
              - service: !secret tts_service
                data:
                  message: "Willkommen zu Hause."
        default:  
          - service: !secret tts_service
            data:
              message: >-
                "Hallo Dennis. Willkommen zu Hause."

                {% if is_state('counter.staubsauger_behaelter_leeren', '0') %}
                  "Der Staubsaugerbehälter muss geleert werden."
                {% endif %}

                {% set count_heimnetz_entities = states('sensor.netzwerkgerate_offline') | int(0) -%}            
                {% if count_heimnetz_entities > 0 %}
                  {{ "Die folgenden Geräte sind offline." if count_heimnetz_entities > 1 else "Das folgende Gerät ist offline."}}

                  {{ state_attr('sensor.netzwerkgerate_offline', 'geraete') | join(', ') }}                         
                {% endif %}
                
                {% set count_flowers = states('sensor.pflanzen_giessen') | int(0) -%}            
                {% if count_flowers > 0 %}
                  {% set flower_warn_level = states('input_number.pflanzen_warnlevel') | int(0) -%}  
                  {{ "Die folgenden Pflanzen müssen gegossen werden." if count_flowers > 1 else "Die folgende Pflanze muss gegossen werden."}}

                  {% for x in expand('group.pflanzen') if x.state|int(100) < flower_warn_level %}
                    {%- if not loop.first %}, {% endif -%}
                    {{- x.name.split(' ')[0] -}}
                  {% endfor %}                       
                {% endif %}

                {% set count_steckdosen_offline = states('sensor.steckdosen_offline') | int(0) -%}            
                {% if count_steckdosen_offline > 0 %}
                  {{ "Die folgenden Geräte sind nicht verfügbar." if count_steckdosen_offline > 1 else "Das folgende Gerät ist nicht verfügbar."}}

                  {{ state_attr('sensor.steckdosen_offline', 'geraete') | join(', ') }}                         
                {% endif %}

                {% set min_battery_level = states('input_number.batteriestand_warnlevel') | int(0) -%}                       
                {% set count_battery_entities = states('sensor.batteriestand_niedrig') | int(0) -%}

                {% if count_battery_entities > 0 %}
                  {{ "Der Batteriestand der folgenden Geräte ist niedrig." if count_battery_entities > 1 else "Der Batteriestand des folgenden Gerätes ist niedrig."}}

                  {% for x in expand('group.batteriestand') if x.state|int(100) <= min_battery_level %}
                    {%- if not loop.first %}, {% endif -%}
                    {{- x.name.split(" ")[:-1] | join(' ') -}}
                  {% endfor %}       
                {% endif %}
            
automation:     
  - alias: "Zu Hause - Alarm ausschalten"
    id: "zu_hause_alarm_ausschalten"
    trigger:
      - platform: state
        entity_id: person.dennis
        to: 'home'       
      - platform: state
        entity_id: person.natalie
        to: 'home'            
    condition:    
      - "{{ is_state('binary_sensor.schlafen_aktiv', 'off') }}"
      - "{{ not is_state('alarm_control_panel.alarmo', 'disarmed') }}"
      - condition: template
        value_template: >-
          {% set now = as_timestamp(now()) %}
          {% set last = as_timestamp(state_attr("script.alles_ausschalten", "last_triggered"), None) | int(0) %}
          {% set diff = ((now - last) / 60) | int(0) %}

          {{ diff >= 10 }}    
    action:         
      - service: alarmo.disarm
        data:
          entity_id: alarm_control_panel.alarmo
          
  - alias: "Zu Hause"
    id: "zu_hause"
    trigger:
      - id: zu_hause
        platform: state
        entity_id: person.dennis
        to: 'home'
      - id: schalter_flur
        platform: event
        event_type: zha_event
        event_data:
          device_ieee: 00:15:8d:00:01:c3:08:67
          command: click
          args:
            click_type: double   
    condition:    
      - "{{ is_state('binary_sensor.schlafen_aktiv', 'off') }}"
      - "{{ is_state('input_boolean.geraete_einschalten', 'on') }}"
      - condition: template
        value_template: >-
          {% set now = as_timestamp(now()) %}
          {% set last = as_timestamp(state_attr("script.alles_ausschalten", "last_triggered"), None) | int(0) %}
          {% set diff = ((now - last) / 60) | int(0) %}

          {{ diff >= 10 }}        
    action:         
      - service: script.zu_hause_standort
      - service: switch.turn_off
        entity_id: switch.abwesenheit_urlaub      
      - service: input_select.select_option
        data:
          entity_id: input_select.computer_ausschalten  
          option: 'Ruhezustand'              
      - choose:    
          - conditions:
              - condition: or
                conditions:
                  - "{{ is_state('binary_sensor.home_office_aktiv', 'on') }}"
                  - condition: template
                    value_template: >-
                      {% set now = as_timestamp(now()) %}
                      {% set last = as_timestamp(state_attr("script.alles_ausschalten", "last_triggered"), None) | int(0) %}
                      {% set minutenUnterwegs = ((now - last) / 60) | int(0) %}
                      {% set minuenHomeOffice = states('input_number.home_office_heute_gearbeitet') | int(0) %}
                      {% set heuteBuero = is_state('binary_sensor.buero_heute', 'on') %}

                      {{ (minutenUnterwegs + minuenHomeOffice < 600) if (minuenHomeOffice > 0 or heuteBuero) else false }}                              
            sequence:              
              - service: script.zu_hause_home_office       
          - conditions:
              - "{{ is_state('binary_sensor.nachts', 'on') }}"
            sequence:           
              - service: script.zu_hause_abends         
          - conditions:
              - "{{ is_state('binary_sensor.nachts', 'off') }}"
            sequence:           
              - service: script.zu_hause                 
      - choose:    
          - conditions:      
              - "{{ (states('input_number.home_office_heute_gearbeitet') | int(0)) > 0 }}"
            sequence:                 
              - service: input_number.set_value        
                data:
                  entity_id: input_number.home_office_heute_gearbeitet
                  value: 0             
      - service: input_boolean.turn_off
        entity_id: input_boolean.geraete_einschalten                  
               
  - alias: "Zu Hause - Tür geöffnet"
    id: "zu_hause_tuer_geoeffnet"
    trigger:
      - platform: state
        entity_id: binary_sensor.wohnungstuer
        to: 'on'
    condition:    
      - "{{ is_state('input_select.zu_hause_begruessung', 'Deaktiviert') }}"
      - "{{ is_state('person.dennis', 'not_home') }}"
      - "{{ is_state('binary_sensor.schlafen_aktiv', 'off') }}"
    action:    
      - service: input_select.select_option            
        entity_id: input_select.zu_hause_begruessung
        data:
          option: 'Tür'
          
  - alias: "Zu Hause - Handy verbunden"
    id: "zu_hause_handy_verbunden"
    trigger:
      - id: zu_hause
        platform: state
        entity_id: person.dennis
        to: 'home'
    condition:    
      - "{{ is_state('input_select.zu_hause_begruessung', 'Deaktiviert') }}"
      - "{{ is_state('binary_sensor.schlafen_aktiv', 'off') }}"
    action:              
      - service: input_select.select_option            
        entity_id: input_select.zu_hause_begruessung
        data:
          option: 'Handy'
                
  - alias: "Zu Hause - Begrüßung"
    id: "zu_hause_begruessung"
    trigger:
      - id: wohnungstuer
        platform: state
        entity_id: binary_sensor.wohnungstuer
        to: 'off' 
      - id: handy
        platform: state
        entity_id: person.dennis
        to: 'home'               
    condition:        
      - "{{ not is_state('input_select.zu_hause_begruessung', 'Deaktiviert') }}"   
      - condition: or
        conditions:
          - "{{ trigger.id == 'handy' and is_state('input_select.zu_hause_begruessung', 'Tür') }}"     
          - "{{ trigger.id == 'wohnungstuer' and is_state('input_select.zu_hause_begruessung', 'Handy') }}"      
    action:      
      - service: input_select.select_option
        entity_id: input_select.zu_hause_begruessung
        data:
          option: 'Deaktiviert'     
      - service: script.zu_hause_begruessung    

  - alias: "Natalie - Anwesenheit"
    id: "natalie_anwesenheit"
    trigger:
      - platform: state
        entity_id: input_boolean.anwesenheit_natalie           
    action:      
      - service: mqtt.publish
        data:
           topic: 'presence/natalie'
           payload: "{{ 'home' if trigger.to_state.state == 'on' else 'not_home' }}"
           retain: true             
           
  - alias: "Franzi - Anwesenheit"
    id: "franzi_anwesenheit"
    trigger:
      - id: boolean
        platform: state
        entity_id: input_boolean.anwesenheit_franzi
      - id: calendar
        platform: state
        entity_id: calendar.franzi_papa_wochenende
      - id: schule_morgens
        platform: template
        value_template: >-
          {% set fahrzeitAuto = states('sensor.fahrzeit_schule') | int(0) %}
          {% set fahrzeitBus = states('input_number.schule_fahrzeit_bus') | int(0) %}
          
          {% set fahrzeitMinuten = fahrzeitAuto if is_state('input_boolean.schule_auto', 'on') else fahrzeitBus %}
          {% set beginnMinuten = (state_attr('input_datetime.schule_beginn', 'timestamp') / 60) | int(0) %}

          {% set abfahrzeitMinuten = beginnMinuten - fahrzeitMinuten %}
          {% set stundeAbfahrt = (abfahrzeitMinuten / 60) | int(0) %}
          {% set minuteAbfahrt = (abfahrzeitMinuten - stundeAbfahrt * 60) | int(0) %}
          {% set uhrzeitAbfahrt = "%0.02d:%0.02d" | format(stundeAbfahrt, minuteAbfahrt ) %}

          {{ states("sensor.time") == uhrzeitAbfahrt }}
      - id: schule_nachmittags
        platform: template
        value_template: >-
          {% set fahrzeitAuto = states('sensor.fahrzeit_schule') | int(0) %}
          {% set fahrzeitBus = states('input_number.schule_fahrzeit_bus') | int(0) %}
          
          {% set fahrzeitMinuten = fahrzeitAuto if is_state('input_boolean.schule_auto', 'on') else fahrzeitBus %}
          {% set endeMinuten = (state_attr('input_datetime.schule_ende', 'timestamp') / 60) | int(0) %}

          {% set ankunftszeitMinuten = endeMinuten + fahrzeitMinuten %}
          {% set stundeAnkunft = (ankunftszeitMinuten / 60) | int(0) %}
          {% set minuteAnkunft = (ankunftszeitMinuten - stundeAnkunft * 60) | int(0) %}
          {% set uhrzeitAnkunft = "%0.02d:%0.02d" | format(stundeAnkunft, minuteAnkunft ) %}

          {{ states("sensor.time") == uhrzeitAnkunft }}          
    variables:       
      aktion: >-
        {% if trigger.id == 'boolean' %}
          {{ 'home' if trigger.to_state.state == 'on' else 'not_home' }}
        {% elif trigger.id == 'schule_morgens' %}
          {{ 'not_home' }}
        {% elif trigger.id == 'schule_nachmittags' %}
          {{ 'home' }}          
        {% else %}
          {{ 'not_home' if trigger.to_state.state == 'on' else 'home' }}
        {% endif %}
    condition:        
      - "{{ aktion != states('device_tracker.franzi_mqtt') }}"
      - condition: or
        conditions:
          - "{{ trigger.id == 'boolean' or trigger.id == 'calendar' }}"          
          - "{{ trigger.id == 'schule_morgens' and is_state('binary_sensor.schultag', 'on') }}"
          - "{{ trigger.id == 'schule_nachmittags' and is_state('binary_sensor.schultag', 'on') and is_state('calendar.franzi_papa_wochenende', 'off') }}"
    action:      
      - service: mqtt.publish
        data:
           topic: "presence/franzi"
           payload: "{{ aktion }}"
           retain: true        
      - if: "{{ aktion == 'home' }}"
        then:                 
          - service: input_boolean.turn_on
            entity_id: input_boolean.anwesenheit_franzi           
        else:             
          - service: input_boolean.turn_off
            entity_id: input_boolean.anwesenheit_franzi   
      - if: "{{ trigger.id == 'calendar' and aktion == 'home' and is_state('binary_sensor.licht_kinderzimmer', 'on') }}"
        then:                 
          - service: light.turn_on
            entity_id: light.kinderzimmer_licht                         
           
  - alias: "Aaron - Anwesenheit"
    id: "aaron_anwesenheit"
    trigger:
      - platform: state
        entity_id: input_boolean.anwesenheit_aaron
    action:      
      - service: mqtt.publish
        data:
           topic: "presence/aaron"
           payload: "{{ 'home' if trigger.to_state.state == 'on' else 'not_home' }}"
           retain: true      
           
  - alias: "Flori - Anwesenheit"
    id: "flori_anwesenheit"
    trigger:
      - platform: state
        entity_id: input_boolean.anwesenheit_flori
    action:      
      - service: mqtt.publish
        data:
           topic: "presence/flori"
           payload: "{{ 'home' if trigger.to_state.state == 'on' else 'not_home' }}"
           retain: true                    
           
homeassistant:
  customize:
    sensor.aufenthaltsort:
      icon: mdi:google-maps

    person.natalie:
      icon: mdi:human-female
    person.franzi:
      icon: mdi:human-child
    person.aaron:
      icon: mdi:baby
    person.flori:
      icon: mdi:dog-side         