input_number:
  batteriestand_warnlevel:
    name: Warnlevel
    min: 10
    max: 80
    step: 5

sensor:
  - platform: template
    sensors:
      bewegungsmelder_wohnzimmer_battery_level:
        friendly_name: Bewegungsmelder Wohnzimmer
        value_template: "{{ states('sensor.bewegungsmelder_wohnzimmer_battery_level_original') | int(0) }}"
        device_class: battery
        
      bewegungsmelder_badezimmer_battery_level:
        friendly_name: Bewegungsmelder Badezimmer
        value_template: "{{ states('sensor.bewegungsmelder_badezimmer_battery_level_original') | int(0) }}"
        device_class: battery
        
      bewegungsmelder_balkon_battery_level:
        friendly_name: Bewegungsmelder Balkon
        value_template: "{{ states('sensor.bewegungsmelder_balkon_battery_level_original') | int(0) }}"
        device_class: battery
        
      batteriestand_niedrig:
        friendly_name: Batteriestand niedrig
        icon_template: >
          {% set entities = expand('group.batteriestand') %}
          {% set min_battery_level = states('input_number.batteriestand_warnlevel') | int(0) -%}
          {% set ns = namespace(found=false) -%}
          
          {% for x in entities if x.state | int(100) <= min_battery_level %}
            {% set ns.found = true -%}
          {% endfor %}  
        
          {{ "mdi:battery-charging-10" if ns.found == True else "mdi:battery" }}

        value_template: >
          {% set entities = expand('group.batteriestand') %}
          {% set min_battery_level = states('input_number.batteriestand_warnlevel') | int(0) -%}
          {% set ns = namespace(found=false) -%}
          
          {% for x in entities if x.state | int(100) <= min_battery_level %}
            {% set ns.found = ns.found + 1 -%}
          {% endfor %}  
          
          {{ ns.found | int(0) }}