input_number:
  batteriestand_warnlevel:
    name: Warnlevel
    min: 10
    max: 80
    step: 5

sensor:
  - platform: attributes
    friendly_name: "Batteriestand"
    attribute: battery_level
    unit_of_measurement: "%"
    entities:
      - zigate.bewegungsmelder_flur_vorne
      - zigate.bewegungsmelder_flur_hinten
      - zigate.bewegungsmelder_arbeitszimmer
      - zigate.bewegungsmelder_sportzimmer
      - zigate.bewegungsmelder_schlafzimmer
      - zigate.bewegungsmelder_kueche
      - zigate.bewegungsmelder_bett
      - zigate.balkontuer
      - zigate.fenster_wohnzimmer
      - zigate.fenster_schlafzimmer
      - zigate.fenster_kueche
      - zigate.fenster_arbeitszimmer
      - zigate.fenster_sportzimmer     
      - zigate.thermometer_flur
      - zigate.thermometer_balkon
      - zigate.thermometer_schlafzimmer
      - zigate.thermometer_arbeitszimmer
      - zigate.thermometer_kueche
      - zigate.thermometer_sportzimmer
      - zigate.thermometer_parkplatz
      - zigate.thermometer_wohnzimmer_hardware
      - zigate.thermometer_arbeitszimmer_hardware
      - zigate.tuersensor      
      - zigate.bett
      - zigate.cube
      - zigate.schalter_wohnzimmer
      - zigate.schalter_schlafzimmer
      - zigate.schalter_flur
      - zigate.schalter_balkon
      - zigate.schalter_arbeitszimmer
      - zigate.schalter_badezimmer

  - platform: template
    sensors:
      batteriestand_niedrig:
        friendly_name: Batteriestand niedrig
        icon_template: >
          {% set entities = expand('group.batteriestand') %}
          {% set min_battery_level = states('input_number.batteriestand_warnlevel') | int -%}
          {% set ns = namespace(found=false) -%}
          
          {% for x in entities if x.state|int < min_battery_level %}
            {% set ns.found = true -%}
          {% endfor %}  
        
          {{ "mdi:battery-charging-10" if ns.found == True else "mdi:battery" }}

        value_template: >
          {% set entities = expand('group.batteriestand') %}
          {% set min_battery_level = states('input_number.batteriestand_warnlevel') | int -%}
          {% set ns = namespace(found=false) -%}
          
          {% for x in entities if x.state|int < min_battery_level %}
            {% set ns.found = ns.found + 1 -%}
          {% endfor %}  
          
          {{ ns.found | int }}
          
homeassistant:
  customize:
    sensor.tuersensor_battery_level:
      friendly_name: "Türsensor"
    sensor.bett_battery_level:
      friendly_name: "Bettsensor"
    sensor.cube_battery_level:
      friendly_name: "Cube"
    sensor.schalter_wohnzimmer_battery_level:
      friendly_name: "Schalter Wohnzimmer"
    sensor.schalter_flur_battery_level:
      friendly_name: "Schalter Flur"
    sensor.schalter_arbeitszimmer_battery_level:
      friendly_name: "Schalter Arbeitszimmer"      
    sensor.schalter_balkon_battery_level:
      friendly_name: "Schalter Balkon"
    sensor.schalter_schlafzimmer_battery_level:
      friendly_name: "Schalter Schlafzimmer"
    sensor.thermometer_flur_battery_level:
      friendly_name: "Thermometer Flur"
    sensor.thermometer_balkon_battery_level:
      friendly_name: "Thermometer Balkon"
    sensor.thermometer_parkplatz_battery_level:
      friendly_name: "Thermometer Parkplatz"
    sensor.thermometer_schlafzimmer_battery_level:
      friendly_name: "Thermometer Schlafzimmer"
    sensor.thermometer_arbeitszimmer_battery_level:
      friendly_name: "Thermometer Arbeitszimmer"
    sensor.thermometer_kueche_battery_level:
      friendly_name: "Thermometer Küche"
    sensor.thermometer_sportzimmer_battery_level:
      friendly_name: "Thermometer Sportzimmer"
    sensor.thermometer_wohnzimmer_hardware_battery_level:
      friendly_name: "Thermometer Wohnzimmer Hardware"
    sensor.thermometer_arbeitszimmer_hardware_battery_level:
      friendly_name: "Thermometer Arbeitszimmer Hardware"      
    sensor.balkontuer_battery_level:
      friendly_name: "Balkontür"
    sensor.fenster_wohnzimmer_battery_level:
      friendly_name: "Fenster Wohnzimmer"
    sensor.fenster_schlafzimmer_battery_level:
      friendly_name: "Fenster Schlafzimmer"
    sensor.fenster_kueche_battery_level:
      friendly_name: "Fenster Küche"
    sensor.fenster_arbeitszimmer_battery_level:
      friendly_name: "Fenster Arbeitszimmer"
    sensor.fenster_sportzimmer_battery_level:
      friendly_name: "Fenster Sportszimmer"
    sensor.bewegungsmelder_badezimmer_battery_level:
      friendly_name: "Bewegungsmelder Badezimmer"
    sensor.bewegungsmelder_flur_vorne_battery_level:
      friendly_name: "Bewegungsmelder Flur vorne"
    sensor.bewegungsmelder_flur_hinten_battery_level:
      friendly_name: "Bewegungsmelder Flur hinten"
    sensor.bewegungsmelder_arbeitszimmer_battery_level:
      friendly_name: "Bewegungsmelder Arbeitszimmer"
    sensor.bewegungsmelder_sportzimmer_battery_level:
      friendly_name: "Bewegungsmelder Sportzimmer"
    sensor.bewegungsmelder_schlafzimmer_battery_level:
      friendly_name: "Bewegungsmelder Schlafzimmer"
    sensor.bewegungsmelder_kueche_battery_level:
      friendly_name: "Bewegungsmelder Küche"
    sensor.bewegungsmelder_balkon_battery_level:
      friendly_name: "Bewegungsmelder Balkon"
    sensor.bewegungsmelder_wohnzimmer_battery_level:
      friendly_name: "Bewegungsmelder Wohnzimmer"
    sensor.ventilator_batterie:
      friendly_name: "Ventilator"
    sensor.xiaomi_vacuum_batterie:
      friendly_name: "Staubsauger"