input_number:
  batteriestand_warnlevel:
    name: Warnlevel
    min: 10
    max: 80
    step: 5

sensor:
  - platform: template
    sensors:
      batteriestand_niedrig:
        friendly_name: Batteriestand niedrig
        icon_template: >
          {% set entities = expand('group.batteriestand') %}
          {% set min_battery_level = states('input_number.batteriestand_warnlevel') | int -%}
          {% set ns = namespace(found=false) -%}
          
          {% for x in entities if x.state|int <= min_battery_level %}
            {% set ns.found = true -%}
          {% endfor %}  
        
          {{ "mdi:battery-charging-10" if ns.found == True else "mdi:battery" }}

        value_template: >
          {% set entities = expand('group.batteriestand') %}
          {% set min_battery_level = states('input_number.batteriestand_warnlevel') | int -%}
          {% set ns = namespace(found=false) -%}
          
          {% for x in entities if x.state|int <= min_battery_level %}
            {% set ns.found = ns.found + 1 -%}
          {% endfor %}  
          
          {{ ns.found | int }}          