input_number:
  batteriestand_warnlevel:
    name: Warnlevel
    min: 10
    max: 80
    step: 5

sensor:
  - platform: attributes
    friendly_name: "Batteriestand"
    attribute: battery_level
    unit_of_measurement: "%"
    entities:
      - zigate.bewegungsmelder_flur_vorne
      - zigate.bewegungsmelder_flur_hinten
      - zigate.bewegungsmelder_arbeitszimmer
      - zigate.bewegungsmelder_sportzimmer
      - zigate.bewegungsmelder_schlafzimmer
      - zigate.bewegungsmelder_kueche
      - zigate.bewegungsmelder_bett
      - zigate.balkontuer
      - zigate.fenster_wohnzimmer
      - zigate.fenster_schlafzimmer
      - zigate.fenster_kueche
      - zigate.fenster_arbeitszimmer
      - zigate.fenster_sportzimmer     
      - zigate.thermometer_flur
      - zigate.thermometer_balkon
      - zigate.thermometer_schlafzimmer
      - zigate.thermometer_arbeitszimmer
      - zigate.thermometer_kueche
      - zigate.thermometer_sportzimmer
      - zigate.thermometer_parkplatz
      - zigate.thermometer_wohnzimmer_hardware
      - zigate.tuersensor      
      - zigate.bett
      - zigate.cube
      - zigate.schalter_wohnzimmer
      - zigate.schalter_schlafzimmer
      - zigate.schalter_flur
      - zigate.schalter_balkon
      - zigate.schalter_arbeitszimmer
      - zigate.schalter_badezimmer

  - platform: template
    sensors:
      batteriestand_niedrig:
        friendly_name: Batteriestand niedrig
        icon_template: >
          {% set entities = expand('group.batteriestand') %}
          {% set min_battery_level = states('input_number.batteriestand_warnlevel') | int -%}
          {% set ns = namespace(found=false) -%}
          
          {% for x in entities if x.state|int < min_battery_level %}
            {% set ns.found = true -%}
          {% endfor %}  
        
          {{ "mdi:battery-charging-10" if ns.found == True else "mdi:battery" }}

        value_template: >
          {% set entities = expand('group.batteriestand') %}
          {% set min_battery_level = states('input_number.batteriestand_warnlevel') | int -%}
          {% set ns = namespace(found=false) -%}
          
          {% for x in entities if x.state|int < min_battery_level %}
            {% set ns.found = ns.found + 1 -%}
          {% endfor %}  
          
          {{ ns.found | int }}          