sensor:
  - platform: template
    sensors:
      letzte_bewegung:
        friendly_name: 'Letzte Bewegung'
        icon_template: mdi:run
        entity_id:
          - sensor.time
          - binary_sensor.bewegungsmelder_schlafzimmer
          - binary_sensor.bewegungsmelder_flur_vorne
          - binary_sensor.bewegungsmelder_flur_hinten
          - binary_sensor.bewegungsmelder_arbeitszimmer
          - binary_sensor.bewegungsmelder_kueche
          - binary_sensor.bewegungsmelder_balkon
          - binary_sensor.bewegungsmelder_wohnzimmer
          - binary_sensor.bewegungsmelder_badezimmer
        value_template: >
          {%- set pirs = [
            states.binary_sensor.bewegungsmelder_schlafzimmer,
            states.binary_sensor.bewegungsmelder_flur_vorne,
            states.binary_sensor.bewegungsmelder_flur_hinten,
            states.binary_sensor.bewegungsmelder_arbeitszimmer,
            states.binary_sensor.bewegungsmelder_kueche,
            states.binary_sensor.bewegungsmelder_balkon,
            states.binary_sensor.bewegungsmelder_wohnzimmer,
            states.binary_sensor.bewegungsmelder_badezimmer
            ] | reject('none') | list %}

          {% if pirs|length > 0 %}
            {% for pir in pirs %}
              {% if as_timestamp(pir.last_changed) == as_timestamp(pirs | map(attribute='last_changed') | max) %}
                {{ pir.name }}
              {% endif %}
            {% endfor %}
          {% else %}
            Unbekannt
          {% endif %}

      bewegungsmelder_flur_vorne_batterie:
        friendly_name: Bewegungsmelder Flur vorne
        entity_id:
          - zigate.bewegungsmelder_flur_vorne
        value_template: >-
          {% if is_state('zigate.bewegungsmelder_flur_vorne', 'unknown') %}
            0
          {% else %}
            {{ state_attr("zigate.bewegungsmelder_flur_vorne", "battery_level") | float }}
          {% endif %}
        unit_of_measurement: '%'
        device_class: battery

      bewegungsmelder_flur_hinten_batterie:
        friendly_name: Bewegungsmelder Flur hinten
        entity_id:
          - zigate.bewegungsmelder_flur_hinten
        value_template: >-
          {% if is_state('zigate.bewegungsmelder_flur_hinten', 'unknown') %}
            0
          {% else %}
            {{ state_attr("zigate.bewegungsmelder_flur_hinten", "battery_level") | float }}
          {% endif %}
        unit_of_measurement: '%'
        device_class: battery

      bewegungsmelder_arbeitszimmer_batterie:
        friendly_name: Bewegungsmelder Arbeitszimmer
        entity_id:
          - zigate.bewegungsmelder_arbeitszimmer
        value_template: >-
          {% if is_state('zigate.bewegungsmelder_arbeitszimmer', 'unknown') %}
            0
          {% else %}
            {{ state_attr("zigate.bewegungsmelder_arbeitszimmer", "battery_level") | float }}
          {% endif %}
        unit_of_measurement: '%'
        device_class: battery

      bewegungsmelder_schlafzimmer_batterie:
        friendly_name: Bewegungsmelder Schlafzimmer
        entity_id:
          - zigate.bewegungsmelder_schlafzimmer
        value_template: >-
          {% if is_state('zigate.bewegungsmelder_schlafzimmer', 'unknown') %}
            0
          {% else %}
            {{ state_attr("zigate.bewegungsmelder_schlafzimmer", "battery_level") | float }}
          {% endif %}
        unit_of_measurement: '%'
        device_class: battery

      bewegungsmelder_kueche_batterie:
        friendly_name: Bewegungsmelder Küche
        entity_id:
          - zigate.bewegungsmelder_kueche
        value_template: >-
          {% if is_state('zigate.bewegungsmelder_kueche', 'unknown') %}
            0
          {% else %}
            {{ state_attr("zigate.bewegungsmelder_kueche", "battery_level") | float }}
          {% endif %}
        unit_of_measurement: '%'
        device_class: battery

      bewegungsmelder_balkon_batterie:
        friendly_name: Bewegungsmelder Balkon
        entity_id:
          - zigate.bewegungsmelder_balkon
        value_template: >-
          {% if is_state('zigate.bewegungsmelder_balkon', 'unknown') %}
            0
          {% else %}
            {{ state_attr("zigate.bewegungsmelder_balkon", "battery_level") | float }}
          {% endif %}
        unit_of_measurement: '%'
        device_class: battery

      bewegungsmelder_badezimmer_batterie:
        friendly_name: Bewegungsmelder Badezimmer
        entity_id:
          - zwave.fibaro_badezimmer
        value_template: >
          {% if is_state('zwave.fibaro_badezimmer', 'unknown') %}
            0
          {% else %}
            {{ state_attr("zwave.fibaro_badezimmer", "battery_level") | float }}
          {% endif %}
        unit_of_measurement: '%'
        device_class: battery

binary_sensor:
  - platform: template
    sensors:
      bewegungsmelder_inaktiv_unterwegs:
        friendly_name: Unterwegs
        entity_id:
          - binary_sensor.zu_hause
        device_class: occupancy
        value_template: "{{ is_state('binary_sensor.zu_hause', 'off') }}"

      bewegungsmelder_wohnzimmer:
        friendly_name: Wohnzimmer
        entity_id:
          - sensor.aeotec_wohnzimmer_burglar
        device_class: motion
        value_template: "{{ is_state('sensor.aeotec_wohnzimmer_burglar', '8') }}"

      bewegungsmelder_badezimmer:
        friendly_name: Badezimmer
        entity_id:
          - sensor.fibaro_badezimmer_burglar
        device_class: motion
        value_template: "{{ is_state('sensor.fibaro_badezimmer_burglar', '8') }}"

entity_controller:
  radio_badezimmer:
    friendly_name: "Radio Badezimmer - Bewegung"
    sensor: binary_sensor.bewegungsmelder_badezimmer
    sensor_type_duration: True
    entity: switch.wiedergabe_badezimmer
    delay: 120
    overrides:
      - binary_sensor.radio_badezimmer_inaktiv

  bewegung_arbeitszimmer:
    friendly_name: "Bewegung Arbeitszimmer"
    sensor: binary_sensor.bewegungsmelder_arbeitszimmer
    entities:
      - light.schreibtisch
      - light.arbeitszimmer_lampe
    delay: 120
    overrides:
#      - binary_sensor.bewegungsmelder_inaktiv_unterwegs
      - binary_sensor.sonne_tagsueber
      - input_boolean.bewegungsmelder_arbeitszimmer_deaktiviert

  bewegung_badezimmer:
    friendly_name: "Bewegung Badezimmer"
    sensor: binary_sensor.bewegungsmelder_badezimmer
    entity: light.badezimmerschrank
    sensor_type_duration: True
    delay: 120
    service_data:
      brightness: 100
    overrides:
#      - binary_sensor.bewegungsmelder_inaktiv_unterwegs
      - binary_sensor.sonne_tagsueber
#      - input_boolean.bewegungsmelder_badezimmer_deaktiviert
    night_mode:
      delay: 120
      service_data:
        brightness: 80
      start_time: '23:00:00'
      end_time: '05:00:00'

  bewegung_balkon:
    friendly_name: "Bewegung Balkon"
    sensor: binary_sensor.bewegungsmelder_balkon
    entity: light.balkon_licht
    delay: 600
    overrides:
#      - binary_sensor.bewegungsmelder_inaktiv_unterwegs
      - binary_sensor.sonne_tagsueber
#      - input_boolean.bewegungsmelder_balkon_deaktiviert

  bewegung_flur_vorne:
    friendly_name: "Bewegung Flur vorne"
    sensor: binary_sensor.bewegungsmelder_flur_vorne
    entity: light.sideboard
    delay: 120
    service_data:
      brightness: 100
    overrides:
#      - binary_sensor.bewegungsmelder_inaktiv_unterwegs
      - binary_sensor.sonne_tagsueber
#      - input_boolean.bewegungsmelder_flur_deaktiviert
    night_mode:
      delay: 120
      service_data:
        brightness: 80
      start_time: '23:00:00'
      end_time: '05:00:00'

  bewegung_flur_hinten:
    friendly_name: "Bewegung Flur hinten"
    sensor: binary_sensor.bewegungsmelder_flur_hinten
    entity: light.schrank
    delay: 120
    service_data:
      brightness: 100
    overrides:
#      - binary_sensor.bewegungsmelder_inaktiv_unterwegs
      - binary_sensor.sonne_tagsueber
#      - input_boolean.bewegungsmelder_flur_deaktiviert
    night_mode:
      delay: 120
      service_data:
        brightness: 60
      start_time: '23:00:00'
      end_time: '05:00:00'

  bewegung_kueche:
    friendly_name: "Bewegung Küche"
    sensor: binary_sensor.bewegungsmelder_kueche
    entity: light.regal
    delay: 120
    service_data:
      brightness: 100
    overrides:
#      - binary_sensor.bewegungsmelder_inaktiv_unterwegs
      - binary_sensor.sonne_tagsueber
#      - input_boolean.bewegungsmelder_kueche_deaktiviert
    night_mode:
      delay: 120
      service_data:
        brightness: 70
      start_time: '23:00:00'
      end_time: '05:00:00'

  bewegung_schlafzimmer:
    friendly_name: "Bewegung Schlafzimmer"
    sensor: binary_sensor.bewegungsmelder_schlafzimmer
    entity: light.bett
    delay: 120
    service_data:
      brightness: 100
    overrides:
#      - binary_sensor.bewegungsmelder_inaktiv_unterwegs
      - binary_sensor.sonne_tagsueber
#      - input_boolean.bewegungsmelder_schlafzimmer_deaktiviert
    night_mode:
      delay: 120
      service_data:
        brightness: 60
      start_time: '23:00:00'
      end_time: '05:00:00'

  bewegung_wohnzimmer:
    friendly_name: "Bewegung Wohnzimmer"
    sensor: binary_sensor.bewegungsmelder_wohnzimmer
    entities:
      - light.couch
      - light.strahler
    delay: 60
    overrides:
#      - binary_sensor.bewegungsmelder_inaktiv_unterwegs
      - binary_sensor.sonne_tagsueber
#      - input_boolean.bewegungsmelder_wohnzimmesr_deaktiviert
      - switch.computer