input_select:
  letzte_bewegung:
    name: Letzte Bewegung
    options:
      - 'Wohnzimmer'
      - 'Arbeitszimmer'
      - 'Sportzimmer'
      - 'Badezimmer'
      - 'Balkon'
      - 'Flur hinten'
      - 'Flur vorne'
      - 'Küche'
      - 'Schlafzimmer'

sensor:
  - platform: template
    sensors:
      letzte_bewegung:
        friendly_name: 'Letzte Bewegung'
        icon_template: mdi:run
        entity_id:
          - input_select.letzte_bewegung
        value_template: >-
          {{ states('input_select.letzte_bewegung') }}

binary_sensor:
  - platform: template
    sensors:
      bewegungsmelder_aktiv:
        friendly_name: Bewegungsmelder aktiv
        entity_id:
          - entity_controller.bewegung_arbeitszimmer
          - entity_controller.bewegung_badezimmer
          - entity_controller.bewegung_balkon
          - entity_controller.bewegung_flur_hinten
          - entity_controller.bewegung_flur_vorne
          - entity_controller.bewegung_kuchenregal
          - entity_controller.bewegung_kuchenschrank
          - entity_controller.bewegung_schlafzimmer_bett
          - entity_controller.bewegung_schlafzimmer_kleiderschrank
          - entity_controller.bewegung_sportzimmer
        device_class: motion
        value_template: >
          {% set ns = namespace(found=false) -%}
          
          {% for entity_id in state_attr('group.entity_controller', 'entity_id') -%}
            {% set parts = entity_id.split('.') -%}
            {% if (states(entity_id)) == 'active_timer' -%}
              {% set ns.found = true -%}
            {% endif -%}
          {% endfor -%}
          
          {{ ns.found }}
        
      bewegungsmelder_inaktiv_unterwegs:
        friendly_name: Bewegungmelder inaktiv - Unterwegs
        entity_id:
          - sensor.time
          - binary_sensor.zu_hause
        device_class: occupancy
        value_template: >-
          {% if is_state('binary_sensor.zu_hause', 'off') %}
            True
          {% else %}
            False
          {% endif %}

      bewegungsmelder_inaktiv_staubsauger:
        friendly_name: Bewegungmelder inaktiv - Staubsauger
        entity_id:
          - sensor.time
          - vacuum.xiaomi_vacuum_cleaner
        device_class: occupancy
        value_template: >-
          {% if is_state('vacuum.xiaomi_vacuum_cleaner', 'cleaning') or is_state('vacuum.xiaomi_vacuum_cleaner', 'returning') %}
            True
          {% else %}
            False
          {% endif %}
          
      bewegungsmelder_wohnzimmer:
        friendly_name: Wohnzimmer
        entity_id:
          - sensor.aeotec_wohnzimmer_burglar
        device_class: motion
        value_template: "{{ is_state('sensor.aeotec_wohnzimmer_burglar', '8') }}"

      bewegungsmelder_badezimmer:
        friendly_name: Badezimmer
        entity_id:
          - sensor.fibaro_badezimmer_burglar
        device_class: motion
        value_template: "{{ is_state('sensor.fibaro_badezimmer_burglar', '8') }}"   

entity_controller:
  radio_badezimmer:
    friendly_name: "Radio Badezimmer - Bewegung"
    sensor: binary_sensor.bewegungsmelder_badezimmer
    sensor_type_duration: True
    entity: switch.wiedergabe_badezimmer
    delay: 120
    overrides:
      - binary_sensor.radio_badezimmer_inaktiv

  bewegung_arbeitszimmer:
    friendly_name: "Bewegung Arbeitszimmer"
    sensor: binary_sensor.bewegungsmelder_arbeitszimmer
    entities:
      - light.schreibtisch
      - light.arbeitszimmer_lampe
    delay: 120
    overrides:
      - binary_sensor.sonne_tagsueber
      - binary_sensor.bewegungsmelder_inaktiv_unterwegs  
      - binary_sensor.bewegungsmelder_inaktiv_staubsauger
      - input_boolean.bewegungsmelder_arbeitszimmer_deaktiviert

  bewegung_sportzimmer:
    friendly_name: "Bewegung Sportzimmer"
    sensor: binary_sensor.bewegungsmelder_sportzimmer
    entities:      
      - light.sportzimmer_regal
    delay: 120
    overrides:
      - binary_sensor.sonne_tagsueber
      - binary_sensor.bewegungsmelder_inaktiv_unterwegs  
      - binary_sensor.bewegungsmelder_inaktiv_staubsauger
      - input_boolean.bewegungsmelder_sportzimmer_deaktiviert
      
  bewegung_badezimmer:
    friendly_name: "Bewegung Badezimmer"
    sensor: binary_sensor.bewegungsmelder_badezimmer
    entity: light.badezimmerschrank
    sensor_type_duration: True
    delay: 120
    service_data:
      brightness: 100
    night_mode:
      delay: 120
      service_data:
        brightness: 80
      start_time: '23:00:00'
      end_time: '05:00:00'      
    overrides:
      - binary_sensor.sonne_tagsueber
      - binary_sensor.bewegungsmelder_inaktiv_unterwegs      
      - binary_sensor.bewegungsmelder_inaktiv_staubsauger
      - input_boolean.bewegungsmelder_badezimmer_deaktiviert
      
  bewegung_balkon:
    friendly_name: "Bewegung Balkon"
    sensor: binary_sensor.bewegungsmelder_balkon
    entity: light.balkon_licht
    delay: 1200
    overrides:  
      - binary_sensor.sonne_tagsueber
      - binary_sensor.bewegungsmelder_inaktiv_unterwegs
      - binary_sensor.bewegungsmelder_inaktiv_staubsauger
      - input_boolean.bewegungsmelder_balkon_deaktiviert

  bewegung_flur_vorne:
    friendly_name: "Bewegung Flur vorne"
    sensor: binary_sensor.bewegungsmelder_flur_vorne
    entity: light.sideboard
    delay: 120
    service_data:
      brightness: 100
    night_mode:
      delay: 120
      service_data:
        brightness: 80
      start_time: '23:00:00'
      end_time: '05:00:00'      
    overrides:
      - binary_sensor.sonne_tagsueber
      - binary_sensor.bewegungsmelder_inaktiv_unterwegs
      - binary_sensor.bewegungsmelder_inaktiv_staubsauger
      - input_boolean.bewegungsmelder_flur_deaktiviert

  bewegung_flur_hinten:
    friendly_name: "Bewegung Flur hinten"
    sensor: binary_sensor.bewegungsmelder_flur_hinten
    entity: light.schrank
    delay: 120
    service_data:
      brightness: 100
    night_mode:
      delay: 120
      service_data:
        brightness: 60
      start_time: '23:00:00'
      end_time: '05:00:00'      
    overrides:
      - binary_sensor.sonne_tagsueber
      - binary_sensor.bewegungsmelder_inaktiv_unterwegs
      - binary_sensor.bewegungsmelder_inaktiv_staubsauger
      - input_boolean.bewegungsmelder_flur_deaktiviert

  bewegung_kuechenregal:
    friendly_name: "Bewegung Küchenregal"
    sensor: binary_sensor.bewegungsmelder_kueche
    entity: light.kuche_regal
    delay: 120
    service_data:
      brightness: 100
    night_mode:
      delay: 120
      service_data:
        brightness: 70
      start_time: '23:00:00'
      end_time: '05:00:00'      
    overrides:
      - binary_sensor.sonne_tagsueber
      - binary_sensor.kuechelregal_inaktiv
      - binary_sensor.bewegungsmelder_inaktiv_unterwegs
      - binary_sensor.bewegungsmelder_inaktiv_staubsauger
      - input_boolean.bewegungsmelder_kueche_deaktiviert

  bewegung_kuechenschrank:
    friendly_name: "Bewegung Küchenschrank"
    sensor: binary_sensor.bewegungsmelder_kueche
    entity: light.kuche_schrank
    delay: 120    
    overrides:            
      - binary_sensor.sonne_tagsueber
      - binary_sensor.kuechenschrank_inaktiv
      - binary_sensor.bewegungsmelder_inaktiv_unterwegs
      - binary_sensor.bewegungsmelder_inaktiv_staubsauger
      - input_boolean.bewegungsmelder_kueche_deaktiviert
      
  bewegung_schlafzimmer_bett:
    friendly_name: "Bewegung Schlafzimmer Bett"
    sensor: binary_sensor.bewegungsmelder_schlafzimmer
    entity: light.bett
    delay: 120
    service_data:
      brightness: 100
    night_mode:
      delay: 120
      service_data:
        brightness: 60
      start_time: '23:00:00'
      end_time: '05:00:00'      
    overrides:
      - binary_sensor.sonne_tagsueber
      - light.kleiderschrank
      - binary_sensor.bewegungsmelder_inaktiv_unterwegs
      - binary_sensor.bewegungsmelder_inaktiv_staubsauger
      - input_boolean.bewegungsmelder_schlafzimmer_deaktiviert

  bewegung_schlafzimmer_kleiderschrank:
    friendly_name: "Bewegung Schlafzimmer Kleiderschrank"
    sensor: binary_sensor.bewegungsmelder_schlafzimmer
    entity: light.kleiderschrank
    delay: 120  
    overrides:
      - binary_sensor.schlafen_aktiv
      - binary_sensor.sonne_tagsueber
      - binary_sensor.fenster_schlafzimmer
      - binary_sensor.bewegungsmelder_inaktiv_unterwegs
      - binary_sensor.bewegungsmelder_inaktiv_staubsauger
      - input_boolean.bewegungsmelder_schlafzimmer_deaktiviert      

  bewegung_wohnzimmer:
    friendly_name: "Bewegung Wohnzimmer"
    sensor: binary_sensor.bewegungsmelder_wohnzimmer
    entities:
      - light.couch
    delay: 60
    overrides:
      - binary_sensor.sonne_tagsueber
      - binary_sensor.bewegungsmelder_inaktiv_unterwegs
      - binary_sensor.bewegungsmelder_inaktiv_staubsauger
      - input_boolean.bewegungsmelder_wohnzimmer_deaktiviert
      - switch.computer     

automation:
  - alias: 'Letzte Bewegung'
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.bewegungsmelder_schlafzimmer
          - binary_sensor.bewegungsmelder_flur_vorne
          - binary_sensor.bewegungsmelder_flur_hinten
          - binary_sensor.bewegungsmelder_arbeitszimmer
          - binary_sensor.bewegungsmelder_sportzimmer
          - binary_sensor.bewegungsmelder_kueche
          - binary_sensor.bewegungsmelder_balkon
          - binary_sensor.bewegungsmelder_wohnzimmer
          - binary_sensor.bewegungsmelder_badezimmer
        from: 'off'
        to: 'on'
    action:
      - service: input_select.select_option
        data_template:
          entity_id: input_select.letzte_bewegung          
          option: '{{ trigger.to_state.attributes.friendly_name }}'
          
  - alias: 'Sonne scheint - Licht ausschalten'
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.sonne_tagsueber
        to: 'on'
    condition:
      - condition: state
        entity_id: binary_sensor.bewegungsmelder_aktiv
        state: 'on'      
    action:
      - service: light.turn_off
        entity_id:
          - light.schreibtisch
          - light.arbeitszimmer_lampe    
          - light.badezimmerschrank
          - light.balkon_licht
          - light.sideboard
          - light.schrank
          - light.kuche_regal
          - light.kuche_schrank
          - light.bett
          - light.kleiderschrank
          - light.couch
          
  - alias: 'Fenster Schlafzimmer - Licht ausschalten'
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.fenster_schlafzimmer
        to: 'on'
    condition:
      - condition: state
        entity_id: light.kleiderschrank
        state: 'on'      
    action:
      - service: light.turn_off
        entity_id:
          - light.kleiderschrank          