template:
  - trigger:
      - platform: state
        entity_id:
          - binary_sensor.bewegungsmelder_arbeitszimmer
          - binary_sensor.bewegungsmelder_badezimmer
          - binary_sensor.bewegungsmelder_balkon
          - binary_sensor.bewegungsmelder_flur_hinten
          - binary_sensor.bewegungsmelder_flur_vorne
          - binary_sensor.bewegungsmelder_kueche
          - binary_sensor.bewegungsmelder_schlafzimmer
          - binary_sensor.bewegungsmelder_sportzimmer
          - binary_sensor.bewegungsmelder_wohnzimmer
          - binary_sensor.bewegungsmelder_bett
        from: 'off'
        to: 'on'
    sensor:      
      - name: Letzte Bewegung
        icon: mdi:run
        state: "{{ trigger.to_state.attributes.friendly_name }}"          
        
automation:
  - alias: "Bewegungsmelder zurücksetzen"
    id: "bewegungsmelder_zuruecksetzen"
    mode: parallel
    max: 10    
    trigger:
      - platform: state
        entity_id: binary_sensor.bewegungsmelder_arbeitszimmer
      - platform: state
        entity_id: binary_sensor.bewegungsmelder_flur_vorne
      - platform: state
        entity_id: binary_sensor.bewegungsmelder_flur_hinten
      - platform: state
        entity_id: binary_sensor.bewegungsmelder_kueche
      - platform: state
        entity_id: binary_sensor.bewegungsmelder_sportzimmer    
      - platform: state
        entity_id: binary_sensor.bewegungsmelder_schlafzimmer    
      - platform: state
        entity_id: binary_sensor.bewegungsmelder_bett        
    condition:
      - condition: template
        value_template: '{{ trigger.to_state.state == "on" }}'
    action:
      - delay:
          seconds: 5
      - service: zha.set_zigbee_cluster_attribute
        data:
          ieee: '{{ device_attr(trigger.entity_id, "identifiers") | first | last }}'
          endpoint_id: 1
          cluster_id: 1280
          attribute: 2
          value: '0'