input_select:
  letzte_bewegung:
    name: Letzte Bewegung
    options:
      - Arbeitszimmer
      - Badezimmer
      - Balkon
      - Flur hinten
      - Flur vorne
      - Küche
      - Schlafzimmer
      - Sportzimmer
      - Wohnzimmer

sensor:
  - platform: template
    sensors:
      letzte_bewegung:
        friendly_name: "Letzte Bewegung"
        icon_template: mdi:run
        value_template: "{{ states('input_select.letzte_bewegung') }}"  

binary_sensor:
  - platform: template
    sensors:             
      bewegungsmelder_inaktiv_unterwegs:
        friendly_name: "Bewegungmelder inaktiv - Unterwegs"
        device_class: occupancy
        value_template: "{{ True if is_state('binary_sensor.zu_hause', 'off') else False }}"

      bewegungsmelder_inaktiv_staubsauger:
        friendly_name: "Bewegungmelder inaktiv - Staubsauger"
        device_class: occupancy
        value_template: "{{ True if is_state('vacuum.roborock_vacuum', 'cleaning') or is_state('vacuum.roborock_vacuum', 'returning') else False }}"
        
automation:
  - alias: 'Letzte Bewegung'
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.bewegungsmelder_arbeitszimmer
          - binary_sensor.bewegungsmelder_badezimmer
          - binary_sensor.bewegungsmelder_balkon
          - binary_sensor.bewegungsmelder_flur_hinten
          - binary_sensor.bewegungsmelder_flur_vorne
          - binary_sensor.bewegungsmelder_kueche
          - binary_sensor.bewegungsmelder_schlafzimmer
          - binary_sensor.bewegungsmelder_sportzimmer
          - binary_sensor.bewegungsmelder_wohnzimmer
        from: 'off'
        to: 'on'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.letzte_bewegung
          option: '{{ trigger.to_state.attributes.friendly_name }}'
        