sensor:
  - platform: template
    sensors:
      letzte_bewegung:
        friendly_name: "Letzte Bewegung"
        icon_template: mdi:run
        value_template: >-
         {% set motionSensors = expand('group.bewegungsmelder') %}
         {% set lastMotion = motionSensors | selectattr('last_changed','==', motionSensors | map(attribute='last_changed') | max) | first %}

         {{ lastMotion.name }}        

binary_sensor:
  - platform: template
    sensors:             
      bewegungsmelder_inaktiv_unterwegs:
        friendly_name: "Bewegungmelder inaktiv - Unterwegs"
        device_class: occupancy
        value_template: "{{ True if is_state('binary_sensor.zu_hause', 'off') else False }}"

      bewegungsmelder_inaktiv_staubsauger:
        friendly_name: "Bewegungmelder inaktiv - Staubsauger"
        device_class: occupancy
        value_template: "{{ True if is_state('vacuum.roborock_vacuum', 'cleaning') or is_state('vacuum.roborock_vacuum', 'returning') else False }}"