sensor:
  - platform: template
    sensors:
      letzte_bewegung:
        friendly_name: 'Letzte Bewegung'
        icon_template: mdi:run
        entity_id:
          - sensor.time
          - binary_sensor.bewegungsmelder_schlafzimmer
          - binary_sensor.bewegungsmelder_flur
          - binary_sensor.bewegungsmelder_arbeitszimmer
          - binary_sensor.bewegungsmelder_kueche
          - binary_sensor.bewegungsmelder_balkon
          - binary_sensor.bewegungsmelder_wohnzimmer_template
          - binary_sensor.bewegungsmelder_badezimmer_template
        value_template: >
          {%- set pirs = [
            states.binary_sensor.bewegungsmelder_schlafzimmer,
            states.binary_sensor.bewegungsmelder_flur,
            states.binary_sensor.bewegungsmelder_arbeitszimmer,
            states.binary_sensor.bewegungsmelder_kueche,
            states.binary_sensor.bewegungsmelder_balkon,
            states.binary_sensor.bewegungsmelder_wohnzimmer_template,
            states.binary_sensor.bewegungsmelder_badezimmer_template
            ] | reject('none') | list %}

          {% if pirs|length > 0 %}
            {% for pir in pirs %}
              {% if as_timestamp(pir.last_changed) == as_timestamp(pirs | map(attribute='last_changed') | max) %}
                {{ pir.name }}
              {% endif %}
            {% endfor %}
          {% else %}
            Unbekannt
          {% endif %}

      xiaomi_bewegungsmelder_flur_batterie:
        friendly_name: Bewegungsmelder Flur
        entity_id:
          - binary_sensor.zigate_7904_presence
        value_template: >-
          {% if is_state('binary_sensor.zigate_7904_presence', 'unknown') %}
            0
          {% else %}
            {{ states.binary_sensor.zigate_7904_presence.attributes["battery_level"] | float}}
          {% endif %}
        unit_of_measurement: '%'
        device_class: battery

      xiaomi_bewegungsmelder_arbeitszimmer_batterie:
        friendly_name: Bewegungsmelder Arbeitszimmer
        entity_id:
          - binary_sensor.zigate_eac1_presence
        value_template: >
          {% if is_state('binary_sensor.zigate_eac1_presence', 'unknown') %}
            0
          {% else %}
            {{ states.binary_sensor.zigate_eac1_presence.attributes["battery_level"] | float}}
          {% endif %}
        unit_of_measurement: '%'
        device_class: battery

      xiaomi_bewegungsmelder_schlafzimmer_batterie:
        friendly_name: Bewegungsmelder Schlafzimmer
        entity_id:
          - binary_sensor.zigate_be83_presence
        value_template: >
          {% if is_state('binary_sensor.zigate_be83_presence', 'unknown') %}
            0
          {% else %}
            {{ states.binary_sensor.zigate_be83_presence.attributes["battery_level"] | float}}
          {% endif %}
        unit_of_measurement: '%'
        device_class: battery

      xiaomi_bewegungsmelder_kueche_batterie:
        friendly_name: Bewegungsmelder Küche
        entity_id:
          - binary_sensor.zigate_a230_presence
        value_template: >
          {% if is_state('binary_sensor.zigate_a230_presence', 'unknown') %}
            0
          {% else %}
            {{ states.binary_sensor.zigate_a230_presence.attributes["battery_level"] | float}}
          {% endif %}
        unit_of_measurement: '%'
        device_class: battery

      xiaomi_bewegungsmelder_balkon_batterie:
        friendly_name: Bewegungsmelder Balkon
        entity_id:
          - binary_sensor.zigate_0b57_presence
        value_template: >
          {% if is_state('binary_sensor.zigate_0b57_presence', 'unknown') %}
            0
          {% else %}
            {{ states.binary_sensor.zigate_0b57_presence.attributes["battery_level"] | float}}
          {% endif %}
        unit_of_measurement: '%'
        device_class: battery

      fibaro_bewegungsmelder_badezimmer_batterie:
        friendly_name: Bewegungsmelder Badezimmer
        entity_id:
          - zwave.fibaro_badezimmer
        value_template: >
          {% if states.zwave.fibaro_badezimmer and states.zwave.fibaro_badezimmer.attributes['battery_level'] %}
            {{ states.zwave.fibaro_badezimmer.attributes['battery_level'] | float}}
          {% else %}
            0
          {% endif %}
        unit_of_measurement: '%'
        device_class: battery

binary_sensor:
  - platform: template
    sensors:
      bewegungsmelder_inaktiv_unterwegs:
        friendly_name: Unterwegs
        entity_id:
          - binary_sensor.zu_hause
        device_class: occupancy
        value_template: "{{ is_state('binary_sensor.zu_hause', 'off') }}"

      bewegungsmelder_flur:
        friendly_name: Flur
        entity_id:
          - binary_sensor.zigate_7904_presence
        device_class: motion
        value_template: "{{ is_state('binary_sensor.zigate_7904_presence', 'on') }}"

      bewegungsmelder_arbeitszimmer:
        friendly_name: Arbeitszimmer
        entity_id:
          - binary_sensor.zigate_eac1_presence
        device_class: motion
        value_template: "{{ is_state('binary_sensor.zigate_eac1_presence', 'on') }}"

      bewegungsmelder_schlafzimmer:
        friendly_name: Schlafzimmer
        entity_id:
          - binary_sensor.zigate_be83_presence
        device_class: motion
        value_template: "{{ is_state('binary_sensor.zigate_be83_presence', 'on') }}"

      bewegungsmelder_kueche:
        friendly_name: Küche
        entity_id:
          - binary_sensor.zigate_a230_presence
        device_class: motion
        value_template: "{{ is_state('binary_sensor.zigate_a230_presence', 'on') }}"

      bewegungsmelder_balkon:
        friendly_name: Balkon
        entity_id:
          - binary_sensor.zigate_0b57_presence
        device_class: motion
        value_template: "{{ is_state('binary_sensor.zigate_0b57_presence', 'on') }}"

      bewegungsmelder_wohnzimmer:
        friendly_name: Bewegungsmelder
        entity_id:
          - sensor.aeotec_wohnzimmer_burglar
        device_class: motion
        value_template: "{{ is_state('sensor.aeotec_wohnzimmer_burglar', '8') }}"
      bewegungsmelder_wohnzimmer_template:
        friendly_name: Wohnzimmer
        entity_id:
          - sensor.aeotec_wohnzimmer_burglar
        device_class: motion
        value_template: "{{ is_state('sensor.aeotec_wohnzimmer_burglar', '8') }}"

      bewegungsmelder_badezimmer:
        friendly_name: Bewegungsmelder
        entity_id:
          - sensor.fibaro_badezimmer_burglar
        device_class: motion
        value_template: "{{ is_state('sensor.fibaro_badezimmer_burglar', '8') }}"
      bewegungsmelder_badezimmer_template:
        friendly_name: Badezimmer
        entity_id:
          - sensor.fibaro_badezimmer_burglar
        device_class: motion
        value_template: "{{ is_state('sensor.fibaro_badezimmer_burglar', '8') }}"

entity_controller:
  radio_badezimmer:
    friendly_name: "Radio Badezimmer - Bewegung"
    sensor: binary_sensor.bewegungsmelder_badezimmer
    sensor_type_duration: True
    entity: switch.wiedergabe_badezimmer
    delay: 120
    overrides:
      - binary_sensor.radio_badezimmer_inaktiv

  bewegung_arbeitszimmer:
    friendly_name: "Bewegung Arbeitszimmer"
    sensor: binary_sensor.zigate_eac1_presence
    entities:
      - light.schreibtisch
      - light.arbeitszimmer_lampe
    delay: 120
    overrides:
      - binary_sensor.bewegungsmelder_inaktiv_unterwegs
      - binary_sensor.sonne_tagsueber
      - input_boolean.bewegungsmelder_arbeitszimmer_deaktiviert

  bewegung_badezimmer:
    friendly_name: "Bewegung Badezimmer"
    sensor: binary_sensor.bewegungsmelder_badezimmer
    entity: light.badezimmerschrank
    sensor_type_duration: True
    delay: 120
    overrides:
      - binary_sensor.bewegungsmelder_inaktiv_unterwegs
      - binary_sensor.sonne_tagsueber
      - input_boolean.bewegungsmelder_badezimmer_deaktiviert

  bewegung_balkon:
    friendly_name: "Bewegung Balkon"
    sensor: binary_sensor.zigate_0b57_presence
    entity: light.balkon_licht
    delay: 600
    overrides:
      - binary_sensor.bewegungsmelder_inaktiv_unterwegs
      - binary_sensor.sonne_tagsueber
      - input_boolean.bewegungsmelder_balkon_deaktiviert

  bewegung_flur_vorne:
    friendly_name: "Bewegung Flur vorne"
    sensor: binary_sensor.zigate_7904_presence
    entity: light.sideboard
    delay: 120
    overrides:
      - binary_sensor.bewegungsmelder_inaktiv_unterwegs
      - binary_sensor.sonne_tagsueber
      - input_boolean.bewegungsmelder_flur_deaktiviert

  bewegung_kueche:
    friendly_name: "Bewegung Küche"
    sensor: binary_sensor.zigate_a230_presence
    entity: light.regal
    delay: 120
    overrides:
      - binary_sensor.bewegungsmelder_inaktiv_unterwegs
      - binary_sensor.sonne_tagsueber
      - input_boolean.bewegungsmelder_kueche_deaktiviert

  bewegung_schlafzimmer:
    friendly_name: "Bewegung Schlafzimmer"
    sensor: binary_sensor.zigate_be83_presence
    entity: light.bett
    delay: 60
    overrides:
      - binary_sensor.bewegungsmelder_inaktiv_unterwegs
      - binary_sensor.sonne_tagsueber
      - input_boolean.bewegungsmelder_schlafzimmer_deaktiviert

  bewegung_wohnzimmer:
    friendly_name: "Bewegung Wohnzimmer"
    sensor: binary_sensor.bewegungsmelder_wohnzimmer
    entities:
      - light.couch
      - light.strahler
    delay: 60
    overrides:
      - binary_sensor.bewegungsmelder_inaktiv_unterwegs
      - binary_sensor.sonne_tagsueber
      - input_boolean.bewegungsmelder_wohnzimmer_deaktiviert
      - switch.computer

homeassistant:
  customize:
    binary_sensor.bewegungsmelder_flur:
      hidden: true
    binary_sensor.bewegungsmelder_arbeitszimmer:
      hidden: true
    binary_sensor.bewegungsmelder_schlafzimmer:
      hidden: true
    binary_sensor.bewegungsmelder_kueche:
      hidden: true
    binary_sensor.bewegungsmelder_balkon:
      hidden: true

    binary_sensor.bewegungsmelder_badezimmer_template:
      hidden: true
    binary_sensor.bewegungsmelder_wohnzimmer_template:
      hidden: true