input_boolean:
  computer_ausschalten:
    name: Computer ausschalten
    initial: on
    icon: mdi:desktop-classic

device_tracker:
  - platform: mqtt
    devices:
      pc: 'iotlink/workgroup/computer/lwt'
    qos: 1
    payload_home: 'ON'
    payload_not_home: 'OFF'
    source_type: router

switch:
  - platform: template
    switches:
      pc:
        friendly_name: PC
        entity_id:
          - device_tracker.pc
        value_template: "{{ is_state('device_tracker.pc', 'home') }}"
        turn_on:
          service: wake_on_lan.send_magic_packet
          data:
            mac: !secret computer_mac
            broadcast_address: !secret fritzbox_broadcast
        turn_off:
          service: mqtt.publish
          data:
            topic: "iotlink/workgroup/computer/commands/hibernate"
            payload: ""
      computer:
        friendly_name: Computer
        entity_id:
          - device_tracker.pc
        value_template: >-
          {{ is_state('switch.pc', 'on') and is_state('switch.monitor', 'on') }}
        turn_on:
          service: switch.turn_on
          entity_id: switch.monitor, switch.pc
        turn_off:
          service: switch.turn_off
          entity_id: switch.monitor, switch.pc

automation:
  - alias: 'Unterwegs - Computer ausschalten'
    trigger:
      - platform: state
        entity_id: binary_sensor.zu_hause
        to: 'off'
        for:
          minutes: 30
    condition:
      - condition: state
        entity_id: switch.computer
        state: 'on'
      - condition: state
        entity_id: input_boolean.computer_ausschalten
        state: 'on'
    action:
      - service: switch.turn_off
        entity_id: switch.computer
      - service: notify.telegram
        data_template:
          title: "Computer eingeschaltet"
          message: "Der Computer war noch eingeschaltet und wird jetzt heruntergefahren."

  - alias: 'Telegram - Computer ausschalten'
    trigger:
      - platform: event
        event_type: telegram_callback
        event_data:
          data: '/computer_ausschalten'
    action:
      - service: switch.turn_off
        entity_id: switch.computer
      - service: telegram_bot.send_message
        data_template:
          target: '{{ trigger.event.data.chat_id }}'
          message: "Der Computer wird ausgeschaltet."
          
homeassistant:
  customize:
    switch.computer:
      icon: mdi:desktop-classic
    switch.pc:
      friendly_name: PC
      icon: mdi:desktop-tower

    binary_sensor.computer_status:
      friendly_name: Computer