input_select:
  computer_ausschalten:
    name: Computer ausschalten
    icon: mdi:power-settings
    options:      
      - Ruhezustand
      - Herunterfahren
      - Nichts unternehmen
      
sensor:   
  - platform: openhardwaremonitor
    host: !secret computer_host
    port: 8580  

switch:
  - platform: template
    switches:
      computer:
        friendly_name: Computer
        value_template: "{{ is_state('binary_sensor.computer_ping', 'on') }}"
        icon_template: mdi:desktop-classic
        turn_on:
          - service: wake_on_lan.send_magic_packet
            data:
              mac: !secret computer_mac
              broadcast_address: !secret fritzbox_broadcast
              broadcast_port: 9
        turn_off:
          - choose:
              - conditions:
                  - "{{ is_state('input_select.computer_ausschalten', 'Ruhezustand') }}"
                sequence:
                  - service: button.press
                    entity_id: button.computer_ruhezustand                  
              - conditions:
                  - "{{ is_state('input_select.computer_ausschalten', 'Herunterfahren') }}"
                sequence:
                  - service: button.press
                    entity_id: button.computer_herunterfahren
    
automation:
  - alias: "Monitore ausschalten"
    id: "monitore_ausschalten"
    trigger:
      - platform: state
        entity_id: switch.computer
        to: 'off'
        for:
          minutes: 10
      - platform: state
        entity_id: switch.computer_arbeit
        to: 'off'
        for:
          minutes: 10          
    condition:
      - "{{ is_state('switch.monitore', 'on') }}"
      - "{{ is_state('switch.computer', 'off') }}"
      - "{{ is_state('switch.computer_arbeit', 'off') }}"
    action:
      - service: switch.turn_off
        entity_id: switch.monitore      

  - alias: "Computer inaktiv"
    id: "computer_inaktiv"
    trigger:
      - platform: template
        value_template: >-
          {% set letzteAktivitaet = as_timestamp(states('sensor.computer_zuletzt_aktiv'), 0) | int(0) %}
          {% set jetzt = now().timestamp() | int(0) %}
          
          {{ letzteAktivitaet > 0 and (jetzt - letzteAktivitaet) > 1800 }}
    condition:
      - condition: state
        entity_id: switch.computer
        state: 'on'
        for:
          minutes: 10
      - "{{ not is_state('input_select.computer_ausschalten', 'Nichts unternehmen') }}"
    action:      
      - service: switch.turn_off
        entity_id: switch.computer
      - if: "{{ is_state('binary_sensor.home_office_aktiv', 'off') }}"
        then:
          - service: switch.turn_off
            entity_id: switch.monitore                
     
  - alias: "Computer einschalten"
    id: "computer_einschalten"
    trigger:
      - platform: event
        event_type: zha_event
        event_data:
          device_ieee: 54:ef:44:10:00:e8:72:44
          command: 1_single
          args:
            click_type: single         
#      - platform: event
#        event_type: zha_event
#        event_data:
#          device_ieee: 00:15:8d:00:02:13:45:68
#          command: attribute_updated
#          args:
#            attribute_id: 0
#            attribute_name: on_off     
#            value: 1            
    condition:       
      - "{{ is_state('binary_sensor.home_office_aktiv', 'off') }}"
      - "{{ is_state('switch.computer', 'off') }}"
    action:
      - service: switch.turn_on
        entity_id: switch.computer, switch.monitore 
            
  - alias: "Unterwegs - Computer ausschalten"
    id: "unterwegs_computer_ausschalten"
    trigger:
      - platform: state
        entity_id: person.dennis
        to: 'not_home'
        for:
          minutes: 30
    condition:
      - "{{ is_state('switch.computer', 'on') }}"
      - "{{ not is_state('input_select.computer_ausschalten', 'Nichts unternehmen') }}"
      - "{{ not is_state('alarm_control_panel.alarmo', 'disarmed') }}"      
    action:
      - service: switch.turn_off
        entity_id: switch.computer
      - service: notify.telegram
        data:          
          message: "Der Computer war noch eingeschaltet und wird jetzt heruntergefahren."

  - alias: "Telegram - Computer ausschalten"
    id: "telegram_computer_ausschalten"
    trigger:
      - platform: event
        event_type: telegram_command
        event_data:
          command: '/computer_ausschalten'
    action:
      - service: switch.turn_off
        entity_id: switch.computer
      - service: telegram_bot.send_message
        data:
          target: '{{ trigger.event.data.chat_id }}'
          message: "Der Computer wird ausgeschaltet."
          
homeassistant:
  customize:      
    sensor.computer_generic_hard_disk_load_used_space:
      friendly_name: SSD Speicherplatz
      icon: mdi:nas
    sensor.computer_generic_memory_data_available_memory:
      friendly_name: Arbeitsspeicher verfügbar
    sensor.computer_generic_memory_data_used_memory:
      friendly_name: Arbeitsspeicher genutzt   
    sensor.computer_generic_memory_load_memory:
      friendly_name: RAM Auslastung
      icon: mdi:speedometer-medium
      
    sensor.computer_intel_core_i5_8259u_clocks_bus_speed:
      friendly_name: CPU Bus Speed
    sensor.computer_intel_core_i5_8259u_clocks_cpu_core_1:
      friendly_name: CPU Bus Speed Core 1
    sensor.computer_intel_core_i5_8259u_clocks_cpu_core_2:
      friendly_name: CPU Bus Speed Core 2
    sensor.computer_intel_core_i5_8259u_clocks_cpu_core_3:
      friendly_name: CPU Bus Speed Core 3
    sensor.computer_intel_core_i5_8259u_clocks_cpu_core_4:
      friendly_name: CPU Bus Speed Core 4
      
    sensor.computer_intel_core_i5_8259u_load_cpu_total:
      friendly_name: CPU Auslastung
      icon: mdi:speedometer-slow
    sensor.computer_intel_core_i5_8259u_load_cpu_core_1:
      friendly_name: CPU Load Core 1
    sensor.computer_intel_core_i5_8259u_load_cpu_core_2:
      friendly_name: CPU Load Core 2
    sensor.computer_intel_core_i5_8259u_load_cpu_core_3:
      friendly_name: CPU Load Core 3
    sensor.computer_intel_core_i5_8259u_load_cpu_core_4:
      friendly_name: CPU Load Core 4

    sensor.computer_intel_core_i5_8259u_powers_cpu_cores:
      friendly_name: Leistung Cores
    sensor.computer_intel_core_i5_8259u_powers_cpu_dram:
      friendly_name: Leistung DRAM
    sensor.computer_intel_core_i5_8259u_powers_cpu_graphics:
      friendly_name: Leistung Grafik
    sensor.computer_intel_core_i5_8259u_powers_cpu_package:
      friendly_name: Leistung CPU

    sensor.computer_intel_core_i5_8259u_temperatures_cpu_package:
      friendly_name: CPU Temperatur
    sensor.computer_intel_core_i5_8259u_temperatures_cpu_core_1:
      friendly_name: CPU Temperatur Core 1
    sensor.computer_intel_core_i5_8259u_temperatures_cpu_core_2:
      friendly_name: CPU Temperatur Core 2
    sensor.computer_intel_core_i5_8259u_temperatures_cpu_core_3:
      friendly_name: CPU Temperatur Core 3
    sensor.computer_intel_core_i5_8259u_temperatures_cpu_core_4:
      friendly_name: CPU Temperatur Core 4
        
    sensor.computer_wdc_wd20spzx_22ua7t0_load_used_space:
      icon: mdi:harddisk
      friendly_name: HDD Speicherplatz      
    sensor.computer_wdc_wd20spzx_22ua7t0_temperatures_temperature:      
      friendly_name: HDD Temperatur