input_select:
  computer_ausschalten:
    name: Computer ausschalten
    icon: mdi:power-settings
    options:      
      - Ruhezustand
      - Herunterfahren
      - Nichts unternehmen
      
sensor:   
  - platform: openhardwaremonitor
    host: !secret computer_host
    port: 8580  

binary_sensor:
  - platform: mqtt
    name: "Computer"
    state_topic: "homeassistant/sensor/COMPUTER/availability"
    payload_on: "online"
    payload_off: "offline"
    device_class: connectivity

switch:
  - platform: template
    switches:
      pc:
        friendly_name: PC
        value_template: "{{ is_state('binary_sensor.computer', 'on') }}"
        icon_template: mdi:desktop-tower
        turn_on:
          - service: wake_on_lan.send_magic_packet
            data:
              mac: !secret computer_mac
              broadcast_address: !secret fritzbox_broadcast
              broadcast_port: 9
        turn_off:
          - choose:
              - conditions:
                  - "{{ is_state('input_select.computer_ausschalten', 'Ruhezustand') }}"
                sequence:
                  - service: switch.turn_on
                    entity_id: switch.computer_ruhezustand
              - conditions:
                  - "{{ is_state('input_select.computer_ausschalten', 'Herunterfahren') }}"
                sequence:
                  - service: switch.turn_on
                    entity_id: switch.computer_herunterfahren            
                    
      computer:
        friendly_name: Computer
        value_template: "{{ is_state('switch.pc', 'on') and is_state('switch.monitor', 'on') }}"
        icon_template: mdi:desktop-classic
        turn_on:
          service: switch.turn_on
          entity_id: switch.monitor, switch.pc
        turn_off:
          service: switch.turn_off
          entity_id: switch.monitor, switch.pc   
    
automation:
  - alias: "Unterwegs - Computer ausschalten"
    id: "unterwegs_computer_ausschalten"
    trigger:
      - platform: state
        entity_id: binary_sensor.zu_hause
        to: 'off'
        for:
          minutes: 30
    condition:
      - condition: state
        entity_id: switch.computer
        state: 'on'
      - condition: not
        conditions:
          - condition: state
            entity_id: input_select.computer_ausschalten
            state: 'Nichts unternehmen'
    action:
      - service: switch.turn_off
        entity_id: switch.computer
      - service: notify.telegram
        data_template:
          title: "Computer eingeschaltet"
          message: "Der Computer war noch eingeschaltet und wird jetzt heruntergefahren."

  - alias: "Telegram - Computer ausschalten"
    id: "telegram_computer_ausschalten"
    trigger:
      - platform: event
        event_type: telegram_command
        event_data:
          command: '/computer_ausschalten'
    action:
      - service: switch.turn_off
        entity_id: switch.computer
      - service: telegram_bot.send_message
        data_template:
          target: '{{ trigger.event.data.chat_id }}'
          message: "Der Computer wird ausgeschaltet."
          
homeassistant:
  customize:
    sensor.computer_generic_hard_disk_load_used_space:
      friendly_name: SSD Speicherplatz
      icon: mdi:nas
    sensor.computer_generic_memory_data_available_memory:
      friendly_name: Arbeitsspeicher verfügbar
    sensor.computer_generic_memory_data_used_memory:
      friendly_name: Arbeitsspeicher genutzt   
    sensor.computer_generic_memory_load_memory:
      friendly_name: RAM Auslastung
      icon: mdi:speedometer-medium
      
    sensor.computer_intel_core_i5_8259u_clocks_bus_speed:
      friendly_name: CPU Bus Speed
    sensor.computer_intel_core_i5_8259u_clocks_cpu_core_1:
      friendly_name: CPU Bus Speed Core 1
    sensor.computer_intel_core_i5_8259u_clocks_cpu_core_2:
      friendly_name: CPU Bus Speed Core 2
    sensor.computer_intel_core_i5_8259u_clocks_cpu_core_3:
      friendly_name: CPU Bus Speed Core 3
    sensor.computer_intel_core_i5_8259u_clocks_cpu_core_4:
      friendly_name: CPU Bus Speed Core 4
      
    sensor.computer_intel_core_i5_8259u_load_cpu_total:
      friendly_name: CPU Auslastung
      icon: mdi:speedometer-slow
    sensor.computer_intel_core_i5_8259u_load_cpu_core_1:
      friendly_name: CPU Load Core 1
    sensor.computer_intel_core_i5_8259u_load_cpu_core_2:
      friendly_name: CPU Load Core 2
    sensor.computer_intel_core_i5_8259u_load_cpu_core_3:
      friendly_name: CPU Load Core 3
    sensor.computer_intel_core_i5_8259u_load_cpu_core_4:
      friendly_name: CPU Load Core 4

    sensor.computer_intel_core_i5_8259u_powers_cpu_cores:
      friendly_name: Leistung Cores
    sensor.computer_intel_core_i5_8259u_powers_cpu_dram:
      friendly_name: Leistung DRAM
    sensor.computer_intel_core_i5_8259u_powers_cpu_graphics:
      friendly_name: Leistung Grafik
    sensor.computer_intel_core_i5_8259u_powers_cpu_package:
      friendly_name: Leistung CPU

    sensor.computer_intel_core_i5_8259u_temperatures_cpu_package:
      friendly_name: CPU Temperatur
    sensor.computer_intel_core_i5_8259u_temperatures_cpu_core_1:
      friendly_name: CPU Temperatur Core 1
    sensor.computer_intel_core_i5_8259u_temperatures_cpu_core_2:
      friendly_name: CPU Temperatur Core 2
    sensor.computer_intel_core_i5_8259u_temperatures_cpu_core_3:
      friendly_name: CPU Temperatur Core 3
    sensor.computer_intel_core_i5_8259u_temperatures_cpu_core_4:
      friendly_name: CPU Temperatur Core 4
        
    sensor.computer_wdc_wd20spzx_22ua7t0_load_used_space:
      icon: mdi:harddisk
      friendly_name: HDD Speicherplatz      
    sensor.computer_wdc_wd20spzx_22ua7t0_temperatures_temperature:      
      friendly_name: HDD Temperatur