shell_command:
  computer_hibernate: curl http://192.168.2.81:7760/hibernate

input_boolean:
  computer_ausschalten:
    name: Computer ausschalten
    initial: on
    icon: mdi:desktop-classic

device_tracker:
  - platform: ping
    interval_seconds: 30
    consider_home: 60
    hosts:
      pc: !secret computer_host

switch:
  - platform: template
    switches:
      pc:
        friendly_name: PC
        entity_id:
          - device_tracker.pc
        value_template: "{{ is_state('device_tracker.pc', 'home') }}"
        turn_on:
          service: wake_on_lan.send_magic_packet
          data:
            mac: !secret computer_mac
            broadcast_address: !secret fritzbox_broadcast
        turn_off:
          service: shell_command.computer_hibernate
      computer:
        friendly_name: Computer
        entity_id:
          - device_tracker.pc
        value_template: "{{ is_state('device_tracker.pc', 'home') }}"
        turn_on:
          service: switch.turn_on
          entity_id: switch.monitor, switch.pc
        turn_off:
          service: switch.turn_off
          entity_id: switch.monitor, switch.pc

automation:
  - alias: 'Unterwegs - Computer ausschalten'
    trigger:
      - platform: state
        entity_id: binary_sensor.zu_hause
        to: 'off'
        for:
          minutes: 30
    condition:
      - condition: state
        entity_id: switch.computer
        state: 'on'
      - condition: state
        entity_id: input_boolean.computer_ausschalten
        state: 'on'
    action:
      - service: switch.turn_off
        entity_id: switch.computer
      - service: notify.telegram
        data_template:
          title: "Computer eingeschaltet"
          message: "Der Computer war noch eingeschaltet und wird jetzt heruntergefahren."

homeassistant:
  customize:
    switch.computer:
      icon: mdi:desktop-classic
    switch.pc:
      friendly_name: PC
      icon: mdi:desktop-tower

    media_player.soundbar:
      icon: mdi:music