homeassistant:
  customize:
    binary_sensor.diskstation:
      friendly_name: Diskstation Healthchecks.io
    binary_sensor.diskstation_security_status:
      friendly_name: Sicherheitsstatus
    sensor.diskstation_cpu_load_total:
      friendly_name: CPU Leistung
    sensor.diskstation_memory_usage_real:
      friendly_name: Auslastung Arbeitsspeicher
    sensor.diskstation_network_up:
      friendly_name: Netzwerk Upload
    sensor.diskstation_network_down:
      friendly_name: Netzwerk Download
    sensor.diskstation_volume_1_status:
      friendly_name: Volume Status
    sensor.diskstation_volume_1_volume_used:
      friendly_name: Belegter Speicherplatz