sensor:
  - platform: epsonworkforce
    host: !secret drucker_host
    monitored_conditions:
      - black
      - yellow
      - magenta
      - cyan
      - clean    

  - platform: mqtt
    name: "Patrone Schwarz"
    unit_of_measurement: '%'
    state_topic: "printer/black"
        
  - platform: mqtt
    name: "Patrone Magenta"
    unit_of_measurement: '%'
    state_topic: "printer/magenta"
    
  - platform: mqtt
    name: "Patrone Gelb"
    unit_of_measurement: '%'
    state_topic: "printer/yellow"
    
  - platform: mqtt
    name: "Patrone Cyan"
    unit_of_measurement: '%'
    state_topic: "printer/cyan"    
    
  - platform: mqtt
    name: "Patrone Abfall"
    unit_of_measurement: '%'
    state_topic: "printer/waste"    
    
automation:
  - alias: "Drucker - Patrone Schwarz"
    id: "drucker_patrone_schwarz"
    trigger:
      - platform: state
        entity_id: sensor.ink_level_black
    condition:
      - condition: state
        entity_id: device_tracker.epsondrucker
        state: 'home'
    action:
      - service: mqtt.publish
        data_template:
          topic: printer/black
          retain: true
          payload: '{{ states("sensor.ink_level_black") }}'
          
  - alias: "Drucker - Patrone Magenta"
    id: "drucker_patrone_magenta"
    trigger:
      - platform: state
        entity_id: sensor.ink_level_magenta
    condition:
      - condition: state
        entity_id: device_tracker.epsondrucker
        state: 'home'     
    action:
      - service: mqtt.publish
        data_template:
          topic: printer/magenta
          retain: true
          payload: '{{ states("sensor.ink_level_magenta") }}'
          
  - alias: "Drucker - Patrone Gelb"
    id: "drucker_patrone_gelb"
    trigger:
      - platform: state
        entity_id: sensor.ink_level_yellow
    condition:
      - condition: state
        entity_id: device_tracker.epsondrucker
        state: 'home'
    action:
      - service: mqtt.publish
        data_template:
          topic: printer/yellow
          retain: true
          payload: '{{ states("sensor.ink_level_yellow") }}'
          
  - alias: "Drucker - Patrone Cyan"
    id: "drucker_patrone_cyan"
    trigger:
      - platform: state
        entity_id: sensor.ink_level_cyan
    condition:
      - condition: state
        entity_id: device_tracker.epsondrucker
        state: 'home'     
    action:
      - service: mqtt.publish
        data_template:
          topic: printer/cyan
          retain: true
          payload: '{{ states("sensor.ink_level_cyan") }}'
          
  - alias: "Drucker - Patrone Abfall"
    id: "drucker_patrone_abfall"
    trigger:
      - platform: state
        entity_id: sensor.cleaning_level
    condition:
      - condition: state
        entity_id: device_tracker.epsondrucker
        state: 'home'
    action:
      - service: mqtt.publish
        data_template:
          topic: printer/waste
          retain: true
          payload: '{{ states("sensor.cleaning_level") }}'          

homeassistant:
  customize:
    sensor.patrone_schwarz:
      friendly_name: Schwarz
      entity_picture: /local/drucker/icon_ink_schwarz.png
    sensor.patrone_magenta:
      friendly_name: Magenta
      entity_picture: /local/drucker/icon_ink_magenta.png
    sensor.patrone_gelb:
      friendly_name: Gelb
      entity_picture: /local/drucker/icon_ink_gelb.png
    sensor.patrone_cyan:
      friendly_name: Cyan
      entity_picture: /local/drucker/icon_ink_cyan.png
    sensor.patrone_abfall:
      friendly_name: Abfall
      entity_picture: /local/drucker/icon_ink_abfall.png
