sensor:
  - platform: epsonworkforce
    host: !secret drucker_host
    monitored_conditions:
      - black
      - yellow
      - magenta
      - cyan
      - clean
    
mqtt:
  sensor:
    - name: "Patrone Schwarz"
      unit_of_measurement: '%'
      state_topic: "printer/black"

    - name: "Patrone Magenta"
      unit_of_measurement: '%'
      state_topic: "printer/magenta"

    - name: "Patrone Gelb"
      unit_of_measurement: '%'
      state_topic: "printer/yellow"

    - name: "Patrone Cyan"
      unit_of_measurement: '%'
      state_topic: "printer/cyan"    

    - name: "Patrone Abfall"
      unit_of_measurement: '%'
      state_topic: "printer/waste"    
      
automation:
  - alias: "Drucker - Tintenstand"
    id: "drucker_tintenstand"
    trigger:
      - platform: state
        entity_id: sensor.ink_level_black
      - platform: state
        entity_id: sensor.ink_level_magenta
      - platform: state
        entity_id: sensor.ink_level_yellow
      - platform: state
        entity_id: sensor.ink_level_cyan
      - platform: state
        entity_id: sensor.cleaning_level        
    condition:
      - condition: state
        entity_id: device_tracker.epsondrucker
        state: 'home'
    action:
      - service: mqtt.publish
        data:
          topic: >-
            {% if trigger.entity_id == 'sensor.ink_level_black' %}
              printer/black
            {% elif trigger.entity_id == 'sensor.ink_level_magenta' %}
              printer/magenta
            {% elif trigger.entity_id == 'sensor.ink_level_yellow' %}
              printer/yellow
            {% elif trigger.entity_id == 'sensor.ink_level_cyan' %}
              printer/cyan
            {% elif trigger.entity_id == 'sensor.cleaning_level' %}
              printer/waste
            {% endif %}
          retain: true
          payload: "{{ states(trigger.entity_id) }}"          

homeassistant:
  customize:
    sensor.patrone_schwarz:
      friendly_name: Schwarz
      entity_picture: /local/drucker/icon_ink_schwarz.png
    sensor.patrone_magenta:
      friendly_name: Magenta
      entity_picture: /local/drucker/icon_ink_magenta.png
    sensor.patrone_gelb:
      friendly_name: Gelb
      entity_picture: /local/drucker/icon_ink_gelb.png
    sensor.patrone_cyan:
      friendly_name: Cyan
      entity_picture: /local/drucker/icon_ink_cyan.png
    sensor.patrone_abfall:
      friendly_name: Abfall
      entity_picture: /local/drucker/icon_ink_abfall.png
