sensor:
  - platform: epsonworkforce
    host: !secret drucker_host
    monitored_conditions:
      - black
      - photoblack
      - yellow
      - magenta
      - cyan

mqtt:
  sensor:
    - name: "Patrone Schwarz"
      unit_of_measurement: '%'
      state_topic: "printer/black"

    - name: "Patrone Photoschwarz"
      unit_of_measurement: '%'
      state_topic: "printer/photoblack"
      
    - name: "Patrone Magenta"
      unit_of_measurement: '%'
      state_topic: "printer/magenta"

    - name: "Patrone Gelb"
      unit_of_measurement: '%'
      state_topic: "printer/yellow"

    - name: "Patrone Cyan"
      unit_of_measurement: '%'
      state_topic: "printer/cyan"    
      
automation:
  - alias: "Drucker - Tintenstand"
    id: "drucker_tintenstand"
    trigger:
      - platform: state
        id: 'black'
        entity_id: sensor.ink_level_black
      - platform: state
        id: 'photoblack'
        entity_id: sensor.ink_level_photoblack        
      - platform: state
        id: 'magenta'
        entity_id: sensor.ink_level_magenta
      - platform: state
        id: 'yellow'
        entity_id: sensor.ink_level_yellow
      - platform: state
        id: 'cyan'
        entity_id: sensor.ink_level_cyan    
    condition:
      - "{{ trigger.to_state.state != 'unavailable'}} "
      - "{{ is_state('device_tracker.epsondrucker', 'home') }}"
    action:
      - service: mqtt.publish
        data:
          topic: printer/{{ trigger.id }}
          retain: true
          payload: "{{ states(trigger.entity_id) }}"          

homeassistant:
  customize:
    switch.drucker:
      icon: mdi:printer
    sensor.patrone_schwarz:
      friendly_name: Schwarz
      entity_picture: /local/drucker/icon_ink_schwarz.png
    sensor.patrone_photoschwarz:
      friendly_name: Photoschwarz
      entity_picture: /local/drucker/icon_ink_photoschwarz.png      
    sensor.patrone_magenta:
      friendly_name: Magenta
      entity_picture: /local/drucker/icon_ink_magenta.png
    sensor.patrone_gelb:
      friendly_name: Gelb
      entity_picture: /local/drucker/icon_ink_gelb.png
    sensor.patrone_cyan:
      friendly_name: Cyan
      entity_picture: /local/drucker/icon_ink_cyan.png
