sensor:
  - platform: epsonworkforce
    host: !secret drucker_host
    monitored_conditions:
      - black
      - yellow
      - magenta
      - cyan
      - clean

  - platform: mqtt
    name: "Patrone Schwarz"
    unit_of_measurement: '%'
    state_topic: "printer/black"
        
  - platform: mqtt
    name: "Patrone Magenta"
    unit_of_measurement: '%'
    state_topic: "printer/magenta"
    
  - platform: mqtt
    name: "Patrone Gelb"
    unit_of_measurement: '%'
    state_topic: "printer/yellow"
    
  - platform: mqtt
    name: "Patrone Cyan"
    unit_of_measurement: '%'
    state_topic: "printer/cyan"    
    
  - platform: mqtt
    name: "Patrone Abfall"
    unit_of_measurement: '%'
    state_topic: "printer/waste"    
    
automation:
  - alias: 'Drucker - Patrone Schwarz'
    trigger:
      - platform: state
        entity_id: sensor.patrone_commandline_schwarz
    condition:
      condition: not
      conditions:
        - condition: state
          entity_id: device_tracker.epsondrucker
          state: 'not_home'
        - condition: state
          entity_id: sensor.patrone_commandline_schwarz
          state: '-'      
    action:
      - service: mqtt.publish
        data_template:
          topic: printer/black
          retain: true
          payload: '{{ states("sensor.patrone_commandline_schwarz") }}'
          
  - alias: 'Drucker - Patrone Magenta'
    trigger:
      - platform: state
        entity_id: sensor.ink_level_magenta
    condition:
      condition: not
      conditions:
        - condition: state
          entity_id: device_tracker.epsondrucker
          state: 'not_home'
        - condition: state
          entity_id: sensor.ink_level_magenta
          state: '-'      
    action:
      - service: mqtt.publish
        data_template:
          topic: printer/magenta
          retain: true
          payload: '{{ states("sensor.ink_level_magenta") }}'
          
  - alias: 'Drucker - Patrone Gelb'
    trigger:
      - platform: state
        entity_id: sensor.ink_level_yellow
    condition:
      condition: not
      conditions:
        - condition: state
          entity_id: device_tracker.epsondrucker
          state: 'not_home'
        - condition: state
          entity_id: sensor.ink_level_yellow
          state: '-'      
    action:
      - service: mqtt.publish
        data_template:
          topic: printer/yellow
          retain: true
          payload: '{{ states("sensor.ink_level_yellow") }}'
          
  - alias: 'Drucker - Patrone Cyan'
    trigger:
      - platform: state
        entity_id: sensor.ink_level_cyan
    condition:
      condition: not
      conditions:
        - condition: state
          entity_id: device_tracker.epsondrucker
          state: 'not_home'
        - condition: state
          entity_id: sensor.ink_level_cyan
          state: '-'      
    action:
      - service: mqtt.publish
        data_template:
          topic: printer/cyan
          retain: true
          payload: '{{ states("sensor.ink_level_cyan") }}'
          
  - alias: 'Drucker - Patrone Abfall'
    trigger:
      - platform: state
        entity_id: sensor.cleaning_level
    condition:
      condition: not
      conditions:
        - condition: state
          entity_id: device_tracker.epsondrucker
          state: 'not_home'
        - condition: state
          entity_id: sensor.cleaning_level
          state: '-'      
    action:
      - service: mqtt.publish
        data_template:
          topic: printer/waste
          retain: true
          payload: '{{ states("sensor.cleaning_level") }}'          

homeassistant:
  customize:
    sensor.patrone_schwarz:
      friendly_name: Schwarz
      entity_picture: /local/drucker/icon_ink_schwarz.png
    sensor.patrone_magenta:
      friendly_name: Magenta
      entity_picture: /local/drucker/icon_ink_magenta.png
    sensor.patrone_gelb:
      friendly_name: Gelb
      entity_picture: /local/drucker/icon_ink_gelb.png
    sensor.patrone_cyan:
      friendly_name: Cyan
      entity_picture: /local/drucker/icon_ink_cyan.png
    sensor.patrone_abfall:
      friendly_name: Abfall
      entity_picture: /local/drucker/icon_ink_abfall.png
