sensor:
  - platform: command_line
    name: Patrone Schwarz
    command: curl -k -X GET https://192.168.2.23/PRESENTATION/HTML/TOP/PRTINFO.HTML | awk -F"'" '/Ink_K.PNG/ && $6+0 == $6 { printf "%.0f\n", $6 / 50 * 100 }'
    unit_of_measurement: '%'
    value_template: >-
        {%- if is_state("device_tracker.epsondrucker", "home") %}
            {{ value | int }}
        {% else %}
            -
        {%- endif %}

  - platform: command_line
    name: Patrone Magenta
    command: curl -k -X GET https://192.168.2.23/PRESENTATION/HTML/TOP/PRTINFO.HTML | awk -F"'" '/Ink_M.PNG/ && $6+0 == $6 { printf "%.0f\n", $6 / 50 * 100 }'
    unit_of_measurement: '%'
    value_template: >-
        {%- if is_state("device_tracker.epsondrucker", "home") %}
            {{ value | int }}
        {% else %}
            -
        {%- endif %}

  - platform: command_line
    name: Patrone Gelb
    command: curl -k -X GET https://192.168.2.23/PRESENTATION/HTML/TOP/PRTINFO.HTML | awk -F"'" '/Ink_Y.PNG/ && $6+0 == $6 { printf "%.0f\n", $6 / 50 * 100 }'
    unit_of_measurement: '%'
    value_template: >-
        {%- if is_state("device_tracker.epsondrucker", "home") %}
            {{ value | int }}
        {% else %}
            -
        {%- endif %}

  - platform: command_line
    name: Patrone Cyan
    command: curl -k -X GET https://192.168.2.23/PRESENTATION/HTML/TOP/PRTINFO.HTML | awk -F"'" '/Ink_C.PNG/ && $6+0 == $6 { printf "%.0f\n", $6 / 50 * 100 }'
    unit_of_measurement: '%'
    value_template: >-
        {%- if is_state("device_tracker.epsondrucker", "home") %}
            {{ value | int }}
        {% else %}
            -
        {%- endif %}

  - platform: command_line
    name: Patrone Abfall
    command: curl -k -X GET https://192.168.2.23/PRESENTATION/HTML/TOP/PRTINFO.HTML | awk -F"'" '/Ink_Waste.PNG/ && $6+0 == $6 { printf "%.0f\n", $6 / 50 * 100 }'
    unit_of_measurement: '%'
    value_template: >-
        {%- if is_state("device_tracker.epsondrucker", "home") %}
            {{ value | int }}
        {% else %}
            -
        {%- endif %}

homeassistant:
  customize:
    sensor.patrone_schwarz:
      friendly_name: Schwarz
      entity_picture: /local/drucker/icon_ink_schwarz.png
    sensor.patrone_magenta:
      friendly_name: Magenta
      entity_picture: /local/drucker/icon_ink_magenta.png
    sensor.patrone_gelb:
      friendly_name: Gelb
      entity_picture: /local/drucker/icon_ink_gelb.png
    sensor.patrone_cyan:
      friendly_name: Cyan
      entity_picture: /local/drucker/icon_ink_cyan.png
    sensor.patrone_abfall:
      friendly_name: Abfall
      entity_picture: /local/drucker/icon_ink_abfall.png
