automation:
  - alias: "Benachrichtigung Fenster"
    id: "benachrichtigungen_fenster"
    trigger:
      - platform: state
        entity_id: binary_sensor.fenster_wohnzimmer
      - platform: state
        entity_id: binary_sensor.fenster_schlafzimmer
      - platform: state
        entity_id: binary_sensor.fenster_kueche
      - platform: state
        entity_id: binary_sensor.fenster_arbeitszimmer
      - platform: state
        entity_id: binary_sensor.fenster_sportzimmer
      - platform: state
        entity_id: binary_sensor.balkontuer        
    condition:
      - "{{ (states('sensor.laufzeit_minuten') | int(0)) > 1 }}"
      - "{{ is_state('media_player.kodi_wohnzimmer', 'playing') }}" 
    action:
      - choose:
          - conditions:
              - condition: template
                value_template: "{{ True if trigger.entity_id == 'binary_sensor.balkontuer' else False }}"
            sequence:
              - service: notify.kodi_wohnzimmer
                data:
                  title: "Balkontür"
                  message: "Die Balkontür wurde {{ 'geöffnet' if trigger.to_state.state == 'on' else 'geschlossen' }}."                    
                  data:
                    displaytime: 5000
        default:
          - service: notify.kodi_wohnzimmer
            data:
              title: "Fenster"
              message: >-
                {% if trigger.to_state.state == 'on' %}
                  {% set status = "geöffnet" %}
                {% else %}
                  {% set status = "geschlossen" %}
                {% endif %}

                {% if trigger.entity_id == "binary_sensor.fenster_wohnzimmer" %}
                  {% set zimmer = "im Wohnzimmer" %}
                {% elif trigger.entity_id == "binary_sensor.fenster_schlafzimmer" %}
                  {% set zimmer = "im Schlafzimmer" %}
                {% elif trigger.entity_id == "binary_sensor.fenster_kueche" %}
                  {% set zimmer = "in der Küche" %}
                {% elif trigger.entity_id == "binary_sensor.fenster_arbeitszimmer" %}
                  {% set zimmer = "im Arbeitszimmer" %}
                {% elif trigger.entity_id == "binary_sensor.fenster_sportzimmer" %}
                  {% set zimmer = "im Sportzimmer" %}
                {% endif %}

                Das Fenster {{ zimmer }} wurde {{ status }}.
              data:
                displaytime: 5000