sensor:
  - platform: template
    sensors:
      fenster_wohnzimmer_batterie:
        friendly_name: Fenster Wohnzimmer
        entity_id:
          - binary_sensor.fenster_wohnzimmer
        value_template: >-
          {% if is_state('binary_sensor.fenster_wohnzimmer', 'unknown') %}
            0
          {% else %}
            {{ state_attr("binary_sensor.fenster_wohnzimmer", "battery_level") | float }}
          {% endif %}
        unit_of_measurement: '%'
        device_class: battery

      fenster_schlafzimmer_batterie:
        friendly_name: Fenster Schlafzimmer
        entity_id:
          - binary_sensor.fenster_schlafzimmer
        value_template: >-
          {% if is_state('binary_sensor.fenster_schlafzimmer', 'unknown') %}
            0
          {% else %}
            {{ state_attr("binary_sensor.fenster_schlafzimmer", "battery_level") | float }}
          {% endif %}
        unit_of_measurement: '%'
        device_class: battery

      fenster_kueche_batterie:
        friendly_name: Fenster Küche
        entity_id:
          - binary_sensor.fenster_kueche
        value_template: >-
          {% if is_state('binary_sensor.fenster_kueche', 'unknown') %}
            0
          {% else %}
            {{ state_attr("binary_sensor.fenster_kueche", "battery_level") | float }}
          {% endif %}
        unit_of_measurement: '%'
        device_class: battery

      fenster_arbeitszimmer_batterie:
        friendly_name: Fenster Arbeitszimmer
        entity_id:
          - binary_sensor.fenster_arbeitszimmer
        value_template: >-
          {% if is_state('binary_sensor.fenster_arbeitszimmer', 'unknown') %}
            0
          {% else %}
            {{ state_attr("binary_sensor.fenster_arbeitszimmer", "battery_level") | float }}
          {% endif %}
        unit_of_measurement: '%'
        device_class: battery

      fenster_sportzimmer_batterie:
        friendly_name: Fenster Sportzimmer
        entity_id:
          - binary_sensor.fenster_sportzimmer
        value_template: >-
          {% if is_state('binary_sensor.fenster_sportzimmer', 'unknown') %}
            0
          {% else %}
            {{ state_attr("binary_sensor.fenster_sportzimmer", "battery_level") | float }}
          {% endif %}
        unit_of_measurement: '%'
        device_class: battery

automation:
  - alias: "Benachrichtigung Fenster"
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.fenster_wohnzimmer
      - platform: state
        entity_id: binary_sensor.fenster_schlafzimmer
      - platform: state
        entity_id: binary_sensor.fenster_kueche
      - platform: state
        entity_id: binary_sensor.fenster_arbeitszimmer
      - platform: state
        entity_id: binary_sensor.fenster_sportzimmer
    condition:
      - condition: state
        entity_id: 'media_player.kodi_wohnzimmer'
        state: 'playing'
      - condition: numeric_state
        entity_id: sensor.laufzeit_minuten
        above: 1
    action:
      service: notify.kodi_wohnzimmer
      data_template:
        title: "Fenster"
        message: >-
          {% if trigger.to_state.state == 'on' %}
            {% set status = "geöffnet" %}
          {% else %}
            {% set status = "geschlossen" %}
          {% endif %}

          {% if trigger.entity_id == "binary_sensor.fenster_wohnzimmer" %}
            {% set zimmer = "im Wohnzimmer" %}
          {% elif trigger.entity_id == "binary_sensor.fenster_schlafzimmer" %}
            {% set zimmer = "im Schlafzimmer" %}
          {% elif trigger.entity_id == "binary_sensor.fenster_kueche" %}
            {% set zimmer = "in der Küche" %}
          {% elif trigger.entity_id == "binary_sensor.fenster_arbeitszimmer" %}
            {% set zimmer = "im Arbeitszimmer" %}
          {% elif trigger.entity_id == "binary_sensor.fenster_sportzimmer" %}
            {% set zimmer = "im Sportzimmer" %}
          {% endif %}

          Das Fenster {{ zimmer }} wurde {{ status }}.
        data:
          displaytime: 5000