sensor:
  - platform: template
    sensors:
      xiaomi_fenster_wohnzimmer_batterie:
        friendly_name: Fenster Wohnzimmer
        entity_id:
          - binary_sensor.zigate_6e71_onoff
        value_template: >-
          {% if is_state('binary_sensor.zigate_6e71_onoff', 'unknown') %}
            0
          {% else %}
            {{ states.binary_sensor.zigate_6e71_onoff.attributes["battery_level"] | float}}
          {% endif %}
        unit_of_measurement: '%'
        device_class: battery

      xiaomi_fenster_schlafzimmer_batterie:
        friendly_name: Fenster Schlafzimmer
        entity_id:
          - binary_sensor.zigate_bd4c_onoff
        value_template: >-
          {% if is_state('binary_sensor.zigate_bd4c_onoff', 'unknown') %}
            0
          {% else %}
            {{ states.binary_sensor.zigate_bd4c_onoff.attributes["battery_level"] | float}}
          {% endif %}
        unit_of_measurement: '%'
        device_class: battery

      xiaomi_fenster_kueche_batterie:
        friendly_name: Fenster Küche
        entity_id:
          - binary_sensor.zigate_9619_onoff
        value_template: >-
          {% if is_state('binary_sensor.zigate_9619_onoff', 'unknown') %}
            0
          {% else %}
            {{ states.binary_sensor.zigate_9619_onoff.attributes["battery_level"] | float}}
          {% endif %}
        unit_of_measurement: '%'
        device_class: battery

      xiaomi_fenster_arbeitszimmer_batterie:
        friendly_name: Fenster Arbeitszimmer
        entity_id:
          - binary_sensor.zigate_3415_onoff
        value_template: >-
          {% if is_state('binary_sensor.zigate_3415_onoff', 'unknown') %}
            0
          {% else %}
            {{ states.binary_sensor.zigate_3415_onoff.attributes["battery_level"] | float}}
          {% endif %}
        unit_of_measurement: '%'
        device_class: battery

      xiaomi_fenster_sportzimmer_batterie:
        friendly_name: Fenster Sportzimmer
        entity_id:
          - binary_sensor.zigate_2d17_onoff
        value_template: >-
          {% if is_state('binary_sensor.zigate_2d17_onoff', 'unknown') %}
            0
          {% else %}
            {{ states.binary_sensor.zigate_2d17_onoff.attributes["battery_level"] | float}}
          {% endif %}
        unit_of_measurement: '%'
        device_class: battery

binary_sensor:
  - platform: template
    sensors:
      fenster_wohnzimmer:
        friendly_name: Wohnzimmer
        device_class: window
        entity_id:
          - binary_sensor.zigate_6e71_onoff
        value_template: "{{ is_state('binary_sensor.zigate_6e71_onoff', 'on') }}"

      fenster_schlafzimmer:
        friendly_name: Schlafzimmer
        device_class: window
        entity_id:
          - binary_sensor.zigate_bd4c_onoff
        value_template: "{{ is_state('binary_sensor.zigate_bd4c_onoff', 'on') }}"

      fenster_kueche:
        friendly_name: Küche
        device_class: window
        entity_id:
          - binary_sensor.zigate_9619_onoff
        value_template: "{{ is_state('binary_sensor.zigate_9619_onoff', 'on') }}"

      fenster_arbeitszimmer:
        friendly_name: Arbeitszimmer
        device_class: window
        entity_id:
          - binary_sensor.zigate_3415_onoff
        value_template: "{{ is_state('binary_sensor.zigate_3415_onoff', 'on') }}"

      fenster_sportzimmer:
        friendly_name: Sportzimmer
        device_class: window
        entity_id:
          - binary_sensor.zigate_2d17_onoff
        value_template: "{{ is_state('binary_sensor.zigate_2d17_onoff', 'on') }}"

automation:
  - alias: "Benachrichtigung Fenster"
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.zigate_6e71_onoff
      - platform: state
        entity_id: binary_sensor.zigate_bd4c_onoff
      - platform: state
        entity_id: binary_sensor.zigate_9619_onoff
      - platform: state
        entity_id: binary_sensor.zigate_3415_onoff
      - platform: state
        entity_id: binary_sensor.zigate_2d17_onoff
    condition:
      - condition: state
        entity_id: 'media_player.kodi_wohnzimmer'
        state: 'playing'
      - condition: numeric_state
        entity_id: sensor.laufzeit_minuten
        above: 1
    action:
      service: notify.kodi_wohnzimmer
      data_template:
        title: "Fenster"
        message: >-
          {% if trigger.to_state.state == 'on' %}
            {% set status = "geöffnet" %}
          {% else %}
            {% set status = "geschlossen" %}
          {% endif %}

          {% if trigger.entity_id == "binary_sensor.zigate_6e71_onoff" %}
            {% set zimmer = "im Wohnzimmer" %}
          {% elif trigger.entity_id == "binary_sensor.zigate_bd4c_onoff" %}
            {% set zimmer = "im Schlafzimmer" %}
          {% elif trigger.entity_id == "binary_sensor.zigate_9619_onoff" %}
            {% set zimmer = "in der Küche" %}
          {% elif trigger.entity_id == "binary_sensor.zigate_3415_onoff" %}
            {% set zimmer = "im Arbeitszimmer" %}
          {% elif trigger.entity_id == "binary_sensor.zigate_2d17_onoff" %}
            {% set zimmer = "im Sportzimmer" %}
          {% endif %}

          Das Fenster {{ zimmer }} wurde {{ status }}.
        data:
          displaytime: 5000