input_text:
  guest_wifi_ssid:
    name: 'Gäste Wlan - SSID'
    
  guest_wifi_password:
    name: 'Gäste Wlan - Password'
      
template:
  - binary_sensor:
      - name: "Wlan tagsüber"
        unique_id: wlan_tagsueber
        state: >-
          {% set istHomeOffice = is_state('binary_sensor.home_office_heute', 'on') %}
          {% set keinArbeitstag = is_state('binary_sensor.arbeitstag', 'off') %}
          {% set istUrlaub = is_state('calendar.urlaub', 'on') %}
          {% set istKrank = is_state('calendar.arbeit_krank', 'on') %}

          {{ True if (istHomeOffice or keinArbeitstag or istUrlaub or istKrank) else False }}  
                   
  - sensor:          
      - name: "Gäste-Wlan SSID"
        unique_id: gaeste_wlan_ssid
        state: "{{ states('input_text.guest_wifi_ssid') }}"
        icon: "{{ 'mdi:wifi' if is_state('switch.fritz_box_6660_cable_wi_fi_pretty_fly_for_a_wifi', 'on') else 'mdi:wifi-off' }}"
        
      - name: "Gäste-Wlan Passwort"
        unique_id: gaeste_wlan_password
        state: "{{ states('input_text.guest_wifi_password') }}"
        icon: "{{ 'mdi:wifi-strength-4-lock' if is_state('switch.fritz_box_6660_cable_wi_fi_pretty_fly_for_a_wifi', 'on') else 'mdi:wifi-strength-lock-outline' }}"
      
      - name: "Netzwerkgeräte offline"
        unique_id: heimnetz_offline
        unit_of_measurement: Geräte(e)
        icon: >
          {% set wifiOffline = expand('group.heimnetz')
            | selectattr('state','eq','not_home') 
            | map(attribute='name')
            | list %}

          {{ 'mdi:access-point-network' if wifiOffline | length == 0 else 'mdi:access-point-network-off' }}
        state: >
          {% set wifiOffline = expand('group.heimnetz')
            | selectattr('state','eq','not_home') 
            | map(attribute='name')
            | list %}

          {{ wifiOffline | length }}       
        attributes:
          geraete: >
            {% set wifiOffline = expand('group.heimnetz')
              | selectattr('state','eq','not_home') 
              | map(attribute='name')
              | list %}

              {{ wifiOffline }}          

automation:
  - alias: "Gäste-Wlan eingeschaltet"
    id: "gaeste_wlan_eingeschaltet"
    trigger:
      - platform: state
        entity_id: switch.fritz_box_6660_cable_wi_fi_pretty_fly_for_a_wifi
        from: 'off'
        to: 'on'        
    action:
      - service: !secret tts_service
        data:
          echo: "wohnzimmer"
          message: >-
            Der Gastzugang wurde eingeschaltet. Der Name lautet "{{ states('sensor.gaeste_wlan_ssid') }}".
            Das Passwort ist "{{ states('sensor.gaeste_wlan_password') }}".

  - alias: "Gäste-Wlan ausgeschaltet"
    id: "gaeste_wlan_ausgeschaltet"
    trigger:
      - platform: state
        entity_id: switch.fritz_box_6660_cable_wi_fi_pretty_fly_for_a_wifi
        from: 'on'
        to: 'off'
    action:        
      - service: !secret tts_service
        data:
          echo: "wohnzimmer"
          message: >-
            Der Gastzugang wurde ausgeschaltet.

  - alias: "Wlan offline"
    id: "wlan_offline"
    trigger:
      - platform: state
        entity_id: switch.fritz_box_6660_cable_wi_fi_netzwerkdj_2_4ghz
        from: 'on'
        for: '00:30:00'
    action:
      - choose:
          - conditions:
            - condition: state
              entity_id: person.dennis
              state: 'not_home'
            sequence:
              - service: notify.telegram
                data:                  
                  message: "Das Wlan ist seit 30 Minuten offline"
        default:
          - service: !secret tts_service
            data:
              message: "Das Wlan ist seit 30 Minuten offline"    
      - service: homeassistant.reload_config_entry
        data:
          entry_id: !secret fritzbox_entry_id
          
homeassistant:
  customize_glob:
    device_tracker.tasmota*:
      icon: mdi:developer-board     
    device_tracker.radio*:
      icon: mdi:raspberry-pi
    device_tracker.magichome*:
      icon: mdi:lightbulb-on-outline
    device_tracker.firetv*:
      icon: mdi:fire
    device_tracker.tablet*:
      icon: mdi:tablet
    device_tracker.echo*:
      icon: mdi:microphone
    device_tracker.handy*:
      icon: mdi:cellphone
    device_tracker.tplink*:
      icon: mdi:power-socket-eu

    device_tracker.computer:
      icon: mdi:desktop-classic
    device_tracker.computerarbeit:
      icon: mdi:desktop-classic
      friendly_name: Computer Arbeit
    device_tracker.broadlinkschlafzimmer:
      icon: mdi:remote
    device_tracker.diskstation:
      icon: mdi:server-network
    device_tracker.epsondrucker:
      icon: mdi:printer
    device_tracker.xiaomivacuum:
      icon: mdi:robot-vacuum-variant
      friendly_name: Xiaomi Staubsauger
    device_tracker.xiaomifan:
      icon: mdi:fan      
      friendly_name: Xiaomi Ventilator
    device_tracker.soundbar:
      icon: mdi:music-note
    device_tracker.fernseherwohnzimmer:
      icon: mdi:television
      friendly_name: Fernseher Wohnzimmer
      
    device_tracker.radiowohnzimmer:
      friendly_name: Radio Wohnzimmer
    device_tracker.radioflur:
      friendly_name: Radio Flur
    device_tracker.radiobadezimmer:
      friendly_name: Radio Badezimme
    device_tracker.radiokueche:
      friendly_name: Radio Küche
    device_tracker.radioschlafzimmer:
      friendly_name: Radio Schlafzimmer
    device_tracker.radioarbeitszimmer:
      friendly_name: Radio Arbeitszimmer
    device_tracker.radiobalkon:
      friendly_name: Radio Balkon

    device_tracker.tplinkschlafzimmerradio:
      friendly_name: Schlafzimmer Radio
    device_tracker.tplinkflurradio:
      friendly_name: Flur Radio
    device_tracker.tplinkbadezimmerradio:
      friendly_name: Badezimmer Radio
    device_tracker.tplinkkuecheradio:
      friendly_name: Küche Radio
    device_tracker.tplinkschlafzimmerfernseher:
      friendly_name: Schlafzimmer Fernseher   
      
    device_tracker.shellytrockner:
      friendly_name: Trocker      
      
    device_tracker.echoflur:
      friendly_name: Echo Flur
    device_tracker.echokueche:
      friendly_name: Echo Küche
    device_tracker.echobadezimmer:
      friendly_name: Echo Badezimmer
    device_tracker.echowohnzimmer:
      friendly_name: Echo Wohnzimmer
    device_tracker.echoschlafzimmer:
      friendly_name: Echo Schlafzimmer      
    device_tracker.echoarbeitszimmer:
      friendly_name: Echo Arbeitszimmer          
    device_tracker.echofranzi:
      friendly_name: Echo Franzi      
      
    device_tracker.firetvschlafzimmer:
      friendly_name: FireTV Schlafzimmer
    device_tracker.firetvarbeitszimmer:
      friendly_name: FireTV Arbeitszimmer
      
    device_tracker.tabletbadezimmer:
      friendly_name: Tablet Badezimmer
    device_tracker.tabletwohnzimmer:
      friendly_name: Tablet Wohnzimmer
    device_tracker.tabletschlafzimmer:
      friendly_name: Tablet Schafzimmer
    device_tracker.tabletbalkon:
      friendly_name: Tablet Balkon
      
    device_tracker.magichomeflurvorne:
      friendly_name: MagicHome Flur vorne
    device_tracker.magichomeflurhinten:
      friendly_name: MagicHome Flur hinten
    device_tracker.magichomekueche:
      friendly_name: MagicHome Küche
    device_tracker.magichomebadezimmer:
      friendly_name: MagicHome Badezimmer
    device_tracker.magichomeschlafzimmer:
      friendly_name: MagicHome Schlafzimmer
    device_tracker.magichomekinderzimmer:
      friendly_name: MagicHome Kinderzimmer
    device_tracker.magichomearbeitszimmer:
      friendly_name: MagicHome Arbeitszimmer      
    device_tracker.magichomebalkon:
      friendly_name: MagicHome Balkon
      
    device_tracker.tasmotalichterkette:
      friendly_name: Tasmota Lichterkette    
    device_tracker.tasmotawohnzimmerschrank:
      friendly_name: Tasmota Wohnzimmer Schrank
    device_tracker.tasmotawohnzimmerradio:
      friendly_name: Tasmota Wohnzimmer Radio
    device_tracker.tasmotawohnzimmercouch:
      friendly_name: Tasmota Wohnzimmer Couch   
    device_tracker.tasmotaarbeitszimmerladegeraet:
      friendly_name: Tasmota Arbeitszimmer Ladegerät
    device_tracker.tasmotabalkonradio:
      friendly_name: Tasmota Balkon Radio
    device_tracker.tasmotakuechenschrank:
      friendly_name: Tasmota Küchenschrank
    device_tracker.tasmotaspuelmaschine:
      friendly_name: Tasmota Spülmaschine     
    device_tracker.tasmotawaschmaschine:
      friendly_name: Waschmaschine      