input_text:
  guest_wifi_ssid:
    name: 'Gäste Wlan - SSID'
    
  guest_wifi_password:
    name: 'Gäste Wlan - Password'
          
binary_sensor:
  - platform: template
    sensors:
      wlan_tagsueber:
        friendly_name: 'Wlan tagsüber'        
        value_template: >-
          {% set istHomeOffice = is_state('binary_sensor.home_office_heute', 'on') %}
          {% set keinArbeitstag = is_state('binary_sensor.arbeitstag', 'off') %}
          {% set istUrlaub = is_state('calendar.urlaub', 'on') %}
          {% set istKrank = is_state('calendar.arbeit_krank', 'on') %}

          {{ True if (istHomeOffice or keinArbeitstag or istUrlaub or istKrank) else False }}  
          
sensor:    
  - platform: template
    sensors:     
      gaeste_wlan_ssid:
        friendly_name: "Gäste-Wlan SSID"
        value_template: "{{ states('input_text.guest_wifi_ssid') }}"
        icon_template: "{{ 'mdi:wifi' if is_state('switch.fritz_box_7272_wi_fi_pretty_fly_for_a_wifi', 'on') else 'mdi:wifi-off' }}"
            
      gaeste_wlan_password:
        friendly_name: "Gäste-Wlan Passwort"
        value_template: "{{ states('input_text.guest_wifi_password') }}"
        icon_template: "{{ 'mdi:wifi-strength-4-lock' if is_state('switch.fritz_box_7272_wi_fi_pretty_fly_for_a_wifi', 'on') else 'mdi:wifi-strength-lock-outline' }}"
            
      heimnetz_offline:
        friendly_name: Netzwerkgeräte offline
        unit_of_measurement: Gerät(e)
        icon_template: >
          {% set wifiOffline = expand('group.heimnetz')
            | selectattr('state','eq','not_home') 
            | map(attribute='name')
            | list %}

          {{ 'mdi:access-point-network' if wifiOffline | length == 0 else 'mdi:access-point-network-off' }}
        value_template: >
          {% set wifiOffline = expand('group.heimnetz')
            | selectattr('state','eq','not_home') 
            | map(attribute='name')
            | list %}

          {{ wifiOffline | length }}       
        attribute_templates:
          geraete: >
            {% set wifiOffline = expand('group.heimnetz')
              | selectattr('state','eq','not_home') 
              | map(attribute='name')
              | list %}

              {{ wifiOffline }}         

automation:
  - alias: "Gäste-Wlan eingeschaltet"
    id: "gaeste_wlan_eingeschaltet"
    trigger:
      - platform: state
        entity_id: switch.fritz_box_7272_wi_fi_pretty_fly_for_a_wifi
        from: 'off'
        to: 'on'        
    action:
      - service: !secret tts_service
        data:
          echo: "wohnzimmer"
          message: >-
            Der Gastzugang wurde eingeschaltet. Der Name lautet "{{ states('sensor.gaeste_wlan_ssid') }}".
            Das Passwort ist "{{ states('sensor.gaeste_wlan_password') }}".

  - alias: "Gäste-Wlan ausgeschaltet"
    id: "gaeste_wlan_ausgeschaltet"
    trigger:
      - platform: state
        entity_id: switch.fritz_box_7272_wi_fi_pretty_fly_for_a_wifi
        from: 'on'
        to: 'off'
    action:        
      - service: !secret tts_service
        data:
          echo: "wohnzimmer"
          message: >-
            Der Gastzugang wurde ausgeschaltet.

  - alias: "Wlan offline"
    id: "wlan_offline"
    trigger:
      - platform: state
        entity_id: switch.fritz_box_7272_wi_fi_netzwerkdj
        from: 'on'
        for: '00:30:00'
    action:
      - choose:
          - conditions:
            - condition: state
              entity_id: person.dennis
              state: 'not_home'
            sequence:
              - service: notify.telegram
                data:                  
                  message: "Das Wlan ist seit 30 Minuten offline"
        default:
          - service: !secret tts_service
            data:
              message: "Das Wlan ist seit 30 Minuten offline"    
      - service: homeassistant.reload_config_entry
        data:
          entry_id: !secret fritzbox_entry_id
          
homeassistant:
  customize_glob:
    device_tracker.tasmota*:
      icon: mdi:developer-board     
    device_tracker.radio*:
      icon: mdi:raspberry-pi
    device_tracker.magichome*:
      icon: mdi:lightbulb-on-outline
    device_tracker.firetv*:
      icon: mdi:fire
    device_tracker.tablet*:
      icon: mdi:tablet-android
    device_tracker.echo*:
      icon: mdi:microphone
    device_tracker.shelly*:
      icon: mdi:connection
    device_tracker.handy*:
      icon: mdi:cellphone
    device_tracker.tplink*:
      icon: mdi:power-socket-eu
      
  customize:
    sensor.fritz_box_7272_external_ip:
      friendly_name: Externe IP
    sensor.fritz_box_7272_gb_received:
      friendly_name: GB empfangen
    sensor.fritz_box_7272_gb_sent:
      friendly_name: GB gesendet
      
    sensor.speedtest_download:
      icon: mdi:download-network
    sensor.speedtest_upload:
      icon: mdi:upload-network
  
    device_tracker.fritzrepeater:
      icon: mdi:wifi
    device_tracker.computer:
      icon: mdi:desktop-classic
    device_tracker.computerarbeit:
      icon: mdi:desktop-classic
      friendly_name: Computer Arbeit
    device_tracker.broadlinkschlafzimmer:
      icon: mdi:remote
    device_tracker.diskstation:
      icon: mdi:server-network
    device_tracker.netzwerkdj:
      icon: mdi:router-wireless
      friendly_name: Netzwerk
    device_tracker.epsondrucker:
      icon: mdi:printer
    device_tracker.xiaomivacuum:
      icon: mdi:robot-vacuum-variant
      friendly_name: Xiaomi Staubsauger
    device_tracker.xiaomifan:
      icon: mdi:fan      
      friendly_name: Xiaomi Ventilator
    device_tracker.soundbar:
      icon: mdi:music-note
    device_tracker.fernseherwohnzimmer:
      icon: mdi:television
      friendly_name: Fernseher Wohnzimmer
      
    device_tracker.radiowohnzimmer:
      friendly_name: Radio Wohnzimmer
    device_tracker.radioflur:
      friendly_name: Radio Flur
    device_tracker.radiobadezimmer:
      friendly_name: Radio Badezimme
    device_tracker.radiokueche:
      friendly_name: Radio Küche
    device_tracker.radioschlafzimmer:
      friendly_name: Radio Schlafzimmer
    device_tracker.radioarbeitszimmer:
      friendly_name: Radio Arbeitszimmer
    device_tracker.radiobalkon:
      friendly_name: Radio Balkon
    device_tracker.radiokeller:
      friendly_name: Radio Keller
              
    device_tracker.tplinkwohnzimmermonitor:
      friendly_name: Wohnzimmer Monitor
    device_tracker.tplinkschlafzimmerradio:
      friendly_name: Schlafzimmer Radio
    device_tracker.tplinkflurradio:
      friendly_name: Flur Radio
    device_tracker.tplinkbadezimmerradio:
      friendly_name: Badezimmer Radio
    device_tracker.tplinkkuecheradio:
      friendly_name: Küche Radio
    device_tracker.tplinkkellerradio:
      friendly_name: Keller Radio
    device_tracker.tplinkschlafzimmerfernseher:
      friendly_name: Schlafzimmer Fernseher   
    device_tracker.tplinkwaschmaschine:
      friendly_name: Waschmaschine
    device_tracker.tplinktrockner:
      friendly_name: Trocker      
      
    device_tracker.echoflur:
      friendly_name: Flur
    device_tracker.echokueche:
      friendly_name: Küche
    device_tracker.echobadezimmer:
      friendly_name: Badezimmer
    device_tracker.echowohnzimmer:
      friendly_name: Wohnzimmer
    device_tracker.echoschlafzimmer:
      friendly_name: Schlafzimmer      
      
    device_tracker.firetvschlafzimmer:
      friendly_name: FireTV Schlafzimmer
    device_tracker.firetvsportzimmer:
      friendly_name: FireTV Sportzimmer
    device_tracker.firetvbadezimmer:
      friendly_name: FireTV Badezimmer
      
    device_tracker.tabletbadezimmer:
      friendly_name: Tablet Badezimmer
    device_tracker.tabletwohnzimmer:
      friendly_name: Tablet Wohnzimmer
    device_tracker.tabletschlafzimmer:
      friendly_name: Tablet Schafzimmer
    device_tracker.tabletbalkon:
      friendly_name: Tablet Balkon
      
    device_tracker.magichomeflurvorne:
      friendly_name: MagicHome Flur vorne
    device_tracker.magichomeflurhinten:
      friendly_name: MagicHome Flur hinten
    device_tracker.magichomekueche:
      friendly_name: MagicHome Küche
    device_tracker.magichomebadezimmer:
      friendly_name: MagicHome Badezimmer
    device_tracker.magichomeschlafzimmer:
      friendly_name: MagicHome Schlafzimmer
    device_tracker.magichomearbeitszimmer:
      friendly_name: MagicHome Arbeitszimmer
    device_tracker.magichomebalkon:
      friendly_name: MagicHome Balkon
      
    device_tracker.tasmotawohnzimmerstrahler:
      friendly_name: Tasmota Wohnzimmer Strahler
    device_tracker.tasmotawohnzimmercouch:
      friendly_name: Tasmota Wohnzimmer Couch
    device_tracker.tasmotawohnzimmerradio:
      friendly_name: Tasmota Wohnzimmer Radio
    device_tracker.tasmotawohnzimmerschrank:
      friendly_name: Tasmota Wohnzimmer Strahler
    device_tracker.tasmotaarbeitszimmerlampe:
      friendly_name: Tasmota Arbeitszimmer Lampe
    device_tracker.tasmotaarbeitszimmerradio:
      friendly_name: Tasmota Arbeitszimmer Radio
    device_tracker.tasmotaarbeitszimmerladegeraet:
      friendly_name: Tasmota Arbeitszimmer Ladegerät
    device_tracker.tasmotaarbeitszimmermonitore:
      friendly_name: Tasmota Arbeitszimmer Monitore
    device_tracker.tasmotasportzimmerregal:
      friendly_name: Tasmota Sportzimmer Regal
    device_tracker.tasmotabalkonradio:
      friendly_name: Tasmota Balkon Radio
    device_tracker.tasmotakuechenschrank:
      friendly_name: Tasmota Küchenschrank
    device_tracker.tasmotaspuelmaschine:
      friendly_name: Tasmota Spülmaschine     