input_boolean:
  heizung_ausgeschaltet_wohnzimmer:
    name: Heizung ausgeschaltet - Wohnzimmer
  heizung_ausgeschaltet_kueche:
    name: Heizung ausgeschaltet - K端che
  heizung_ausgeschaltet_arbeitszimmer:
    name: Heizung ausgeschaltet - Arbeitszimmer

input_number:
  heizung_start:
    name: Heizung Start
    min: 18
    max: 22
    step: 1
    
  heizung_stop:
    name: Heizung Stop
    min: 20
    max: 24
    step: 1
    
schedule:
  heizung:
    name: "Zeitplan Heizung"
    monday:
      - from: "05:30:00"
        to: "08:00:00"
      - from: "15:30:00"
        to: "20:00:00"        
    tuesday:
      - from: "05:30:00"
        to: "08:00:00"
      - from: "15:30:00"
        to: "20:00:00"    
    wednesday:
      - from: "05:30:00"
        to: "08:00:00"
      - from: "15:30:00"
        to: "20:00:00"    
    thursday:
      - from: "05:30:00"
        to: "08:00:00"
      - from: "15:30:00"
        to: "20:00:00"    
    friday:
      - from: "05:30:00"
        to: "08:00:00"
      - from: "15:30:00"
        to: "20:00:00"    
    saturday:
      - from: "08:00:00"
        to: "11:00:00"
      - from: "17:00:00"
        to: "21:00:00"    
    sunday:
      - from: "08:00:00"
        to: "11:00:00"
      - from: "17:00:00"
        to: "21:00:00"
        
template:
  - binary_sensor:
      - name: "Heizung Arbeitszimmer Batterie"
        unique_id: "heizung_arbeitszimmer_batterie"
        device_class: battery
        state: "{{ state_attr('climate.heizung_arbeitszimmer', 'battery_low') }}"
    
      - name: "Heizung Badezimmer Batterie"
        unique_id: "heizung_badezimmer_batterie"
        device_class: battery
        state: "{{ state_attr('climate.heizung_badezimmer', 'battery_low') }}"
        
      - name: "Heizung K端che Batterie"
        unique_id: "heizung_kueche_batterie"
        device_class: battery
        state: "{{ state_attr('climate.heizung_kueche', 'battery_low') }}"

automation:
  - alias: "Heizung Wohnzimmer"
    id: "heizung_wohnzimmer"
    trigger:
      - platform: state
        id: 'start'
        entity_id: schedule.heizung
        to: 'on'  
      - platform: numeric_state
        id: 'start'
        entity_id: sensor.wohnzimmer_temperatur
        below: input_number.heizung_start
        for: '00:05:00'      
      - platform: state
        id: 'stop'
        entity_id: schedule.heizung
        to: 'off'  
      - platform: numeric_state
        id: 'stop'
        entity_id: sensor.wohnzimmer_temperatur
        above: input_number.heizung_stop        
      - platform: state
        id: 'stop'
        entity_id: binary_sensor.schlafen_aktiv
        to: 'on'            
    condition:
      - condition: or
        conditions:                  
          - condition: and
            conditions:      
              - "{{ trigger.id == 'start' }}"
              - "{{ is_state('climate.heizung_wohnzimmer', 'off') }}"
              - "{{ is_state('schedule.heizung', 'on') }}"
              - "{{ states('sensor.wohnzimmer_temperatur') | float(18) < states('input_number.heizung_start') | float(0) }}"    
          - condition: and
            conditions:      
              - "{{ trigger.id == 'stop' }}"
              - "{{ is_state('climate.heizung_wohnzimmer', 'heat') }}"
              - condition: or
                conditions:                   
                  - "{{ is_state('schedule.heizung', 'off') }}"
                  - "{{ states('sensor.wohnzimmer_temperatur') | float(21) > states('input_number.heizung_stop') | float(0) }}"
                  - "{{ is_state('binary_sensor.schlafen_aktiv', 'on') }}"
    action:
      - choose:
          - conditions:
              - "{{ trigger.id == 'start' }}"
            sequence:
              - service: climate.set_hvac_mode
                data:
                  entity_id: climate.heizung_wohnzimmer
                  hvac_mode: 'heat'  
          - conditions:
              - "{{ trigger.id == 'stop' }}"
            sequence:
              - service: climate.set_hvac_mode
                data:
                  entity_id: climate.heizung_wohnzimmer
                  hvac_mode: 'off'                    
        
  - alias: "Heizung Wohnzimmer - Fenster"
    id: "heizung_wohnzimmer_fenster"
    trigger:
      - platform: state
        id: 'open'
        entity_id: binary_sensor.balkontuer
        to: 'on'
        for:
          seconds: 30
      - platform: state
        id: 'open'
        entity_id: binary_sensor.fenster_wohnzimmer
        to: 'on'
        for:
          seconds: 30
      - platform: state
        id: 'close'
        entity_id: binary_sensor.balkontuer
        to: 'off'      
      - platform: state
        id: 'close'
        entity_id: binary_sensor.fenster_wohnzimmer
        to: 'off'     
    condition:
      - condition: or
        conditions:
          - "{{ trigger.id == 'open' and is_state('climate.heizung_wohnzimmer', 'heat') }}"
          - "{{ trigger.id == 'close' and is_state('input_boolean.heizung_ausgeschaltet_wohnzimmer', 'on') }}"
    action:
      - choose:
          - conditions:
              - "{{ trigger.id == 'open' }}"
              - "{{ is_state('input_boolean.heizung_ausgeschaltet_wohnzimmer', 'off') }}"
              - "{{ is_state('climate.heizung_wohnzimmer', 'heat') }}"
            sequence:
              - service: climate.set_hvac_mode
                data:
                  entity_id: climate.heizung_wohnzimmer
                  hvac_mode: 'off'
              - service: input_boolean.turn_on
                entity_id: input_boolean.heizung_ausgeschaltet_wohnzimmer           
          - conditions:
              - "{{ trigger.id == 'close' }}"
              - "{{ is_state('input_boolean.heizung_ausgeschaltet_wohnzimmer', 'on') }}"
              - "{{ is_state('binary_sensor.balkontuer', 'off') }}"
              - "{{ is_state('binary_sensor.fenster_wohnzimmer', 'off') }}"
            sequence:
              - service: climate.set_hvac_mode
                data:
                  entity_id: climate.heizung_wohnzimmer
                  hvac_mode: 'heat'
              - service: input_boolean.turn_off
                entity_id: input_boolean.heizung_ausgeschaltet_wohnzimmer
        
  - alias: "Heizung K端che"
    id: "heizung_kueche"
    trigger:
      - platform: state
        id: 'start'
        entity_id: schedule.heizung
        to: 'on'  
      - platform: numeric_state
        id: 'start'
        entity_id: sensor.kueche_temperatur
        below: input_number.heizung_start
        for: '00:05:00'      
      - platform: state
        id: 'stop'
        entity_id: schedule.heizung
        to: 'off'  
      - platform: numeric_state
        id: 'stop'
        entity_id: sensor.kueche_temperatur
        above: input_number.heizung_stop    
      - platform: state
        id: 'stop'
        entity_id: binary_sensor.schlafen_aktiv
        to: 'on'           
    condition:
      - condition: or
        conditions:                  
          - condition: and
            conditions:      
              - "{{ trigger.id == 'start' }}"
              - "{{ is_state('climate.heizung_kueche', 'off') }}"
              - "{{ is_state('schedule.heizung', 'on') }}"
              - "{{ states('sensor.kueche_temperatur') | float(18) < states('input_number.heizung_start') | float(0) }}"    
          - condition: and
            conditions:   
              - "{{ trigger.id == 'stop' }}"
              - "{{ is_state('climate.heizung_kueche', 'heat') }}"       
              - condition: or
                conditions:                   
                  - "{{ is_state('schedule.heizung', 'off') }}"
                  - "{{ states('sensor.kueche_temperatur') | float(21) > states('input_number.heizung_stop') | float(0) }}"
                  - "{{ is_state('binary_sensor.schlafen_aktiv', 'on') }}"
    action:
      - choose:
          - conditions:
              - "{{ trigger.id == 'start' }}"
            sequence:
              - service: climate.set_hvac_mode
                data:
                  entity_id: climate.heizung_kueche
                  hvac_mode: 'heat'  
          - conditions:
              - "{{ trigger.id == 'stop' }}"
            sequence:
              - service: climate.set_hvac_mode
                data:
                  entity_id: climate.heizung_kueche
                  hvac_mode: 'off'                         
              
  - alias: "Heizung K端che - Fenster"
    id: "heizung_kueche_fenster"
    trigger:
      - platform: state
        id: 'open'
        entity_id: binary_sensor.fenster_kueche
        to: 'on'
        for:
          seconds: 30
      - platform: state
        id: 'close'
        entity_id: binary_sensor.fenster_kueche
        to: 'off'      
    condition:
      - condition: or
        conditions:
          - "{{ trigger.id == 'open' and is_state('climate.heizung_kueche', 'heat') }}"
          - "{{ trigger.id == 'close' and is_state('input_boolean.heizung_ausgeschaltet_kueche', 'on') }}"        
    action:
      - choose:
          - conditions:
              - "{{ trigger.id == 'open' }}"
              - "{{ is_state('input_boolean.heizung_ausgeschaltet_kueche', 'off') }}"
              - "{{ is_state('climate.heizung_kueche', 'heat') }}"
            sequence:
              - service: climate.set_hvac_mode
                data:
                  entity_id: climate.heizung_kueche
                  hvac_mode: 'off'   
              - service: input_boolean.turn_on
                entity_id: input_boolean.heizung_ausgeschaltet_kueche           
          - conditions:
              - "{{ trigger.id == 'close' }}"
              - "{{ is_state('input_boolean.heizung_ausgeschaltet_kueche', 'on') }}"
            sequence:
              - service: climate.set_hvac_mode
                data:
                  entity_id: climate.heizung_kueche
                  hvac_mode: 'heat'   
              - service: input_boolean.turn_off
                entity_id: input_boolean.heizung_ausgeschaltet_kueche
        
  - alias: "Heizung Arbeitszimmer"
    id: "heizung_arbeitszimmer"
    trigger:
      - platform: state
        id: 'start'
        entity_id: schedule.heizung
        to: 'on'  
      - platform: numeric_state
        id: 'start'
        entity_id: sensor.arbeitszimmer_temperatur
        below: input_number.heizung_start
        for: '00:05:00'      
      - platform: state
        id: 'stop'
        entity_id: schedule.heizung
        to: 'off'  
      - platform: numeric_state
        id: 'stop'
        entity_id: sensor.arbeitszimmer_temperatur
        above: input_number.heizung_stop          
      - platform: state
        id: 'stop'
        entity_id: binary_sensor.home_office_aktiv
        to: 'off'            
    condition:      
      - condition: or
        conditions:                  
          - condition: and
            conditions:      
              - "{{ trigger.id == 'start' }}"
              - "{{ is_state('climate.heizung_arbeitszimmer', 'off') }}"
              - "{{ is_state('schedule.heizung', 'on') }}"
              - "{{ states('sensor.arbeitszimmer_temperatur') | float(18) < states('input_number.heizung_start') | float(0) }}"
              - "{{ is_state('binary_sensor.home_office_heute', 'on') }}"
          - condition: and
            conditions:    
              - "{{ trigger.id == 'stop' }}"
              - "{{ is_state('climate.heizung_arbeitszimmer', 'heat') }}"
              - condition: or
                conditions:                   
                  - "{{ is_state('schedule.heizung', 'off') }}"
                  - "{{ states('sensor.arbeitszimmer_temperatur') | float(21) > states('input_number.heizung_stop') | float(0) }}"
                  - "{{ is_state('binary_sensor.home_office_aktiv', 'off') }}"
    action:
      - choose:
          - conditions:
              - "{{ trigger.id == 'start' }}"
            sequence:
              - service: climate.set_hvac_mode
                data:
                  entity_id: climate.heizung_arbeitszimmer
                  hvac_mode: 'heat'  
          - conditions:
              - "{{ trigger.id == 'stop' }}"
            sequence:
              - service: climate.set_hvac_mode
                data:
                  entity_id: climate.heizung_arbeitszimmer
                  hvac_mode: 'off'      
                  
  - alias: "Heizung Arbeitszimmer - Fenster"
    id: "heizung_arbeitszimmer_fenster"
    trigger:
      - platform: state
        id: 'open'
        entity_id: binary_sensor.fenster_arbeitszimmer
        to: 'on'
        for:
          seconds: 30
      - platform: state
        id: 'close'
        entity_id: binary_sensor.fenster_arbeitszimmer
        to: 'off'    
    condition:
      - condition: or
        conditions:
          - "{{ trigger.id == 'open' and is_state('climate.heizung_arbeitszimmer', 'heat') }}"
          - "{{ trigger.id == 'close' and is_state('input_boolean.heizung_ausgeschaltet_arbeitszimmer', 'on') }}"            
    action:
      - choose:
          - conditions:
              - "{{ trigger.id == 'open' }}"
              - "{{ is_state('input_boolean.heizung_ausgeschaltet_arbeitszimmer', 'off') }}"
              - "{{ is_state('climate.heizung_arbeitszimmer', 'heat') }}"
            sequence:
              - service: climate.set_hvac_mode
                data:
                  entity_id: climate.heizung_arbeitszimmer
                  hvac_mode: 'off'
              - service: input_boolean.turn_on
                entity_id: input_boolean.heizung_ausgeschaltet_arbeitszimmer           
          - conditions:
              - "{{ trigger.id == 'close' }}"
              - "{{ is_state('input_boolean.heizung_ausgeschaltet_arbeitszimmer', 'on') }}"
            sequence:
              - service: climate.set_hvac_mode
                data:
                  entity_id: climate.heizung_arbeitszimmer
                  hvac_mode: 'heat'   
              - service: input_boolean.turn_off
                entity_id: input_boolean.heizung_ausgeschaltet_arbeitszimmer
        
  - alias: "Heizung Badezimmer"
    id: "heizung_badezimmer"
    trigger:
      - platform: state
        id: 'start'
        entity_id: schedule.heizung
        to: 'on'  
      - platform: numeric_state
        id: 'start'
        entity_id: sensor.badezimmer_temperatur
        below: input_number.heizung_start
        for: '00:05:00'      
      - platform: state
        id: 'stop'
        entity_id: schedule.heizung
        to: 'off'  
      - platform: numeric_state
        id: 'stop'
        entity_id: sensor.badezimmer_temperatur
        above: input_number.heizung_stop      
      - platform: state
        id: 'stop'
        entity_id: binary_sensor.schlafen_aktiv
        to: 'on'                  
    condition:
      - condition: or
        conditions:                  
          - condition: and
            conditions:      
              - "{{ trigger.id == 'start' }}"
              - "{{ is_state('climate.heizung_badezimmer', 'off') }}"
              - "{{ is_state('schedule.heizung', 'on') }}"
              - "{{ states('sensor.badezimmer_temperatur') | float(18) < states('input_number.heizung_start') | float(0) }}"    
          - condition: and
            conditions:    
              - "{{ trigger.id == 'stop' }}"
              - "{{ is_state('climate.heizung_badezimmer', 'heat') }}"
              - condition: or
                conditions:                   
                  - "{{ is_state('schedule.heizung', 'off') }}"
                  - "{{ states('sensor.badezimmer_temperatur') | float(21) > states('input_number.heizung_stop') | float(0) }}"
                  - "{{ is_state('binary_sensor.schlafen_aktiv', 'on') }}"             
    action:
      - choose:
          - conditions:
              - "{{ trigger.id == 'start' }}"
            sequence:
              - service: climate.set_hvac_mode
                data:
                  entity_id: climate.heizung_badezimmer
                  hvac_mode: 'heat'  
          - conditions:
              - "{{ trigger.id == 'stop' }}"
            sequence:
              - service: climate.set_hvac_mode
                data:
                  entity_id: climate.heizung_badezimmer
                  hvac_mode: 'off'      
                  