input_boolean:
  heizung_ausgeschaltet_wohnzimmer:
    name: Heizung ausgeschaltet - Wohnzimmer
  heizung_ausgeschaltet_kueche:
    name: Heizung ausgeschaltet - Küche
  heizung_ausgeschaltet_arbeitszimmer:
    name: Heizung ausgeschaltet - Arbeitszimmer

binary_sensor:
  - platform: template
    sensors:
      heizung_arbeitszimmer_batterie:
        friendly_name: Arbeitszimmer
        device_class: battery
        value_template: >
          {{ state_attr('climate.arbeitszimmer', 'battery_low') }}
      heizung_badezimmer_batterie:
        friendly_name: Badezimmer
        device_class: battery
        value_template: >
          {{ state_attr('climate.badezimmer', 'battery_low') }}
      heizung_kueche_batterie:
        friendly_name: Küche
        device_class: battery
        value_template: >
          {{ state_attr('climate.kuche', 'battery_low') }}
      heizung_wohnzimmer_batterie:
        friendly_name: Wohnzimmer
        device_class: battery
        value_template: >
          {{ state_attr('climate.wohnzimmer', 'battery_low') }}

automation:
  - alias: "Heizung Wohnzimmer - Fenster geöffnet"
    id: "heizung_wohnzimmer_fenster_geoeffnet"
    trigger:
      - platform: state
        entity_id: binary_sensor.balkontuer
        to: 'on'
        for:
          seconds: 30      
      - platform: state
        entity_id: binary_sensor.fenster_wohnzimmer
        to: 'on'
        for:
          seconds: 30
    condition:
      - condition: state
        entity_id: climate.wohnzimmer
        state: 'heat'
      - condition: template
        value_template: '{{ state_attr("climate.wohnzimmer", "preset_mode") == "comfort" }}'        
    action:
      - service: climate.set_preset_mode
        data:
          entity_id: climate.wohnzimmer
          preset_mode: 'eco'
      - service: input_boolean.turn_on
        entity_id: input_boolean.heizung_ausgeschaltet_wohnzimmer

  - alias: "Heizung Wohnzimmer - Fenster geschlossen"
    id: "heizung_wohnzimmer_fenster_geschlossen"
    trigger:
      - platform: state
        entity_id: binary_sensor.balkontuer
        to: 'off'      
      - platform: state
        entity_id: binary_sensor.fenster_wohnzimmer
        to: 'off'
    condition:
      - condition: state
        entity_id: input_boolean.heizung_ausgeschaltet_wohnzimmer
        state: 'on'
    action:
      - service: climate.set_preset_mode
        data:
          entity_id: climate.wohnzimmer
          preset_mode: 'comfort'
      - service: input_boolean.turn_off
        entity_id: input_boolean.heizung_ausgeschaltet_wohnzimmer

  - alias: "Heizung Wohnzimmer - Heizung eingeschaltet"
    id: "heizung_wohnzimmer_heizung_eingeschaltet"
    trigger:
      - platform: state
        entity_id: climate.wohnzimmer
        to: 'heat'
      - platform: template
        value_template: '{{ state_attr("climate.wohnzimmer", "preset_mode") == "comfort" }}'
    condition:
      - condition: state
        entity_id: binary_sensor.balkontuer
        state: 'on'
      - condition: state
        entity_id: binary_sensor.fenster_wohnzimmer
        state: 'on'        
    action:
      - service: climate.set_preset_mode
        data:
          entity_id: climate.wohnzimmer
          preset_mode: 'eco'
      - service: input_boolean.turn_on
        entity_id: input_boolean.heizung_ausgeschaltet_wohnzimmer

  - alias: "Heizung Küche - Fenster geöffnet"
    id: "heizung_kueche_fenster_geoeffnet"
    trigger:
      - platform: state
        entity_id: binary_sensor.fenster_kueche
        to: 'on'
        for:
          seconds: 30
    condition:
      - condition: state
        entity_id: climate.kuche
        state: 'heat'
      - condition: template
        value_template: '{{ state_attr("climate.kuche", "preset_mode") == "comfort" }}'        
    action:
      - service: climate.set_preset_mode
        data:
          entity_id: climate.kuche
          preset_mode: 'eco'
      - service: input_boolean.turn_on
        entity_id: input_boolean.heizung_ausgeschaltet_kueche

  - alias: "Heizung Küche - Fenster geschlossen"
    id: "heizung_kueche_fenster_geschlossen"
    trigger:
      - platform: state
        entity_id: binary_sensor.fenster_kueche
        to: 'off'
    condition:
      - condition: state
        entity_id: input_boolean.heizung_ausgeschaltet_kueche
        state: 'on'
    action:
      - service: climate.set_preset_mode
        data:
          entity_id: climate.kuche
          preset_mode: 'comfort'
      - service: input_boolean.turn_off
        entity_id: input_boolean.heizung_ausgeschaltet_kueche

  - alias: "Heizung Küche - Heizung eingeschaltet"
    id: "heizung_kueche_heizung_eingeschaltet"
    trigger:
      - platform: state
        entity_id: climate.kuche
        to: 'heat'
      - platform: template
        value_template: '{{ state_attr("climate.wohnzimmer", "preset_mode") == "comfort" }}'        
    condition:
      - condition: state
        entity_id: binary_sensor.fenster_kueche
        state: 'on'
    action:
      - service: climate.set_preset_mode
        data:
          entity_id: climate.kuche
          preset_mode: 'eco'
      - service: input_boolean.turn_on
        entity_id: input_boolean.heizung_ausgeschaltet_kueche

  - alias: "Heizung Arbeitszimmer - Fenster geöffnet"
    id: "heizung_arbeitszimmer_fenster_geoeffnet"
    trigger:
      - platform: state
        entity_id: binary_sensor.fenster_arbeitszimmer
        to: 'on'
        for:
          seconds: 30
    condition:
      - condition: state
        entity_id: climate.arbeitszimmer
        state: 'heat'
      - condition: template
        value_template: '{{ state_attr("climate.arbeitszimmer", "preset_mode") == "comfort" }}'          
    action:
      - service: climate.set_preset_mode
        data:
          entity_id: climate.arbeitszimmer
          preset_mode: 'eco'
      - service: input_boolean.turn_on
        entity_id: input_boolean.heizung_ausgeschaltet_arbeitszimmer

  - alias: "Heizung Arbeitszimmer - Fenster geschlossen"
    id: "heizung_arbeitszimmer_fenster_geschlossen"
    trigger:
      - platform: state
        entity_id: binary_sensor.fenster_arbeitszimmer
        to: 'off'
    condition:
      - condition: state
        entity_id: input_boolean.heizung_ausgeschaltet_arbeitszimmer
        state: 'on'
    action:
      - service: climate.set_preset_mode
        data:
          entity_id: climate.arbeitszimmer
          preset_mode: 'comfort'
      - service: input_boolean.turn_off
        entity_id: input_boolean.heizung_ausgeschaltet_arbeitszimmer

  - alias: "Heizung Arbeitszimmer - Heizung eingeschaltet"
    id: "heizung_arbeitszimmer_heizunug_eingeschaltet"
    trigger:
      - platform: state
        entity_id: climate.wohnzimmer
        to: 'heat'
      - platform: template
        value_template: '{{ state_attr("climate.wohnzimmer", "preset_mode") == "comfort" }}'
    condition:
      - condition: state
        entity_id: binary_sensor.fenster_arbeitszimmer
        state: 'on'
    action:
      - service: climate.set_preset_mode
        data:
          entity_id: climate.wohnzimmer
          preset_mode: 'eco'
      - service: input_boolean.turn_on
        entity_id: input_boolean.heizung_ausgeschaltet_arbeitszimmer
