input_boolean:
  heizung_ausgeschaltet_wohnzimmer:
    name: Heizung ausgeschaltet - Wohnzimmer
  heizung_ausgeschaltet_kueche:
    name: Heizung ausgeschaltet - Küche
  heizung_ausgeschaltet_arbeitszimmer:
    name: Heizung ausgeschaltet - Arbeitszimmer

schedule:
  heizung:
    name: "Zeitplan Heizung"
    monday:
      - from: "06:00:00"
        to: "07:00:00"
      - from: "16:00:00"
        to: "18:00:00"        
    tuesday:
      - from: "06:00:00"
        to: "07:00:00"
      - from: "16:00:00"
        to: "18:00:00"    
    wednesday:
      - from: "06:00:00"
        to: "07:00:00"
      - from: "16:00:00"
        to: "18:00:00"    
    thursday:
      - from: "06:00:00"
        to: "07:00:00"
      - from: "16:00:00"
        to: "18:00:00"    
    friday:
      - from: "06:00:00"
        to: "07:00:00"
      - from: "16:00:00"
        to: "18:00:00"    
    saturday:
      - from: "08:00:00"
        to: "09:00:00"
      - from: "17:00:00"
        to: "20:00:00"    
    sunday:
      - from: "08:00:00"
        to: "09:00:00"
      - from: "17:00:00"
        to: "20:00:00"
        
binary_sensor:
  - platform: template
    sensors:
      heizung_arbeitszimmer_batterie:
        friendly_name: Arbeitszimmer
        device_class: battery
        value_template: "{{ state_attr('climate.heizung_arbeitszimmer', 'battery_low') }}"
        
      heizung_badezimmer_batterie:
        friendly_name: Badezimmer
        device_class: battery
        value_template: "{{ state_attr('climate.heizung_badezimmer', 'battery_low') }}"
        
      heizung_kueche_batterie:
        friendly_name: Küche
        device_class: battery
        value_template: "{{ state_attr('climate.heizung_kueche', 'battery_low') }}"

automation:
  - alias: "Heizung Wohnzimmer - Fenster"
    id: "heizung_wohnzimmer_fenster"
    trigger:
      - platform: state
        id: 'open'
        entity_id: binary_sensor.balkontuer
        to: 'on'
        for:
          seconds: 30
      - platform: state
        id: 'open'
        entity_id: binary_sensor.fenster_wohnzimmer
        to: 'on'
        for:
          seconds: 30          
      - platform: state
        id: 'close'
        entity_id: binary_sensor.balkontuer
        to: 'off'      
      - platform: state
        id: 'close'
        entity_id: binary_sensor.fenster_wohnzimmer
        to: 'off'     
    condition:
      - condition: or
        conditions:
          - "{{ trigger.id == 'open' and is_state('climate.heizung_wohnzimmer', 'heat') }}"
          - "{{ trigger.id == 'close' and is_state('input_boolean.heizung_ausgeschaltet_wohnzimmer', 'on') }}"
    action:
      - choose:
          - conditions:
              - "{{ trigger.id == 'open' }}"
              - "{{ is_state('input_boolean.heizung_ausgeschaltet_wohnzimmer', 'off') }}"
              - "{{ is_state('climate.heizung_wohnzimmer', 'heat') }}"
            sequence:
              - service: climate.set_hvac_mode
                data:
                  entity_id: climate.heizung_wohnzimmer
                  hvac_mode: 'off'
              - service: input_boolean.turn_on
                entity_id: input_boolean.heizung_ausgeschaltet_wohnzimmer           
          - conditions:
              - "{{ trigger.id == 'close' }}"
              - "{{ is_state('input_boolean.heizung_ausgeschaltet_wohnzimmer', 'on') }}"
              - "{{ is_state('binary_sensor.balkontuer', 'off') }}"
              - "{{ is_state('binary_sensor.fenster_wohnzimmer', 'off') }}"
            sequence:
              - service: climate.set_hvac_mode
                data:
                  entity_id: climate.heizung_wohnzimmer
                  hvac_mode: 'heat'
              - service: input_boolean.turn_off
                entity_id: input_boolean.heizung_ausgeschaltet_wohnzimmer
        
  - alias: "Heizung Küche - Fenster"
    id: "heizung_kueche_fenster"
    trigger:
      - platform: state
        id: 'open'
        entity_id: binary_sensor.fenster_kueche
        to: 'on'
        for:
          seconds: 30
      - platform: state
        id: 'close'
        entity_id: binary_sensor.fenster_kueche
        to: 'off'      
    condition:
      - condition: or
        conditions:
          - "{{ trigger.id == 'open' and is_state('climate.heizung_kueche', 'heat') }}"
          - "{{ trigger.id == 'close' and is_state('input_boolean.heizung_ausgeschaltet_kueche', 'on') }}"        
    action:
      - choose:
          - conditions:
              - "{{ trigger.id == 'open' }}"
              - "{{ is_state('input_boolean.heizung_ausgeschaltet_kueche', 'off') }}"
              - "{{ is_state('climate.heizung_kueche', 'heat') }}"
            sequence:
              - service: climate.set_preset_mode
                data:
                  entity_id: climate.heizung_kueche
                  preset_mode: 'eco'
              - service: input_boolean.turn_on
                entity_id: input_boolean.heizung_ausgeschaltet_kueche           
          - conditions:
              - "{{ trigger.id == 'close' }}"
              - "{{ is_state('input_boolean.heizung_ausgeschaltet_kueche', 'on') }}"
            sequence:
              - service: climate.set_preset_mode
                data:
                  entity_id: climate.heizung_kueche
                  preset_mode: 'comfort'
              - service: input_boolean.turn_off
                entity_id: input_boolean.heizung_ausgeschaltet_kueche

  - alias: "Heizung Arbeitszimmer - Fenster"
    id: "heizung_arbeitszimmer_fenster"
    trigger:
      - platform: state
        id: 'open'
        entity_id: binary_sensor.fenster_arbeitszimmer
        to: 'on'
        for:
          seconds: 30
      - platform: state
        id: 'close'
        entity_id: binary_sensor.fenster_arbeitszimmer
        to: 'off'    
    condition:
      - condition: or
        conditions:
          - "{{ trigger.id == 'open' and is_state('climate.heizung_arbeitszimmer', 'heat') }}"
          - "{{ trigger.id == 'close' and is_state('input_boolean.heizung_ausgeschaltet_arbeitszimmer', 'on') }}"            
    action:
      - choose:
          - conditions:
              - "{{ trigger.id == 'open' }}"
              - "{{ is_state('input_boolean.heizung_ausgeschaltet_arbeitszimmer', 'off') }}"
              - "{{ is_state('climate.heizung_arbeitszimmer', 'heat') }}"
            sequence:
              - service: climate.set_preset_mode
                data:
                  entity_id: climate.heizung_arbeitszimmer
                  preset_mode: 'eco'
              - service: input_boolean.turn_on
                entity_id: input_boolean.heizung_ausgeschaltet_arbeitszimmer           
          - conditions:
              - "{{ trigger.id == 'close' }}"
              - "{{ is_state('input_boolean.heizung_ausgeschaltet_arbeitszimmer', 'on') }}"
            sequence:
              - service: climate.set_preset_mode
                data:
                  entity_id: climate.heizung_arbeitszimmer
                  preset_mode: 'comfort'
              - service: input_boolean.turn_off
                entity_id: input_boolean.heizung_ausgeschaltet_arbeitszimmer
