switch:
  - platform: command_line
    switches:
      kamera_wohnzimmer:
        command_on: !secret kamera_url_switch_on
        command_off: !secret kamera_url_switch_off
        command_state: !secret kamera_url_state
        value_template: >-
          {{ value_json['SWITCH_ON'] == 'yes' if value_json is defined else False }}
        friendly_name: Kamera 
        
automation:
  - alias: "Telegram - Kamera"
    id: "telegram_kamera"
    trigger:
      - platform: event
        event_type: telegram_command
        event_data:
          command: '/kamera'
    action:
      - choose:
          conditions:
            - condition: state
              entity_id: switch.kamera_wohnzimmer
              state: 'on'      
          sequence:
            - service: telegram_bot.send_photo
              data:
                caption: 'Kamera'
                url: 'http://192.168.2.75:8123/api/camera_proxy/camera.kamera_wohnzimmer?token={{ state_attr("camera.kamera_wohnzimmer", "access_token") }}'
        default:
          - service: notify.telegram
            data:
              message: "Die Kamera ist nicht eingeschaltet."        