input_select:
  sportzimmer_ladegeraet_status:
    name: Sportzimmer Ladegerät Status
    options:
      - Ausgeschaltet
      - Stillstand
      - Laden
    icon: mdi:power-plug-outline

sensor:
  - platform: template
    sensors:
      sportzimmer_ladegeraet_verbrauch:
        friendly_name: Sportzimmer Ladegerät Verbrauch
        value_template: >-
          {% if is_state('switch.sportzimmer_ladegerat', 'unavailable') or is_state('sensor.sportzimmer_ladegerat_power', 'unavailable') %}
            {{ 0.00 | float(0) }}
          {% else %}
            {{ states('sensor.sportzimmer_ladegerat_power') | float(0) }}
          {% endif %}
        unit_of_measurement: 'W'
        icon_template: 'mdi:power-cycle'

      sportzimmer_ladegeraet_status:
        friendly_name: Sportzimmer Ladegerät Status
        value_template: "{{ states('input_select.sportzimmer_ladegeraet_status') }}"
        icon_template: "mdi:power-plug-outline"

automation:
  - alias: "Sportzimmer Ladegerät - Ausgeschaltet"
    id: "sportzimmer_ladegeraet_ausgeschaltet"
    trigger:
      - platform: state
        entity_id: switch.sportzimmer_ladegerat
        from: 'on'
        to: 'off'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.sportzimmer_ladegeraet_status
          option: 'Ausgeschaltet'

  - alias: "Sportzimmer Ladegerät - Stillstand"
    id: "sportzimmer_ladegeraet_stillstand"
    trigger:
      - platform: numeric_state
        entity_id: sensor.sportzimmer_ladegeraet_verbrauch
        below: 5
        for: '00:03:00'
      - platform: state
        entity_id: switch.sportzimmer_ladegerat
        from: 'off'
        to: 'on'
    condition:
      - condition: state
        entity_id: switch.sportzimmer_ladegerat
        state: 'on'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.sportzimmer_ladegeraet_status
          option: 'Stillstand'

  - alias: "Sportzimmer Ladegerät - Laden"
    id: "sportzimmer_ladegeraet_laden"
    trigger:
      - platform: numeric_state
        entity_id: sensor.sportzimmer_ladegeraet_verbrauch
        above: 5
        for: '00:01:00'
    condition:
      - condition: state
        entity_id: switch.sportzimmer_ladegerat
        state: 'on'
      - condition: state
        entity_id: input_select.sportzimmer_ladegeraet_status
        state: 'Stillstand'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.sportzimmer_ladegeraet_status
          option: 'Laden'

  - alias: "Sportzimmer Ladegerät - Fertig"
    id: "sportzimmer_ladegeraet_fertig"
    trigger:      
      - platform: state
        entity_id: input_select.sportzimmer_ladegeraet_status
        from: 'Laden'
        to: 'Stillstand'      
    action:
      - service: switch.turn_off
        entity_id: switch.sportzimmer_ladegerat
      - choose:
          - conditions:
              - condition: state
                entity_id: person.dennis
                state: 'not_home'
            sequence:
              - service: notify.telegram
                data:                  
                  message: "Der Ladevorgang im Sportzimmer wurde abgeschlossen."
        default:
          - service: !secret tts_service
            data:
              message: "Der Ladevorgang im Sportzimmer wurde abgeschlossen."                     