sensor:    
  - platform: template
    sensors:
      pflanzen_giessen:
        friendly_name: Pflanzen gießen
        value_template: >
          {% set pflanzenGiessen = expand('group.pflanzen')
            | map(attribute='state') | map('float', 0)
            | select('lt', 20) | list | count %}

          {{ pflanzenGiessen | int(0) }}          
        icon_template: >
          {% set pflanzenGiessen = expand('group.pflanzen')
            | map(attribute='state') | map('float', 0)
            | select('lt', 20) | list | count %}

          {{ 'mdi:flower' if pflanzenGiessen == 0 else 'mdi:flower-outline' }} 
              
automation:
  - alias: "Pflanze gießen"
    id: "pflanze_giessen"
    trigger:
      - id: wohnzimmer
        platform: numeric_state
        entity_id: sensor.pflanze_wohnzimmer_feuchtigkeit
        below: 20 
      - id: arbeitszimmer
        platform: numeric_state
        entity_id: sensor.pflanze_arbeitszimmer_feuchtigkeit
        below: 20         
    condition:
      - "{{ is_state('person.dennis', 'home') }}"
    action:
      - service: !secret tts_service
        data:
          message: >-
            {% if trigger.id == 'wohnzimmer' %}
              {% set zimmer = 'im Wohnzimmer' %}
            {% elif trigger.id == 'arbeitszimmer' %}
              {% set zimmer = 'im Arbeitszimmer' %}       
            {% else %}
              {% set zimmer = '' %}
            {% endif %}

            {{ "Die Pflanze " ~ zimmer ~ " muss gegossen werden." }}   