input_select:
  status_spuelmaschine:
    name: Status Spülmaschine
    options:
      - Ausgeschaltet
      - Stillstand
      - Aktiv
    icon: mdi:dishwasher
    
sensor:   
  - platform: template
    sensors:
      spuelmaschine_status:
        friendly_name: Status Spülmaschine
        value_template: "{{ states('input_select.status_spuelmaschine') }}"
        icon_template: 'mdi:dishwasher'    
    
automation:
  - alias: "Spülmaschine - Ausgeschaltet"
    id: "spuelmaschine_ausgeschaltet"
    trigger:
      - platform: state
        entity_id: switch.spuelmaschine
        from: 'on'
        to: 'off'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.status_spuelmaschine
          option: 'Ausgeschaltet'

  - alias: 'Spülmaschine - Stillstand'
    id: "spuelmaschine_stillstand"
    trigger:
      - id: spuelmaschine_verbrauch
        platform: numeric_state
        entity_id: sensor.spuelmaschine_verbrauch
        below: 2
        for: '00:00:30'
      - id: spuelmaschine_schalter
        platform: state
        entity_id: switch.spuelmaschine
        from: 'off'
        to: 'on'
    condition:
      - condition: state
        entity_id: switch.spuelmaschine
        state: 'on'
      - "{{ trigger.id == 'spuelmaschine_schalter' or not is_state('input_select.status_spuelmaschine', 'Stillstand') }}"
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.status_spuelmaschine
          option: 'Stillstand'

  - alias: 'Spülmaschine - Aktiv'
    id: "spuelmaschine_aktiv"
    trigger:
      - platform: numeric_state
        entity_id: sensor.spuelmaschine_verbrauch
        above: 20
        for: '00:01:00'
    condition:
      - condition: state
        entity_id: switch.spuelmaschine
        state: 'on'
      - condition: state
        entity_id: input_select.status_spuelmaschine
        state: 'Stillstand'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.status_spuelmaschine
          option: 'Aktiv'              

  - alias: 'Spülmaschine - Fertig'
    id: "spuelmaschine_fertig"
    trigger:      
      - platform: state
        entity_id: input_select.status_spuelmaschine
        from: 'Aktiv'
        to: 'Stillstand'   
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: person.dennis
                state: 'not_home'
            sequence:
              - service: notify.telegram
                data:                  
                  message: "Die Spülmaschine ist fertig"
        default:
          - service: !secret tts_service
            data:
              message: "Die Spülmaschine ist fertig."