input_select:
  status_spuelmaschine:
    name: Status Spülmaschine
    options:
      - Ausgeschaltet
      - Stillstand
      - Aktiv
    icon: mdi:dishwasher

switch:
  - platform: mqtt
    name: "Spülmaschine"
    state_topic: "stat/spuelmaschine/POWER"
    command_topic: "cmnd/spuelmaschine/POWER"
    availability_topic: "tele/spuelmaschine/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    icon: "mdi:dishwasher"
    
sensor:
  - platform: mqtt
    name: "Spülmaschine Verbrauch"
    unit_of_measurement: "W"
    icon: "mdi:power-cycle"
    state_topic: "tele/spuelmaschine/SENSOR" 
    value_template: "{{ value_json['ENERGY']['Power'] }}"
    
  - platform: template
    sensors:
      spuelmaschine_status:
        friendly_name: Status Spülmaschine
        value_template: "{{ states('input_select.status_spuelmaschine') }}"
        icon_template: 'mdi:dishwasher'    
    
automation:
  - alias: 'Spülmaschine - Ausgeschaltet'
    trigger:
      - platform: state
        entity_id: switch.spulmaschine
        from: 'on'
        to: 'off'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.status_spuelmaschine
          option: 'Ausgeschaltet'

  - alias: 'Spülmaschine - Stillstand'
    trigger:
      - platform: numeric_state
        entity_id: sensor.spulmaschine_verbrauch
        below: 2
        for: '00:01:00'
      - platform: state
        entity_id: switch.spulmaschine
        from: 'off'
        to: 'on'
    condition:
      - condition: state
        entity_id: switch.spulmaschine
        state: 'on'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.status_spuelmaschine
          option: 'Stillstand'

  - alias: 'Spülmaschine - Aktiv'
    trigger:
      - platform: numeric_state
        entity_id: sensor.spulmaschine_verbrauch
        above: 20
        for: '00:01:00'
    condition:
      - condition: state
        entity_id: switch.spulmaschine
        state: 'on'
      - condition: state
        entity_id: input_select.status_spuelmaschine
        state: 'Stillstand'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.status_spuelmaschine
          option: 'Aktiv'              

  - alias: 'Spülmaschine fertig'
    trigger:      
      - platform: state
        entity_id: input_select.status_spuelmaschine
        from: 'Aktiv'
        to: 'Stillstand'   
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: binary_sensor.zu_hause
                state: 'off'
            sequence:
              - service: notify.telegram
                data_template:
                  title: "Spülmaschine fertig"
                  message: "Die Spülmaschine ist fertig"
        default:
          - service: !secret tts_service
            data_template:
              message: "Die Spülmaschine ist fertig."