vacuum:
  - platform: xiaomi_miio
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token

input_boolean:
  staubsauger_automatische_reinigung:
    name: Automatische Reinigung
    icon: mdi:flash-auto
  staubsauger_automatische_reinigung_gestartet:
    name: Automatische Reinigung gestartet    
    
input_select:
  staubsauger_raumauswahl:
    name: Raum reinigen
    options:
      - Raum auswählen
      - Wohnzimmer
      - Schlafzimmer
      - Arbeitszimmer
      - Flur
      - Küche
    initial: Raum auswählen
    
binary_sensor:
  - platform: template
    sensors:
      reinigung_heute:
        friendly_name: Reinigung heute        
        entity_id:
          - sensor.time
          - binary_sensor.arbeitstag
          - vacuum.xiaomi_vacuum_cleaner
        icon_template: mdi:calendar
        value_template: >-
          {% set arbeitstag = is_state('binary_sensor.arbeitstag', 'off') %}
          {% set wochentag = now().isoweekday() | int %}
          
          {% set tag_heute = now().today().day %}
          {% set tag_letzte_reinigung = as_timestamp(state_attr("vacuum.xiaomi_vacuum_cleaner", "clean_stop")) | timestamp_custom("%d", True) | int  %}
          {% set abstand_letzte_reinigung = tag_heute - tag_letzte_reinigung | int %}
                   
          {% if (wochentag != 7 and (arbeitstag or wochentag == 6) and abstand_letzte_reinigung >= 1) and
            ((wochentag == 1 or wochentag == 4) or abstand_letzte_reinigung >= 3)
          %}
            True
          {% else %}
            False
          {% endif %}

script:
  staubsauger_wohnzimmer:
    alias: "Staubsauger - Wohnzimmer"
    sequence:
      - service: xiaomi_miio.vacuum_clean_zone
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
          zone:
            - [20357,27051,25157,31151]
          repeats: 1
  staubsauger_schlafzimmer:
    alias: "Staubsauger - Schlafzimmer"
    sequence:
      - service: xiaomi_miio.vacuum_clean_zone
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
          zone:
            - [16151,27033,20051,31083]
          repeats: 1
  staubsauger_arbeitszimmer:
    alias: "Staubsauger - Arbeitszimmer"
    sequence:
      - service: xiaomi_miio.vacuum_clean_zone
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
          zone:
            - [22659,23908,25809,27008]
          repeats: 1
  staubsauger_flur:
    alias: "Staubsauger - Flur"
    sequence:
      - service: xiaomi_miio.vacuum_clean_zone
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
          zone:
            - [17951,25375,22651,26925]
            - [21342,22607,22642,25357]
          repeats: 1
  staubsauger_kueche:
    alias: "Staubsauger - Küche"
    sequence:
      - service: xiaomi_miio.vacuum_clean_zone
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
          zone:
            - [16139,24393,18089,26993]
          repeats: 1          
    
counter:
  behaelter_leeren:
    name: Behälter leeren
    icon: mdi:delete-empty
    initial: 3
    step: 1
          
sensor:
  - platform: template
    sensors:
      letzte_reinigung:
        friendly_name: Letzte Reinigung
        entity_id:
          - vacuum.xiaomi_vacuum_cleaner
        icon_template: mdi:clock-end
        value_template: >-
          {% if is_state("vacuum.xiaomi_vacuum_cleaner", "unavailable") or state_attr("vacuum.xiaomi_vacuum_cleaner", "clean_stop") == None %}
            -
          {% else %}
            {% set lastClean = state_attr("vacuum.xiaomi_vacuum_cleaner", "clean_stop") %}
            {% set weekday = as_timestamp(lastClean) | timestamp_custom("%w", True) | int %}

            {{ ['Montag','Dienstag','Mittwoch','Donnerstag','Freitag','Samstag','Sonntag'][weekday-1] }}, {{ as_timestamp(lastClean) | timestamp_custom("%d.%m.%Y", True) | string }}              
          {% endif %}
      reinigung_filter:
        friendly_name: Reinigung Filter
        unit_of_measurement: 'Stunden'
        entity_id:
          - vacuum.xiaomi_vacuum_cleaner
        icon_template: mdi:air-filter
        value_template: >-
          {% if state_attr("vacuum.xiaomi_vacuum_cleaner", "filter_left") == None %}
            -
          {% else %}
            {{ state_attr("vacuum.xiaomi_vacuum_cleaner", "filter_left") }}
          {% endif %}

      reinigung_buerste:
        friendly_name: Reinigung Bürste
        unit_of_measurement: 'Stunden'
        entity_id:
          - vacuum.xiaomi_vacuum_cleaner
        icon_template: mdi:broom
        value_template: >-
          {% if state_attr("vacuum.xiaomi_vacuum_cleaner", "main_brush_left") == None %}
            -
          {% else %}
            {{ state_attr("vacuum.xiaomi_vacuum_cleaner", "main_brush_left") }}
          {% endif %}

      reinigung_seitenbuerste:
        friendly_name: Reinigung Seitenbürste
        unit_of_measurement: 'Stunden'
        entity_id:
          - vacuum.xiaomi_vacuum_cleaner
        icon_template: mdi:broom
        value_template: >-
          {% if state_attr("vacuum.xiaomi_vacuum_cleaner", "side_brush_left") == None %}
            -
          {% else %}
            {{ state_attr("vacuum.xiaomi_vacuum_cleaner", "side_brush_left") }}
          {% endif %}

      reinigung_sensor:
        friendly_name: Reinigung Sensor
        unit_of_measurement: 'Stunden'
        entity_id:
          - vacuum.xiaomi_vacuum_cleaner
        icon_template: mdi:trash-can
        value_template: >-
          {% if state_attr("vacuum.xiaomi_vacuum_cleaner", "sensor_dirty_left") == None %}
            -
          {% else %}
            {{ state_attr("vacuum.xiaomi_vacuum_cleaner", "sensor_dirty_left") }}
          {% endif %}                  
          
      xiaomi_vacuum_batterie:
        friendly_name: Batterie
        device_class: battery
        entity_id:
          - vacuum.xiaomi_vacuum_cleaner
        value_template: >
          {% if is_state('vacuum.xiaomi_vacuum_cleaner', 'unknown') %}
            0
          {% else %}
            {{ state_attr("vacuum.xiaomi_vacuum_cleaner","battery_level") | float }}
          {% endif %}
        unit_of_measurement: '%'

automation:
  - alias: "Staubsaugen - Automatische Reinigung"
    trigger:
      - platform: state
        entity_id: binary_sensor.zu_hause
        to: 'off'
        for:
          minutes: 15
      - platform: time
        at: '7:00:00'        
    condition:
      - condition: time
        after: '06:00'
        before: '22:00'
      - condition: state
        entity_id: vacuum.xiaomi_vacuum_cleaner
        state: 'docked'
      - condition: state
        entity_id: binary_sensor.zu_hause
        state: 'off'
      - condition: state
        entity_id: input_boolean.staubsauger_automatische_reinigung
        state: 'on'        
      - condition: state
        entity_id: binary_sensor.reinigung_heute
        state: 'on'
    action:
      - service: vacuum.start
        entity_id: vacuum.xiaomi_vacuum_cleaner
      - service: input_boolean.turn_on
        entity_id: input_boolean.staubsauger_automatische_reinigung_gestartet
      - service: notify.telegram
        data_template:
          title: 'Staubsaugen gestartet'
          message: 'Das Saugen der Wohnung wurde gestartet.'

  - alias: "Staubsaugen - Beendet"
    trigger:
      - platform: state
        entity_id: vacuum.xiaomi_vacuum_cleaner
        from: 'returning'
        to: 'docked'    
    condition:
      - condition: state
        entity_id: input_boolean.staubsauger_automatische_reinigung_gestartet
        state: 'on'      
      - condition: template
        value_template: >-
          {% set letzter_start = as_timestamp(state_attr("automation.staubsaugen_automatische_reinigung", "last_triggered")) | timestamp_custom("%s", True) | int  %}
          {% set now = now().strftime("%s") | int %}
          {% set abstand_stunden = ((now - letzter_start | timestamp_custom("%s") | int) / 3600) | int %}

          {{ True if abstand_stunden <= 2 else False }}         
    action:
      - service: counter.decrement
        entity_id: counter.behaelter_leeren        
      - service: input_boolean.turn_off
        entity_id: input_boolean.staubsauger_automatische_reinigung_gestartet        

  - alias: "Staubsaugen - Nachricht Telegram"
    trigger:
      - platform: state
        entity_id: vacuum.xiaomi_vacuum_cleaner
        from: 'returning'
        to: 'docked'
    condition:        
      - condition: state
        entity_id: binary_sensor.zu_hause
        state: 'off'        
    action:   
      - service: notify.telegram
        data_template:
          title: 'Staubsaugen beendet'
          message: 'Die Wohnung wurde vollständig gesaugt.'
          
  - alias: "Staubsaugen - Fehler"
    trigger:
      - platform: state
        entity_id: vacuum.xiaomi_vacuum_cleaner
        to: 'error'
    condition:
      - condition: state
        entity_id: binary_sensor.zu_hause
        state: 'off'        
    action:
      - service: notify.telegram
        data_template:
          title: 'Fehler beim Staubsaugen'
          message: 'Während des Staubsaugens ist ein Fehler aufgetreten.'             
                                 
  - alias: "Staubsaugen - Behälter leeren"
    trigger:
      - platform: numeric_state
        entity_id: counter.behaelter_leeren
        below: 1
    action:
      - service: persistent_notification.create
        data:
          title: "Staubsauger"
          message: "Der Staubsaugerbehälter muss geleert werden."
          notification_id: staubsauger_leeren
      - service: vacuum.send_command
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
          command: app_goto_target
          params: [33463,24839]
        
  - alias: "Staubsaugen - Behälter geleert"
    trigger:
      - platform: event
        event_type: call_service
        event_data:
          domain: persistent_notification
          service: dismiss      
    condition:
      - condition: template
        value_template: '{{ trigger.event.data.service_data.notification_id == "staubsauger_leeren" }}'
    action:
      - service: counter.reset
        entity_id: counter.behaelter_leeren
      - service: vacuum.return_to_base
        entity_id: vacuum.xiaomi_vacuum_cleaner
        
  - alias: "Staubsauger - Raum reinigen"    
    trigger:
      - platform: state
        entity_id: input_select.staubsauger_raumauswahl
        from: 'Raum auswählen'
    condition:
      - condition: state
        entity_id: vacuum.xiaomi_vacuum_cleaner
        state: 'docked'      
    action:
      - service: script.turn_on
        data_template:
          entity_id: >
            {% if is_state("input_select.staubsauger_raumauswahl", "Wohnzimmer") %}
              script.staubsauger_wohnzimmer
            {% elif is_state("input_select.staubsauger_raumauswahl", "Schlafzimmer") %}
              script.staubsauger_schlafzimmer
            {% elif is_state("input_select.staubsauger_raumauswahl", "Arbeitszimmer") %}
              script.staubsauger_arbeitszimmer
            {% elif is_state("input_select.staubsauger_raumauswahl", "Flur") %}
              script.staubsauger_flur
            {% elif is_state("input_select.staubsauger_raumauswahl", "Küche") %}
              script.staubsauger_kueche
            {% else %}
            {% endif %}
      - service: input_select.select_option
        data:
          entity_id: input_select.staubsauger_raumauswahl
          option: "Raum auswählen"        
        
  - alias: "Staubsauger - Bereits aktiv"    
    trigger:
      - platform: state
        entity_id: input_select.staubsauger_raumauswahl
        from: 'Raum auswählen'
    condition:
      - condition: state
        entity_id: vacuum.xiaomi_vacuum_cleaner
        state: 'cleaning'      
    action:
      - service: !secret tts_service
        data_template:
          echo: "wohnzimmer"
          message: >-
            "Der Staubsauger ist bereits aktiv."     
      - service: input_select.select_option
        data:
          entity_id: input_select.staubsauger_raumauswahl
          option: "Raum auswählen"    
          
homeassistant:
  customize:
    vacuum.xiaomi_vacuum_cleaner:
      friendly_name: Xiaomi Robot