sensor:    
  - platform: template
    sensors:
      steckdosen_offline:
        friendly_name: Steckdosen offline
        icon_template: >
          {% set steckdosenOffline = expand('group.steckdosen')
            | selectattr('state','eq','unavailable') 
            | map(attribute='name')
            | list %}

          {{ 'mdi:power-plug-outline' if steckdosenOffline | length == 0 else 'mdi:power-plug-off-outline' }}
        value_template: >
          {% set steckdosenOffline = expand('group.steckdosen')
            | selectattr('state','eq','unavailable') 
            | map(attribute='name')
            | list %}

          {{ steckdosenOffline | length }}      