input_datetime:
  tablet_wohnzimmer_zuletzt_geladen:
    name: Tablet Wohnzimmer - Zuletzt geladen
    has_date: true
    has_time: false
  tablet_balkon_zuletzt_geladen:
    name: Tablet Balkon - Zuletzt geladen
    has_date: true
    has_time: false
  tablet_badezimmer_zuletzt_geladen:
    name: Tablet Badezimmer - Zuletzt geladen
    has_date: true
    has_time: false
  tablet_schlafzimmer_zuletzt_geladen:
    name: Tablet Schlafzimmer - Zuletzt geladen
    has_date: true
    has_time: false
    
sensor:
  - platform: template
    sensors:
      tablet_wohnzimmer_zuletzt_geladen:
        friendly_name: Tablet Wohnzimmer - Zuletzt geladen
        icon_template: mdi:clock-start
        value_template: "{{ as_timestamp(states('input_datetime.tablet_wohnzimmer_zuletzt_geladen')) | timestamp_custom('%d.%m.%Y', True) }}"
      tablet_balkon_zuletzt_geladen:
        friendly_name: Tablet Balkon - Zuletzt geladen
        icon_template: mdi:clock-start
        value_template: "{{ as_timestamp(states('input_datetime.tablet_balkon_zuletzt_geladen')) | timestamp_custom('%d.%m.%Y', True) }}"
      tablet_badezimmer_zuletzt_geladen:
        friendly_name: Tablet Badezimmer - Zuletzt geladen
        icon_template: mdi:clock-start
        value_template: "{{ as_timestamp(states('input_datetime.tablet_badezimmer_zuletzt_geladen')) | timestamp_custom('%d.%m.%Y', True) }}"
      tablet_schlafzimmer_zuletzt_geladen:
        friendly_name: Tablet Schlafzimmer - Zuletzt geladen
        icon_template: mdi:clock-start
        value_template: "{{ as_timestamp(states('input_datetime.tablet_schlafzimmer_zuletzt_geladen')) | timestamp_custom('%d.%m.%Y', True) }}"
                                                                                               
automation:
  - alias: "Tablet - Batteriestand niedrig"
    id: "tablet_batteriestand_niedrig"
    trigger:
      - platform: state
        entity_id: 
          - sensor.tablet_wohnzimmer_battery_level
          - sensor.tablet_schlafzimmer_battery_level
          - sensor.tablet_badezimmer_battery_level
          - sensor.tablet_balkon_battery_level
    condition:               
      - "{{ trigger.to_state.state is defined and trigger.to_state.state != 'unknown' }}"
      - "{{ trigger.to_state.state | int(0) < trigger.from_state.state | int(0) }}"
      - "{{ (trigger.to_state.state | int(0)) <= states('input_number.batteriestand_warnlevel') | int(0) }}"
      - "{{ is_state('person.dennis', 'home') }}"
    action:
      - service: !secret tts_service
        data:
          message: >-
            {% set tablet = trigger.entity_id %}
            {% set tabletBatteriestand =  trigger.to_state.state | int(0) %}

            {% if tablet == 'sensor.tablet_wohnzimmer_battery_level' %}
              {% set tabletName = 'im Wohnzimmer' %}
            {% elif tablet == 'sensor.tablet_schlafzimmer_battery_level' %}
              {% set tabletName = 'im Schlafzimmer' %}       
            {% elif tablet == 'sensor.tablet_badezimmer_battery_level' %}
              {% set tabletName = 'im Badezimmer' %}   
            {% elif tablet == 'sensor.tablet_balkon_battery_level' %}
              {% set tabletName = 'auf dem Balkon' %}     
            {% else %}
              {% set tabletName = '' %}
            {% endif %}

            {{ "Das Tablet " ~ tabletName ~ " muss aufgeladen werden. Der Batteriestand beträgt " ~ tabletBatteriestand ~ " Prozent." }}
    
  - alias: "Tablet - Aufgeladen"
    id: "tablet_aufgeladen"
    trigger:
      - platform: state
        entity_id: 
          - sensor.tablet_wohnzimmer_battery_level
          - sensor.tablet_schlafzimmer_battery_level
          - sensor.tablet_badezimmer_battery_level
          - sensor.tablet_balkon_battery_level
    condition:
      - "{{ (trigger.to_state.state | int(100)) > 99 }}"
      - "{{ trigger.to_state.state | int(0) > trigger.from_state.state | int(0) }}"
    action:
      - service: input_datetime.set_datetime
        target:
          entity_id: >
            {% if trigger.entity_id == 'sensor.tablet_wohnzimmer_battery_level' %}
              input_datetime.tablet_wohnzimmer_zuletzt_geladen
            {% elif trigger.entity_id == 'sensor.tablet_schlafzimmer_battery_level' %}
              input_datetime.tablet_schlafzimmer_zuletzt_geladen
            {% elif trigger.entity_id == 'sensor.tablet_badezimmer_battery_level' %}
              input_datetime.tablet_badezimmer_zuletzt_geladen
            {% else %}
              input_datetime.tablet_balkon_zuletzt_geladen
            {% endif %}
        data:
          timestamp: "{{ now().timestamp() }}"
      - choose:
          - conditions:
              - "{{ is_state('person.dennis', 'home') }}"
              - "{{ is_state('binary_sensor.schlafen_aktiv', 'off') }}"
            sequence:
              - service: !secret tts_service
                data:
                  message: >-
                    {% set tablet = trigger.entity_id %}

                    {% if tablet == 'sensor.tablet_wohnzimmer_battery_level' %}
                      {% set tabletName = 'im Wohnzimmer' %}
                    {% elif tablet == 'sensor.tablet_schlafzimmer_battery_level' %}
                      {% set tabletName = 'im Schlafzimmer' %}       
                    {% elif tablet == 'sensor.tablet_badezimmer_battery_level' %}
                      {% set tabletName = 'im Badezimmer' %}    
                    {% elif tablet == 'sensor.tablet_balkon_battery_level' %}
                      {% set tabletName = 'auf dem Balkon' %}     
                    {% else %}
                      {% set tabletName = '' %}
                    {% endif %}

                    {{ "Das Tablet " ~ tabletName ~ " wurde vollständig aufgeladen." }}
    
homeassistant:
  customize:
    sensor.tablet_schlafzimmer_battery_level:
      friendly_name: Tablet Schlafzimmer
    sensor.tablet_badezimmer_battery_level:
      friendly_name: Tablet Badezimmer 
    sensor.tablet_wohnzimmer_battery_level:
      friendly_name: Tablet Wohnzimmer
    sensor.tablet_balkon_battery_level:
      friendly_name: Tablet Balkon