sensor:
  - platform: mitemp_bt
    mac: !secret xiaomi_temperature_mac
    name: Thermometer Wohnzimmer

  - platform: template
    sensors:
      wohnzimmer_temperatur:
        friendly_name: Temperatur
        entity_id:
          - sensor.thermometer_wohnzimmer_temperature
        value_template: >-
          {% if is_state('sensor.thermometer_wohnzimmer_temperature', 'unknown') %}
            0
          {% else %}
            {{ states.sensor.thermometer_wohnzimmer_temperature.state | float }}
          {% endif %}
        unit_of_measurement: '°C'
        device_class: temperature

      wohnzimmer_luftfeuchtigkeit:
        friendly_name: Luftfeuchtigkeit
        entity_id:
          - sensor.thermometer_wohnzimmer_humidity
        value_template: >-
          {% if is_state('sensor.thermometer_wohnzimmer_humidity', 'unknown') %}
            0
          {% else %}
            {{ states.sensor.thermometer_wohnzimmer_humidity.state | float }}
          {% endif %}
        unit_of_measurement: '%'
        device_class: humidity

      thermometer_wohnzimmer_batterie:
        friendly_name: Thermometer Wohnzimmer
        entity_id:
          - sensor.thermometer_wohnzimmer_battery
        value_template: >-
          {% if is_state('sensor.thermometer_wohnzimmer_battery', 'unknown') %}
            0
          {% else %}
            {{ states.sensor.thermometer_wohnzimmer_battery.state | float }}
          {% endif %}
        unit_of_measurement: '%'
        device_class: battery

      thermometer_flur_batterie:
        friendly_name: Thermometer Flur
        entity_id:
          - zigate.thermometer_flur
        value_template: >-
          {% if is_state('zigate.thermometer_flur', 'unknown') %}
            0
          {% else %}
            {{ state_attr("zigate.thermometer_flur", "battery_level") | float }}
          {% endif %}
        unit_of_measurement: '%'
        device_class: battery

      thermometer_balkon_batterie:
        friendly_name: Thermometer Balkon
        entity_id:
          - zigate.thermometer_balkon
        value_template: >-
          {% if is_state('zigate.thermometer_balkon', 'unknown') %}
            0
          {% else %}
            {{ state_attr("zigate.thermometer_balkon", "battery_level") | float }}
          {% endif %}
        unit_of_measurement: '%'
        device_class: battery

      thermometer_kuehlschrank_batterie:
        friendly_name: Thermometer Kühlschrank
        entity_id:
          - zigate.thermometer_kuehlschrank
        value_template: >-
          {% if is_state('zigate.thermometer_kuehlschrank', 'unknown') %}
            0
          {% else %}
            {{ state_attr("zigate.thermometer_kuehlschrank", "battery_level") | float }}
          {% endif %}
        unit_of_measurement: '%'
        device_class: battery

      thermometer_gefrierschrank_batterie:
        friendly_name: Thermometer Gefrierschrank
        entity_id:
          - zigate.thermometer_gefrierschrank
        value_template: >-
          {% if is_state('zigate.thermometer_gefrierschrank', 'unknown') %}
            0
          {% else %}
            {{ state_attr("zigate.thermometer_gefrierschrank", "battery_level") | float }}
          {% endif %}
        unit_of_measurement: '%'
        device_class: battery

      thermometer_schlafzimmer_batterie:
        friendly_name: Thermometer Schlafzimmer
        entity_id:
          - zigate.thermometer_schlafzimmer
        value_template: >-
          {% if is_state('zigate.thermometer_schlafzimmer', 'unknown') %}
            0
          {% else %}
            {{ state_attr("zigate.thermometer_schlafzimmer", "battery_level") | float }}
          {% endif %}
        unit_of_measurement: '%'
        device_class: battery

      thermometer_arbeitszimmer_batterie:
        friendly_name: Thermometer Arbeitszimmer
        entity_id:
          - zigate.thermometer_arbeitszimmer
        value_template: >-
          {% if is_state('zigate.thermometer_arbeitszimmer', 'unknown') %}
            0
          {% else %}
            {{ state_attr("zigate.thermometer_arbeitszimmer", "battery_level") | float }}
          {% endif %}
        unit_of_measurement: '%'
        device_class: battery

      thermometer_kueche_batterie:
        friendly_name: Thermometer Küche
        entity_id:
          - zigate.thermometer_kueche
        value_template: >-
          {% if is_state('zigate.thermometer_kueche', 'unknown') %}
            0
          {% else %}
            {{ state_attr("zigate.thermometer_kueche", "battery_level") | float }}
          {% endif %}
        unit_of_measurement: '%'
        device_class: battery

      thermometer_sportzimmer_batterie:
        friendly_name: Thermometer Sportzimmer
        entity_id:
          - zigate.thermometer_sportzimmer
        value_template: >-
          {% if is_state('zigate.thermometer_sportzimmer', 'unknown') %}
            0
          {% else %}
            {{ state_attr("zigate.thermometer_sportzimmer", "battery_level") | float }}
          {% endif %}
        unit_of_measurement: '%'
        device_class: battery

      thermometer_parkplatz_batterie:
        friendly_name: Thermometer Parkplatz
        entity_id:
          - zigate.thermometer_parkplatz
        value_template: >-
          {% if is_state('zigate.thermometer_parkplatz', 'unknown') %}
            0
          {% else %}
            {{ state_attr("zigate.thermometer_parkplatz", "battery_level") | float }}
          {% endif %}
        unit_of_measurement: '%'
        device_class: battery