sensor:
  - platform: template
    sensors:
      thermometer_flur_batterie:
        friendly_name: Thermometer Flur
        entity_id:
          - zha.thermometer_flur
        value_template: >-
          {% if is_state('zha.thermometer_flur', 'unknown') %}
            0
          {% else %}
            {{ state_attr("zha.thermometer_flur", "battery_level") | float }}
          {% endif %}
        unit_of_measurement: '%'
        device_class: battery

      thermometer_balkon_batterie:
        friendly_name: Thermometer Balkon
        entity_id:
          - zha.thermometer_balkon
        value_template: >-
          {% if is_state('zha.thermometer_balkon', 'unknown') %}
            0
          {% else %}
            {{ state_attr("zha.thermometer_balkon", "battery_level") | float }}
          {% endif %}
        unit_of_measurement: '%'
        device_class: battery

      thermometer_kuehlschrank_batterie:
        friendly_name: Thermometer Kühlschrank
        entity_id:
          - zha.thermometer_kuehlschrank
        value_template: >-
          {% if is_state('zha.thermometer_kuehlschrank', 'unknown') %}
            0
          {% else %}
            {{ state_attr("zha.thermometer_kuehlschrank", "battery_level") | float }}
          {% endif %}
        unit_of_measurement: '%'
        device_class: battery

      thermometer_gefrierschrank_batterie:
        friendly_name: Thermometer Gefrierschrank
        entity_id:
          - zha.thermometer_gefrierschrank
        value_template: >-
          {% if is_state('zha.thermometer_gefrierschrank', 'unknown') %}
            0
          {% else %}
            {{ state_attr("zha.thermometer_gefrierschrank", "battery_level") | float }}
          {% endif %}
        unit_of_measurement: '%'
        device_class: battery

      thermometer_schlafzimmer_batterie:
        friendly_name: Thermometer Schlafzimmer
        entity_id:
          - zha.thermometer_schlafzimmer
        value_template: >-
          {% if is_state('zha.thermometer_schlafzimmer', 'unknown') %}
            0
          {% else %}
            {{ state_attr("zha.thermometer_schlafzimmer", "battery_level") | float }}
          {% endif %}
        unit_of_measurement: '%'
        device_class: battery

      thermometer_arbeitszimmer_batterie:
        friendly_name: Thermometer Arbeitszimmer
        entity_id:
          - zha.thermometer_arbeitszimmer
        value_template: >-
          {% if is_state('zha.thermometer_arbeitszimmer', 'unknown') %}
            0
          {% else %}
            {{ state_attr("zha.thermometer_arbeitszimmer", "battery_level") | float }}
          {% endif %}
        unit_of_measurement: '%'
        device_class: battery

      thermometer_kueche_batterie:
        friendly_name: Thermometer Küche
        entity_id:
          - zha.thermometer_kueche
        value_template: >-
          {% if is_state('zha.thermometer_kueche', 'unknown') %}
            0
          {% else %}
            {{ state_attr("zha.thermometer_kueche", "battery_level") | float }}
          {% endif %}
        unit_of_measurement: '%'
        device_class: battery

      thermometer_sportzimmer_batterie:
        friendly_name: Thermometer Sportzimmer
        entity_id:
          - zha.thermometer_sportzimmer
        value_template: >-
          {% if is_state('zha.thermometer_sportzimmer', 'unknown') %}
            0
          {% else %}
            {{ state_attr("zha.thermometer_sportzimmer", "battery_level") | float }}
          {% endif %}
        unit_of_measurement: '%'
        device_class: battery

      thermometer_parkplatz_batterie:
        friendly_name: Thermometer Parkplatz
        entity_id:
          - zha.thermometer_parkplatz
        value_template: >-
          {% if is_state('zha.thermometer_parkplatz', 'unknown') %}
            0
          {% else %}
            {{ state_attr("zha.thermometer_parkplatz", "battery_level") | float }}
          {% endif %}
        unit_of_measurement: '%'
        device_class: battery