sensor:
  - platform: mitemp_bt
    mac: !secret xiaomi_temperature_mac
    name: Thermometer Wohnzimmer BT

  - platform: template
    sensors:
      wohnzimmer_temperatur:
        friendly_name: Temperatur
        entity_id:
          - sensor.thermometer_wohnzimmer_temperature
        value_template: >-
          {% if is_state('sensor.thermometer_wohnzimmer_temperature', 'unknown') %}
            0
          {% else %}
            {{ states.sensor.thermometer_wohnzimmer_temperature.state | float }}
          {% endif %}
        unit_of_measurement: '°C'
        device_class: temperature

      wohnzimmer_luftfeuchtigkeit:
        friendly_name: Luftfeuchtigkeit
        entity_id:
          - sensor.thermometer_wohnzimmer_humidity
        value_template: >-
          {% if is_state('sensor.thermometer_wohnzimmer_humidity', 'unknown') %}
            0
          {% else %}
            {{ states.sensor.thermometer_wohnzimmer_humidity.state | float }}
          {% endif %}
        unit_of_measurement: '%'
        device_class: humidity