sensor:
  - platform: mqtt
    name: "Gewicht"
    state_topic: "scale/Dennis/weight"
    value_template: "{{ value_json['Weight'] }}"    
    json_attributes_topic: "scale/Dennis/weight"
    unit_of_measurement: "kg"
    icon: mdi:scale-bathroom   

  - platform: mqtt
    name: "BMI"
    state_topic: "scale/Dennis/weight"
    value_template: "{{ value_json['BMI'] }}"
    icon: mdi:human-pregnant

  - platform: mqtt
    name: "Wasser"
    state_topic: "scale/Dennis/weight"
    value_template: "{{ value_json['Water'] }}"   
    unit_of_measurement: "kg"
    icon: mdi:water

  - platform: mqtt
    name: "Fett"
    state_topic: "scale/Dennis/weight"
    value_template: "{{ value_json['Body Fat'] }}"    
    unit_of_measurement: "kg"
    icon: mdi:scale-balance

  - platform: statistics
    entity_id: sensor.gewicht
    name: "Gewicht Durchschnitt"

homeassistant:
  customize:
    sensor.gewicht_durchschnitt:
      friendly_name: Durchschnitt