input_select:
  status_waschmaschine:
    name: Status Waschmaschine
    options:
      - Ausgeschaltet
      - Stillstand
      - Waschen
    icon: mdi:washing-machine

  status_trockner:
    name: Status Trockner
    options:
      - Ausgeschaltet
      - Stillstand
      - Trocknen
    icon: mdi:tumble-dryer

sensor:
  - platform: template
    sensors:
      waschmaschine_status:
        friendly_name: Status Waschmaschine
        value_template: "{{ states('input_select.status_waschmaschine') }}"
        icon_template: 'mdi:washing-machine'

      trockner_status:
        friendly_name: Status Trockner
        value_template: "{{ states('input_select.status_trockner') }}"
        icon_template: 'mdi:tumble-dryer'

automation:
  - alias: "Waschmaschine - Ausgeschaltet"
    id: "waschmaschine_ausgeschaltet"
    trigger:
      - platform: state
        entity_id: switch.waschmaschine
        from: 'on'
        to: 'off'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.status_waschmaschine
          option: 'Ausgeschaltet'

  - alias: "Waschmaschine - Stillstand"
    id: "waschmaschine_stillstand"
    trigger:
      - platform: numeric_state
        entity_id: sensor.waschmaschine_verbrauch
        below: 10
        for: '00:00:30'
      - platform: state
        entity_id: switch.waschmaschine
        from: 'off'
        to: 'on'
    condition:
      - "{{ is_state('switch.waschmaschine', 'on') }}"     
      - "{{ not is_state('sensor.waschmaschine_status', 'Stillstand') }}"           
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.status_waschmaschine
          option: 'Stillstand'

  - alias: "Waschmaschine - Aktiv"
    id: "waschmaschine_aktiv"
    trigger:
      - platform: numeric_state
        entity_id: sensor.waschmaschine_verbrauch
        above: 20
        for: '00:01:00'
    condition:
      - "{{ is_state('switch.waschmaschine', 'on') }}"     
      - "{{ is_state('sensor.waschmaschine_status', 'Stillstand') }}"
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.status_waschmaschine
          option: 'Waschen'

  - alias: "Waschmaschine - Gestartet"
    id: "waschmaschine_gestartet"
    trigger:
      - platform: state
        entity_id: input_select.status_waschmaschine
        from: 'Stillstand'
        to: 'Waschen'
    condition:
      - "{{ not is_state('person.dennis', 'home') }}"
    action:
      - service: notify.telegram
        data:          
          message: "Die Waschmaschine wurde gestartet."

  - alias: "Waschmaschine - Fertig"
    id: "waschmaschine_fertig"
    trigger:      
      - platform: state
        entity_id: input_select.status_waschmaschine
        from: 'Waschen'
        to: 'Stillstand'      
    action:
      - choose:
          - conditions:
              - "{{ not is_state('person.dennis', 'home') }}"
            sequence:
              - service: notify.telegram
                data:                  
                  message: "Die Waschmaschine ist fertig."
        default:
          - service: !secret tts_service
            data:
              message: "Die Waschmaschine ist fertig."
      - choose:
          - conditions:
              - "{{ is_state('switch.trockner', 'off') }}"
            sequence:
              - service: switch.turn_on
                entity_id: switch.trockner        
              
  - alias: "Waschmaschine - Noch eingeschaltet"
    id: "waschmaschine_noch_eingeschaltet"
    trigger:
      - platform: state
        entity_id: input_select.status_waschmaschine
        to: 'Stillstand'
        for: '01:00:00'
    condition:
      - "{{ is_state('switch.waschmaschine', 'on') }}"
    action:
      - choose:
          - conditions:
              - "{{ not is_state('person.dennis', 'home') }}"
            sequence:
              - service: notify.telegram
                data:                  
                  message: "Die Waschmaschine ist noch eingeschaltet."
                  data:
                    inline_keyboard:
                      - 'Waschmaschine ausschalten:/waschmaschine_ausschalten'                  
        default:
          - service: !secret tts_service
            data:
              message: "Die Waschmaschine ist noch eingeschaltet."

  - alias: "Waschmaschine - Ausschalten"
    id: "waschmaschine_ausschalten"
    trigger:
      - platform: event
        event_type: telegram_callback
        event_data:
          data: '/waschmaschine_ausschalten'
    action:
      - service: switch.turn_off
        entity_id: switch.waschmaschine
      - service: telegram_bot.edit_replymarkup
        data:
          message_id: 'last'
          chat_id: '{{ trigger.event.data.user_id }}'
          inline_keyboard: []
      - service: telegram_bot.send_message
        data:
          target: '{{ trigger.event.data.chat_id }}'
          message: "Die Waschmaschine wird ausgeschaltet."          
          
  - alias: "Trockner - Ausgeschaltet"
    id: "trockner_ausgeschaltet"
    trigger:
      - platform: state
        entity_id: switch.trockner
        from: 'on'
        to: 'off'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.status_trockner
          option: 'Ausgeschaltet'

  - alias: "Trockner - Stillstand"
    id: "trockner_stillstand"
    trigger:
      - platform: numeric_state
        entity_id: sensor.trockner_verbrauch
        below: 10
        for: '00:00:30'
      - platform: state
        entity_id: switch.trockner
        from: 'off'
        to: 'on'
    condition:
      - "{{ is_state('switch.trockner','on') }}"     
      - "{{ not is_state('sensor.trockner_status', 'Stillstand') }}"     
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.status_trockner
          option: 'Stillstand'

  - alias: "Trockner - Aktiv"
    id: "trockner_aktiv"
    trigger:
      - platform: numeric_state
        entity_id: sensor.trockner_verbrauch
        above: 150
        for: '00:01:00'
    condition:
      - "{{ is_state('switch.trockner','on') }}"     
      - "{{ is_state('sensor.trockner_status', 'Stillstand') }}"
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.status_trockner
          option: 'Trocknen'

  - alias: "Trockner - Nachricht Telegram"
    id: "trockner_nachricht_telegram"
    trigger:
      - platform: state
        entity_id: input_select.status_trockner
        from: 'Stillstand'
        to: 'Trocknen'
    condition:
      - "{{ not is_state('person.dennis', 'home') }}"
    action:
      - service: notify.telegram
        data:          
          message: "Der Trockner wurde gestartet."

  - alias: "Trockner - Fertig"
    id: "trockner_fertig"
    trigger:
      - platform: state
        entity_id: input_select.status_trockner
        from: 'Trocknen'
        to: 'Stillstand'    
    action:
      - choose:
          - conditions:
              - "{{ not is_state('person.dennis', 'home') }}"
            sequence:
              - service: notify.telegram
                data:                  
                  message: "Der Trockner ist fertig."
        default:
          - service: !secret tts_service
            data:
              message: "Der Trockner ist fertig."                              

  - alias: "Trockner - Noch eingeschaltet"
    id: "trockner_noch_eingeschaltet"
    trigger:
      - platform: state
        entity_id: input_select.status_trockner
        to: 'Stillstand'
        for: '01:00:00'
    condition:
      - "{{ is_state('switch.trockner', 'on') }}"
      - "{{ not is_state('sensor.waschmaschine_status', 'Waschen') }}"  
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: person.dennis
                state: 'not_home'
            sequence:
              - service: notify.telegram
                data:                  
                  message: "Der Trockner ist noch eingeschaltet."
                  data:
                    inline_keyboard:
                      - 'Trockner ausschalten:/trockner_ausschalten'                  
        default:
          - service: !secret tts_service
            data:
              message: "Der Trockner ist noch eingeschaltet."
              
  - alias: "Trockner - Ausschalten"
    id: "trockner_ausschalten"
    trigger:
      - platform: event
        event_type: telegram_callback
        event_data:
          data: '/trockner_ausschalten'
    action:
      - service: switch.turn_off
        entity_id: switch.trockner
      - service: telegram_bot.edit_replymarkup
        data:
          message_id: 'last'
          chat_id: '{{ trigger.event.data.user_id }}'
          inline_keyboard: []
      - service: telegram_bot.send_message
        data:
          target: '{{ trigger.event.data.chat_id }}'
          message: "Der Trockner wird ausgeschaltet."                                 