input_select:
  status_waschmaschine:
    name: Status Waschmaschine
    options:
      - Ausgeschaltet
      - Stillstand
      - Waschen
    icon: mdi:washing-machine

  status_trockner:
    name: Status Trockner
    options:
      - Ausgeschaltet
      - Stillstand
      - Trocknen
    icon: mdi:tumble-dryer

sensor:
  - platform: template
    sensors:
      waschmaschine_verbrauch:
        friendly_name: Verbrauch Waschmaschine
        entity_id:
          - switch.waschmaschine
        value_template: >-
          {% if is_state('switch.waschmaschine', 'unavailable') %}
            {{ 0.00 | float }}
          {% else %}
            {{ state_attr('switch.waschmaschine', 'current_power_w') | float }}
          {% endif %}
        unit_of_measurement: 'W'
        icon_template: 'mdi:power-cycle'

      waschmaschine_status:
        friendly_name: Status Waschmaschine
        entity_id:
          - input_select.status_waschmaschine
        value_template: >-
          {{ states('input_select.status_waschmaschine') }}
        icon_template: 'mdi:washing-machine'

      trockner_verbrauch:
        friendly_name: Verbrauch Trockner
        entity_id:
          - switch.trockner
        value_template: >-
          {% if is_state('switch.trockner', 'unavailable') %}
            {{ 0.00 | float }}
          {% else %}
            {{ state_attr('switch.trockner', 'current_power_w') | float }}            
          {% endif %}
        unit_of_measurement: 'W'
        icon_template: 'mdi:power-cycle'

      trockner_status:
        friendly_name: Status Trockner
        entity_id:
          - input_select.status_trockner
        value_template: >-
          {{ states('input_select.status_trockner') }}
        icon_template: 'mdi:tumble-dryer'

automation:
  - alias: 'Waschmaschine - Ausgeschaltet'
    trigger:
      - platform: state
        entity_id: switch.waschmaschine
        from: 'on'
        to: 'off'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.status_waschmaschine
          option: 'Ausgeschaltet'

  - alias: 'Waschmaschine - Stillstand'
    trigger:
      - platform: numeric_state
        entity_id: sensor.waschmaschine_verbrauch
        below: 10
        for: '00:03:00'
      - platform: state
        entity_id: switch.waschmaschine
        from: 'off'
        to: 'on'
    condition:
      - condition: state
        entity_id: switch.waschmaschine
        state: 'on'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.status_waschmaschine
          option: 'Stillstand'

  - alias: 'Waschmaschine - Waschen'
    trigger:
      - platform: numeric_state
        entity_id: sensor.waschmaschine_verbrauch
        above: 20
        for: '00:01:00'
    condition:
      - condition: state
        entity_id: switch.waschmaschine
        state: 'on'
      - condition: state
        entity_id: input_select.status_waschmaschine
        state: 'Stillstand'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.status_waschmaschine
          option: 'Waschen'

  - alias: 'Trockner - Ausgeschaltet'
    trigger:
      - platform: state
        entity_id: switch.trockner
        from: 'on'
        to: 'off'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.status_trockner
          option: 'Ausgeschaltet'

  - alias: 'Trockner - Stillstand'
    trigger:
      - platform: numeric_state
        entity_id: sensor.trockner_verbrauch
        below: 10
        for: '00:03:00'
      - platform: state
        entity_id: switch.trockner
        from: 'off'
        to: 'on'
    condition:
      - condition: state
        entity_id: switch.trockner
        state: 'on'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.status_trockner
          option: 'Stillstand'

  - alias: 'Trockner - Trocknen'
    trigger:
      - platform: numeric_state
        entity_id: sensor.trockner_verbrauch
        above: 150
        for: '00:01:00'
    condition:
      - condition: state
        entity_id: switch.trockner
        state: 'on'
      - condition: state
        entity_id: input_select.status_trockner
        state: 'Stillstand'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.status_trockner
          option: 'Trocknen'

  - alias: 'Waschmaschine gestartet'
    trigger:
      - platform: state
        entity_id: input_select.status_waschmaschine
        from: 'Stillstand'
        to: 'Waschen'
    condition:
      - condition: state
        entity_id: binary_sensor.zu_hause
        state: 'off'
    action:
      - service: notify.telegram
        data_template:
          title: "Waschmaschine gestartet"
          message: >-
            Die Waschmaschine wurde gestartet.

  - alias: 'Waschmaschine fertig - Trockner einschalten'
    trigger:
      - platform: state
        entity_id: input_select.status_waschmaschine
        from: 'Waschen'
        to: 'Stillstand'
    condition:
      - condition: state
        entity_id: switch.trockner
        state: 'off'
    action:
      - service: switch.turn_on
        entity_id: switch.trockner

  - alias: 'Waschmaschine fertig - TTS'
    trigger:      
      - platform: state
        entity_id: input_select.status_waschmaschine
        from: 'Waschen'
        to: 'Stillstand'
    condition:
      - condition: state
        entity_id: binary_sensor.zu_hause
        state: 'on'        
    action:
      - service: !secret tts_service
        data_template:
          message: >-
            Die Waschmaschine ist fertig.

  - alias: 'Waschmaschine fertig - Telegram'
    trigger:
      - platform: state
        entity_id: input_select.status_waschmaschine
        from: 'Waschen'
        to: 'Stillstand'
    condition:
      - condition: state
        entity_id: binary_sensor.zu_hause
        state: 'off'
    action:
      - service: notify.telegram
        data_template:
          title: "Waschmaschine fertig"
          message: >-
            Die Waschmaschine ist fertig.

  - alias: 'Trockner gestartet - Telegram'
    trigger:
      - platform: state
        entity_id: input_select.status_trockner
        from: 'Stillstand'
        to: 'Trocknen'
    condition:
      - condition: state
        entity_id: binary_sensor.zu_hause
        state: 'off'
    action:
      - service: notify.telegram
        data_template:
          title: "Trockner gestartet"
          message: >-
            Der Trockner wurde gestartet.

  - alias: 'Trockner fertig - TTS'
    trigger:
      - platform: state
        entity_id: input_select.status_trockner
        from: 'Trocknen'
        to: 'Stillstand'
    condition:
      - condition: state
        entity_id: binary_sensor.zu_hause
        state: 'on'        
    action:
      - service: !secret tts_service
        data_template:
          message: >-
            Der Trockner ist fertig.

  - alias: 'Trockner fertig - Telegram'
    trigger:
      - platform: state
        entity_id: input_select.status_trockner
        from: 'Trocknen'
        to: 'Stillstand'
    condition:
      - condition: state
        entity_id: binary_sensor.zu_hause
        state: 'off'
    action:
      - service: notify.telegram
        data_template:
          title: "Trockner fertig"
          message: >-
            Der Trockner ist fertig.