device_tracker:
  - platform: mqtt
    devices:
      pc_arbeit: 'iotlink/schenck/jaeschke-pc/lwt'
    qos: 1
    payload_home: 'ON'
    payload_not_home: 'OFF'
    source_type: router      
      
sensor:
  - platform: here_travel_time
    name: Fahrzeit zur Arbeit
    api_key: !secret here_api_key
    origin_latitude: !secret home_latitude
    origin_longitude: !secret home_longitude
    destination_latitude: !secret work_latitude
    destination_longitude: !secret work_longitude
    traffic_mode: true

  - platform: here_travel_time
    name: Fahrzeit nach Hause
    api_key: !secret here_api_key
    origin_latitude: !secret work_latitude
    origin_longitude: !secret work_longitude    
    destination_latitude: !secret home_latitude
    destination_longitude: !secret home_longitude
    traffic_mode: true

  - platform: template
    sensors:
      abfahrzeit:
        friendly_name: Abfahrzeit
        icon_template: mdi:clock-start
        unit_of_measurement: 'Uhr'
        entity_id:
          - input_select.arbeit_stunden
          - input_select.arbeit_minuten
          - input_select.arbeit_puffer
          - sensor.fahrzeit_zur_arbeit
          - binary_sensor.schlechtes_wetter
        value_template: >-
          {% set minuten_arbeit = (states('input_select.arbeit_stunden') | int * 60) + (states('input_select.arbeit_minuten') | int) | int %}
          {% set verzoegerung_wetter = (10 if is_state('binary_sensor.schlechtes_wetter', 'on') else 0) %}
          {% set minuten_minus_fahrzeit = (minuten_arbeit - states('sensor.fahrzeit_zur_arbeit') | int) - (states('input_select.arbeit_puffer') | int) - (verzoegerung_wetter | int) | int %}
          {% set stunde_abfahrt = (minuten_minus_fahrzeit / 60) | int %}
          {% set minuten_abfahrt = (minuten_minus_fahrzeit - stunde_abfahrt * 60) | int %}
          {% set abfahrt = "%0.02d:%0.02d" | format(stunde_abfahrt, minuten_abfahrt ) %}

          {{ abfahrt }}

binary_sensor:
  - platform: template
    sensors:
      home_office:
        friendly_name: Home Office
        icon_template: mdi:home-city
        entity_id:
          - input_boolean.home_office
          - binary_sensor.arbeitstag
          - calendar.urlaub
          - sensor.time
        value_template: >-
          {% set istHomeOffice = is_state('input_boolean.home_office', 'on') %}
          {% set istArbeitstag = is_state('binary_sensor.arbeitstag', 'on') %}
          {% set keinUrlaub = is_state('calendar.urlaub', 'off') %}
          {% set nachArbeitsBeginn = states('sensor.time') >= (state_attr('input_datetime.arbeit_beginn', 'timestamp') | int | timestamp_custom('%H:%M', False)) %}
          {% set vorArbeitsEnde = states('sensor.time') <= (state_attr('input_datetime.arbeit_ende', 'timestamp') | int | timestamp_custom('%H:%M', False)) %}
          
          {{ True if (istHomeOffice and istArbeitstag and keinUrlaub and nachArbeitsBeginn and vorArbeitsEnde) else False }}
          
switch:
  - platform: template
    switches:
      pc_arbeit:
        friendly_name: PC Arbeit
        entity_id:
          - device_tracker.pc_arbeit
        value_template: "{{ is_state('device_tracker.pc_arbeit', 'home') }}"
        icon_template: mdi:desktop-tower
        turn_on:
          service: wake_on_lan.send_magic_packet
          data:
            mac: !secret computerarbeit_mac
            broadcast_address: !secret fritzbox_broadcast
            broadcast_port: 9
        turn_off:
          service: mqtt.publish
          data:
            topic: "iotlink/schenck/jaeschke-pc/commands/hibernate"
            payload: ""
            
  - platform: mqtt
    name: "Arbeitszimmer Monitor links"
    state_topic: "stat/arbeitszimmermonitorlinks/POWER"
    command_topic: "cmnd/arbeitszimmermonitorlinks/POWER"
    availability_topic: "tele/arbeitszimmermonitorlinks/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"  
          
  - platform: mqtt
    name: "Arbeitszimmer Monitor rechts"
    state_topic: "stat/arbeitszimmermonitorrechts/POWER"
    command_topic: "cmnd/arbeitszimmermonitorrechts/POWER"
    availability_topic: "tele/arbeitszimmermonitorrechts/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"  
    
  - platform: template
    switches:
      arbeitszimmer_monitore:
        friendly_name: Monitore
        icon_template: "mdi:monitor-dashboard"
        value_template: "{{ is_state('switch.arbeitszimmer_monitor_links', 'on') or is_state('switch.arbeitszimmer_monitor_rechts', 'on')}}"
        turn_on:
          service: switch.turn_on
          data:
            entity_id: switch.arbeitszimmer_monitor_links, switch.arbeitszimmer_monitor_rechts
        turn_off:
          service: switch.turn_off
          data:
            entity_id: switch.arbeitszimmer_monitor_links, switch.arbeitszimmer_monitor_rechts
            
input_boolean:
  home_office:
    name: Home Office
    icon: mdi:home-city-outline
  
  computer_arbeit_ausschalten:
    name: Computer Arbeit ausschalten
    initial: on
    icon: mdi:desktop-classic
    
input_datetime:
  arbeit_beginn:
    name: Arbeitsbeginn    
    has_time: true
    icon: mdi:clock-start
    initial: '06:30'
  arbeit_ende:
    name: Arbeitsende    
    has_time: true
    icon: mdi:clock-end
    initial: '15:30'    
    
input_select:
  arbeit_stunden:
    name: Stunde
    options:
      - 5
      - 6
      - 7
    icon: mdi:av-timer

  arbeit_minuten:
    name: Minute
    options:
      - 0
      - 10
      - 20
      - 30
      - 40
      - 50
    icon: mdi:timer

  arbeit_puffer:
    name: Puffer
    options:
      - 0
      - 10
      - 20
      - 30
    icon: mdi:timelapse

script:
  home_office_start:
    alias: 'Home Office - Start'
    sequence:
      - service: switch.turn_off
        entity_id: switch.schlafzimmer_radio, switch.monitor
      - service: switch.turn_on
        entity_id: switch.arbeitszimmer_radio, switch.pc_arbeit, switch.arbeitszimmer_monitore
      - condition: state
        entity_id: input_boolean.computer_ausschalten
        state: 'on'
      - service: switch.turn_off
        entity_id: switch.pc           
          
  home_office_ende:
    alias: 'Home Office - Ende'
    sequence:
      - service: switch.turn_off
        entity_id: switch.arbeitszimmer_radio, switch.arbeitszimmer_monitore
      - service: switch.turn_on
        entity_id: switch.computer
      - condition: state
        entity_id: input_boolean.computer_arbeit_ausschalten
        state: 'on'
      - service: switch.turn_off
        entity_id: switch.pc_arbeit               
        
automation:
  - alias: 'Home Office - Start'
    trigger:
      - platform: state
        entity_id: sensor.schalter_flur
        to: '2'
    condition:
      - condition: state
        entity_id: binary_sensor.home_office
        state: 'on'
      - condition: state
        entity_id: device_tracker.pc_arbeit
        state: 'not_home'        
    action:
      - service: !secret tts_service
        data_template:
          echo: "flur"
          message: "Der Computer im Arbeitszimmer wird jetzt eingeschaltet."
      - service: script.home_office_start      
                  
  - alias: 'Home Office - Ende'
    trigger:
      - platform: state
        entity_id: sensor.schalter_flur
        to: '2'           
    condition:
      - condition: state
        entity_id: device_tracker.pc_arbeit
        state: 'home'  
    action:      
      - service: !secret tts_service
        data_template:
          echo: "flur"
          message: "Der Computer im Arbeitszimmer wird jetzt ausgeschaltet."      
      - service: script.home_office_ende

  - alias: 'Benachrichtigung Arbeit'
    trigger:
      - platform: template
        value_template: '{{ states("sensor.time") == states("sensor.abfahrzeit") }}'
    condition:
      - condition: state
        entity_id: binary_sensor.arbeitstag
        state: 'on'
      - condition: state
        entity_id: calendar.urlaub
        state: 'off'
      - condition: state
        entity_id: input_boolean.home_office
        state: 'off'        
    action:
      - service: !secret tts_service
        data_template:
          message: >-
            "Es ist Zeit zur Arbeit zu fahren. Die aktuelle Fahrzeit beträgt {{ states('sensor.fahrzeit_zur_arbeit') }} Minuten.{% if is_state('binary_sensor.schlechtes_wetter', 'on') %} Aktuell ist mit {{ states('sensor.wetterlage') }} zu rechnen.{% endif %}"

  - alias: 'Telegram - Fahrzeit nach Hause'
    trigger:
      platform: event
      event_type: telegram_command
      event_data:
        command: '/fahrzeit'
    action:
      - service: notify.telegram
        data_template:
          title: "Fahrzeit nach Hause"
          message: >-
            Die Fahrzeit von der Arbeit nach Hause beträgt aktuell {{ states('sensor.fahrzeit_nach_hause') }} Minuten.
            
            
            Die folgende Route wird empfohlen:
            {{ state_attr('sensor.fahrzeit_nach_hause', 'route') }}
          
homeassistant:
  customize:
    sensor.fahrzeit_zur_arbeit:
      icon: mdi:car-estate
    sensor.fahrzeit_nach_hause:
      icon: mdi:car-sports
