input_select:
  arbeit_puffer:
    name: Puffer
    options:
      - "10"
      - "20"
      - "30"
    icon: mdi:timelapse         

input_datetime:
  arbeit_beginn:
    name: Arbeit Beginn
    has_date: false
    has_time: true
    icon: mdi:timer

input_number:   
  arbeit_dauer:
    name: Arbeit Dauer
    min: 0
    max: 12
    step: 1
  
template:
  - binary_sensor:
      - default_entity_id: binary_sensor.buero_heute
        name: Büro heute
        state:  >-
          {% set NextOffice = state_attr('calendar.arbeit_buero', 'start_time') %}

          {% set istBuero = false if NextOffice == None else (NextOffice | as_datetime).strftime('%j')|int - now().strftime('%j')|int == 0 %}         
          {% set istHomeOffice = is_state('input_boolean.home_office', 'on') %}
          {% set istArbeitstag = is_state('binary_sensor.arbeitstag', 'on') %}
          {% set keinUrlaub = is_state('calendar.urlaub', 'off') %}
          {% set nichtKrank = is_state('calendar.arbeit_krank', 'off') %}

          {{ True if (istBuero and istArbeitstag and keinUrlaub and nichtKrank) else False }}
          
      - default_entity_id: binary_sensor.buero_morgen
        name: Büro morgen
        state: >-
          {% set NextOffice = state_attr('calendar.arbeit_buero', 'start_time') %}
          
          {{ false if NextOffice == None else (NextOffice | as_datetime).strftime('%j')|int - now().strftime('%j')|int == 1 }}                          
      
  - sensor:
      - default_entity_id: sensor.abfahrzeit
        name: Abfahrzeit
        icon: mdi:clock-start
        state: >-
          {% set fahrzeitMinuten = states('sensor.fahrzeit_zur_arbeit') | int(0) %}
          {% set beginnMinuten = (state_attr('input_datetime.arbeit_beginn', 'timestamp') / 60) | int(0) %}
          {% set pufferMinuten = states('input_select.arbeit_puffer') | int(0) %}
          {% set verzoegerungWetter = (10 if is_state('binary_sensor.schlechtes_wetter', 'on') else 0) %}

          {% set abfahrzeitMinuten = beginnMinuten - fahrzeitMinuten - pufferMinuten - verzoegerungWetter %}
          {% set stundeAbfahrt = (abfahrzeitMinuten / 60) | int(0) %}
          {% set minuteAbfahrt = (abfahrzeitMinuten - stundeAbfahrt * 60) | int(0) %}
          {% set uhrzeitAbfahrt = "%0.02d:%0.02d" | format(stundeAbfahrt, minuteAbfahrt ) %}

          {{ uhrzeitAbfahrt }}
          
      - default_entity_id: sensor.naechstes_buero
        name: Nächstes Büro
        icon: mdi:briefcase  
        state: >
          {% if state_attr('calendar.arbeit_buero', 'start_time') %}
            {% set weekday = as_timestamp(state_attr('calendar.arbeit_buero', 'start_time'), None) | timestamp_custom("%w", True) | int(0) %}

            {{ ['Montag','Dienstag','Mittwoch','Donnerstag','Freitag','Samstag','Sonntag'][weekday-1] }}, {{ as_timestamp(state_attr('calendar.arbeit_buero', 'start_time'), None) | timestamp_custom("%d.%m.%Y", True) | string }}
          {% else %}
            -
          {% endif %}
                
automation:            
  - alias: 'Fahrzeit aktualisieren'
    id: "fahrzeit_aktualisieren"
    trigger:
      - platform: time_pattern
        minutes: "/5"
    condition:
      - "{{ is_state('binary_sensor.buero_heute', 'on') }}"
      - "{{ is_state('binary_sensor.arbeitstag', 'on') }}"
      - "{{ is_state('calendar.urlaub', 'off') }}"
      - "{{ is_state('calendar.arbeit_krank', 'off') }}"
    action:
      - service: homeassistant.update_entity
        target:
          entity_id:
          - sensor.fahrzeit_nach_hause
          - sensor.fahrzeit_zur_arbeit
          
  - alias: 'Benachrichtigung Arbeit'
    id: "benachrichtigung_arbeit"
    trigger:
      - platform: template
        value_template: '{{ states("sensor.time") == states("sensor.abfahrzeit") }}'
    condition:
      - condition: template
        value_template: >-        
          {% set istBuero = is_state('binary_sensor.buero_heute', 'on') %}          
          {% set istArbeitstag = is_state('binary_sensor.arbeitstag', 'on') %}
          {% set keinUrlaub = is_state('calendar.urlaub', 'off') %}
          {% set nichtKrank = is_state('calendar.arbeit_krank', 'off') %}

          {{ True if (istBuero and istArbeitstag and keinUrlaub and nichtKrank) else False }}        
    action:
      - service: !secret tts_service
        data:
          message: >-
            "Es ist Zeit zur Arbeit zu fahren. Die aktuelle Fahrzeit beträgt {{ states('sensor.fahrzeit_zur_arbeit') }} Minuten.{% if is_state('binary_sensor.schlechtes_wetter', 'on') %} Aktuell ist mit {{ states('sensor.wetterlage') }} zu rechnen.{% endif %}"     

  - alias: "Fahrzeit nach Hause"
    id: "fahrzeit_nach_hause"
    trigger:
      platform: event
      event_type: telegram_command
      event_data:
        command: '/fahrzeit'
    action:
      - service: notify.telegram
        data:
          title: "Fahrzeit nach Hause"
          message: >-
            Die Fahrzeit von der Arbeit nach Hause beträgt aktuell {{ states('sensor.fahrzeit_nach_hause') }} Minuten.
          
homeassistant:
  customize:
    sensor.fahrzeit_zur_arbeit:
      icon: mdi:car-estate
    sensor.fahrzeit_nach_hause:
      icon: mdi:car-sports
