input_number:
  corona_grenzwert:
    name: Corona Grenzwert
    min: 0
    max: 1000
    step: 5

sensor:
  - platform: rest
    resource: https://worldometers.p.rapidapi.com/api/coronavirus/country/Germany
    name: "Corona Deutschland"
    headers:
      x-rapidapi-key: !secret rapidapi_corona_apikey
      x-rapidapi-host: "worldometers.p.rapidapi.com"
    value_template: "[OK]"
    scan_interval: 3600    
    json_attributes:
      - data

  - platform: template
    sensors:
      coronavirus_deutschland_bestaetigt:
          friendly_name: Corona Bestätigt
          icon_template: mdi:emoticon-neutral-outline
          value_template: "{{ state_attr('sensor.corona_deutschland','data')['Total Cases'] | replace(',','') | int(0) }}"
          unit_of_measurement: Personen
          
      coronavirus_deutschland_aktuell:
          friendly_name: Corona Aktuell
          icon_template: mdi:emoticon-sad-outline        
          value_template: "{{ state_attr('sensor.corona_deutschland','data')['Active Cases'] | replace(',','') | int(0) }}"
          unit_of_measurement: Personen
          
      coronavirus_deutschland_tote:
          friendly_name: Corona Tote
          icon_template: mdi:emoticon-cry-outline
          value_template: "{{ state_attr('sensor.corona_deutschland','data')['Total Deaths'] | replace(',','') | int(0) }}"
          unit_of_measurement: Personen
          
      coronavirus_deutschland_genesene:
          friendly_name: Corona Genesene
          icon_template: mdi:emoticon-happy-outline
          value_template: "{{ state_attr('sensor.corona_deutschland','data')['Total Recovered'] | replace(',','') | int(0) }}"
          unit_of_measurement: Personen  