tankerkoenig:
  api_key: !secret tankerkoenig_apikey 
  fuel_types:
    - 'e10'
  radius: 1
  stations:
    - !secret tankerkoenig_id_real
    - !secret tankerkoenig_id_jet
      
input_number:
  corona_grenzwert:
    name: Corona Grenzwert
    min: 0
    max: 1000
    step: 5
    initial: 50  
    
  alexa_timer:
    name: Alexa Timer
    min: 1
    max: 120
    step: 1
    initial: 5      
    
input_text:
  corona_dortmund_gestern:
    name: Corona Dortmund gestern   
  corona_mulheim_gestern:
    name: Corona Mülheim gestern
    
sensor:
  - platform: imap
    server: !secret email_server
    port: 993
    name: Ungelesene Mails
    username: !secret email_username
    password: !secret email_password

  - platform: time_date
    display_options:
      - 'time'
      - 'date'

  - platform: template
    sensors:
      tankstelle_real:
        friendly_name: 'Tankstelle Real'        
        unit_of_measurement: €
        icon_template: mdi:gas-station
        value_template: >-
          {% set price = states('sensor.tankerkoenig_supermarkt_tankstelle_am_real_markt_dortmund_wulfshofstr_e10') %}

          {% if price == 'unknown' %}
            -
          {% else %}
            {{ price }}
          {% endif %}          
      
      tankstelle_jet:
        friendly_name: 'Tankstelle Jet'    
        unit_of_measurement: €
        icon_template: mdi:gas-station
        value_template: >-
          {% set price = states('sensor.tankerkoenig_jet_muelheim_strassburger_allee_75_e10') %}

          {% if price == 'unknown' %}
            -
          {% else %}
            {{ price }}
          {% endif %}
          
      next_launch_day_de:
        friendly_name: 'Nächster Start - Datum'
        icon_template: mdi:calendar
        value_template: '{{ state_attr("sensor.next_launch_day", "launch_date_unix") | int | timestamp_custom("%d.%m.%Y")}}'

      next_launch_time_de:
        friendly_name: 'Nächster Start - Uhrzeit'
        value_template: '{{ state_attr("sensor.next_launch_day", "launch_date_unix") | int | timestamp_custom("%H:%M")}}'
        icon_template: mdi:clock-outline
        unit_of_measurement: 'Uhr'          

binary_sensor:
  - platform: workday
    name: Arbeitstag
    country: DE
    province: NW
    
  - platform: workday
    name: Arbeitstag morgen
    country: DE
    province: NW
    days_offset: 1    
    
  - platform: template
    sensors:
      tankstelle_real_status:
        friendly_name: 'Status'
        device_class: door
        value_template: >-
          {{ is_state_attr('sensor.tankerkoenig_supermarkt_tankstelle_am_real_markt_dortmund_wulfshofstr_e10', 'is_open', True) }}

      tankstelle_jet_status:
        friendly_name: 'Status'
        device_class: door
        value_template: >-
          {{ is_state_attr('sensor.tankerkoenig_jet_muelheim_strassburger_allee_75_e10', 'is_open', True) }}
                
automation:
  - alias: 'Neue E-Mail - Kodi'
    trigger:
      - platform: state
        entity_id: sensor.ungelesene_mails
    condition:
      - condition: state
        entity_id: media_player.kodi_wohnzimmer
        state: 'playing'
      - condition: template     
        value_template: >-
          {% set oldMailCount = trigger.from_state.state | int %}
          {% set newMailCount = trigger.to_state.state | int %}
          
          {{ newMailCount > oldMailCount }}
    action:
      - service: notify.kodi_wohnzimmer
        data:
          title: 'E-Mail'
          message: >-
            {% set mailCount = states('sensor.ungelesene_mails') | default(0) | int %}

            {% if mailCount == 1 %}
              Eine neue E-Mail ist eingegangen.
            {% else %}
              Es sind {{ mailCount }} neue E-Mails eingegangen.
            {% endif %}
          data:
            displaytime: 5000
            icon: "info"

  - alias: "Neue E-Mail - TTS"
    trigger:
      - platform: state
        entity_id: sensor.ungelesene_mails
    condition:
      - condition: state
        entity_id: binary_sensor.zu_hause
        state: 'on'
      - condition: template     
        value_template: >-
          {% set oldMailCount = trigger.from_state.state | int %}
          {% set newMailCount = trigger.to_state.state | int %}
          
          {{ newMailCount > oldMailCount }}        
    action:
      service: !secret tts_service
      data_template:
        message: >-
          {% set mailCount = (trigger.to_state.state | int) - (trigger.from_state.state | int) %}

          {% if mailCount == 1 %}
            Eine neue E-Mail ist eingegangen.
          {% else %}
            Es sind {{ mailCount }} neue E-Mails eingegangen.
          {% endif %}          
          
  - alias: "Corona-Werte geändert"
    trigger:
      - platform: state
        entity_id: sensor.sk_dortmund_weekincidence
        attribute: last_update
      - platform: state
        entity_id: sensor.sk_mulheim_a_d_ruhr_weekincidence
        attribute: last_update          
    action:
      - choose:
          - conditions:
              - condition: template
                value_template: "{{ True if trigger.entity_id == 'sensor.sk_dortmund_weekincidence' else False }}"
            sequence:
              - service: input_text.set_value
                data:
                  entity_id: input_text.corona_dortmund_gestern
                  value: "{{ trigger.from_state.state }}" 
          - conditions:
              - condition: template
                value_template: "{{ True if trigger.entity_id == 'sensor.sk_mulheim_a_d_ruhr_weekincidence' else False }}"
            sequence:
              - service: input_text.set_value
                data:
                  entity_id: input_text.corona_mulheim_gestern
                  value: "{{ trigger.from_state.state }}" 
                
#  - alias: "Alexa Timer"
#    trigger:
#      - platform: state
#        entity_id: input_number.alexa_timer
#    condition:
#      - condition: state
#        entity_id: binary_sensor.zu_hause
#        state: 'on'        
#    action:
#      - service: media_player.play_media
#        entity_id: media_player.echo_wohnzimmer
#        media_content_id: "Stell einen Timer auf {{ input_number.alexa_timer }} Minuten."
#        media_content_type: custom
                  
panel_iframe:
  infoscreen:
    title: Infoscreen
    icon: mdi:information
    url: http://192.168.2.100/infoscreen/

homeassistant:
  customize:
    sensor.countdown_sudtirol:
      unit_of_measurement: Tage
      
    binary_sensor.arbeitstag:
      icon: mdi:account-hard-hat
      
    sensor.time:
      friendly_name: Uhrzeit
      
    sensor.tankerkoenig_dortmund_borussiastrasse_118_e10:
      friendly_name: Tankstelle Borussiastraße
    sensor.tankerkoenig_jet_muelheim_strassburger_allee_75_e10:
      friendly_name: Tankstelle Jet
    sensor.tankerkoenig_supermarkt_tankstelle_am_real_markt_dortmund_wulfshofstr_e10:
      friendly_name: Tankstelle Real
      
    sensor.sk_dortmund_weekincidence:
      icon: mdi:home-analytics
      friendly_name: "Dortmund"
    sensor.sk_mulheim_a_d_ruhr_weekincidence:
      icon: mdi:briefcase
      friendly_name: "Mülheim an der Ruhr"