tankerkoenig:
  api_key: !secret tankerkoenig_apikey 
  fuel_types:
    - 'e10'
  radius: 1
  stations:
    - !secret tankerkoenig_id_real
    - !secret tankerkoenig_id_jet

sensor:
  - platform: imap
    server: !secret email_server
    port: 993
    name: Ungelesene Mails
    username: !secret email_username
    password: !secret email_password

  - platform: time_date
    display_options:
      - 'time'

#  - platform: seventeentrack
#    username: !secret 17track_name
#    password: !secret 17track_password

#  - platform: aftership  
#    api_key: !secret aftership_apikey    
    
  - platform: template
    sensors:
      tankstelle_real:
        friendly_name: 'Tankstelle Real'        
        unit_of_measurement: €
        icon_template: mdi:gas-station
        entity_id:
          - sensor.tankerkoenig_supermarkt_tankstelle_am_real_markt_dortmund_wulfshofstr_e10
        value_template: >-
          {% set price = states('sensor.tankerkoenig_supermarkt_tankstelle_am_real_markt_dortmund_wulfshofstr_e10') %}

          {% if price == 'unknown' %}
            -
          {% else %}
            {{ price }}
          {% endif %}          
      
      tankstelle_jet:
        friendly_name: 'Tankstelle Jet'    
        unit_of_measurement: €
        icon_template: mdi:gas-station
        entity_id:
          - sensor.tankerkoenig_jet_muelheim_strassburger_allee_75_e10
        value_template: >-
          {% set price = states('sensor.tankerkoenig_jet_muelheim_strassburger_allee_75_e10') %}

          {% if price == 'unknown' %}
            -
          {% else %}
            {{ price }}
          {% endif %}
          
      kommende_pakete:
        friendly_name: 'Kommende Pakete'
        entity_id:
          - sensor.aftership
        value_template: >-
          {% set pakete = states('sensor.aftership') | int %}

          {% if pakete == 0 %}
            -
          {% else %}
            {{ pakete }}
          {% endif %}
        icon_template: >-
          mdi:truck-delivery

binary_sensor:
  - platform: workday
    name: Arbeitstag
    country: DE
    province: NW
    
  - platform: workday
    name: Arbeitstag morgen
    country: DE
    province: NW
    days_offset: 1    
    
  - platform: template
    sensors:
      tankstelle_real_status:
        friendly_name: 'Status'
        device_class: door
        entity_id:
          - sensor.tankerkoenig_supermarkt_tankstelle_am_real_markt_dortmund_wulfshofstr_e10
        value_template: >-
          {{ is_state_attr('sensor.tankerkoenig_supermarkt_tankstelle_am_real_markt_dortmund_wulfshofstr_e10', 'is_open', True) }}

      tankstelle_jet_status:
        friendly_name: 'Status'
        device_class: door
        entity_id:
          - sensor.tankerkoenig_jet_muelheim_strassburger_allee_75_e10
        value_template: >-
          {{ is_state_attr('sensor.tankerkoenig_jet_muelheim_strassburger_allee_75_e10', 'is_open', True) }}
       
automation:
  - alias: 'Neue E-Mail - Kodi'
    trigger:
      - platform: numeric_state
        entity_id: sensor.ungelesene_mails
        above: 0
    condition:
      - condition: state
        entity_id: media_player.kodi_wohnzimmer
        state: 'playing'
    action:
      - service: notify.kodi_wohnzimmer
        data:
          title: 'E-Mail'
          message: >-
            {% set mailCount = states('sensor.ungelesene_mails') | default(0) | int %}

            {% if mailCount == 1 %}
              Eine neue E-Mail ist eingegangen.
            {% else %}
              Es sind {{ mailCount }} neue E-Mails eingegangen.
            {% endif %}
          data:
            displaytime: 5000
            icon: "info"

  - alias: "Neue E-Mail - TTS"
    trigger:
      - platform: numeric_state
        entity_id: sensor.ungelesene_mails
        above: 0 
    condition:
      - condition: state
        entity_id: binary_sensor.zu_hause
        state: 'on'
    action:
      service: !secret tts_service
      data_template:
        message: >-
          {% set mailCount = states('sensor.ungelesene_mails') | int %}

          {% if mailCount == 1 %}
            Eine neue E-Mail ist eingegangen.
          {% else %}
            Es sind {{ mailCount }} neue E-Mails eingegangen.
          {% endif %}

panel_iframe:
  infoscreen:
    title: Infoscreen
    icon: mdi:information
    url: http://192.168.2.74/infoscreen/

homeassistant:
  customize:
    sensor.countdown_sudtirol:
      unit_of_measurement: Tage
      
    binary_sensor.arbeitstag:
      icon: mdi:worker
      
    sensor.time:
      friendly_name: Uhrzeit
      
    sensor.tankerkoenig_dortmund_borussiastrasse_118_e10:
      friendly_name: Tankstelle Borussiastraße
    sensor.tankerkoenig_jet_muelheim_strassburger_allee_75_e10:
      friendly_name: Tankstelle Jet
    sensor.tankerkoenig_supermarkt_tankstelle_am_real_markt_dortmund_wulfshofstr_e10:
      friendly_name: Tankstelle Real