tankerkoenig:
  api_key: !secret tankerkoenig_apikey 
  fuel_types:
    - 'e10'
  radius: 1
  stations:
    - !secret tankerkoenig_id_real
    - !secret tankerkoenig_id_jet

input_number:
  alexa_timer:
    name: Alexa Timer
    min: 1
    max: 120
    step: 1
    initial: 5      
    
zodiac:
  
template:
  - trigger:
    - platform: time
      at: "00:00:00"
    - platform: homeassistant
      event: start
    - platform: event
      event_type: event_template_reloaded      
    sensor:
      - unique_id: zeitumstellung
        name: "Zeitumstellung"
        device_class: timestamp
        state: >
          {%- macro hms(t) %}
          {%- set h, m, s = (t.dst() | string).split(':') | map('int') %}
          {{- h * 60 * 60 + m * 60 + s }}
          {%- endmacro %}

          {%- macro is_dst(t) %}
          {{- hms(t) | int != 0 }}
          {%- endmacro %}

          {%- macro finddst(t, kwarg, rng) %}
          {%- set ns = namespace(previous=is_dst(t), found=none) %}
          {%- for i in range(rng) %}
            {%- set ts = t + timedelta(**{kwarg:i}) %}
            {%- if ns.previous != is_dst(ts) and ns.found is none %}
              {%- set ns.found = i %}
            {%- endif %}
          {%- endfor %}
          {{ ns.found }}
          {%- endmacro %}

          {%- set t = now().replace(hour=0, minute=0, second=0, microsecond=0) %}
          {%- set d = finddst(t, 'days', 365) | int - 1 %}
          {%- set h = finddst(t + timedelta(days=d), 'hours', 24) | int %}
          {%- set m = finddst(t + timedelta(days=d, hours=h), 'minutes', 60) | int %}
          {{ (t.astimezone() + timedelta(days=d, hours=h, minutes=m)).isoformat() }}

  - sensor:
    - unique_id: zeitumstellung_tage
      name: "Zeitumstellung Tage"
      unit_of_measurement: Tage
      state: >
        {% set next = states('sensor.zeitumstellung') | as_datetime %}
        {% set today = now().replace(hour=0, minute=0, second=0, microsecond=0) %}
        
        {{ (next - today).days if next is not none else 0 }}
      availability: >
        {{ states('sensor.zeitumstellung') not in ['unknown', 'unavailable'] }}

    - unique_id: zeitumstellung_richtung
      name: "Zeitumstellung Richtung"
      state: >
        {%- macro hms(t) %}
        {%- set h, m, s = (t.dst() | string).split(':') | map('int') %}
        {{- h * 60 * 60 + m * 60 + s }}
        {%- endmacro %}

        {%- macro phrase(seconds, name, divisor, mod=None) %}
          {%- set value = ((seconds | abs // divisor) % (mod if mod else divisor)) | int %}
          {%- set end = 'n' if value > 1 else '' %}
          {{- '{} {}{}'.format(value, name, end) if value > 0 else '' }}
        {%- endmacro %}

        {%- macro total(seconds) %}
        {%- set values = [ 
          phrase(seconds, 'Stunde', 60*60, 60*60*24),
          phrase(seconds, 'Minute', 60, 60),
          ] | select('!=','') | list %}
        {{- values[:-1] | join(', ') ~ ' and ' ~ values[-1] if values | length > 1 else values | first }}
        {%- endmacro %}

        {%- set next = states('sensor.zeitumstellung') %}
        {%- set nextLocal = None if next in ['unknown', 'unavailable'] else next | as_datetime | as_local %}
        
        {%- if nextLocal is not none %}
          {%- set ns = hms(nextLocal) | int %}
          {%- set ps = hms(nextLocal - timedelta(days=1)) | int %}
          {% if ns %}
            {{ total(ns) }} vor
          {% else %}
            {{ total(ps) }} zurück
          {% endif %}
        {%- endif %}
      availability: >
        {{ states('sensor.zeitumstellung') not in ['unknown', 'unavailable'] }}  
  
sensor:
  - platform: imap
    server: !secret email_server
    port: 993
    name: Ungelesene Mails
    username: !secret email_username
    password: !secret email_password

  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time'

  - platform: bitcoin
    currency: 'EUR'
    display_options:
      - exchangerate
      - trade_volume_btc

  - platform: template
    sensors:
      tankstelle_real:
        friendly_name: 'Tankstelle Real'        
        unit_of_measurement: €
        icon_template: mdi:gas-station
        value_template: >-
          {% set price = states('sensor.tankerkoenig_supermarkt_tankstelle_am_real_markt_dortmund_wulfshofstr_e10') %}

          {% if price == 'unknown' %}
            -
          {% else %}
            {{ price }}
          {% endif %}          
      
      tankstelle_jet:
        friendly_name: 'Tankstelle Jet'    
        unit_of_measurement: €
        icon_template: mdi:gas-station
        value_template: >-
          {% set price = states('sensor.tankerkoenig_jet_muelheim_strassburger_allee_75_e10') %}

          {% if price == 'unknown' %}
            -
          {% else %}
            {{ price }}
          {% endif %}
          
      next_launch_day_de:
        friendly_name: 'Nächster Start - Datum'
        icon_template: mdi:calendar
        value_template: '{{ state_attr("sensor.next_launch_day", "launch_date_unix") | int | timestamp_custom("%d.%m.%Y")}}'

      next_launch_time_de:
        friendly_name: 'Nächster Start - Uhrzeit'
        value_template: '{{ state_attr("sensor.next_launch_day", "launch_date_unix") | int | timestamp_custom("%H:%M")}}'
        icon_template: mdi:clock-outline
        unit_of_measurement: 'Uhr'          
          
binary_sensor:   
  - platform: template
    sensors:
      tankstelle_real_status:
        friendly_name: 'Status'
        device_class: door
        value_template: >-
          {{ is_state_attr('sensor.tankerkoenig_supermarkt_tankstelle_am_real_markt_dortmund_wulfshofstr_e10', 'is_open', True) }}

      tankstelle_jet_status:
        friendly_name: 'Status'
        device_class: door
        value_template: >-
          {{ is_state_attr('sensor.tankerkoenig_jet_muelheim_strassburger_allee_75_e10', 'is_open', True) }}
                
automation:
  - alias: "Neue E-Mail"
    id: "neue_email"
    trigger:
      - platform: state
        entity_id: sensor.ungelesene_mails
    condition:
      - condition: state
        entity_id: person.dennis
        state: 'home'
      - condition: state
        entity_id: binary_sensor.schlafen_aktiv
        state: 'off'        
      - condition: template     
        value_template: >-
          {% set oldMailCount = trigger.from_state.state | int %}
          {% set newMailCount = trigger.to_state.state | int %}
          
          {{ newMailCount > oldMailCount }}        
    action:
      - service: !secret tts_service
        data:
          message: >-
            {% set mailCount = (trigger.to_state.state | int) - (trigger.from_state.state | int) %}

            {% if mailCount == 1 %}
              Eine neue E-Mail ist eingegangen.
            {% else %}
              Es sind {{ mailCount }} neue E-Mails eingegangen.
            {% endif %}      
      - choose:
          - conditions:
              - condition: state
                entity_id: media_player.kodi_wohnzimmer
                state: 'playing'
            sequence:
              - service: notify.kodi_wohnzimmer
                data:
                  title: 'E-Mail'
                  message: >-
                    {% set mailCount = states('sensor.ungelesene_mails') | default(0) | int %}

                    {% if mailCount == 1 %}
                      Eine neue E-Mail ist eingegangen.
                    {% else %}
                      Es sind {{ mailCount }} neue E-Mails eingegangen.
                    {% endif %}
                  data:
                    displaytime: 5000
                    icon: "info"

  - alias: "Telegram - Tanken"
    id: "telegram_tanken"
    trigger:
      platform: event
      event_type: telegram_command
      event_data:
        command: '/tanken'
    action:
      - service: notify.telegram
        data:
          title: "Aktuelle Benzinpreise"
          message: >
            Real: {% if states('sensor.tankstelle_real') != 'unknown' %}{{ states('sensor.tankstelle_real') }}€{% else %}{%if states('sensor.tankstelle_real_status') == 'off' %}geschlossen{% else %}-{% endif %}{% endif %}

            Jet: {% if states('sensor.tankstelle_jet') != 'unknown' %}{{ states('sensor.tankstelle_jet') }}€{% else %}{%if states('sensor.tankstelle_jet_status') == 'off' %}geschlossen{% else %}-{% endif %}{% endif %}
                  
panel_iframe:
  infoscreen:
    title: Infoscreen
    icon: mdi:information
    url: http://192.168.2.100/infoscreen/

homeassistant:
  customize:      
    binary_sensor.arbeitstag:
      icon: mdi:account-hard-hat
      
    sensor.time:
      friendly_name: Uhrzeit
      
    sensor.tankerkoenig_dortmund_borussiastrasse_118_e10:
      friendly_name: Tankstelle Borussiastraße
    sensor.tankerkoenig_jet_muelheim_strassburger_allee_75_e10:
      friendly_name: Tankstelle Jet
    sensor.tankerkoenig_supermarkt_tankstelle_am_real_markt_dortmund_wulfshofstr_e10:
      friendly_name: Tankstelle Real
      
    sensor.sk_dortmund_weekincidence:
      icon: mdi:home-analytics
      friendly_name: "Dortmund"
    sensor.sk_mulheim_a_d_ruhr_weekincidence:
      icon: mdi:briefcase
      friendly_name: "Mülheim an der Ruhr"