tankerkoenig:
  api_key: !secret tankerkoenig_apikey 
  fuel_types:
    - 'e10'
  radius: 1
  stations:
    - !secret tankerkoenig_id_real
    - !secret tankerkoenig_id_jet
      
input_text:
  einkaufen:
    name: Einkaufen    
      
input_select:
  einkaufen:
    name: Einkaufsliste
    options:
      - Artikel auswählen
      
sensor:
  - platform: imap
    server: !secret email_server
    port: 993
    name: Ungelesene Mails
    username: !secret email_username
    password: !secret email_password

  - platform: time_date
    display_options:
      - 'time'
      - 'date'

  - platform: template
    sensors:
      tankstelle_real:
        friendly_name: 'Tankstelle Real'        
        unit_of_measurement: €
        icon_template: mdi:gas-station
        entity_id:
          - sensor.tankerkoenig_supermarkt_tankstelle_am_real_markt_dortmund_wulfshofstr_e10
        value_template: >-
          {% set price = states('sensor.tankerkoenig_supermarkt_tankstelle_am_real_markt_dortmund_wulfshofstr_e10') %}

          {% if price == 'unknown' %}
            -
          {% else %}
            {{ price }}
          {% endif %}          
      
      tankstelle_jet:
        friendly_name: 'Tankstelle Jet'    
        unit_of_measurement: €
        icon_template: mdi:gas-station
        entity_id:
          - sensor.tankerkoenig_jet_muelheim_strassburger_allee_75_e10
        value_template: >-
          {% set price = states('sensor.tankerkoenig_jet_muelheim_strassburger_allee_75_e10') %}

          {% if price == 'unknown' %}
            -
          {% else %}
            {{ price }}
          {% endif %}

binary_sensor:
  - platform: workday
    name: Arbeitstag
    country: DE
    province: NW
    
  - platform: workday
    name: Arbeitstag morgen
    country: DE
    province: NW
    days_offset: 1    
    
  - platform: template
    sensors:
      tankstelle_real_status:
        friendly_name: 'Status'
        device_class: door
        entity_id:
          - sensor.tankerkoenig_supermarkt_tankstelle_am_real_markt_dortmund_wulfshofstr_e10
        value_template: >-
          {{ is_state_attr('sensor.tankerkoenig_supermarkt_tankstelle_am_real_markt_dortmund_wulfshofstr_e10', 'is_open', True) }}

      tankstelle_jet_status:
        friendly_name: 'Status'
        device_class: door
        entity_id:
          - sensor.tankerkoenig_jet_muelheim_strassburger_allee_75_e10
        value_template: >-
          {{ is_state_attr('sensor.tankerkoenig_jet_muelheim_strassburger_allee_75_e10', 'is_open', True) }}
       
script:
  einkaufen_artikel_hinzu:
    alias: "Einkaufen - Artikel hinzufügen"
    sequence:
      - condition: template
        value_template: >-
          {{ states('input_text.einkaufen') != '' }}      
      - service: !secret tts_service
        data_template:
          message: >-
            {{ states('input_text.einkaufen') }} wird der Einkaufsliste hinzugefügt.
      - service: gkeep.new_item
        data_template:          
          item_title: "{{ states('input_text.einkaufen') }}"     
      - service: input_text.set_value
        data_template:
          entity_id: input_text.einkaufen
          value: ""
          
automation:
  - alias: 'Neue E-Mail - Kodi'
    trigger:
      - platform: state
        entity_id: sensor.ungelesene_mails
    condition:
      - condition: state
        entity_id: media_player.kodi_wohnzimmer
        state: 'playing'
      - condition: template     
        value_template: >-
          {% set oldMailCount = trigger.from_state.state | int %}
          {% set newMailCount = trigger.to_state.state | int %}
          
          {{ newMailCount > oldMailCount }}
    action:
      - service: notify.kodi_wohnzimmer
        data:
          title: 'E-Mail'
          message: >-
            {% set mailCount = states('sensor.ungelesene_mails') | default(0) | int %}

            {% if mailCount == 1 %}
              Eine neue E-Mail ist eingegangen.
            {% else %}
              Es sind {{ mailCount }} neue E-Mails eingegangen.
            {% endif %}
          data:
            displaytime: 5000
            icon: "info"

  - alias: "Neue E-Mail - TTS"
    trigger:
      - platform: state
        entity_id: sensor.ungelesene_mails
    condition:
      - condition: state
        entity_id: binary_sensor.zu_hause
        state: 'on'
      - condition: template     
        value_template: >-
          {% set oldMailCount = trigger.from_state.state | int %}
          {% set newMailCount = trigger.to_state.state | int %}
          
          {{ newMailCount > oldMailCount }}        
    action:
      service: !secret tts_service
      data_template:
        message: >-
          {% set mailCount = (trigger.to_state.state | int) - (trigger.from_state.state | int) %}

          {% if mailCount == 1 %}
            Eine neue E-Mail ist eingegangen.
          {% else %}
            Es sind {{ mailCount }} neue E-Mails eingegangen.
          {% endif %}
          
  - alias: "Einkaufen - Liste aktualisieren"
    trigger:
      - platform: state
        entity_id: sensor.gkeep_einkaufen
    action:
      - service: python_script.input_select_set_options        
        data_template:
          entity_inputselect: input_select.einkaufen
#          empty_value: "Artikel auswählen"
          data_source: >-
            {% set items = state_attr('sensor.gkeep_einkaufen', 'items') %}
            {% set data = namespace(items = []) -%}

            {% for item in items %}
              {% if item.checked == False %}
                {%- set data.items = data.items + [item.name] -%}
              {% endif %}
            {% endfor %}

            {{ data.items|join(",") }}        
          
panel_iframe:
  infoscreen:
    title: Infoscreen
    icon: mdi:information
    url: http://192.168.2.100/infoscreen/

homeassistant:
  customize:
    sensor.countdown_sudtirol:
      unit_of_measurement: Tage
      
    binary_sensor.arbeitstag:
      icon: mdi:account-hard-hat
      
    sensor.time:
      friendly_name: Uhrzeit
      
    sensor.tankerkoenig_dortmund_borussiastrasse_118_e10:
      friendly_name: Tankstelle Borussiastraße
    sensor.tankerkoenig_jet_muelheim_strassburger_allee_75_e10:
      friendly_name: Tankstelle Jet
    sensor.tankerkoenig_supermarkt_tankstelle_am_real_markt_dortmund_wulfshofstr_e10:
      friendly_name: Tankstelle Real