#tankerkoenig:
#  api_key: tankerkoenig_apikey 
#  fuel_types:
#    - 'e10'
#  stations:
#    - !secret tankerkoenig_id_real
#    - !secret tankerkoenig_id_jet

sensor:
  - platform: imap
    server: mail.manitu.de
    port: 993
    name: Ungelesene Mails
    username: !secret email_username
    password: !secret email_password

  - platform: rest
    resource: !secret tankerkoenig_url_real
    name: Tankstelle Real
    unit_of_measurement: '€'
    value_template: >-
      {% if value_json.prices is defined == False %}
        -
      {% elif value_json.prices["51d4b714-a095-1aa0-e100-80009459e03a"] is defined == False or value_json.prices["51d4b714-a095-1aa0-e100-80009459e03a"].e10 is defined == False %}
        -
      {% else %}
        {{ value_json.prices["51d4b714-a095-1aa0-e100-80009459e03a"].e10 }}
      {% endif %}
    scan_interval: 1800
    json_attributes:
      - prices

  - platform: rest
    resource: !secret tankerkoenig_url_jet
    name: Tankstelle Jet
    unit_of_measurement: '€'
    value_template: >-
      {% if value_json.prices is defined == False %}
        -
      {% elif value_json.prices["51d4b5ae-a095-1aa0-e100-80009459e03a"] is defined == False or value_json.prices["51d4b5ae-a095-1aa0-e100-80009459e03a"].e10 is defined == False %}
        -
      {% else %}
        {{ value_json.prices["51d4b5ae-a095-1aa0-e100-80009459e03a"].e10 }}
      {% endif %}
    scan_interval: 1800
    json_attributes:
      - prices

  - platform: date_countdown
    name: Countdown Neuhaus
    date: '2020-07-18'
    
  - platform: time_date
    display_options:
      - 'time'

  - platform: seventeentrack
    username: !secret 17track_name
    password: !secret 17track_password

  - platform: template
    sensors:
      kommende_pakete:
        friendly_name: 'Kommende Pakete'
        entity_id:
          - sensor.packages_in_transit
        value_template: >-
          {% set pakete = states('sensor.packages_in_transit') | int %}

          {% if pakete == 0 %}
            -
          {% else %}
            {{ pakete }}
          {% endif %}
        icon_template: >-
          mdi:truck-delivery

binary_sensor:
  - platform: workday
    name: Arbeitstag
    country: DE
    province: NW
    
  - platform: template
    sensors:
      tankstelle_real_status:
        friendly_name: 'Status'
        device_class: door
        entity_id:
          - sensor.tankstelle_real
        value_template: >-
          {% set prices = state_attr('sensor.tankstelle_real', 'prices') %}
          
          {% if prices['51d4b714-a095-1aa0-e100-80009459e03a'] %}
            {% if prices['51d4b714-a095-1aa0-e100-80009459e03a']['status'] %}
              {{ prices['51d4b714-a095-1aa0-e100-80009459e03a']['status'] == 'open' }}
            {% else %}
              False
            {% endif %}            
          {% else %}
            False
          {% endif %}

      tankstelle_jet_status:
        friendly_name: 'Status'
        device_class: door
        entity_id:
          - sensor.tankstelle_jet
        value_template: >-
          {% set prices = state_attr('sensor.tankstelle_jet', 'prices') %}
          
          {% if prices['51d4b5ae-a095-1aa0-e100-80009459e03a'] %}
            {% if prices['51d4b5ae-a095-1aa0-e100-80009459e03a']['status'] %}
              {{ prices['51d4b5ae-a095-1aa0-e100-80009459e03a']['status'] == 'open' }}
            {% else %}
              False
            {% endif %}            
          {% else %}
            False
          {% endif %}          

automation:
  - alias: 'Neue E-Mail - Kodi'
    trigger:
      - platform: numeric_state
        entity_id: sensor.ungelesene_mails
        above: 0
    condition:
      - condition: state
        entity_id: media_player.kodi_wohnzimmer
        state: 'playing'
    action:
      - service: notify.kodi_wohnzimmer
        data:
          title: 'E-Mail'
          message: >-
            {% set mailCount = states('sensor.ungelesene_mails') | default(0) | int %}

            {% if mailCount == 1 %}
              Eine neue E-Mail ist eingegangen.
            {% else %}
              Es sind {{ mailCount }} neue E-Mails eingegangen.
            {% endif %}
          data:
            displaytime: 5000
            icon: "info"

  - alias: "Neue E-Mail - TTS"
    trigger:
      - platform: numeric_state
        entity_id: sensor.ungelesene_mails
        above: 0 
    condition:
      - condition: state
        entity_id: binary_sensor.zu_hause
        state: 'on'
    action:
      service: !secret tts_service
      data_template:
        message: >-
          {% set mailCount = states('sensor.ungelesene_mails') | int %}

          {% if mailCount == 1 %}
            Eine neue E-Mail ist eingegangen.
          {% else %}
            Es sind {{ mailCount }} neue E-Mails eingegangen.
          {% endif %}

panel_iframe:
  infoscreen:
    title: Infoscreen
    icon: mdi:information
    url: http://192.168.2.74/infoscreen/

homeassistant:
  customize:
    binary_sensor.arbeitstag:
      icon: mdi:worker
      
    sensor.time:
      friendly_name: Uhrzeit
      hidden: true

    sensor.tankstelle_real:
      icon: mdi:gas-station