calendar:
  - platform: caldav
    url: !secret nextcloud_calendar_url
    username: !secret nextcloud_username
    password: !secret nextcloud_password

google:
  client_id: !secret google_clientid
  client_secret: !secret google_apikey

binary_sensor:
  - platform: template
    sensors:
      urlaub_morgen:
        friendly_name: 'Urlaub morgen'
        device_class: opening
        value_template: >-
          {% set nextVacation = state_attr('calendar.urlaub', 'start_time') %}
          
          {% if nextVacation == None %}
            False
          {% else %}
            {% set nextVacationTime = strptime(state_attr('calendar.urlaub', 'start_time'),'%Y-%m-%d %H:%M:%S') %}

            {{ nextVacationTime.strftime('%j')|int - now().strftime('%j')|int == 1 }}          
          {% endif %}

      formeleins_aktiv:
        friendly_name: 'Formel 1 aktiv'
        value_template: "{{ is_state('media_player.kodi_wohnzimmer', 'playing') and 'Live F1' in state_attr('media_player.kodi_wohnzimmer', 'media_title') }}"
          
sensor:
  - platform: template
    sensors:
      edg_restmuell:
        friendly_name: Restmüll
        value_template: >
          {% if state_attr('calendar.edg_restmuell', 'start_time') %}
            {% set weekday = as_timestamp(state_attr('calendar.edg_restmuell', 'start_time')) | timestamp_custom("%w", True) | int %}

            {{ ['Montag','Dienstag','Mittwoch','Donnerstag','Freitag','Samstag','Sonntag'][weekday-1] }}, {{ as_timestamp(state_attr('calendar.edg_restmuell', 'start_time')) | timestamp_custom("%d.%m.%Y", True) | string }}
          {% else %}
            -
          {% endif %}
        icon_template: mdi:trash-can

      edg_wertstoff:
        friendly_name: Wertstoff
        value_template: >
          {% if state_attr('calendar.edg_wertstoff', 'start_time') %}
            {% set weekday = as_timestamp(state_attr('calendar.edg_wertstoff', 'start_time')) | timestamp_custom("%w", True) | int %}

            {{ ['Montag','Dienstag','Mittwoch','Donnerstag','Freitag','Samstag','Sonntag'][weekday-1] }}, {{ as_timestamp(state_attr('calendar.edg_wertstoff', 'start_time')) | timestamp_custom("%d.%m.%Y", True) | string }}
          {% else %}
            -
          {% endif %}
        icon_template: mdi:recycle

      edg_papier:
        friendly_name: Papier
        value_template: >
          {% if state_attr('calendar.edg_papier', 'start_time') %}
            {% set weekday = as_timestamp(state_attr('calendar.edg_papier', 'start_time')) | timestamp_custom("%w", True) | int %}

            {{ ['Montag','Dienstag','Mittwoch','Donnerstag','Freitag','Samstag','Sonntag'][weekday-1] }}, {{ as_timestamp(state_attr('calendar.edg_papier', 'start_time')) | timestamp_custom("%d.%m.%Y", True) | string }}
          {% else %}
            -
          {% endif %}
        icon_template: mdi:newspaper

      bvb_spiel:
        friendly_name: Nächstes Spiel
        value_template: >
          {% if state_attr('calendar.borussia_dortmund', 'message') %}
            {{ state_attr('calendar.borussia_dortmund', 'message') }}
          {% else %}
            -
          {% endif %}
        icon_template: mdi:soccer

      bvb_datum:
        friendly_name: Datum
        value_template: >
          {% if state_attr('calendar.borussia_dortmund', 'start_time') %}
            {% set weekday = as_timestamp(state_attr('calendar.borussia_dortmund', 'start_time')) | timestamp_custom("%w", True) | int %}

            {{ ['Montag','Dienstag','Mittwoch','Donnerstag','Freitag','Samstag','Sonntag'][weekday-1] }}, {{ as_timestamp(state_attr('calendar.borussia_dortmund', 'start_time')) | timestamp_custom("%d.%m.%Y", True) | string }}
          {% else %}
            -
          {% endif %}
        icon_template: mdi:calendar-alert

      bvb_uhrzeit:
        friendly_name: Uhrzeit
        value_template: >
          {% if state_attr('calendar.borussia_dortmund', 'start_time') %}
            {{ as_timestamp(state_attr('calendar.borussia_dortmund', 'start_time')) | timestamp_custom("%H:%M Uhr", True) | string }}
          {% else %}
            -
          {% endif %}
        icon_template: mdi:clock-outline

      bvb_ort:
        friendly_name: Ort
        value_template: >
          {% if state_attr('calendar.borussia_dortmund', 'location') %}
            {{ state_attr('calendar.borussia_dortmund', 'location') }}
          {% else %}
            -
          {% endif %}
        icon_template: mdi:city

      formel1_rennen:
        friendly_name: Nächstes Rennen
        value_template: >       
          {% set ort = state_attr('calendar.formel1_rennen', 'location') %}          
          {% set location = state_attr('calendar.formel1_rennen', 'message').split(':')[1].split('/') %}

          {% if ort != None and ort != '' %}
            {{ ort }}
          {% elif location != None and location != '' %}
            {{ location[1] }} ({{ location[0].strip() }})
          {% else %}
            -
          {% endif %}
        icon_template: mdi:car-sports

      formel1_datum:
        friendly_name: Datum
        value_template: >
          {% set rennen = state_attr('calendar.formel1_rennen', 'start_time') %}
        
          {% if rennen == None %}
            -
          {% else %}
            {% set rennenTs = as_timestamp(state_attr('calendar.formel1_rennen', 'start_time')) %}
            {{ rennenTs | timestamp_custom("%d.%m.%Y", True) | string }}, {{ rennenTs | timestamp_custom("%H:%M Uhr", True) | string }}       
          {% endif %}         
        icon_template: mdi:calendar-alert

      formel1_qualifikation:
        friendly_name: Qualifikation
        value_template: >
          {% set qualifikation = state_attr('calendar.formel1_qualifikation', 'start_time') %}
          {% set rennen = state_attr('calendar.formel1_rennen', 'start_time') %}
          
          {% if qualifikation == None or rennen == None %}
            -
          {% else %}
            {% set qualifikationTs = as_timestamp(state_attr('calendar.formel1_qualifikation', 'start_time')) %}
            {% set rennenTs = as_timestamp(state_attr('calendar.formel1_rennen', 'start_time')) %}
            
            {% if qualifikation > rennen %}
              -
            {% else %}
              {% if state_attr('calendar.formel1_qualifikation', 'start_time') %}
                {{ qualifikationTs | timestamp_custom("%d.%m.%Y", True) | string }}, {{ qualifikationTs | timestamp_custom("%H:%M Uhr", True) | string }}
              {% else %}
                -
              {% endif %}
            {% endif %}
          {% endif %}       
        icon_template: mdi:car-sports

      naechster_urlaub:
        friendly_name: Nächster Urlaub
        value_template: >
          {% if state_attr('calendar.urlaub', 'start_time') %}          
            {% set weekday = as_timestamp(state_attr('calendar.urlaub', 'start_time')) | timestamp_custom("%w", True) | int %}

            {{ ['Montag','Dienstag','Mittwoch','Donnerstag','Freitag','Samstag','Sonntag'][weekday-1] }}, {{ as_timestamp(state_attr('calendar.urlaub', 'start_time')) | timestamp_custom("%d.%m.%Y", True) | string }}
          {% else %}
            -
          {% endif %}
        friendly_name_template: >-
          {% if state_attr('calendar.urlaub', 'message') %}
            {{ state_attr('calendar.urlaub', 'message') }}
          {% else %}
            -
          {% endif %}          
        icon_template: mdi:sunglasses
        
      naechster_feiertag:
        friendly_name: Nächster Feiertag
        value_template: >
          {% if state_attr('calendar.ferien_feiertage', 'start_time') %}             
            {% set weekday = as_timestamp(state_attr('calendar.ferien_feiertage', 'start_time')) | timestamp_custom("%w", True) | int %}

            {{ ['Montag','Dienstag','Mittwoch','Donnerstag','Freitag','Samstag','Sonntag'][weekday-1] }}, {{ as_timestamp(state_attr('calendar.ferien_feiertage', 'start_time')) | timestamp_custom("%d.%m.%Y", True) | string }}
          {% else %}
            -
          {% endif %}
        friendly_name_template: >-
          {% if state_attr('calendar.ferien_feiertage', 'message') %}
            {{ state_attr('calendar.ferien_feiertage', 'message') }}
          {% else %}
            -
          {% endif %}
        icon_template: mdi:calendar-star
        
automation:
  - alias: "Formel 1 - Wiedergabe pausieren"
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.formeleins_aktiv   
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: binary_sensor.formeleins_aktiv
                state: 'on'
            sequence:
              - service: input_boolean.turn_off
                entity_id: input_boolean.kodi_pausieren
        default:
          - service: input_boolean.turn_on
            entity_id: input_boolean.kodi_pausieren          