calendar:
  - platform: caldav
    url: !secret nextcloud_calendar_url
    username: !secret nextcloud_username
    password: !secret nextcloud_password

google:
  client_id: !secret google_clientid
  client_secret: !secret google_apikey

binary_sensor:
  - platform: template
    sensors:
      urlaub_morgen:
        friendly_name: 'Urlaub morgen'
        device_class: opening
        value_template: >-
          {% if state_attr('calendar.urlaub', 'start_time') == None %}
            False
          {% else %}
            {% set nextVacationTime = strptime(state_attr('calendar.urlaub', 'start_time'),'%Y-%m-%d %H:%M:%S', None) %}

            {{ nextVacationTime.strftime('%j')|int - now().strftime('%j')|int == 1 }}          
          {% endif %}
          
      krank_morgen:
        friendly_name: 'Krank morgen'
        device_class: opening
        value_template: >-
          {% if not state_attr('calendar.arbeit_krank', 'end_time') %}
            False
          {% else %}
            {% set nextEndTime = state_attr('calendar.arbeit_krank', 'end_time') | as_datetime %}

            {{ nextEndTime.strftime('%j')|int - now().strftime('%j')|int >= 1 }}          
          {% endif %}          
          
      adventszeit:
        friendly_name: 'Adventszeit'
        value_template: >-
          {% set first_advent = now().replace(day=25, month=12) - timedelta(days = 21 + now().replace(day=25, month=12).isoweekday() ) %}
          {{ first_advent <= now() <= now().replace(day=26, month=12) }}
        icon_template: >-
          {% set first_advent = now().replace(day=25, month=12) - timedelta(days = 21 + now().replace(day=25, month=12).isoweekday() ) %}
          {{ 'mdi:string-lights' if first_advent <= now() <= now().replace(day=26, month=12) else 'mdi:string-lights-off' }}          
         
sensor:
  - platform: template
    sensors:
      edg_restmuell:
        friendly_name: Restmüll
        value_template: >
          {% if state_attr('calendar.edg_restmuell', 'start_time') %}
            {% set weekday = as_timestamp(state_attr('calendar.edg_restmuell', 'start_time'), None) | timestamp_custom("%w", True) | int(0) %}

            {{ ['Montag','Dienstag','Mittwoch','Donnerstag','Freitag','Samstag','Sonntag'][weekday-1] }}, {{ as_timestamp(state_attr('calendar.edg_restmuell', 'start_time'), None) | timestamp_custom("%d.%m.%Y", True) | string }}
          {% else %}
            -
          {% endif %}
        icon_template: mdi:trash-can

      edg_wertstoff:
        friendly_name: Wertstoff
        value_template: >
          {% if state_attr('calendar.edg_wertstoff', 'start_time') %}
            {% set weekday = as_timestamp(state_attr('calendar.edg_wertstoff', 'start_time'), None) | timestamp_custom("%w", True) | int(0) %}

            {{ ['Montag','Dienstag','Mittwoch','Donnerstag','Freitag','Samstag','Sonntag'][weekday-1] }}, {{ as_timestamp(state_attr('calendar.edg_wertstoff', 'start_time'), None) | timestamp_custom("%d.%m.%Y", True) | string }}
          {% else %}
            -
          {% endif %}
        icon_template: mdi:recycle

      edg_papier:
        friendly_name: Papier
        value_template: >
          {% if state_attr('calendar.edg_papier', 'start_time') %}
            {% set weekday = as_timestamp(state_attr('calendar.edg_papier', 'start_time'), None) | timestamp_custom("%w", True) | int(0) %}

            {{ ['Montag','Dienstag','Mittwoch','Donnerstag','Freitag','Samstag','Sonntag'][weekday-1] }}, {{ as_timestamp(state_attr('calendar.edg_papier', 'start_time'), None) | timestamp_custom("%d.%m.%Y", True) | string }}
          {% else %}
            -
          {% endif %}
        icon_template: mdi:newspaper

      bvb_spiel:
        friendly_name: Nächstes Spiel
        value_template: >
          {% if state_attr('calendar.borussia_dortmund', 'message') %}
            {{ state_attr('calendar.borussia_dortmund', 'message') }}
          {% else %}
            -
          {% endif %}
        icon_template: mdi:soccer

      bvb_datum:
        friendly_name: Datum
        value_template: >
          {% if state_attr('calendar.borussia_dortmund', 'start_time') %}
            {% set weekday = as_timestamp(state_attr('calendar.borussia_dortmund', 'start_time'), None) | timestamp_custom("%w", True) | int(0) %}

            {{ ['Montag','Dienstag','Mittwoch','Donnerstag','Freitag','Samstag','Sonntag'][weekday-1] }}, {{ as_timestamp(state_attr('calendar.borussia_dortmund', 'start_time'), None) | timestamp_custom("%d.%m.%Y", True) | string }}
          {% else %}
            -
          {% endif %}
        icon_template: mdi:calendar-alert

      bvb_uhrzeit:
        friendly_name: Uhrzeit
        value_template: >
          {% if state_attr('calendar.borussia_dortmund', 'start_time') %}
            {% set dateSplitted = state_attr('calendar.borussia_dortmund', 'start_time').split(' ') %}
            {% set timeSplitted = dateSplitted[1].split(':') %}
            {{ timeSplitted[0] ~ ':' ~ timeSplitted[1] ~ ' Uhr' }}            
          {% else %}
            -
          {% endif %}
        icon_template: mdi:clock-outline

      bvb_ort:
        friendly_name: Ort
        value_template: >
          {% if state_attr('calendar.borussia_dortmund', 'location') %}
            {{ state_attr('calendar.borussia_dortmund', 'location') }}
          {% else %}
            -
          {% endif %}
        icon_template: mdi:city

      dfb_spiel:
        friendly_name: Nächstes Spiel
        value_template: >
          {% if state_attr('calendar.nationalmannschaft', 'message') %}
            {% set messageSplitted = state_attr('calendar.nationalmannschaft', 'message').split(' | ') %}

            {% if  messageSplitted|length == 1 %}
              {{ messageSplitted[0] }}
            {% else %}
              {{ messageSplitted[0] ~ ' (' ~ messageSplitted[1] ~ ')' }}
            {% endif %}           
          {% else %}
            -
          {% endif %}
        icon_template: mdi:soccer

      dfb_datum:
        friendly_name: Datum
        value_template: >
          {% if state_attr('calendar.nationalmannschaft', 'start_time') %}
            {% set weekday = as_timestamp(state_attr('calendar.nationalmannschaft', 'start_time'), None) | timestamp_custom("%w", True) | int(0) %}

            {{ ['Montag','Dienstag','Mittwoch','Donnerstag','Freitag','Samstag','Sonntag'][weekday-1] }}, {{ as_timestamp(state_attr('calendar.nationalmannschaft', 'start_time'), None) | timestamp_custom("%d.%m.%Y", True) | string }}
          {% else %}
            -
          {% endif %}
        icon_template: mdi:calendar-alert

      dfb_uhrzeit:
        friendly_name: Uhrzeit
        value_template: >
          {% if state_attr('calendar.nationalmannschaft', 'start_time') %}
            {% set dateSplitted = state_attr('calendar.nationalmannschaft', 'start_time').split(' ') %}
            {% set timeSplitted = dateSplitted[1].split(':') %}
            {{ timeSplitted[0] ~ ':' ~ timeSplitted[1] ~ ' Uhr' }}            
          {% else %}
            -
          {% endif %}
        icon_template: mdi:clock-outline

      dfb_ort:
        friendly_name: Ort
        value_template: >
          {% if state_attr('calendar.nationalmannschaft', 'location') %}
            {% set locationSplitted = state_attr('calendar.nationalmannschaft', 'location').split(' | ') %}

            {% if locationSplitted|length == 2 %}
              {{ locationSplitted[1] }}
            {% else %}
              -
            {% endif %}            
          {% else %}
            -
          {% endif %}
        icon_template: mdi:city
        
      formel1_rennen:
        friendly_name: Nächstes Rennen
        icon_template: mdi:car-sports
        value_template: >       
          {% set rennen = as_timestamp(state_attr('calendar.formel1_rennen', 'start_time'), None) %}
          {% set sprint = as_timestamp(state_attr('calendar.formel1_sprint', 'start_time'), None) %}
          
          {% if sprint == None and rennen == None %}
            {% set location = None %}
          {% elif sprint != None and sprint < rennen %}
            {% set location = state_attr('calendar.formel1_sprint', 'message').split(':')[1].split('/') %}
          {% else %}
            {% set location = state_attr('calendar.formel1_rennen', 'message').split(':')[1].split('/') %}
          {% endif %}
          
          {% if location != None and location != '' %}
            {{ location[1] }} ({{ location[0].strip() }})
          {% else %}
            -
          {% endif %}                                   

      formel1_datum:
        friendly_name: Datum
        icon_template: mdi:calendar-alert
        value_template: >
          {% set rennen = as_timestamp(state_attr('calendar.formel1_rennen', 'start_time'), None) %}
          {% set sprint = as_timestamp(state_attr('calendar.formel1_sprint', 'start_time'), None) %}        
        
          {% if sprint == None and rennen == None %}
            {% set start = None %}
          {% elif sprint != None and sprint < rennen %}
            {% set start = sprint %}
          {% else %}
            {% set start = rennen %}
          {% endif %}

          {% if start == None %}
            -
          {% else %}           
            {{ start | timestamp_custom("%d.%m.%Y", True) | string }}, {{ start | timestamp_custom("%H:%M Uhr") | string }}       
          {% endif %}                 

      formel1_qualifikation:
        friendly_name: Qualifikation
        icon_template: mdi:car-sports
        value_template: >
          {% set qualifikation = state_attr('calendar.formel1_qualifikation', 'start_time') %}
          {% set rennen = state_attr('calendar.formel1_rennen', 'start_time') %}
          
          {% if qualifikation == None or rennen == None %}
            -
          {% else %}
            {% set qualifikationTs = as_timestamp(state_attr('calendar.formel1_qualifikation', 'start_time'), None) %}
            {% set rennenTs = as_timestamp(state_attr('calendar.formel1_rennen', 'start_time'), None) %}
            
            {% if qualifikation > rennen %}
              -
            {% else %}
              {% if state_attr('calendar.formel1_qualifikation', 'start_time') %}
                {{ qualifikationTs | timestamp_custom("%d.%m.%Y", True) | string }}, {{ qualifikationTs | timestamp_custom("%H:%M Uhr") | string }}
              {% else %}
                -
              {% endif %}
            {% endif %}
          {% endif %}               

      naechster_urlaub:
        friendly_name: Nächster Urlaub
        icon_template: mdi:sunglasses
        value_template: >
          {% if state_attr('calendar.urlaub', 'message') %}
            {{ state_attr('calendar.urlaub', 'message') }}
          {% else %}
            -
          {% endif %}
        attribute_templates:
          datum: >
            {% if state_attr('calendar.urlaub', 'start_time') %}             
              {% set weekday = as_timestamp(state_attr('calendar.urlaub', 'start_time'), None) | timestamp_custom("%w", True) | int(0) %}

              {{ ['Montag','Dienstag','Mittwoch','Donnerstag','Freitag','Samstag','Sonntag'][weekday-1] }}, {{ as_timestamp(state_attr('calendar.urlaub', 'start_time'), None) | timestamp_custom("%d.%m.%Y", True) | string }}
            {% else %}
              -              
            {% endif %}
          tage: >
            {% set start = as_timestamp(state_attr('calendar.urlaub', 'start_time'), None) | int(0) %}
            {% set heute = as_timestamp(now().replace(hour=0, minute=0, second=0)) | int(0) %}
            
            {{ 0 if start == 0 else ((start - heute) | int / 60 / 60 / 24) | int(0) }}   
             
      naechste_ferien:
        friendly_name: Nächste Ferien
        icon_template: mdi:calendar-star
        value_template: >
          {% if state_attr('calendar.ferien', 'message') %}
            {{ state_attr('calendar.ferien', 'message') }}
          {% else %}
            -
          {% endif %}
        attribute_templates:
          datum: >
            {% if state_attr('calendar.ferien', 'start_time') %}             
              {% set weekday = as_timestamp(state_attr('calendar.ferien', 'start_time'), None) | timestamp_custom("%w", True) | int(0) %}

              {{ ['Montag','Dienstag','Mittwoch','Donnerstag','Freitag','Samstag','Sonntag'][weekday-1] }}, {{ as_timestamp(state_attr('calendar.ferien', 'start_time'), None) | timestamp_custom("%d.%m.%Y", True) | string }}
            {% else %}
              -
            {% endif %}
          tage: >
            {% set start = as_timestamp(state_attr('calendar.ferien', 'start_time'), None) | int(0) %}
            {% set heute = as_timestamp(now().replace(hour=0, minute=0, second=0)) | int(0) %}
            
            {{ 0 if start == 0 else ((start - heute) | int / 60 / 60 / 24) | int(0) }}            