binary_sensor:
  - platform: uptimerobot
    api_key: !secret uptimerobot_apikey

sensor:
  - platform: cert_expiry
    host: !secret nextcloud_url
    name: Nextcloud Zertifikat

homeassistant:
  customize:
    binary_sensor.nextcloud:
      friendly_name: Status

    sensor.nextcloud_zertifikat:
      friendly_name: Laufzeit Zertifikat