binary_sensor:
  - platform: uptimerobot
    api_key: !secret uptimerobot_apikey

sensor:
  - platform: cert_expiry
    host: !secret nextcloud_url
    
  - platform: nextcloud
    url: !secret nextcloud_url_https
    username: !secret nextcloud_username
    password: !secret nextcloud_app_password
    
  - platform: template
    sensors:  
      nextcloud_datenbank:
        friendly_name: "Datenbankgröße"
        entity_id:
          - sensor.nextcloud_server_database_size       
        unit_of_measurement: MB
        value_template: >-
          {% set bytesSent = (states('sensor.nextcloud_server_database_size') | int / 1024 / 1024) | round() %}
          {{ bytesSent }}          
        icon_template: >-
          mdi:server
          
homeassistant:
  customize:
    binary_sensor.nextcloud:
      friendly_name: Status

    sensor.nextcloud_zertifikat:
      friendly_name: Laufzeit Zertifikat
      unit_of_measurement: Tage      
    sensor.nextcloud_system_version:
      friendly_name: Installierte Version          