input_number:
  schule_puffer_fertigmachen:
    name: Puffer fertigmachen
    min: 10
    max: 60
    step: 5

  schule_puffer_losgehen_erste_stunde:
    name: Puffer losgehen Erste Stunde
    min: 10
    max: 60
    step: 5
    
  schule_puffer_losgehen_spaeter:
    name: Puffer losgehen Später
    min: 10
    max: 60
    step: 5
    
input_datetime:
  erste_stunde:
    name: Erste Stunde
    has_date: false
    has_time: true
    icon: mdi:timer

template:
  - binary_sensor:
      - name: "Schultag"
        unique_id: schultag
        state: >
          {% set arbeitstag = is_state('binary_sensor.arbeitstag', 'on') %}
          {% set keineFerien = is_state('calendar.ferien', 'off') %}
          {% set schule = is_state('calendar.franzi_keine_schule', 'off') %}         

          {{ arbeitstag and keineFerien and schule }}          
           
      - name: "Schule - Info morgens"
        unique_id: schule_info_morgens
        state: >
          {% set schultag = is_state('binary_sensor.schultag', 'on') %}
          {% set schuleAktiv = is_state('schedule.schule_franzi', 'on') %}
          {% set tagSchedule = as_timestamp(state_attr('schedule.schule_franzi', 'next_event'), None) | timestamp_custom('%d', True, 0) | int(0) %}
          {% set tagHeute = as_timestamp(now()) | timestamp_custom('%d', True) | int(0) %}    

          {{ schultag and tagSchedule == tagHeute and not schuleAktiv }}          
            
      - name: "Schule - Info nachmittags"
        unique_id: schule_info_nachmittags
        state: >
          {% set schultag = is_state('binary_sensor.schultag', 'on') %}
          {% set schuleAktiv = is_state('schedule.schule_franzi', 'on') %}
          {% set tagSchedule = as_timestamp(state_attr('schedule.schule_franzi', 'next_event'), None) | timestamp_custom('%d', True, 0) | int(0) %}
          {% set tagHeute = as_timestamp(now()) | timestamp_custom('%d', True) | int(0) %}    

          {{ schultag and tagSchedule == tagHeute and schuleAktiv }}         
          
  - sensor:
      - name: "Schule Beginn"
        unique_id: schule_beginn
        state: >
          {% if is_state('binary_sensor.schule_info_morgens', 'on') %}
            {{ as_timestamp(state_attr('schedule.schule_franzi', 'next_event'), None) | timestamp_custom('%H:%M', True, 0) }} Uhr          
          {% else %}
            -
          {% endif %}
        icon: mdi:clock-outline

      - name: "Schule Ende"
        unique_id: schule_ende
        state: >
          {% if is_state('binary_sensor.schule_info_nachmittags', 'on') %}
            {{ as_timestamp(state_attr('schedule.schule_franzi', 'next_event'), None) | timestamp_custom('%H:%M', True, 0) }} Uhr          
          {% else %}
            -
          {% endif %}
        icon: mdi:clock-outline
        
  - trigger:
      - platform: state
        entity_id:
          - schedule.schule_franzi
        from: 'off'
        to: 'on'          
    sensor:      
      - name: Franzi Schule
        state: "{{ state_attr('schedule.schule_franzi', 'next_event') + timedelta(minutes=30) }}"
          
automation:             
  - alias: 'Benachrichtigung Schule'
    id: "benachrichtigung_schule"
    trigger:
      - id: fertigmachen
        platform: template
        value_template: >-
          {% set jetzt = as_timestamp(states('sensor.date_time').replace(',',''), None) | int(0) %} 
          {% set pufferFertigmachen = (states('input_number.schule_puffer_fertigmachen') | int(0)) * 60 %}
          {% set schuleBeginn = as_timestamp(state_attr('schedule.schule_franzi', 'next_event')) | int(0) %}
          
          {{ schuleBeginn == jetzt + pufferFertigmachen }}        
      - id: losgehen
        platform: template
        value_template: >-
          {% set jetzt = as_timestamp(states('sensor.date_time').replace(',',''), None) | int(0) %} 
          {% set uhrZeitErsteStunde = states('input_datetime.erste_stunde') %}
          {% set uhrZeitSchulBeginn = (state_attr('schedule.schule_franzi', 'next_event') |as_datetime|as_local).strftime('%H:%M:%S') %}
          {% set schuleBeginn = as_timestamp(state_attr('schedule.schule_franzi', 'next_event')) | int(0) %}
          
          {% if uhrZeitErsteStunde == uhrZeitSchulBeginn %}
            {% set pufferLosgehen = (states('input_number.schule_puffer_losgehen_erste_stunde') | int(0)) * 60 %}
          {% else %}
            {% set pufferLosgehen = (states('input_number.schule_puffer_losgehen_spaeter') | int(0)) * 60 %}
          {% endif %}
          
          {{ schuleBeginn == jetzt + pufferLosgehen }}             
    condition:
      - "{{ is_state('binary_sensor.schultag', 'on') }}"
      - "{{ is_state('schedule.schule_franzi', 'off') }}"
    action:
      - if: "{{ trigger.id == 'fertigmachen' }}"
        then:
          - service: !secret tts_service            
            data:
              echo: "wohnzimmer"
              message: "Es ist Zeit sich fertig für die Schule zu machen."             
        else:
          - service: !secret tts_service
            data:
              message: "Es ist Zeit sich auf dem Weg zur Schule zu machen."                       