mqtt:
  sensor:
    - name: "Tankstelle Real"
      unit_of_measurement: '€'    
      state_topic: "tanken/real"

    - name: "Tankstelle Jet Dortmund"
      unit_of_measurement: '€'
      state_topic: "tanken/jet_do"

    - name: "Tankstelle Jet Mülheim"
      unit_of_measurement: '€'
      state_topic: "tanken/jet_mh"

automation:
  - alias: "Tanken Telegram"
    id: "tanken_telegram"
    trigger:
      platform: event
      event_type: telegram_command
      event_data:
        command: '/tanken'
    action:
      - service: notify.telegram
        data:
          title: "Aktuelle Benzinpreise"
          message: >
            {% set realPrice = states('sensor.tankerkoenig_supermarkt_tankstelle_am_real_markt_dortmund_wulfshofstr_e10') %}
            {% set RealText = (realPrice | float) ~ '€' if realPrice != 'unknown' else ('geschlossen' if is_state('binary_sensor.supermarkt_tankstelle_wulfshofstrasse_6_8_status', 'off') else '-') %}

            {% set jetDoPrice = states('sensor.tankerkoenig_jet_dortmund_provinzialstr_229_e10') %}
            {% set jetDoText = (jetDoPrice | float) ~ '€' if jetDoPrice != 'unknown' else ('geschlossen' if is_state('binary_sensor.jet_provinzialstr_229_status', 'off') else '-') %}

            {% set jetMhPrice = states('sensor.tankerkoenig_jet_muelheim_strassburger_allee_75_e10') %}
            {% set jetMhText = (jetMhPrice | float) ~ '€' if jetMhPrice != 'unknown' else ('geschlossen' if is_state('binary_sensor.jet_strassburger_allee_75_status', 'off') else '-') %}

            {{ 'Real: ' ~ RealText }}       
            
            {{ 'Jet Dortmund: ' ~ jetDoText }}    
            
            {{ 'Jet Mülheim: ' ~ jetMhText }}    

  - alias: "Tanken Preis"
    id: "tanken_preis"
    mode: parallel
    trigger:
      - platform: state
        id: "tanken/real"
        entity_id: sensor.tankerkoenig_supermarkt_tankstelle_am_real_markt_dortmund_wulfshofstr_e10
      - platform: state
        id: "tanken/jet_do"
        entity_id: sensor.tankerkoenig_jet_dortmund_provinzialstr_229_e10
      - platform: state
        id: "tanken/jet_mh"
        entity_id: sensor.tankerkoenig_jet_muelheim_strassburger_allee_75_e10          
    condition:
      - "{{ trigger.to_state.state != 'unknown' }}"
    action:
      - service: mqtt.publish
        data:
          topic: "{{ trigger.id }}"          
          payload: "{{ states(trigger.entity_id) }}"
          retain: true

homeassistant:
  customize:           
    sensor.tankerkoenig_jet_muelheim_strassburger_allee_75_e10:
      friendly_name: Tankstelle Jet Mülheim
    sensor.tankerkoenig_jet_dortmund_provinzialstr_229_e10:
      friendly_name: Tankstelle Jet Dortmund      
    sensor.tankerkoenig_supermarkt_tankstelle_am_real_markt_dortmund_wulfshofstr_e10:
      friendly_name: Tankstelle Real
    sensor.tankerkoenig_sb_dortmund_borussiastrasse_118_e10:
      friendly_name: Tankstelle Borussiastraße
