input_boolean:
  alles_auschalten_aktiv:
    name: "Alles ausschalten aktiv"

timer:
  alles_auschalten:
    name: "Alles ausschalten"
    duration: 15

alarm_control_panel:
  - platform: manual
    name: Alarm
    arming_time: 60
    delay_time: 60
    trigger_time: 10
    disarmed:
      trigger_time: 0
    armed_home:
      arming_time: 0
      delay_time: 0
    armed_away:
      arming_time: 0

automation:
  - alias: "Alles ausschalten aktivieren"
    trigger:
      - platform: state
        entity_id: sensor.schalter_flur
        to: '2'
    condition:
      - condition: state
        entity_id: automation.alles_ausschalten
        state: 'off'
    action:
      - service: script.radios_pausieren
      - service: !secret tts_service
        data_template:
          echo: "flur"
          message: "Alle Geräte können jetzt ausgeschaltet werden."
      - delay: '00:00:02'
      - service: timer.start
        entity_id: timer.alles_auschalten
      - service: media_player.play_media
        data_template:
          entity_id:
            - media_player.smarthome
          media_content_id: >-
            http://192.168.2.75:8123/local/countdown/countdown_10.mp3
          media_content_type: music
      - service: automation.turn_on
        entity_id: automation.alles_ausschalten
      - service: automation.turn_off
        entity_id: automation.alles_ausschalten_aktivieren

  - alias: "Alles ausschalten"
    initial_state: false
    trigger:
      - platform: state
        entity_id: binary_sensor.schalter_flur
        to: 'off'
    condition:
      - condition: state
        entity_id: timer.alles_auschalten
        state: 'active'
    action:
      - service: media_player.media_pause
        entity_id: media_player.smarthome
      - service: !secret tts_service
        data_template:
          echo: "flur"
          message: >-
            {% if is_state('binary_sensor.reinigung_heute', 'on') %}
              "Die Wohnung wird heute gesaugt. Alle Geräte werden ausgeschaltet. Auf Wiedersehen."
            {% else %}
              "Alle Geräte werden ausgeschaltet. Auf Wiedersehen."
            {% endif %}            
      - service: timer.cancel
        entity_id: timer.alles_auschalten
      - service: automation.turn_off
        entity_id: automation.alles_ausschalten
      - service: automation.turn_on
        entity_id: automation.alles_ausschalten_aktivieren
      - service: script.alles_ausschalten

  - alias: "Alles ausschalten deaktivieren"
    trigger:
      platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.alles_auschalten
    action:
      - service: !secret tts_service
        data_template:
          echo: "flur"
          message: "Der Vorgang wurde abgebrochen."
      - service: automation.turn_off
        entity_id: automation.alles_ausschalten
      - service: automation.turn_on
        entity_id: automation.alles_ausschalten_aktivieren
      - service: script.radios_starten

  - alias: "Alarm aktiviert"
    trigger:
      - platform: state
        entity_id: binary_sensor.zu_hause
        to: 'off'
        for:
          minutes: 1
    action:
      - service: alarm_control_panel.alarm_arm_away
        entity_id: alarm_control_panel.alarm

  - alias: "Alarm ausgelöst"
    trigger:
      - platform: state
        entity_id: binary_sensor.tuersensor
        to: 'on'
    condition:
      - condition: state
        entity_id: alarm_control_panel.alarm
        state: armed_away
      - condition: state
        entity_id: binary_sensor.zu_hause
        state: 'off'
    action:
      service: alarm_control_panel.alarm_trigger
      entity_id: alarm_control_panel.alarm

  - alias: "Alarm Nachricht"
    trigger:
      - platform: state
        entity_id: alarm_control_panel.alarm
        to: 'triggered'
    action:
      service: notify.telegram
      data_template:
        title: "Alarm"
        message: "Der Alarm in der Wohnung wurde ausgelöst."

  - alias: "Alarm - Bewegung"
    trigger:
      - platform: state
        entity_id: binary_sensor.bewegungsmelder_badezimmer
        to: 'on'
      - platform: state
        entity_id: binary_sensor.bewegungsmelder_wohnzimmer
        to: 'on'
      - platform: state
        entity_id: binary_sensor.bewegungsmelder_flur_vorne
        to: 'on'
      - platform: state
        entity_id: binary_sensor.bewegungsmelder_arbeitszimmer
        to: 'on'
      - platform: state
        entity_id: binary_sensor.bewegungsmelder_sportszimmer
        to: 'on'        
      - platform: state
        entity_id: binary_sensor.bewegungsmelder_schlafzimmer
        to: 'on'
      - platform: state
        entity_id: binary_sensor.bewegungsmelder_kueche
        to: 'on'
    condition:
      - condition: state
        entity_id: binary_sensor.zu_hause
        state: 'off'
      - condition: state
        entity_id: alarm_control_panel.alarm
        state: 'armed_away'
      - condition: state
        entity_id: 'vacuum.xiaomi_vacuum_cleaner'
        state: 'docked'
    action:
      service: notify.telegram
      data_template:
        title: "Bewegung erkannt"
        message: >-
          {% if trigger.entity_id == "binary_sensor.bewegungsmelder_badezimmer" %}
             Im Badezimmer wurde eine Bewegung erkannt.
          {% elif trigger.entity_id == "binary_sensor.bewegungsmelder_wohnzimmer" %}
            Im Wohnzimmer wurde eine Bewegung erkannt.
          {% elif trigger.entity_id == "binary_sensor.bewegungsmelder_flur_vorne" %}
            Im Flur wurde eine Bewegung erkannt.
          {% elif trigger.entity_id == "binary_sensor.bewegungsmelder_arbeitszimmer" %}
            Im Arbeitszimmer wurde eine Bewegung erkannt.
          {% elif trigger.entity_id == "binary_sensor.bewegungsmelder_sportszimmer" %}
            Im Sportzimmer wurde eine Bewegung erkannt.            
          {% elif trigger.entity_id == "binary_sensor.bewegungsmelder_schlafzimmer" %}
            Im Schlafzimmer wurde eine Bewegung erkannt.
          {% elif trigger.entity_id == "binary_sensor.bewegungsmelder_kueche" %}
            In der Küche wurde eine Bewegung erkannt.
          {% else %}
            Eine sonstige Bewegung wurde erkannt.
          {% endif %}

  - alias: "Alarm - Fenster"
    trigger:
      - platform: state
        entity_id: binary_sensor.fenster_balkontuer
        to: 'on'      
      - platform: state
        entity_id: binary_sensor.fenster_wohnzimmer
        to: 'on'
      - platform: state
        entity_id: binary_sensor.fenster_schlafzimmer
        to: 'on'
      - platform: state
        entity_id: binary_sensor.fenster_kueche
        to: 'on'
      - platform: state
        entity_id: binary_sensor.fenster_arbeitszimmer
        to: 'on'
      - platform: state
        entity_id: binary_sensor.fenster_sportzimmer
        to: 'on'
    condition:
      - condition: state
        entity_id: binary_sensor.zu_hause
        state: 'off'
      - condition: state
        entity_id: alarm_control_panel.alarm
        state: 'armed_away'
    action:
      service: notify.telegram
      data_template:
        title: "Fenster geöffnet"
        message: >-
          {% if trigger.entity_id == "binary_sensor.fenster_balkontuer" %}
            Die Balontür wurde geöffnet.
          {% elif trigger.entity_id == "binary_sensor.fenster_wohnzimmer" %}
            Das Fenster im Wohnzimmer wurde geöffnet.            
          {% elif trigger.entity_id == "binary_sensor.fenster_schlafzimmer" %}
            Das Fenster im Schlafzimmer wurde geöffnet.
          {% elif trigger.entity_id == "binary_sensor.fenster_kueche" %}
            Das Fenster in der Küche wurde geöffnet.
          {% elif trigger.entity_id == "binary_sensor.fenster_arbeitszimmer" %}
            Das Fenster im Arbeitszimmer wurde geöffnet.
          {% elif trigger.entity_id == "binary_sensor.fenster_sportzimmer" %}
            Das Fenster im Sportzimmer wurde geöffnet.
          {% endif %}

script:
  alles_ausschalten_nfc:
    alias: "Alles ausschalten - NFC"
    sequence:
      - service: script.radios_pausieren
      - service: !secret tts_service
        data_template:
          echo: "flur"          
          message: >-
            {% if is_state('binary_sensor.reinigung_heute', 'on') %}
              "Die Wohnung wird heute gesaugt. Alle Geräte werden ausgeschaltet. Auf Wiedersehen."
            {% else %}
              "Alle Geräte werden ausgeschaltet. Auf Wiedersehen."
            {% endif %}               
      - service: script.alles_ausschalten   
      
  alles_ausschalten:
    alias: "Alles ausschalten"
    sequence:
      - service: switch.turn_off
        entity_id: switch.alle_radios, switch.monitor, switch.schlafzimmer_fernseher, switch.watchtv_wohnzimmer, switch.watchtv_schlafzimmer
      - service: light.turn_off
        entity_id: light.couch, light.strahler, light.sideboard, light.schrank, light.badezimmerschrank, light.bett, light.kleiderschrank, light.kuche_regal, light.schreibtisch, light.balkon_licht, light.arbeitszimmer_lampe, light.sportzimmer_regal
      - service: mqtt.publish
        data:
           topic: 'location/handy'
           payload: 'not_home'
           retain: true
      - condition: state
        entity_id: input_boolean.computer_ausschalten
        state: 'on'
      - service: switch.turn_off
        entity_id: switch.pc