http:
config:
websocket_api:
api:
frontend:
mobile_app:
scene:
discovery:
wake_on_lan:
system_health:
map:
lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
      type: module
    - url: /hacsfiles/weather-card/weather-card.js
      type: module   
    - url: /hacsfiles/stack-in-card/stack-in-card.js
      type: module
    - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
      type: module
    - url: /hacsfiles/layout-card/layout-card.js
      type: module    
    - url: /hacsfiles/lovelace-layout-card/layout-card.js
      type: module    
    - url: /hacsfiles/atomic-calendar-revive/atomic-calendar-revive.js
      type: module      
    - url: /hacsfiles/secondaryinfo-entity-row/secondaryinfo-entity-row.js
      type: module
    - url: /hacsfiles/lovelace-card-tools/card-tools.js
      type: module            
    - url: /hacsfiles/home-assistant-sun-card/home-assistant-sun-card.js
      type: module         
    - url: /hacsfiles/zha-network-card/zha-network-card.js
      type: module      
    - url: /hacsfiles/flipdown-timer-card/flipdown-timer-card.js
      type: module         
    - url: /hacsfiles/battery-state-card/battery-state-card.js
      type: module
    
  dashboards:      
    lovelace-rooms:
      mode: yaml
      filename: lovelace-rooms.yaml
      title: Zimmer
      icon: mdi:home-assistant
      show_in_sidebar: true  
  
panel_custom:
  - name: panel-redirect
    url_path: redirect-server-controls
    sidebar_title: Logs
    sidebar_icon: mdi:text
    module_url: /local/scripts/panel-redirect.js
    config:
      target: /config/logs
      
browser_mod:
  disable:
    - all

zone:
  - name: Home
    latitude: !secret home_latitude
    longitude: !secret home_longitude
    radius: 50
    icon: mdi:home-account
  - name: Arbeit
    latitude: !secret work_latitude
    longitude: !secret work_longitude
    radius: 70
    icon: mdi:wan 
    
sensor:
  - platform: command_line
    name: Installierte Version
    command: "head -5 /config/.HA_VERSION"
    scan_interval: 3600

  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: memory_use_percent
      - type: processor_use
      - type: last_boot
      - type: processor_temperature

  - platform: template
    sensors:
      hass_installierte_version:
        friendly_name: "Installierte Version"
        icon_template: mdi:cloud-sync
        value_template: "{{ state_attr('update.home_assistant_core_update', 'installed_version') }}"
        
      hass_aktuelle_version:
        friendly_name: "Aktuelle Version"
        icon_template: mdi:cloud-sync-outline
        value_template: "{{ state_attr('update.home_assistant_core_update', 'latest_version') }}"
        
      rpi_letzter_neustart:
        friendly_name: "Letzter Neustart"
        icon_template: mdi:av-timer
        value_template: "{{ as_timestamp(states('sensor.last_boot'), None) | timestamp_custom('%d.%m.%Y') | string }}"
          
      laufzeit_minuten:
        friendly_name: "Laufzeit Minuten"
        icon_template: mdi:clock
        unit_of_measurement: 'Minuten'
        value_template: >-
          {% set up_time =  states('sensor.letzter_neustart') %}
     
          {{ '-' if up_time == 'unknown' else ((as_timestamp(now()) - as_timestamp(up_time, None)) / 60) | int(0) }}
              
      laufzeit_stunden:
        friendly_name: "Laufzeit Stunden"
        icon_template: mdi:clock
        unit_of_measurement: 'Stunden'
        value_template: >-
          {% set up_time =  states('sensor.letzter_neustart') %}
     
          {{ '-' if up_time == 'unknown' else ((as_timestamp(now()) - as_timestamp(up_time, None)) / 60 / 60) | round(2, 0) }}

script:  
  homeassistant_neustart:
    alias: Home Assistant - Neustart
    sequence:
      - service: !secret tts_service
        data:
          echo: "wohnzimmer"
          message: "Home Assistant wird neugestartet."
      - delay: '00:00:05'      
      - service: media_player.play_media
        data:
          entity_id: media_player.squeezebox
          media_content_id:  http://192.168.2.75:8123/local/sounds/winxp_shutdown.mp3
          media_content_type: music
      - wait_template: "{{is_state('media_player.squeezebox', 'idle')}}"
        timeout: '00:00:02'
        continue_on_timeout: 'true'      
      - service: homeassistant.restart

  homeassistant_gestartet:
    alias: Home Assistant - Gestartet
    sequence:
      - service: hassio.addon_stdin
        data:
          addon: 15d21743_samba_backup
          input: restore-sensor     
      - if: "{{ is_state('person.dennis', 'not_home') }}"
        then:
          - service: notify.telegram
            data:                  
              message: "Home Assistant wurde neugestartet."    
        else:
          - service: script.zu_hause_standort
          - service: media_player.play_media
            data:
              entity_id: media_player.squeezebox
              media_content_id: http://192.168.2.75:8123/local/sounds/winxp_start.mp3
              media_content_type: music
          - delay: '00:00:02'
          - service: !secret tts_service
            data:
              echo: "wohnzimmer"
              message: "Home Assistant wurde neugestartet."              
      
automation:
  - alias: "Home Assisant - Update verfügbar"
    id: "home_assistant_update_verfuegbar"
    trigger:
      - platform: state
        entity_id: update.home_assistant_core_update
        to: 'on'
    action:
      - choose:
          - conditions:
            - condition: state
              entity_id: person.dennis
              state: 'not_home'
            sequence:
              - service: notify.telegram
                data:
                  title: 'Neue Version'
                  message: "Home Assistant {{ states('sensor.hass_aktuelle_version') }} ist jetzt verfügbar."
        default:
          - service: persistent_notification.create
            data:
              title: "Update verfügbar"
              message: "Home Assistant {{ states('sensor.hass_aktuelle_version') }} ist jetzt verfügbar."
              notification_id: neue_version
               
  - alias: "Home Assistant - Gestartet"
    id: "home_assistant_gestartet"
    trigger:
      - platform: homeassistant
        event: start
    action:
      - service: script.homeassistant_gestartet
          
  - alias: "Home Assistant - Gestoppt"
    id: "home_assistant_gestoppt"
    trigger:   
      - platform: homeassistant
        event: shutdown     
    condition:
      - condition: state
        entity_id: person.dennis
        state: 'not_home'      
    action:
      - service: notify.telegram
        data:                  
          message: "Home Assistant wurde gestoppt."        
      - service: homeassistant.restart

  - alias: "Home Assistant - Fehler Neustart"
    id: "home_assistant_fehler_neustart"
    trigger:
      - platform: state
        entity_id: persistent_notification.homeassistant_check_config
        to: 'notifying'
    action:
      - service: media_player.play_media
        data:
          entity_id: media_player.squeezebox
          media_content_id: http://192.168.2.75:8123/local/sounds/winxp_error.mp3
          media_content_type: music  
      - service: !secret tts_service
        data:
          echo: "wohnzimmer"
          message: "Während des Neustarts ist ein Fehler aufgetreten."

homeassistant:
  customize:      
    zone.home:
      friendy_name: Zu Hause
  
    script.homeassistant_neustart:
      icon: mdi:home-assistant
      name: Neustart

    sensor.hacs:
      friendly_name: HACS
      unit_of_measurement: Update(s)
      
    sensor.disk_use_percent:
      friendly_name: Belegter Speicherplatz
    sensor.memory_use_percent:
      friendly_name: Benutzter Arbeitsspeicher
      icon: mdi:database-plus
    sensor.processor_temperature:
      friendly_name: CPU Temperatur
      icon: mdi:creation
        
    sensor.database_size:
      friendly_name: Größe Datenbank
      icon: mdi:database