logger:
  default: error
  logs:
    homeassistant.components.gdacs: fatal
    custom_components.satellitetracker: fatal
    homeassistant.components.bluetooth: fatal
  filters:
    custom_components.average:
      - "Unable to find an entity"
    homeassistant.components.tplink.coordinator:
      - "Unable to connect to the device"
      - "Unable to query the device"
    homeassistant.components.flux_led: 
      - 'Failed to change power state'
    homeassistant.components.flux_led.coordinator:
      - "Bulb stopped responding"
      - '^Error fetching \b(?:\d{1,3}\.){3}\d{1,3}\b data'      
    homeassistant.components.fritz.common:
      - "Timeout fetching fritz-192.168.2.1-coordinator data"
      - "Error fetching fritz-192.168.2.1-coordinator data"
      - "Please check the device is properly configured for remote login"
    homeassistant.components.fritzbox:
      - "Timeout fetching"
    homeassistant.components.xiaomi_miio:
      - "Timeout fetching Staubsauger data"

recorder:
  purge_keep_days: 7
  db_url: !secret mariadb_url
  commit_interval: 10
  include:
    domains:
      - sensor
      - binary_sensor
      - switch
      - light     
      - device_tracker
      - input_boolean
      - input_datetime
      - input_number
      - input_select
      - calendar
      - entity_controller
      - media_player
      - person
      - counter
      - climate
      - proximity
      - alarm_control_panel
      - vacuum
      - zone
      - schedule
    entity_globs:
      - device_tracker.handy*  
  exclude:
    entities:
      - sensor.satelliten
      - sensor.time
      - sensor.date_time      
      
system_log:
  max_entries: 100

logbook:
  include:
    domains:
      - switch
      - light
      - automation
      - entity_controller
      - person    
      - climate
      - proximity
      - alarm_control_panel
      - vacuum
      - zone
      - schedule
    entity_globs:  
      - device_tracker.handy*  
  exclude:
    entities:     
      - switch.wohnzimmer_couch
      - switch.wohnzimmer_schrank
      - switch.kleiderschrank
      - switch.computer
      - switch.monitore
      - switch.computer_arbeit   
      - switch.kuechenschrank
    entity_globs:
      - switch.*_led

history:
  include:
    domains:
      - switch
      - media_player
      - lights
      - entity_controller
      - person
      - climate
      - vacuum
      - zone
      - schedule
  exclude:
    entities:
      - switch.wohnzimmer_couch
      - switch.kleiderschrank
      - switch.wohnzimmer_schrank
      - switch.kuechenschrank
    entity_globs:
      - switch.*_led      
      - switch.echo_*_do_not_disturb_switch
      - switch.adguard_*