logger:
  default: error
  logs:
    homeassistant.components.emulated_hue.hue_api: fatal
    
recorder:
  purge_keep_days: 14
  db_url: !secret mariadb_url

system_log:
  max_entries: 100

logbook:
  include:
    domains:
      - switch
      - light
      - automation
  exclude:
    entities:
      - automation.letzte_bewegung
      - switch.licht_fernseher_schlafzimmer
      - switch.sportzimmer_regal
      - switch.couch
      - switch.strahler
      - switch.kleiderschrank
      - switch.arbeitszimmer_monitor_links
      - switch.arbeitszimmer_monitor_rechts
      - switch.monitor
      - switch.pc
      
history:
  include:
    domains:
      - switch
      - media_player
      - lights
  exclude:
    entities:
      - switch.echo_badezimmer_do_not_disturb_switch
      - switch.echo_badezimmer_repeat_switch
      - switch.echo_badezimmer_shuffle_switch
      - switch.echo_flur_do_not_disturb_switch
      - switch.echo_flur_repeat_switch
      - switch.echo_flur_shuffle_switch
      - switch.echo_kuche_do_not_disturb_switch
      - switch.echo_kuche_repeat_switch
      - switch.echo_kuche_shuffle_switch
      - switch.echo_schlafzimmer_do_not_disturb_switch
      - switch.echo_schlafzimmer_repeat_switch
      - switch.echo_schlafzimmer_shuffle_switch
      - switch.echo_wohnzimmer_do_not_disturb_switch
      - switch.echo_wohnzimmer_repeat_switch
      - switch.echo_wohnzimmer_shuffle_switch
      - switch.fernseher_schlafzimmer_remote
      - switch.licht_fernseher_schlafzimmer
      - switch.sportzimmer_regal
      - switch.couch
      - switch.strahler
      - switch.kleiderschrank