logger:
  default: error
  logs:
    homeassistant.components.gdacs: fatal
    custom_components.satellitetracker: fatal
  filters:
    homeassistant.components.tplink.coordinator:
      - "Unable to connect to the device"
      - "Unable to query the device"
    homeassistant.components.flux_led.coordinator:
      - "Bulb stopped responding"
    homeassistant.components.bluetooth:
      - "Error stopping scanner: [org.bluez.Error.Failed] No discovery started"
      
recorder:
  purge_keep_days: 7
  db_url: !secret mariadb_url
  commit_interval: 10
  include:
    domains:
      - sensor
      - binary_sensor
      - switch
      - light     
      - device_tracker
      - input_boolean
      - input_datetime
      - input_number
      - input_select
      - calendar
      - entity_controller
      - media_player
      - person
      - counter
      - climate
      - proximity
      - alarm_control_panel
      - vacuum
      - zone
    entity_globs:
      - device_tracker.handy*  
  exclude:
    entities:
      - sensor.satelliten
      - sensor.time
      - sensor.date_time      
      
system_log:
  max_entries: 100

logbook:
  include:
    domains:
      - switch
      - light
      - automation
      - entity_controller
      - person    
      - climate
      - proximity
      - alarm_control_panel
      - vacuum
      - zone
    entity_globs:  
      - device_tracker.handy*  
  exclude:
    entities:     
      - switch.sportzimmer_regal
      - switch.wohnzimmer_couch
      - switch.wohnzimmer_strahler
      - switch.wohnzimmer_schrank
      - switch.kleiderschrank
      - switch.monitor
      - switch.pc
      - switch.arbeitszimmer_monitore
      - switch.pc_arbeit   
      - switch.arbeitszimmer_lampe
      - switch.kuechenschrank
    entity_globs:
      - switch.*_led

history:
  include:
    domains:
      - switch
      - media_player
      - lights
      - entity_controller
      - person
      - climate
      - vacuum
      - zone
  exclude:
    entities:
      - switch.sportzimmer_regal
      - switch.wohnzimmer_couch
      - switch.wohnzimmer_strahler
      - switch.kleiderschrank
      - switch.wohnzimmer_schrank
      - switch.arbeitszimmer_lampe
      - switch.kuechenschrank
      - switch.fritz_box_7272_call_deflection_0
      - switch.fritz_box_7272_call_deflection_1
    entity_globs:
      - switch.*_led      
      - switch.echo_*_do_not_disturb_switch
      - switch.adguard_*