logger:
  default: error
  logs:
    homeassistant.components.openhardwaremonitor.sensor: fatal

recorder:
  purge_interval: 1
  purge_keep_days: 14
  db_url: !secret mariadb_url

system_log:
  max_entries: 100

logbook:
  include:
    domains:
      - switch
      - light
      - automation
  exclude:
    entities:
      - automation.home_assistant_healthcheck
      - automation.letzte_bewegung

history:
  include:
    domains:
      - switch
      - media_player
      - lights