logger:
  default: error
  logs:
    fritzconnection: info
    
recorder:
  purge_keep_days: 7
  db_url: !secret mariadb_url
  commit_interval: 10
  include:
    domains:
      - sensor
      - binary_sensor
      - switch
      - light     
      - device_tracker
      - input_boolean
      - input_datetime
      - input_number
      - input_select
      - calendar
      - entity_controller
      - media_player
      - person
      - counter
      - climate
  exclude:
    entities:
      - sensor.home_assistant_overhead_satellites
      - sensor.time
      - sensor.date_time      
      
system_log:
  max_entries: 100

logbook:
  include:
    domains:
      - switch
      - light
      - automation
      - entity_controller
      - person    
      - climate
    entities:  
      - devicve_tracker.handy
      - devicve_tracker.handygps
      - devicve_tracker.handyping
  exclude:
    entities:     
      - switch.schlafzimmer_fernseher_licht
      - switch.sportzimmer_regal
      - switch.wohnzimmer_couch
      - switch.wohnzimmer_strahler
      - switch.wohnzimmer_schrank
      - switch.kleiderschrank
      - switch.monitor
      - switch.pc
      - switch.arbeitszimmer_monitore
      - switch.pc_arbeit   
      - switch.arbeitszimmer_lampe
      - switch.kuechenschrank

history:
  include:
    domains:
      - switch
      - media_player
      - lights
      - entity_controller
      - person
      - climate
  exclude:
    entities:
      - switch.sportzimmer_regal
      - switch.wohnzimmer_couch
      - switch.wohnzimmer_strahler
      - switch.kleiderschrank
      - switch.wohnzimmer_schrank
      - switch.arbeitszimmer_lampe
      - switch.kuechenschrank
      - switch.schlafzimmer_fernseher_remote
      - switch.schlafzimmer_fernseher_licht      
      - switch.echo_badezimmer_do_not_disturb_switch
      - switch.echo_badezimmer_repeat_switch
      - switch.echo_badezimmer_shuffle_switch
      - switch.echo_flur_do_not_disturb_switch
      - switch.echo_flur_repeat_switch
      - switch.echo_flur_shuffle_switch
      - switch.echo_kueche_do_not_disturb_switch
      - switch.echo_kueche_repeat_switch
      - switch.echo_kueche_shuffle_switch
      - switch.echo_schlafzimmer_do_not_disturb_switch
      - switch.echo_schlafzimmer_repeat_switch
      - switch.echo_schlafzimmer_shuffle_switch
      - switch.echo_wohnzimmer_do_not_disturb_switch
      - switch.echo_wohnzimmer_repeat_switch
      - switch.echo_wohnzimmer_shuffle_switch
      - switch.firetv_badezimmer_do_not_disturb_switch
      - switch.firetv_schlafzimmer_do_not_disturb_switch
      - switch.firetv_sportzimmer_do_not_disturb_switch      
      - switch.adguard_filtering
      - switch.adguard_parental_control
      - switch.adguard_protection
      - switch.adguard_safe_browsing
      - switch.adguard_safe_search
      - switch.computer_arbeit_herunterfahren
      - switch.computer_arbeit_ruhezustand
      - switch.computer_herunterfahren
      - switch.computer_ruhezustand
      - switch.computer_lautlos
      - switch.computer_wiedergabe      
      - switch.fritz_box_7272_call_deflection_0
      - switch.fritz_box_7272_call_deflection_1