logger:
  default: error
  logs:
    fritzconnection: info
    homeassistant.components.gdacs: fatal
    custom_components.satellitetracker: fatal
    
recorder:
  purge_keep_days: 7
  db_url: !secret mariadb_url
  commit_interval: 10
  include:
    domains:
      - sensor
      - binary_sensor
      - switch
      - light     
      - device_tracker
      - input_boolean
      - input_datetime
      - input_number
      - input_select
      - calendar
      - entity_controller
      - media_player
      - person
      - counter
      - climate
      - proximity
      - alarm_control_panel
      - vacuum
    entity_globs:
      - devicve_tracker.handy*  
  exclude:
    entities:
      - sensor.home_assistant_overhead_satellites
      - sensor.time
      - sensor.date_time      
      
system_log:
  max_entries: 100

logbook:
  include:
    domains:
      - switch
      - light
      - automation
      - entity_controller
      - person    
      - climate
      - proximity
      - alarm_control_panel
      - vacuum
    entity_globs:  
      - devicve_tracker.handy*  
  exclude:
    entities:     
      - switch.schlafzimmer_fernseher_licht
      - switch.sportzimmer_regal
      - switch.wohnzimmer_couch
      - switch.wohnzimmer_strahler
      - switch.wohnzimmer_schrank
      - switch.kleiderschrank
      - switch.monitor
      - switch.pc
      - switch.arbeitszimmer_monitore
      - switch.pc_arbeit   
      - switch.arbeitszimmer_lampe
      - switch.kuechenschrank

history:
  include:
    domains:
      - switch
      - media_player
      - lights
      - entity_controller
      - person
      - climate
      - vacuum
  exclude:
    entities:
      - switch.sportzimmer_regal
      - switch.wohnzimmer_couch
      - switch.wohnzimmer_strahler
      - switch.kleiderschrank
      - switch.wohnzimmer_schrank
      - switch.arbeitszimmer_lampe
      - switch.kuechenschrank
      - switch.schlafzimmer_fernseher_remote
      - switch.schlafzimmer_fernseher_licht      
      - switch.echo_badezimmer_do_not_disturb_switch
      - switch.echo_kueche_do_not_disturb_switch
      - switch.echo_schlafzimmer_do_not_disturb_switch
      - switch.echo_wohnzimmer_do_not_disturb_switch
      - switch.echo_flur_do_not_disturb_switch 
      - switch.adguard_filtering
      - switch.adguard_parental_control
      - switch.adguard_protection
      - switch.adguard_safe_browsing
      - switch.adguard_safe_search
      - switch.fritz_box_7272_call_deflection_0
      - switch.fritz_box_7272_call_deflection_1