logger:
  default: error
  logs:
    homeassistant.components.openhardwaremonitor.sensor: fatal
    custom_components.squeezebox.media_player: fatal

recorder:
  purge_interval: 1
  purge_keep_days: 14
  db_url: !secret mariadb_url

system_log:
  max_entries: 100

logbook:
  include:
    domains:
      - switch
      - light
      - automation
  exclude:
    entities:
      - automation.home_assistant_healthcheck
      - automation.letzte_bewegung

history:
  include:
    domains:
      - switch
      - media_player
      - lights
  exclude:
    entities:
      - switch.echo_badezimmer_do_not_disturb_switch
      - switch.echo_badezimmer_repeat_switch
      - switch.echo_badezimmer_shuffle_switch
      - switch.echo_flur_do_not_disturb_switch
      - switch.echo_flur_repeat_switch
      - switch.echo_flur_shuffle_switch
      - switch.echo_kuche_do_not_disturb_switch
      - switch.echo_kuche_repeat_switch
      - switch.echo_kuche_shuffle_switch
      - switch.echo_schlafzimmer_do_not_disturb_switch
      - switch.echo_schlafzimmer_repeat_switch
      - switch.echo_schlafzimmer_shuffle_switch
      - switch.echo_wohnzimmer_do_not_disturb_switch
      - switch.echo_wohnzimmer_repeat_switch
      - switch.echo_wohnzimmer_shuffle_switch