speedtestdotnet:

pi_hole:
  host: !secret pihole_host
  verify_ssl: false

synology_dsm:
  host: !secret synology_host        
  username: !secret synology_username
  password: !secret synology_password
  ssl: false

switch:
  - platform: command_line
    switches:
      pi_hole:
        command_on: "curl -X GET 'http://192.168.2.74/admin/api.php?enable&auth=f7e48f5d33ae1d2adf8f75b6a6a9b94cafd74890d86fe0df5a5d1ab78deaeb68'"
        command_off: "curl -X GET 'http://192.168.2.74/admin/api.php?disable=3600&auth=f7e48f5d33ae1d2adf8f75b6a6a9b94cafd74890d86fe0df5a5d1ab78deaeb68'"
        command_state: "curl -X GET 'http://192.168.2.74/admin/api.php?status&auth=f7e48f5d33ae1d2adf8f75b6a6a9b94cafd74890d86fe0df5a5d1ab78deaeb68'"
        value_template: "{{ value_json.status == 'enabled' }}"

homeassistant:
  customize:
    sensor.synology_cpu_load_total:
      friendly_name: CPU Leistung
    sensor.synology_memory_usage_real:
      friendly_name: Auslastung Arbeitsspeicher
    sensor.synology_network_up:
      friendly_name: Netzwerk Upload
    sensor.synology_network_down:
      friendly_name: Netzwerk Download
    sensor.synology_status_volume_1:
      friendly_name: Volume Status
    sensor.synology_volume_used_volume_1:
      friendly_name: Belegter Speicherplatz

    sensor.speedtest_download:
      icon: mdi:download-network
    sensor.speedtest_upload:
      icon: mdi:upload-network

    switch.pi_hole:
      friendly_name: Pi-hole
      icon: mdi:cancel
    sensor.pi_hole_ads_blocked_today:
      friendly_name: Anfragen blockiert
    sensor.pi_hole_ads_percentage_blocked_today:
      friendly_name: Prozent blockiert
    sensor.pi_hole_dns_unique_clients:
      friendly_name: Geräte heute
    sensor.pi_hole_seen_clients:
      friendly_name: Geräte insgesamt