speedtestdotnet:

shell_command:
  pihole_enable: !secret pi_hole_enable
  pihole_disable: !secret pi_hole_disable
  pihole_disable_time: !secret pi_hole_disable_time

input_select:
  pihole_time:
    name: "Deaktivieren (Sekunden)"
    options:      
      - "0"
      - "10"
      - "30"
      - "60"
      - "300"
      - "600"
      - "900"
      - "1800"
      - "3600"
    initial: "0"
    
pi_hole:
  host: !secret pihole_host
  api_key: !secret pihole_apikey
  verify_ssl: false

binary_sensor:
  - platform: command_line
    name: Pi-hole Status
    command: !secret pi_hole_status
    device_class: connectivity
    value_template: >-
      {% if value_json.status == 'enabled' %}
         {{'ON'}}
      {% else %}
         {{'OFF'}}
      {% endif %}

synology_dsm:
  host: !secret synology_host        
  username: !secret synology_username
  password: !secret synology_password

switch:
  - platform: template
    switches:
      pi_hole:
        friendly_name: "Pi-hole"
        value_template: "{{ is_state('binary_sensor.pi_hole_status', 'on') }}"
        turn_on:
          - service: shell_command.pihole_enable
          - service: homeassistant.update_entity
            data:
              entity_id: binary_sensor.pi_hole_status
        turn_off:
          - service_template: >-
             {% if states('input_select.pihole_time') | float > 0 %}
                shell_command.pihole_disable_time
             {% else %}
                shell_command.pihole_disable
             {% endif %}
          - service: input_select.select_option
            data:
              entity_id: input_select.pihole_time
              option: 0
          - service: homeassistant.update_entity
            data:
              entity_id: binary_sensor.pi_hole_status
        icon_template: >-
          {% if is_state('binary_sensor.pi_hole_status', 'on') %}
            mdi:server-network
          {% else %}
            mdi:server-network-off
          {% endif %}

homeassistant:
  customize:
    binary_sensor.diskstation_security_status:
      friendly_name: Sicherheitsstatus
    sensor.diskstation_cpu_load_total:
      friendly_name: CPU Leistung
    sensor.diskstation_memory_usage_real:
      friendly_name: Auslastung Arbeitsspeicher
    sensor.diskstation_network_up:
      friendly_name: Netzwerk Upload
    sensor.diskstation_network_down:
      friendly_name: Netzwerk Download
    sensor.diskstation_volume_1_status:
      friendly_name: Volume Status
    sensor.diskstation_volume_1_volume_used:
      friendly_name: Belegter Speicherplatz

    sensor.speedtest_download:
      icon: mdi:download-network
    sensor.speedtest_upload:
      icon: mdi:upload-network

    sensor.pi_hole_ads_blocked_today:
      friendly_name: Anfragen blockiert
    sensor.pi_hole_ads_percentage_blocked_today:
      friendly_name: Prozent blockiert
    sensor.pi_hole_dns_unique_clients:
      friendly_name: Geräte heute
    sensor.pi_hole_seen_clients:
      friendly_name: Geräte insgesamt